docs(README.md): update organizational stuff & small update to features
qTox/qTox pull request #3740
Opened 2016-09-23 04:36 UTC by zetok

Meetings on IRC didn't work out.

2016-09-23 06:35 UTC, Diadlo commented
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/3740#-:-KSKk2BxF3ztw-JAdMi4:bnfp4nl)*
<!-- Sent from Reviewable.io -->

2016-09-23 09:20 UTC, sudden6 commented on README.md
> +There are available [IRC logs].
Should be "There are IRC logs available"

Sorry for not using reviewable, doesn't work on mobile...

2016-09-23 09:20 UTC, sudden6 requested changes

2016-09-23 09:47 UTC, zetok commented on README.md
> +There are available [IRC logs].
>Should be "There are IRC logs available"

Done.

>Sorry for not using reviewable, doesn't work on mobile...

No problem :)

2016-09-25 00:00 UTC, zetok commented
Updated.

2016-09-25 10:12 UTC, sudden6 approved these changes

2016-09-25 14:43 UTC, sudden6 commented
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/3740#-:-KSWn8r8FMt5S7Ftqp1E:bnfp4nl)*
<!-- Sent from Reviewable.io -->

2016-09-25 15:02 UTC, merged