fix: remove unnecessary variable when checking whether save is a TES
qTox/qTox pull request #3956
Opened 2016-12-08 18:03 UTC by zetok

There is a reason why magic length is not exposed via TES header –
knowing it is not needed. Client should check whether file is a TES with
a define that is provided in the public API.

2016-12-08 18:19 UTC, Diadlo requested changes

2016-12-08 18:19 UTC, Diadlo commented on src/persistence/profile.cpp
>   * @brief How much data we need to read to check if the file is encrypted.
Why you remove `@var`, but save `@brief` and `@note`?)

2016-12-08 18:19 UTC, Diadlo commented on src/persistence/profile.h
> -    static constexpr int encryptHeaderSize = 8;
I'm nut sure, but seems `TOX_PASS_ENCRYPTION_EXTRA_LENGTH == 80`, but `encryptHeaderSize == 8`. It's correct?

2016-12-08 18:20 UTC, zetok commented on src/persistence/profile.cpp
>   * @brief How much data we need to read to check if the file is encrypted.
Oh, right, done.

2016-12-08 18:20 UTC, zetok commented on src/persistence/profile.h
> -    static constexpr int encryptHeaderSize = 8;
Yep.

2016-12-08 18:21 UTC, Diadlo approved these changes

2016-12-08 18:21 UTC, Diadlo commented
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

---

Reviewed 1 of 2 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/3956#-:-KYUerE17XMTx6yGWGJW:bnfp4nl)*
<!-- Sent from Reviewable.io -->

2016-12-09 14:16 UTC, sudden6 commented
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/3956#-:-KYYwHxxMgKlaGPLCsrA:bnfp4nl)*
<!-- Sent from Reviewable.io -->

2016-12-09 19:35 UTC, merged