Search
qTox/qTox pull request #5191
Opened 2018-06-24 21:57 UTC by TriKriSta

Add settings for search:
Start search from the end of the chat
Start searching from the beginning
Start search from a specific date

Search with the case sensitive.
Search whole words only
Search use regular expressions

- [ ] Commits follow our [git commit guidelines](https://github.com/qTox/qTox/blob/master/CONTRIBUTING.md#git-commit-guidelines)
![screenshot_20180625_004523](https://user-images.githubusercontent.com/2956022/41824019-fb5c8284-7811-11e8-9a47-5a30326c8891.png)
![screenshot_20180625_004557](https://user-images.githubusercontent.com/2956022/41824020-ff623f36-7811-11e8-8187-da88d199c5e0.png)
![screenshot_20180625_004626](https://user-images.githubusercontent.com/2956022/41824023-032886fc-7812-11e8-83a5-583be1178bfa.png)

2018-06-25 06:13 UTC, sudden6 commented
Great Idea!

This seems to have build problems atm: https://travis-ci.org/qTox/qTox/jobs/396179682#L2643

2018-06-26 18:50 UTC, TriKriSta commented
I fixed

2018-06-28 07:08 UTC, sudden6 commented
I did a very short review, overall I see no major issues, but a bit more comments and documentation would be nice. We will definitely need some time to review this, since it's quite a big PR.

---

Reviewed 2 of 28 files at r1.
Review status: 0 of 1 LGTMs obtained

---

*[src/persistence/history.cpp, line 331 at r2](https://reviewable.io/reviews/qtox/qtox/5191#-LG4AtQPCccAnqOlSMWD:-LG4AtQPCccAnqOlSMWE:bebtln4) ([raw file](https://github.com/qtox/qtox/blob/d1afc7f6dfa13c0570e1c37e3bede37a5a1f13a8/src/persistence/history.cpp#L331)):*
> ```cpp
>     switch (parameter.filter) {
>     case FilterSearch::Register:
>         message = QString("message LIKE '%%1%'").arg(phrase);
> ```

This whole file could probably profit from the rules in https://github.com/qTox/qTox/blob/master/doc/coding_standards.md#strings

---

*[src/persistence/db/rawdatabase.cpp, line 721 at r2](https://reviewable.io/reviews/qtox/qtox/5191#-LG4BLqu6ZknIhvwaj6o:-LG4BLqu6ZknIhvwaj6p:b-a8llcg) ([raw file](https://github.com/qtox/qtox/blob/d1afc7f6dfa13c0570e1c37e3bede37a5a1f13a8/src/persistence/db/rawdatabase.cpp#L721)):*
> ```cpp
> }
> 
> void RawDatabase::regexpInsensitive(sqlite3_context* ctx, int argc, sqlite3_value** argv)
> ```

A bit of documentation for these functions would be good.

---

*[src/widget/searchform.h, line 38 at r2](https://reviewable.io/reviews/qtox/qtox/5191#-LG4BUGa7sdcZvUddHBg:-LG4BUGa7sdcZvUddHBh:b5r1p1w) ([raw file](https://github.com/qtox/qtox/blob/d1afc7f6dfa13c0570e1c37e3bede37a5a1f13a8/src/widget/searchform.h#L38)):*
> ```objc
>     void removeSearchPhrase();
>     QString getSearchPhrase() const;
>     ParameterSearch getParametrSearch();
> ```

typo: `getParameterSearch`

---

*[src/widget/form/chatform.cpp, line 543 at r2](https://reviewable.io/reviews/qtox/qtox/5191#-LG4CC7P1MbjyvNUDNG3:-LG4CC7P1MbjyvNUDNG4:b-t5xz7k) ([raw file](https://github.com/qtox/qtox/blob/d1afc7f6dfa13c0570e1c37e3bede37a5a1f13a8/src/widget/form/chatform.cpp#L543)):*
> ```cpp
> 
>     if (startLine == 0 && loadHistory(phrase, parameter)) {
> //        QString pk = f->getPublicKey().toString();
> ```

no commented out code in the final revision please

---


*Comments from [Reviewable](https://reviewable.io/reviews/qtox/qtox/5191#-:-LG4CqdoEFUzbfK9a6Dr:b-ty4cqo)*
<!-- Sent from Reviewable.io -->

2018-06-29 17:06 UTC, TriKriSta commented
Review status: 0 of 1 LGTMs obtained

---

*[src/persistence/history.cpp, line 331 at r2](https://reviewable.io/reviews/qtox/qtox/5191#-LG4AtQPCccAnqOlSMWD:-LGBUqgPCfaAJCrvNXrf:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/d1afc7f6dfa13c0570e1c37e3bede37a5a1f13a8/src/persistence/history.cpp#L331)):*
<details><summary><i>Previously, sudden6 wrote…</i></summary><blockquote>

This whole file could probably profit from the rules in https://github.com/qTox/qTox/blob/master/doc/coding_standards.md#strings
</blockquote></details>

Done.

---

*[src/persistence/db/rawdatabase.cpp, line 721 at r2](https://reviewable.io/reviews/qtox/qtox/5191#-LG4BLqu6ZknIhvwaj6o:-LGBUvJ19Un1Uw-r_ycZ:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/d1afc7f6dfa13c0570e1c37e3bede37a5a1f13a8/src/persistence/db/rawdatabase.cpp#L721)):*
<details><summary><i>Previously, sudden6 wrote…</i></summary><blockquote>

A bit of documentation for these functions would be good.
</blockquote></details>

Done.

---

*[src/widget/searchform.h, line 38 at r2](https://reviewable.io/reviews/qtox/qtox/5191#-LG4BUGa7sdcZvUddHBg:-LGBUwzbDGDwyScJEN2I:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/d1afc7f6dfa13c0570e1c37e3bede37a5a1f13a8/src/widget/searchform.h#L38)):*
<details><summary><i>Previously, sudden6 wrote…</i></summary><blockquote>

typo: `getParameterSearch`
</blockquote></details>

Done.

---

*[src/widget/form/chatform.cpp, line 543 at r2](https://reviewable.io/reviews/qtox/qtox/5191#-LG4CC7P1MbjyvNUDNG3:-LGBUyGv9dt02IW9HodL:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/d1afc7f6dfa13c0570e1c37e3bede37a5a1f13a8/src/widget/form/chatform.cpp#L543)):*
<details><summary><i>Previously, sudden6 wrote…</i></summary><blockquote>

no commented out code in the final revision please
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/qtox/qtox/5191)*
<!-- Sent from Reviewable.io -->

2018-07-01 17:30 UTC, Talkless commented
Review status: 0 of 1 LGTMs obtained

---

*[src/persistence/history.cpp, line 342 at r3](https://reviewable.io/reviews/qtox/qtox/5191#-LGLgRS7El61LxHntZKn:-LGLgRS7El61LxHntZKo:b2py0d5) ([raw file](https://github.com/qtox/qtox/blob/74468fde32b67ab27dc8fc8af6e0a89619f1edbb/src/persistence/history.cpp#L342)):*
> ```cpp
>         break;
>     case FilterSearch::WordsOnly:
>         message = QStringLiteral("message REGEXP '\\b%1\\b'").arg(phrase.toLower());
> ```

Shouldn't `phrase` be escaped against regexp and SQL?
Will it work if someone searches for `\` or `'` ?

---

*[src/persistence/db/rawdatabase.cpp, line 745 at r3](https://reviewable.io/reviews/qtox/qtox/5191#-LGLhabS00R6KCGabb2B:-LGLhabS00R6KCGabb2C:b9m9ak) ([raw file](https://github.com/qtox/qtox/blob/74468fde32b67ab27dc8fc8af6e0a89619f1edbb/src/persistence/db/rawdatabase.cpp#L745)):*
> ```cpp
> void RawDatabase::regexp(sqlite3_context* ctx, int argc, sqlite3_value** argv, const Qt::CaseSensitivity cs)
> {
>     QRegExp regex;
> ```

QRegularExpression should be used instead, it's a replacement:
https://doc.qt.io/qt-5/qregularexpression.html#notes-for-qregexp-users

---

*[src/persistence/db/rawdatabase.cpp, line 746 at r3](https://reviewable.io/reviews/qtox/qtox/5191#-LGLiQtkBYZK6mzU3i7m:-LGLiQtkBYZK6mzU3i7n:ba0elat) ([raw file](https://github.com/qtox/qtox/blob/74468fde32b67ab27dc8fc8af6e0a89619f1edbb/src/persistence/db/rawdatabase.cpp#L746)):*
> ```cpp
> {
>     QRegExp regex;
>     QString str1((const char*)sqlite3_value_text(argv[0]));
> ```

could be `const QString`. Maybe static_cast or reinterpret_cast for more idiomatic c++. 

---

*[src/persistence/db/rawdatabase.cpp, line 752 at r3](https://reviewable.io/reviews/qtox/qtox/5191#-LGLihZm4A6mxPIFALUb:-LGLihZm4A6mxPIFALUc:b-ry5h2s) ([raw file](https://github.com/qtox/qtox/blob/74468fde32b67ab27dc8fc8af6e0a89619f1edbb/src/persistence/db/rawdatabase.cpp#L752)):*
> ```cpp
>     regex.setCaseSensitivity(cs);
> 
>     bool b = str2.contains(regex);
> ```

const bool

---

*[src/widget/searchform.h, line 61 at r3](https://reviewable.io/reviews/qtox/qtox/5191#-LGLitP3-c6Zad62mKyl:-LGLitP4AlcCCBe0bvNV:b886d2i) ([raw file](https://github.com/qtox/qtox/blob/74468fde32b67ab27dc8fc8af6e0a89619f1edbb/src/widget/searchform.h#L61)):*
> ```objc
>     ParameterSearch parameter;
> 
>     bool isActiveSettings;
> ```

Could be initialzied here `bool isActiverSettings{false}` instead of constructor body.

---

*[src/widget/searchform.cpp, line 136 at r3](https://reviewable.io/reviews/qtox/qtox/5191#-LGLk6IgCXGpyE9tzzA_:-LGLk6IgCXGpyE9tzzAa:b-4hm03y) ([raw file](https://github.com/qtox/qtox/blob/74468fde32b67ab27dc8fc8af6e0a89619f1edbb/src/widget/searchform.cpp#L136)):*
> ```cpp
> void SearchForm::changedSearchPhrase(const QString& text)
> {
>     QString l = text.right(1);
> ```

`QString l` could be moved below first if statement, it's not needed yet.

---

*[src/widget/searchform.cpp, line 142 at r3](https://reviewable.io/reviews/qtox/qtox/5191#-LGLkBP-1l9_-Td3wQWP:-LGLkBP-1l9_-Td3wQWQ:b6xu04i) ([raw file](https://github.com/qtox/qtox/blob/74468fde32b67ab27dc8fc8af6e0a89619f1edbb/src/widget/searchform.cpp#L142)):*
> ```cpp
>     }
> 
>     if (!l.isEmpty() && l != " " && l[0].isSpace()) {
> ```

How it can be *not* eaqual to space `" "` and also be `isSpace()` at the same time?

Note that `l` is size of 1 (or empty) because of `.right(1)`.

---

*[src/widget/searchform.cpp, line 149 at r3](https://reviewable.io/reviews/qtox/qtox/5191#-LGLm75a5BAjLfD7a6t9:-LGLm75a5BAjLfD7a6tA:bqjuf21) ([raw file](https://github.com/qtox/qtox/blob/74468fde32b67ab27dc8fc8af6e0a89619f1edbb/src/widget/searchform.cpp#L149)):*
> ```cpp
>     searchPhrase = text;
>     isChangedPhrase = true;
>     if (isActiveSettings) {
> ```

maybe simplify into single if statement `if (isActiveSettings && start...)`

---

*[src/widget/searchform.cpp, line 194 at r3](https://reviewable.io/reviews/qtox/qtox/5191#-LGLmMre0rU74v-jyLHD:-LGLmMre0rU74v-jyLHE:b-pzx5we) ([raw file](https://github.com/qtox/qtox/blob/74468fde32b67ab27dc8fc8af6e0a89619f1edbb/src/widget/searchform.cpp#L194)):*
> ```cpp
> 
>     if (isActiveSettings) {
>         settingsButton->setProperty("state", "red");
> ```

QStringLiteral("red").

---

*[src/widget/searchtypes.h, line 24 at r3](https://reviewable.io/reviews/qtox/qtox/5191#-LGLmXxB3sydqbA66Q-O:-LGLmXxB3sydqbA66Q-P:b7lqtww) ([raw file](https://github.com/qtox/qtox/blob/74468fde32b67ab27dc8fc8af6e0a89619f1edbb/src/widget/searchtypes.h#L24)):*
> ```objc
> 
> struct ParameterSearch {
>     FilterSearch filter;
> ```

consider initializing variables here, making constructor obsolete:
`
FilterSearch filter{FilterSrarch::None};
...
`

---

*[src/widget/searchtypes.h, line 35 at r3](https://reviewable.io/reviews/qtox/qtox/5191#-LGLnB-H4zuwE1CIzgIV:-LGLnB-H4zuwE1CIzgIW:bo79xzz) ([raw file](https://github.com/qtox/qtox/blob/74468fde32b67ab27dc8fc8af6e0a89619f1edbb/src/widget/searchtypes.h#L35)):*
> ```objc
>     }
> 
>     bool operator ==(const ParameterSearch& other) {
> ```

isUpdate comparison is intentionally skipped?

Could be simplifiend into one (though  a bit long) statement:
```
return filter == other.filter && 
    period == other.period && 
    date == other.date
```
Short-circuit return will be done automatically.

---

*[src/widget/form/chatform.cpp, line 506 at r3](https://reviewable.io/reviews/qtox/qtox/5191#-LGLp1WnA1XhyT2GZuyq:-LGLp1Wo7sFBlrC22Pak:bsv9i61) ([raw file](https://github.com/qtox/qtox/blob/74468fde32b67ab27dc8fc8af6e0a89619f1edbb/src/widget/form/chatform.cpp#L506)):*
> ```cpp
>     searchPoint = QPoint(1, -1);
> 
>     bool b = (parameter.period == PeriodSearch::WithTheFirst);
> ```

could be const b, cosnt b1. Also, maybe more desriptive names could be possible?

---

*[src/widget/form/chatform.cpp, line 510 at r3](https://reviewable.io/reviews/qtox/qtox/5191#-LGLp7fF6fLogl1A90Nv:-LGLp7fG8kZlZtipApAN:bqxhdeo) ([raw file](https://github.com/qtox/qtox/blob/74468fde32b67ab27dc8fc8af6e0a89619f1edbb/src/widget/form/chatform.cpp#L510)):*
> ```cpp
>     if (b || b1) {
>         if (b || (b1 && parameter.date < getFirstDate())) {
>             QString pk = f->getPublicKey().toString();
> ```

const QString

---

*[src/widget/form/chatform.cpp, line 521 at r3](https://reviewable.io/reviews/qtox/qtox/5191#-LGLpCD33_Fhn0lHMJcl:-LGLpCD33_Fhn0lHMJcm:bqxhdeo) ([raw file](https://github.com/qtox/qtox/blob/74468fde32b67ab27dc8fc8af6e0a89619f1edbb/src/widget/form/chatform.cpp#L521)):*
> ```cpp
>     } else {
>         if (parameter.period == PeriodSearch::BeforeDate && parameter.date < getFirstDate()) {
>             QString pk = f->getPublicKey().toString();
> ```

const QString

---

*[src/widget/form/chatform.cpp, line 1071 at r3](https://reviewable.io/reviews/qtox/qtox/5191#-LGLpMBkCaovDkZ-U_lR:-LGLpMBkCaovDkZ-U_lS:bqxhdeo) ([raw file](https://github.com/qtox/qtox/blob/74468fde32b67ab27dc8fc8af6e0a89619f1edbb/src/widget/form/chatform.cpp#L1071)):*
> ```cpp
> bool ChatForm::loadHistory(const QString& phrase, const ParameterSearch& parameter)
> {
>     QString pk = f->getPublicKey().toString();
> ```

const QString

---

*[src/widget/form/chatform.cpp, line 1072 at r3](https://reviewable.io/reviews/qtox/qtox/5191#-LGLpNvLBllGEW3UiKLb:-LGLpNvLBllGEW3UiKLc:boiek16) ([raw file](https://github.com/qtox/qtox/blob/74468fde32b67ab27dc8fc8af6e0a89619f1edbb/src/widget/form/chatform.cpp#L1072)):*
> ```cpp
> {
>     QString pk = f->getPublicKey().toString();
>     QDateTime newBaseDate = history->getDateWhereFindPhrase(pk, earliestMessage, phrase, parameter);
> ```

const QDateTime

---

*[src/widget/form/genericchatform.cpp, line 543 at r3](https://reviewable.io/reviews/qtox/qtox/5191#-LGLpd4CDvIJUikFCc4U:-LGLpd4CDvIJUikFCc4V:bepgpx7) ([raw file](https://github.com/qtox/qtox/blob/74468fde32b67ab27dc8fc8af6e0a89619f1edbb/src/widget/form/genericchatform.cpp#L543)):*
> ```cpp
> {
>     if (chatLine) {
>         Timestamp* timestamp = qobject_cast<Timestamp*>(chatLine->g [...]

2018-07-08 11:29 UTC, sudden6 requested changes
> Reviewed 15 of 28 files at r1, 4 of 12 files at r4.
> *[Reviewable](https://reviewable.io/reviews/qtox/qtox/5191)* status: 0 of 1 LGTMs obtained

___
*[.travis/build-ubuntu-14-04.sh, line 56 at r4](https://reviewable.io/reviews/qtox/qtox/5191#-LGtayAx-JIr7C-bGU54:-LGtayAx-JIr7C-bGU55:b-dti3z) ([raw file](https://github.com/qtox/qtox/blob/ea8bbfd8a531faa6ff06900a6db367757ddaa66a/.travis/build-ubuntu-14-04.sh#L56)):*
> ```Shell
> 
> # sqlite
> wget https://sqlite.org/2018/sqlite-autoconf-3240000.tar.gz
> ```

why do we need sqlite here? shouldn't sqlcipher provide everything we need?
___
*[src/chatlog/content/text.cpp, line 453 at r4](https://reviewable.io/reviews/qtox/qtox/5191#-LGtbE8r8RFDAQvFUKa5:-LGtbE8s-88mG8ECjm54:bhf3lws) ([raw file](https://github.com/qtox/qtox/blob/ea8bbfd8a531faa6ff06900a6db367757ddaa66a/src/chatlog/content/text.cpp#L453)):*
> ```cpp
> 
>         QTextCharFormat format;
>         format.setBackground(QBrush(QColor("#ff7626")));
> ```

did you invent this color or does it come from the theme? could you make it a constexpr somewhere?
___
*[src/widget/searchtypes.h, line 42 at r4](https://reviewable.io/reviews/qtox/qtox/5191#-LGtcPhiE35cGM2obJ45:-LGtcPhiE35cGM2obJ46:b-strcfl) ([raw file](https://github.com/qtox/qtox/blob/ea8bbfd8a531faa6ff06900a6db367757ddaa66a/src/widget/searchtypes.h#L42)):*
> ```objc
> class SearchExtraFunctions {
> public:
>     static QString generateFilterWordsOnly(const QString &phrase) {
> ```

Can you add a comment documenting the purpose of this function?
___
*[src/widget/form/searchsettingsform.h, line 5 at r4](https://reviewable.io/reviews/qtox/qtox/5191#-LGtdKw27nYMksUAyhz_:-LGtdKw27nYMksUAyhza:b-nnystf) ([raw file](https://github.com/qtox/qtox/blob/ea8bbfd8a531faa6ff06900a6db367757ddaa66a/src/widget/form/searchsettingsform.h#L5)):*
> ```objc
> 
> #include <QWidget>
> #include "../searchtypes.h"
> ```

please use the full path
___
*[src/widget/form/searchsettingsform.cpp, line 19 at r3](https://reviewable.io/reviews/qtox/qtox/5191#-LGLsYLQECvfPP6TiK9p:-LGtdR8FAm_aZEggAhdz:bngjs0r) ([raw file](https://github.com/qtox/qtox/blob/74468fde32b67ab27dc8fc8af6e0a89619f1edbb/src/widget/form/searchsettingsform.cpp#L19)):*
<details><summary><i>Previously, Talkless (Vincas Dargis) wrote…</i></summary><blockquote>

QStringLiteral.
Not sure about hardcoding styles here. Maintainers could comment more.
</blockquote></details>

A style file is needed, as @tox-user is rewriting themes support atm


<!-- Sent from Reviewable.io -->

2018-07-08 12:00 UTC, TriKriSta commented
@sudden6 What do I need to do with requested changes?

2018-07-08 12:16 UTC, sudden6 commented
@TriKriSta if you fixed a requested change, click the `Done` button on reviewable. Or do you mean something different?

2018-07-08 12:22 UTC, TriKriSta commented
@sudden6 I mean your merge pull request #5172 in my repository.

2018-07-08 12:27 UTC, sudden6 commented
@TriKriSta I don't know what you mean? this PR was in the qTox repo and is merged into master. typo?

2018-07-08 12:35 UTC, TriKriSta commented
@sudden6 Sorry, I didn't correctly understand the notice from GitHub

2018-07-08 14:47 UTC, Talkless reviewed
> *[Reviewable](https://reviewable.io/reviews/qtox/qtox/5191)* status: 0 of 1 LGTMs obtained

___
*[src/widget/searchtypes.h, line 42 at r4](https://reviewable.io/reviews/qtox/qtox/5191#-LGtcPhiE35cGM2obJ45:-LGuKfIuEEteAkcHON9i:b-3x0rie) ([raw file](https://github.com/qtox/qtox/blob/ea8bbfd8a531faa6ff06900a6db367757ddaa66a/src/widget/searchtypes.h#L42)):*
<details><summary><i>Previously, sudden6 wrote…</i></summary><blockquote>

Can you add a comment documenting the purpose of this function?
</blockquote></details>

Partially looks like  escaping. Escaping should be done with [QRegularExpresson::escape()](https://doc.qt.io/qt-5/qregularexpression.html#escape).
___
*[src/widget/searchtypes.h, line 51 at r5](https://reviewable.io/reviews/qtox/qtox/5191#-LGuJx46BSAGa8Wu1NpP:-LGuJx46BSAGa8Wu1NpQ:bfbauvr) ([raw file](https://github.com/qtox/qtox/blob/3c9015fc751748aba2fef8803e6661a6de1a9bc3/src/widget/searchtypes.h#L51)):*
> ```objc
>         QString filter = phrase;
> 
>         if (filter.contains("\\")) {
> ```

Contains has QLatin1String oveload, hence it should be `filter.contains(QLatin1String("\\"))`. Though actually it could be `.contains('\\')` (char).
___
*[src/widget/searchtypes.h, line 54 at r5](https://reviewable.io/reviews/qtox/qtox/5191#-LGuLWd_4Y6BQCT6OIXY:-LGuLWd_4Y6BQCT6OIXZ:b9rtt9h) ([raw file](https://github.com/qtox/qtox/blob/3c9015fc751748aba2fef8803e6661a6de1a9bc3/src/widget/searchtypes.h#L54)):*
> ```objc
>             filter.replace("\\", "\\\\");
> 
>             if (filter.left(1) != "\\") {
> ```

`.front() != '\\'`
___
*[src/widget/searchtypes.h, line 57 at r5](https://reviewable.io/reviews/qtox/qtox/5191#-LGuLYxt8_tfvgf1iRvz:-LGuLYxt8_tfvgf1iRw-:bbeq4wx) ([raw file](https://github.com/qtox/qtox/blob/3c9015fc751748aba2fef8803e6661a6de1a9bc3/src/widget/searchtypes.h#L57)):*
> ```objc
>                 filter = "\\b" + filter;
>             }
>             if (filter.right(1) != "\\") {
> ```

`.back() != '\\'`
___
*[src/widget/form/genericchatform.cpp, line 641 at r3](https://reviewable.io/reviews/qtox/qtox/5191#-LGLqcreEz21zS3pi7AX:-LGuLwmv2pEK_xxfxkFS:b-hf6xsw) ([raw file](https://github.com/qtox/qtox/blob/74468fde32b67ab27dc8fc8af6e0a89619f1edbb/src/widget/form/genericchatform.cpp#L641)):*
<details><summary><i>Previously, Talkless (Vincas Dargis) wrote…</i></summary><blockquote>

phrase probaly needs to be escaped here too against regexp? What if searched string contains `\`, or any regex-special symbol?

Could be QStringLiteral("\\b%1\\b").

Or if you care enougth, pedantic fast implementation would be
`QLatin1String("\\b") % phrase % QLatin1String("\\b")` with 'QStringBuilder` included.
See https://wiki.qt.io/Using_QString_Effectively#QStringBuilder_:_Fast_QString_concatenation
</blockquote></details>

new `generateFilterWordsOnly()` does not handle all RegExp special symbols.


<!-- Sent from Reviewable.io -->

2018-07-08 21:16 UTC, TriKriSta commented
___
*[src/widget/form/genericchatform.cpp, line 641 at r3](https://reviewable.io/reviews/qtox/qtox/5191#-LGLqcreEz21zS3pi7AX:-LGtcEwPEuFOIIcxQ2Ou:b-s2x2u) ([raw file](https://github.com/qtox/qtox/blob/74468fde32b67ab27dc8fc8af6e0a89619f1edbb/src/widget/form/genericchatform.cpp#L641)):*
<details><summary><i>Previously, Talkless (Vincas Dargis) wrote…</i></summary><blockquote>

phrase probaly needs to be escaped here too against regexp? What if searched string contains `\`, or any regex-special symbol?

Could be QStringLiteral("\\b%1\\b").

Or if you care enougth, pedantic fast implementation would be
`QLatin1String("\\b") % phrase % QLatin1String("\\b")` with 'QStringBuilder` included.
See https://wiki.qt.io/Using_QString_Effectively#QStringBuilder_:_Fast_QString_concatenation
</blockquote></details>

I added the special function


<!-- Sent from Reviewable.io -->

2018-07-08 21:17 UTC, TriKriSta reviewed
> *[Reviewable](https://reviewable.io/reviews/qtox/qtox/5191)* status: 0 of 1 LGTMs obtained

___
*[.travis/build-ubuntu-14-04.sh, line 56 at r4](https://reviewable.io/reviews/qtox/qtox/5191#-LGtayAx-JIr7C-bGU54:-LGtjc5O215TYEp8bBUe:b-mo0yvp) ([raw file](https://github.com/qtox/qtox/blob/ea8bbfd8a531faa6ff06900a6db367757ddaa66a/.travis/build-ubuntu-14-04.sh#L56)):*
> why do we need sqlite here? shouldn't sqlcipher provide everything we need?
sqlcipher doesn't have sqlite3_create_function
___
*[src/chatlog/content/text.cpp, line 453 at r4](https://reviewable.io/reviews/qtox/qtox/5191#-LGtbE8r8RFDAQvFUKa5:-LGtk99M8JlDn8xvvmNF:bocjgh8) ([raw file](https://github.com/qtox/qtox/blob/ea8bbfd8a531faa6ff06900a6db367757ddaa66a/src/chatlog/content/text.cpp#L453)):*
<details><summary><i>Previously, sudden6 wrote…</i></summary><blockquote>

did you invent this color or does it come from the theme? could you make it a constexpr somewhere?
</blockquote></details>

I invented this color
___
*[src/persistence/history.cpp, line 342 at r3](https://reviewable.io/reviews/qtox/qtox/5191#-LGLgRS7El61LxHntZKn:-LGtZNzm8RII5i3pqY88:bh2ifl4) ([raw file](https://github.com/qtox/qtox/blob/74468fde32b67ab27dc8fc8af6e0a89619f1edbb/src/persistence/history.cpp#L342)):*
<details><summary><i>Previously, Talkless (Vincas Dargis) wrote…</i></summary><blockquote>

Shouldn't `phrase` be escaped against regexp and SQL?
Will it work if someone searches for `\` or `'` ?
</blockquote></details>

yes, already
___
*[src/persistence/db/rawdatabase.cpp, line 745 at r3](https://reviewable.io/reviews/qtox/qtox/5191#-LGLhabS00R6KCGabb2B:-LGtZa_f0TNjf_Z6H-PY:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/74468fde32b67ab27dc8fc8af6e0a89619f1edbb/src/persistence/db/rawdatabase.cpp#L745)):*
<details><summary><i>Previously, Talkless (Vincas Dargis) wrote…</i></summary><blockquote>

QRegularExpression should be used instead, it's a replacement:
https://doc.qt.io/qt-5/qregularexpression.html#notes-for-qregexp-users
</blockquote></details>

Done.
___
*[src/persistence/db/rawdatabase.cpp, line 746 at r3](https://reviewable.io/reviews/qtox/qtox/5191#-LGLiQtkBYZK6mzU3i7m:-LGtZdSQ-cjpK8VpE53L:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/74468fde32b67ab27dc8fc8af6e0a89619f1edbb/src/persistence/db/rawdatabase.cpp#L746)):*
<details><summary><i>Previously, Talkless (Vincas Dargis) wrote…</i></summary><blockquote>

could be `const QString`. Maybe static_cast or reinterpret_cast for more idiomatic c++. 
</blockquote></details>

Done.
___
*[src/persistence/db/rawdatabase.cpp, line 752 at r3](https://reviewable.io/reviews/qtox/qtox/5191#-LGLihZm4A6mxPIFALUb:-LGt_YMSBhvcpLrfDkhf:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/74468fde32b67ab27dc8fc8af6e0a89619f1edbb/src/persistence/db/rawdatabase.cpp#L752)):*
<details><summary><i>Previously, Talkless (Vincas Dargis) wrote…</i></summary><blockquote>

const bool
</blockquote></details>

Done.
___
*[src/widget/searchform.h, line 61 at r3](https://reviewable.io/reviews/qtox/qtox/5191#-LGLitP3-c6Zad62mKyl:-LGt_cG0CYM_6fkc1-EF:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/74468fde32b67ab27dc8fc8af6e0a89619f1edbb/src/widget/searchform.h#L61)):*
<details><summary><i>Previously, Talkless (Vincas Dargis) wrote…</i></summary><blockquote>

Could be initialzied here `bool isActiverSettings{false}` instead of constructor body.
</blockquote></details>

Done.
___
*[src/widget/searchform.cpp, line 136 at r3](https://reviewable.io/reviews/qtox/qtox/5191#-LGLk6IgCXGpyE9tzzA_:-LGt_l9m3iNIl2Bqb0Mg:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/74468fde32b67ab27dc8fc8af6e0a89619f1edbb/src/widget/searchform.cpp#L136)):*
<details><summary><i>Previously, Talkless (Vincas Dargis) wrote…</i></summary><blockquote>

`QString l` could be moved below first if statement, it's not needed yet.
</blockquote></details>

Done.
___
*[src/widget/searchform.cpp, line 142 at r3](https://reviewable.io/reviews/qtox/qtox/5191#-LGLkBP-1l9_-Td3wQWP:-LGt_tFE0SNYKPYZK0qs:b4hy7mk) ([raw file](https://github.com/qtox/qtox/blob/74468fde32b67ab27dc8fc8af6e0a89619f1edbb/src/widget/searchform.cpp#L142)):*
> How it can be not eaqual to space " " and also be isSpace() at the same time?
> Note that l is size of 1 (or empty) because of .right(1)
for example: isSpace is true if letter == "\n"
___
*[src/widget/searchform.cpp, line 149 at r3](https://reviewable.io/reviews/qtox/qtox/5191#-LGLm75a5BAjLfD7a6t9:-LGtatPq00UhmsbbDOT2:b-r7skk) ([raw file](https://github.com/qtox/qtox/blob/74468fde32b67ab27dc8fc8af6e0a89619f1edbb/src/widget/searchform.cpp#L149)):*
<details><summary><i>Previously, Talkless (Vincas Dargis) wrote…</i></summary><blockquote>

maybe simplify into single if statement `if (isActiveSettings && start...)`
</blockquote></details>

then need to change the second part "else if (!isActiveSettings)"
___
*[src/widget/searchform.cpp, line 194 at r3](https://reviewable.io/reviews/qtox/qtox/5191#-LGLmMre0rU74v-jyLHD:-LGtbfqX8b5ufVmzpje-:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/74468fde32b67ab27dc8fc8af6e0a89619f1edbb/src/widget/searchform.cpp#L194)):*
<details><summary><i>Previously, Talkless (Vincas Dargis) wrote…</i></summary><blockquote>

QStringLiteral("red").
</blockquote></details>

Done.
___
*[src/widget/searchtypes.h, line 24 at r3](https://reviewable.io/reviews/qtox/qtox/5191#-LGLmXxB3sydqbA66Q-O:-LGtbiK6ExcN1idts2MC:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/74468fde32b67ab27dc8fc8af6e0a89619f1edbb/src/widget/searchtypes.h#L24)):*
<details><summary><i>Previously, Talkless (Vincas Dargis) wrote…</i></summary><blockquote>

consider initializing variables here, making constructor obsolete:
`
FilterSearch filter{FilterSrarch::None};
...
`
</blockquote></details>

Done.
___
*[src/widget/searchtypes.h, line 35 at r3](https://reviewable.io/reviews/qtox/qtox/5191#-LGLnB-H4zuwE1CIzgIV:-LGtbjhlEfzZ58mWxciv:b-oprzrn) ([raw file](https://github.com/qtox/qtox/blob/74468fde32b67ab27dc8fc8af6e0a89619f1edbb/src/widget/searchtypes.h#L35)):*
> isUpdate comparison is intentionally skipped?
yes
___
*[src/widget/searchtypes.h, line 42 at r4](https://reviewable.io/reviews/qtox/qtox/5191#-LGtcPhiE35cGM2obJ45:-LGvjh8ZEcUAdHt0tgOB:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/ea8bbfd8a531faa6ff06900a6db367757ddaa66a/src/widget/searchtypes.h#L42)):*
<details><summary><i>Previously, Talkless (Vincas Dargis) wrote…</i></summary><blockquote>

Partially looks like  escaping. Escaping should be done with [QRegularExpresson::escape()](https://doc.qt.io/qt-5/qregularexpression.html#escape).
</blockquote></details>

Done.
___
*[src/widget/searchtypes.h, line 51 at r5](https://reviewable.io/reviews/qtox/qtox/5191#-LGuJx46BSAGa8Wu1NpP:-LGvjjCs4MUeUWeZo56N:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/3c9015fc751748aba2fef8803e6661a6de1a9bc3/src/widget/searchtypes.h#L51)):*
<details><summary><i>Previously, Talkless (Vincas Dargis) wrote…</i></summary><blockquote>

Contains has QLatin1String oveload, hence it should be `filter.contains(QLatin1String("\\"))`. Though actually it could be `.contains('\\')` (char).
</blockquote></details>

Done.
___
*[src/widget/searchtypes.h, line 54 at r5](https://reviewable.io/reviews/qtox/qtox/5191#-LGuLWd_4Y6BQCT6OIXY:-LGvjvgJCT4Ii4bxOAVJ:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/3c9015fc751748aba2fef8803e6661a6de1a9bc3/src/widget/searchtypes.h#L54)):*
<details><summary><i>Previously, Talkless (Vincas Dargis) wrote…</i></summary><blockquote>

`.front() != '\\'`
</blockquote></details>

Done.
___
*[src/widget/searchtypes.h, line 57 at r5](https://reviewable.io/reviews/qtox/qtox/5191#-LGuLYxt8_tfvgf1iRvz:-LGvjwIQBwDZKt-R8zkp:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/3c9015fc751748aba2fef8803e6661a6de1a9bc3/src/widget/searchtypes.h#L57)):*
<details><summary><i>Previously, Talkless (Vincas Dargis) wrote…</i></summary><blockquote>

`.back() != '\\'`
</blockquote></details>

Done.
___
*[src/widget/ [...]

2018-07-08 22:04 UTC, sudden6 requested changes
> Reviewed 6 of 7 files at r5.
> *[Reviewable](https://reviewable.io/reviews/qtox/qtox/5191)* status: 0 of 1 LGTMs obtained

___
*[.travis/build-ubuntu-14-04.sh, line 56 at r4](https://reviewable.io/reviews/qtox/qtox/5191#-LGtayAx-JIr7C-bGU54:-LGvtdSqDgR0C7On6HDp:b3fvhko) ([raw file](https://github.com/qtox/qtox/blob/ea8bbfd8a531faa6ff06900a6db367757ddaa66a/.travis/build-ubuntu-14-04.sh#L56)):*
<details><summary><i>Previously, TriKriSta wrote…</i></summary><blockquote>

> why do we need sqlite here? shouldn't sqlcipher provide everything we need?
sqlcipher doesn't have sqlite3_create_function
</blockquote></details>

on my system it has this function (in `/usr/include/sqlcipher/sqlite3.h`), maybe we just need to update sqlcipher in the build system? As far as I understood sqlcipher extends sqlite3 so it should have all the functions and we shouldn't need sqlite3 directly.
___
*[src/chatlog/content/text.cpp, line 453 at r4](https://reviewable.io/reviews/qtox/qtox/5191#-LGtbE8r8RFDAQvFUKa5:-LGvtqkB5yNRWA6FXwpn:b32wtd) ([raw file](https://github.com/qtox/qtox/blob/ea8bbfd8a531faa6ff06900a6db367757ddaa66a/src/chatlog/content/text.cpp#L453)):*
<details><summary><i>Previously, TriKriSta wrote…</i></summary><blockquote>

I invented this color
</blockquote></details>

ok
___
*[src/widget/form/searchsettingsform.cpp, line 19 at r3](https://reviewable.io/reviews/qtox/qtox/5191#-LGLsYLQECvfPP6TiK9p:-LGvuaY0BQPPlAVV3B8M:b32wtd) ([raw file](https://github.com/qtox/qtox/blob/74468fde32b67ab27dc8fc8af6e0a89619f1edbb/src/widget/form/searchsettingsform.cpp#L19)):*
<details><summary><i>Previously, TriKriSta wrote…</i></summary><blockquote>

I added file
</blockquote></details>

ok


<!-- Sent from Reviewable.io -->

2018-07-10 17:39 UTC, Talkless reviewed
> *[Reviewable](https://reviewable.io/reviews/qtox/qtox/5191)* status: 0 of 1 LGTMs obtained

___
*[src/chatlog/content/text.h, line 39 at r6](https://reviewable.io/reviews/qtox/qtox/5191#-LH49KNjCmttwnsvulWg:-LH49KNjCmttwnsvulWh:b-m7hdjv) ([raw file](https://github.com/qtox/qtox/blob/42f5ac67e7b5afee1d86807346e19592d91bf489/src/chatlog/content/text.h#L39)):*
> ```objc
> 
>     void setText(const QString& txt);
>     void selectText(const QString& txt, const std::pair<int, int>& point);
> ```

Generally it is said that objects not bigger than two-three pointers should not be passed via references/pointers (unless pointers semantics is needed as out parameters or need for nullptr) to avoid useless indirection  (see https://github.com/isocpp/CppCoreGuidelines/blob/master/CppCoreGuidelines.md#Rf-in). Two ints are just a pointer-size and std::pair does not perform reference counting, it could be passed just by value.

Though you can ignore this as we are kinda accustomed to pass user-defined objects via references I guess.
___
*[src/chatlog/content/text.h, line 100 at r6](https://reviewable.io/reviews/qtox/qtox/5191#-LH4BQcE-8gDpElgjQ_G:-LH4BQcE-8gDpElgjQ_H:bgr51gl) ([raw file](https://github.com/qtox/qtox/blob/42f5ac67e7b5afee1d86807346e19592d91bf489/src/chatlog/content/text.h#L100)):*
> ```objc
>     QString defStyleSheet;
>     QColor color;
>     const QColor colorHighlight{"#ff7626"};
> ```

Another hard-coded color?
___
*[src/persistence/history.cpp, line 406 at r6](https://reviewable.io/reviews/qtox/qtox/5191#-LH4CWyqDAeqzP7pSxBp:-LH4Bswh8EqD9DwdGNR9:b1d5ftl) ([raw file](https://github.com/qtox/qtox/blob/42f5ac67e7b5afee1d86807346e19592d91bf489/src/persistence/history.cpp#L406)):*
> ```cpp
> QDateTime History::getStartDateChatHistory(const QString &friendPk)
> {
>     QList<QDateTime> counts;
> ```

Using container here is kinda misleading I believe. Query returns just one element (due to LIMIT 1) or none, yes? Couldn't it be just a default-constructor QDateTime()? If callback is called and QDateTime object is re-assigned, it will not be `QDateTime::isNull` any more. 

Thoug I might be misunderstanding something here.
___
*[src/widget/searchform.cpp, line 142 at r3](https://reviewable.io/reviews/qtox/qtox/5191#-LGLkBP-1l9_-Td3wQWP:-LH4DaE1979nLJY3Jws3:b-4mm725) ([raw file](https://github.com/qtox/qtox/blob/74468fde32b67ab27dc8fc8af6e0a89619f1edbb/src/widget/searchform.cpp#L142)):*
<details><summary><i>Previously, TriKriSta wrote…</i></summary><blockquote>

> How it can be not eaqual to space " " and also be isSpace() at the same time?
> Note that l is size of 1 (or empty) because of .right(1)
for example: isSpace is true if letter == "\n"
</blockquote></details>

Oh right, `isSpace()` means *whitespace*. Sorry.
___
*[src/widget/searchform.cpp, line 149 at r3](https://reviewable.io/reviews/qtox/qtox/5191#-LGLm75a5BAjLfD7a6t9:-LH4DzE495e6qo09T0gt:b-jz2m3u) ([raw file](https://github.com/qtox/qtox/blob/74468fde32b67ab27dc8fc8af6e0a89619f1edbb/src/widget/searchform.cpp#L149)):*
<details><summary><i>Previously, TriKriSta wrote…</i></summary><blockquote>

then need to change the second part "else if (!isActiveSettings)"
</blockquote></details>

Right, missed that else.
___
*[src/widget/form/genericchatform.cpp, line 543 at r3](https://reviewable.io/reviews/qtox/qtox/5191#-LGLpd4CDvIJUikFCc4U:-LH4ENJaAm4pQert0uwi:b-6rdf3f) ([raw file](https://github.com/qtox/qtox/blob/74468fde32b67ab27dc8fc8af6e0a89619f1edbb/src/widget/form/genericchatform.cpp#L543)):*
<details><summary><i>Previously, TriKriSta wrote…</i></summary><blockquote>

getTime()  isn't const
</blockquote></details>

Ok, but pointer itself is not change is this function, so it could be "at least" `Timestamp* const timestamp`.
___
*[src/widget/form/genericchatform.cpp, line 600 at r6](https://reviewable.io/reviews/qtox/qtox/5191#-LH4FO229u3OkWi3ftb5:-LH4FO229u3OkWi3ftb6:b-oo03e5) ([raw file](https://github.com/qtox/qtox/blob/42f5ac67e7b5afee1d86807346e19592d91bf489/src/widget/form/genericchatform.cpp#L600)):*
> ```cpp
>         }
>     } else if (parameter.period == PeriodSearch::BeforeDate) {
>         for (int i = lines.size() - 1; i >= 0; --i) {
> ```

It would be really cool to have these two loops (after and before) implemented in terms of algorithms. std::find_if(), in this BeforeDate case, could find element using reverse iterators, and you can get distance (for that startLine) via std::distance().

Reading these kind of raw loops is hard, and all these `- 1` and `>=` just screams as off-by-one horrors :) .

Leave it as is if you think using std::find_if is more complicated.


<!-- Sent from Reviewable.io -->

2018-07-10 17:54 UTC, Talkless reviewed
> *[Reviewable](https://reviewable.io/reviews/qtox/qtox/5191)* status: 0 of 1 LGTMs obtained

___
*[src/widget/searchtypes.h, line 57 at r5](https://reviewable.io/reviews/qtox/qtox/5191#-LGuLYxt8_tfvgf1iRvz:-LH4H-as8zX_xaVgth5b:bm924z3) ([raw file](https://github.com/qtox/qtox/blob/3c9015fc751748aba2fef8803e6661a6de1a9bc3/src/widget/searchtypes.h#L57)):*
<details><summary><i>Previously, TriKriSta wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Something's wrong with Reviewable, I don't see `back()` or `front()` being used.
___
*[src/widget/searchtypes.h, line 52 at r6](https://reviewable.io/reviews/qtox/qtox/5191#-LH4JYOy5zaHA3nWSLjY:-LH4JYOy5zaHA3nWSLjZ:b-cql3r8) ([raw file](https://github.com/qtox/qtox/blob/42f5ac67e7b5afee1d86807346e19592d91bf489/src/widget/searchtypes.h#L52)):*
> ```objc
>         QString filter = QRegularExpression::escape(phrase);
> 
>         QString symbols = {"\\[]/^$.|?*+(){}"};
> ```

const QString ... = QStringLiteral("\\....
___
*[src/widget/searchtypes.h, line 56 at r6](https://reviewable.io/reviews/qtox/qtox/5191#-LH4HmeT8yCRXouMwYpP:-LH4HmeT8yCRXouMwYpQ:b-o9t2cm) ([raw file](https://github.com/qtox/qtox/blob/42f5ac67e7b5afee1d86807346e19592d91bf489/src/widget/searchtypes.h#L56)):*
> ```objc
>         if (filter != phrase) {
>             if (filter.left(1) != QLatin1String("\\")) {
>                 filter = "\\b" + filter;
> ```

When appending, consider use `QLatin1String("\\b")`, it will know string size at compile time.
___
*[src/widget/searchtypes.h, line 58 at r6](https://reviewable.io/reviews/qtox/qtox/5191#-LH4JTYuAJv9qtQLfKH5:-LH4JTYuAJv9qtQLfKH6:b-uv5105) ([raw file](https://github.com/qtox/qtox/blob/42f5ac67e7b5afee1d86807346e19592d91bf489/src/widget/searchtypes.h#L58)):*
> ```objc
>                 filter = "\\b" + filter;
>             } else {
>                 filter = "(^|\\s)" + filter;
> ```

QLatin1String()
___
*[src/widget/searchtypes.h, line 61 at r6](https://reviewable.io/reviews/qtox/qtox/5191#-LH4JvcJ1H__CGGPCZQX:-LH4JvcJ1H__CGGPCZQY:bpggfsw) ([raw file](https://github.com/qtox/qtox/blob/42f5ac67e7b5afee1d86807346e19592d91bf489/src/widget/searchtypes.h#L61)):*
> ```objc
>             }
>             if (!symbols.contains(filter.right(1))) {
>                 filter += "\\b";
> ```

QLatin1String for both `+=`


<!-- Sent from Reviewable.io -->

2018-07-10 18:43 UTC, TriKriSta commented
___
*[src/chatlog/content/text.h, line 100 at r6](https://reviewable.io/reviews/qtox/qtox/5191#-LH4BQcE-8gDpElgjQ_G:-LH4Uztb5EbK8b3lUiDS:b5l5yde) ([raw file](https://github.com/qtox/qtox/blob/42f5ac67e7b5afee1d86807346e19592d91bf489/src/chatlog/content/text.h#L100)):*
<details><summary><i>Previously, Talkless (Vincas Dargis) wrote…</i></summary><blockquote>

Another hard-coded color?
</blockquote></details>

Yes, but I only moved it in this pull request, didn't add.


<!-- Sent from Reviewable.io -->

2018-07-10 18:50 UTC, TriKriSta commented
___
*[src/widget/searchtypes.h, line 57 at r5](https://reviewable.io/reviews/qtox/qtox/5191#-LGuLYxt8_tfvgf1iRvz:-LH4WLqv1iCtRY285O3u:b-kjbbct) ([raw file](https://github.com/qtox/qtox/blob/3c9015fc751748aba2fef8803e6661a6de1a9bc3/src/widget/searchtypes.h#L57)):*
<details><summary><i>Previously, Talkless (Vincas Dargis) wrote…</i></summary><blockquote>

Something's wrong with Reviewable, I don't see `back()` or `front()` being used.
</blockquote></details>


I used "push -f", probably it broke Reviewable


<!-- Sent from Reviewable.io -->

2018-07-12 20:55 UTC, sudden6 reviewed
> *[Reviewable](https://reviewable.io/reviews/qtox/qtox/5191)* status: 0 of 1 LGTMs obtained

___
*[src/chatlog/content/text.h, line 100 at r6](https://reviewable.io/reviews/qtox/qtox/5191#-LH4BQcE-8gDpElgjQ_G:-LH7KaCy4HOEpPePrtL5:b-wyjytq) ([raw file](https://github.com/qtox/qtox/blob/42f5ac67e7b5afee1d86807346e19592d91bf489/src/chatlog/content/text.h#L100)):*
<details><summary><i>Previously, TriKriSta wrote…</i></summary><blockquote>

Yes, but I only moved it in this pull request, didn't add.
</blockquote></details>

Can you make it a named constant too, while you're at it?


<!-- Sent from Reviewable.io -->

2018-07-13 22:18 UTC, sudden6 reviewed
> *[Reviewable](https://reviewable.io/reviews/qtox/qtox/5191)* status: 0 of 1 LGTMs obtained

___
*[src/chatlog/content/text.h, line 100 at r6](https://reviewable.io/reviews/qtox/qtox/5191#-LH4BQcE-8gDpElgjQ_G:-LHKiHS69jdSKKTTzV2Z:b4hwzln) ([raw file](https://github.com/qtox/qtox/blob/42f5ac67e7b5afee1d86807346e19592d91bf489/src/chatlog/content/text.h#L100)):*
<details><summary><i>Previously, sudden6 wrote…</i></summary><blockquote>

Can you make it a named constant too, while you're at it?
</blockquote></details>

ok, better now


<!-- Sent from Reviewable.io -->

2018-07-15 10:57 UTC, Talkless reviewed
> *[Reviewable](https://reviewable.io/reviews/qtox/qtox/5191)* status: 0 of 1 LGTMs obtained

___
*[src/widget/form/genericchatform.cpp, line 592 at r7](https://reviewable.io/reviews/qtox/qtox/5191#-LHSYvMN692OignXWCFB:-LHSYvMO6Z5svzgl0XzJ:b-thnrfd) ([raw file](https://github.com/qtox/qtox/blob/5668aa57c5da9d21aada4a506ce1771a247f138d/src/widget/form/genericchatform.cpp#L592)):*
> ```cpp
>         startLine = 0;
>     } else if (parameter.period == PeriodSearch::AfterDate) {
>         auto lambda = [=](const ChatLine::Ptr& item) {
> ```

`const auto lambda`, const lambdas are highly optimized-away. There was C++ Weekly episode about that (or was it a CPPCon talk..?).
___
*[src/widget/form/genericchatform.cpp, line 593 at r7](https://reviewable.io/reviews/qtox/qtox/5191#-LHSZWBM0PkyzbGMA5NM:-LHSZWBM0PkyzbGMA5NN:b-9d7pbf) ([raw file](https://github.com/qtox/qtox/blob/5668aa57c5da9d21aada4a506ce1771a247f138d/src/widget/form/genericchatform.cpp#L593)):*
> ```cpp
>     } else if (parameter.period == PeriodSearch::AfterDate) {
>         auto lambda = [=](const ChatLine::Ptr& item) {
>             auto d = getDate(item);
> ```

const auto d
___
*[src/widget/form/genericchatform.cpp, line 597 at r7](https://reviewable.io/reviews/qtox/qtox/5191#-LHSZ_2X2Y0rqhh-_wBF:-LHSZ_2X2Y0rqhh-_wBG:bqhzgx4) ([raw file](https://github.com/qtox/qtox/blob/5668aa57c5da9d21aada4a506ce1771a247f138d/src/widget/form/genericchatform.cpp#L597)):*
> ```cpp
>           };
> 
>         auto find = std::find_if(lines.begin(), lines.end(), lambda);
> ```

const auto find
___
*[src/widget/form/genericchatform.cpp, line 603 at r7](https://reviewable.io/reviews/qtox/qtox/5191#-LHSZdRc8DJynegDSXpU:-LHSZdRc8DJynegDSXpV:b-v9q9my) ([raw file](https://github.com/qtox/qtox/blob/5668aa57c5da9d21aada4a506ce1771a247f138d/src/widget/form/genericchatform.cpp#L603)):*
> ```cpp
>         }
>     } else if (parameter.period == PeriodSearch::BeforeDate) {
>         auto lambda = [=](const ChatLine::Ptr& item) {
> ```

const auto lambda
___
*[src/widget/form/genericchatform.cpp, line 604 at r7](https://reviewable.io/reviews/qtox/qtox/5191#-LHSZepz5uxLnJpWhGBv:-LHSZepz5uxLnJpWhGBw:b-9d7pbf) ([raw file](https://github.com/qtox/qtox/blob/5668aa57c5da9d21aada4a506ce1771a247f138d/src/widget/form/genericchatform.cpp#L604)):*
> ```cpp
>     } else if (parameter.period == PeriodSearch::BeforeDate) {
>         auto lambda = [=](const ChatLine::Ptr& item) {
>             auto d = getDate(item);
> ```

const auto d
___
*[src/widget/form/genericchatform.cpp, line 608 at r7](https://reviewable.io/reviews/qtox/qtox/5191#-LHSZg2b7omFmdEI856Z:-LHSZg2b7omFmdEI856_:bqhzgx4) ([raw file](https://github.com/qtox/qtox/blob/5668aa57c5da9d21aada4a506ce1771a247f138d/src/widget/form/genericchatform.cpp#L608)):*
> ```cpp
>           };
> 
>         auto find = std::find_if(lines.rbegin(), lines.rend(), lambda);
> ```

const auto find
___
*[src/widget/form/genericchatform.cpp, line 673 at r7](https://reviewable.io/reviews/qtox/qtox/5191#-LHS_KryEcCek8aBsSAf:-LHS_KrzCf8ZirCxaXwO:b-uucjpy) ([raw file](https://github.com/qtox/qtox/blob/5668aa57c5da9d21aada4a506ce1771a247f138d/src/widget/form/genericchatform.cpp#L673)):*
> ```cpp
>         }
> 
>         auto point = indexForSearchInLine(txt, phrase, parameter, searchUp);
> ```

could be const auto point?
___
*[src/widget/form/genericchatform.cpp, line 780 at r7](https://reviewable.io/reviews/qtox/qtox/5191#-LHS_Uta6RVaiWq-HmHJ:-LHS_Uta6RVaiWq-HmHK:b-ry5zhr) ([raw file](https://github.com/qtox/qtox/blob/5668aa57c5da9d21aada4a506ce1771a247f138d/src/widget/form/genericchatform.cpp#L780)):*
> ```cpp
> 
>         if (!exp.pattern().isEmpty()) {
>             auto match = exp.match(txt, startIndex);
> ```

const auto
___
*[src/widget/form/searchsettingsform.cpp, line 79 at r7](https://reviewable.io/reviews/qtox/qtox/5191#-LHSX51zBtpXkCIT40Y_:-LHSX520EqbTCJaP7VWP:b-egbvom) ([raw file](https://github.com/qtox/qtox/blob/5668aa57c5da9d21aada4a506ce1771a247f138d/src/widget/form/searchsettingsform.cpp#L79)):*
> ```cpp
> void SearchSettingsForm::updateStartDateLabel()
> {
>     ui->startDateLabel->setText(startDate.toString(QStringLiteral("dd.MM.yyyy")));
> ```

Wait a minute, why this date format is hardcoded into this particular one? Maybe it should be `Qt::DefaultLocaleShortDate` or something similarly locale-dependant?

What's the "qTox" way of handling dates @sudden6 ?


<!-- Sent from Reviewable.io -->

2018-07-15 12:35 UTC, sudden6 reviewed
> *[Reviewable](https://reviewable.io/reviews/qtox/qtox/5191)* status: 0 of 1 LGTMs obtained

___
*[src/widget/form/searchsettingsform.cpp, line 79 at r7](https://reviewable.io/reviews/qtox/qtox/5191#-LHSX51zBtpXkCIT40Y_:-LHSvWI18d7fOTUlXdAF:b-8vumhj) ([raw file](https://github.com/qtox/qtox/blob/5668aa57c5da9d21aada4a506ce1771a247f138d/src/widget/form/searchsettingsform.cpp#L79)):*
<details><summary><i>Previously, Talkless (Vincas Dargis) wrote…</i></summary><blockquote>

Wait a minute, why this date format is hardcoded into this particular one? Maybe it should be `Qt::DefaultLocaleShortDate` or something similarly locale-dependant?

What's the "qTox" way of handling dates @sudden6 ?
</blockquote></details>

Right, qTox has a setting for the date format, so it should use https://github.com/qTox/qTox/blob/master/src/persistence/settings.h#L443


<!-- Sent from Reviewable.io -->

2018-07-15 21:12 UTC, TriKriSta reviewed
> *[Reviewable](https://reviewable.io/reviews/qtox/qtox/5191)* status: 0 of 1 LGTMs obtained

___
*[.travis/build-ubuntu-14-04.sh, line 56 at r4](https://reviewable.io/reviews/qtox/qtox/5191#-LGtayAx-JIr7C-bGU54:-LHUXcbqDKOzArY5hEUe:b-7srhxh) ([raw file](https://github.com/qtox/qtox/blob/ea8bbfd8a531faa6ff06900a6db367757ddaa66a/.travis/build-ubuntu-14-04.sh#L56)):*
<details><summary><i>Previously, sudden6 wrote…</i></summary><blockquote>

on my system it has this function (in `/usr/include/sqlcipher/sqlite3.h`), maybe we just need to update sqlcipher in the build system? As far as I understood sqlcipher extends sqlite3 so it should have all the functions and we shouldn't need sqlite3 directly.
</blockquote></details>

I fixed it.
___
*[src/chatlog/content/text.h, line 39 at r6](https://reviewable.io/reviews/qtox/qtox/5191#-LH49KNjCmttwnsvulWg:-LHUXqnoAWRjMCLOWVFi:b-csj8qr) ([raw file](https://github.com/qtox/qtox/blob/42f5ac67e7b5afee1d86807346e19592d91bf489/src/chatlog/content/text.h#L39)):*
<details><summary><i>Previously, Talkless (Vincas Dargis) wrote…</i></summary><blockquote>

Generally it is said that objects not bigger than two-three pointers should not be passed via references/pointers (unless pointers semantics is needed as out parameters or need for nullptr) to avoid useless indirection  (see https://github.com/isocpp/CppCoreGuidelines/blob/master/CppCoreGuidelines.md#Rf-in). Two ints are just a pointer-size and std::pair does not perform reference counting, it could be passed just by value.

Though you can ignore this as we are kinda accustomed to pass user-defined objects via references I guess.
</blockquote></details>

I ignore it
___
*[src/persistence/history.cpp, line 406 at r6](https://reviewable.io/reviews/qtox/qtox/5191#-LH4CWyqDAeqzP7pSxBp:-LHUY5O_Cxv8txNw3sKy:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/42f5ac67e7b5afee1d86807346e19592d91bf489/src/persistence/history.cpp#L406)):*
<details><summary><i>Previously, Talkless (Vincas Dargis) wrote…</i></summary><blockquote>

Using container here is kinda misleading I believe. Query returns just one element (due to LIMIT 1) or none, yes? Couldn't it be just a default-constructor QDateTime()? If callback is called and QDateTime object is re-assigned, it will not be `QDateTime::isNull` any more. 

Thoug I might be misunderstanding something here.
</blockquote></details>

Done.
___
*[src/widget/searchtypes.h, line 52 at r6](https://reviewable.io/reviews/qtox/qtox/5191#-LH4JYOy5zaHA3nWSLjY:-LHUYNYTAndiFQP0RUoF:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/42f5ac67e7b5afee1d86807346e19592d91bf489/src/widget/searchtypes.h#L52)):*
<details><summary><i>Previously, Talkless (Vincas Dargis) wrote…</i></summary><blockquote>

const QString ... = QStringLiteral("\\....
</blockquote></details>

Done.
___
*[src/widget/searchtypes.h, line 56 at r6](https://reviewable.io/reviews/qtox/qtox/5191#-LH4HmeT8yCRXouMwYpP:-LHUYI6U7pCaY1URPNpF:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/42f5ac67e7b5afee1d86807346e19592d91bf489/src/widget/searchtypes.h#L56)):*
<details><summary><i>Previously, Talkless (Vincas Dargis) wrote…</i></summary><blockquote>

When appending, consider use `QLatin1String("\\b")`, it will know string size at compile time.
</blockquote></details>

Done.
___
*[src/widget/searchtypes.h, line 58 at r6](https://reviewable.io/reviews/qtox/qtox/5191#-LH4JTYuAJv9qtQLfKH5:-LHUYKwyERZvMz8J-pEY:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/42f5ac67e7b5afee1d86807346e19592d91bf489/src/widget/searchtypes.h#L58)):*
<details><summary><i>Previously, Talkless (Vincas Dargis) wrote…</i></summary><blockquote>

QLatin1String()
</blockquote></details>

Done.
___
*[src/widget/searchtypes.h, line 61 at r6](https://reviewable.io/reviews/qtox/qtox/5191#-LH4JvcJ1H__CGGPCZQX:-LHUYSVNCt5mMQT72eW8:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/42f5ac67e7b5afee1d86807346e19592d91bf489/src/widget/searchtypes.h#L61)):*
<details><summary><i>Previously, Talkless (Vincas Dargis) wrote…</i></summary><blockquote>

QLatin1String for both `+=`
</blockquote></details>

Done.
___
*[src/widget/form/genericchatform.cpp, line 600 at r6](https://reviewable.io/reviews/qtox/qtox/5191#-LH4FO229u3OkWi3ftb5:-LHUYWDq0KywjZgMjkQj:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/42f5ac67e7b5afee1d86807346e19592d91bf489/src/widget/form/genericchatform.cpp#L600)):*
<details><summary><i>Previously, Talkless (Vincas Dargis) wrote…</i></summary><blockquote>

It would be really cool to have these two loops (after and before) implemented in terms of algorithms. std::find_if(), in this BeforeDate case, could find element using reverse iterators, and you can get distance (for that startLine) via std::distance().

Reading these kind of raw loops is hard, and all these `- 1` and `>=` just screams as off-by-one horrors :) .

Leave it as is if you think using std::find_if is more complicated.
</blockquote></details>

Done.
___
*[src/widget/form/genericchatform.cpp, line 592 at r7](https://reviewable.io/reviews/qtox/qtox/5191#-LHSYvMN692OignXWCFB:-LHUYYsh5rcJ-pw2TxWE:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/5668aa57c5da9d21aada4a506ce1771a247f138d/src/widget/form/genericchatform.cpp#L592)):*
<details><summary><i>Previously, Talkless (Vincas Dargis) wrote…</i></summary><blockquote>

`const auto lambda`, const lambdas are highly optimized-away. There was C++ Weekly episode about that (or was it a CPPCon talk..?).
</blockquote></details>

Done.
___
*[src/widget/form/genericchatform.cpp, line 593 at r7](https://reviewable.io/reviews/qtox/qtox/5191#-LHSZWBM0PkyzbGMA5NM:-LHUYa3d5e9Mr71mWlvs:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/5668aa57c5da9d21aada4a506ce1771a247f138d/src/widget/form/genericchatform.cpp#L593)):*
<details><summary><i>Previously, Talkless (Vincas Dargis) wrote…</i></summary><blockquote>

const auto d
</blockquote></details>

Done.
___
*[src/widget/form/genericchatform.cpp, line 597 at r7](https://reviewable.io/reviews/qtox/qtox/5191#-LHSZ_2X2Y0rqhh-_wBF:-LHUYcSt6uZA8Y-Xxg5C:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/5668aa57c5da9d21aada4a506ce1771a247f138d/src/widget/form/genericchatform.cpp#L597)):*
<details><summary><i>Previously, Talkless (Vincas Dargis) wrote…</i></summary><blockquote>

const auto find
</blockquote></details>

Done.
___
*[src/widget/form/genericchatform.cpp, line 603 at r7](https://reviewable.io/reviews/qtox/qtox/5191#-LHSZdRc8DJynegDSXpU:-LHUYeeq0__3Gjm-JFOD:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/5668aa57c5da9d21aada4a506ce1771a247f138d/src/widget/form/genericchatform.cpp#L603)):*
<details><summary><i>Previously, Talkless (Vincas Dargis) wrote…</i></summary><blockquote>

const auto lambda
</blockquote></details>

Done.
___
*[src/widget/form/genericchatform.cpp, line 604 at r7](https://reviewable.io/reviews/qtox/qtox/5191#-LHSZepz5uxLnJpWhGBv:-LHUYhfF4B9Wj3lkk0sy:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/5668aa57c5da9d21aada4a506ce1771a247f138d/src/widget/form/genericchatform.cpp#L604)):*
<details><summary><i>Previously, Talkless (Vincas Dargis) wrote…</i></summary><blockquote>

const auto d
</blockquote></details>

Done.
___
*[src/widget/form/genericchatform.cpp, line 608 at r7](https://reviewable.io/reviews/qtox/qtox/5191#-LHSZg2b7omFmdEI856Z:-LHUYlY99LIEU2Ft8m0c:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/5668aa57c5da9d21aada4a506ce1771a247f138d/src/widget/form/genericchatform.cpp#L608)):*
<details><summary><i>Previously, Talkless (Vincas Dargis) wrote…</i></summary><blockquote>

const auto find
</blockquote></details>

Done.
___
*[src/widget/form/genericchatform.cpp, line 673 at r7](https://reviewable.io/reviews/qtox/qtox/5191#-LHS_KryEcCek8aBsSAf:-LHUYs2vE10y60leke2l:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/5668aa57c5da9d21aada4a506ce1771a247f138d/src/widget/form/genericchatform.cpp#L673)):*
<details><summary><i>Previously, Talkless (Vincas Dargis) wrote…</i>< [...]

2018-07-19 18:41 UTC, sudden6 requested changes
> Reviewed 2 of 8 files at r7.
> *[Reviewable](https://reviewable.io/reviews/qtox/qtox/5191)* status: 0 of 1 LGTMs obtained

___
*[.travis/build-ubuntu-14-04.sh, line 56 at r4](https://reviewable.io/reviews/qtox/qtox/5191#-LGtayAx-JIr7C-bGU54:-LHnpzCP4vXQmALMdN5Y:b-nsod8x) ([raw file](https://github.com/qtox/qtox/blob/ea8bbfd8a531faa6ff06900a6db367757ddaa66a/.travis/build-ubuntu-14-04.sh#L56)):*
<details><summary><i>Previously, TriKriSta wrote…</i></summary><blockquote>

I fixed it.
</blockquote></details>

In principle I'd be ok with updating the minimum required Qt version, but can you provide the reason why we need Qt 5.6 now?


<!-- Sent from Reviewable.io -->

2018-07-19 18:49 UTC, TriKriSta commented
___
*[.travis/build-ubuntu-14-04.sh, line 56 at r4](https://reviewable.io/reviews/qtox/qtox/5191#-LGtayAx-JIr7C-bGU54:-LHnrOOTAr4xoPiTb_YK:bhmpvhm) ([raw file](https://github.com/qtox/qtox/blob/ea8bbfd8a531faa6ff06900a6db367757ddaa66a/.travis/build-ubuntu-14-04.sh#L56)):*
<details><summary><i>Previously, sudden6 wrote…</i></summary><blockquote>

In principle I'd be ok with updating the minimum required Qt version, but can you provide the reason why we need Qt 5.6 now?
</blockquote></details>

for functions QVector::rbegin() and QVector::rend()


<!-- Sent from Reviewable.io -->

2018-07-19 20:52 UTC, sudden6 commented
Sorry for the back and forth, but can you rewrite the code in a way that we don't need `rbegin` and `rend`? and then put it inside an `#if` to select based on the Qt version? This way we could stay with the current Qt version and already have the code done for when we bump the Qt version.

2018-07-20 21:58 UTC, sudden6 approved these changes
AFAICT this looks pretty good now, I'll do some more intense testing and wait for the lgtm of @Talkless

> Reviewed 2 of 12 files at r4, 4 of 8 files at r7, 1 of 2 files at r8, 2 of 2 files at r9.
> *[Reviewable](https://reviewable.io/reviews/qtox/qtox/5191#-:-LHtgo0t1Ar2FRGQ3JfL:b-xcfk5k)* status: 0 of 1 LGTMs obtained



<!-- Sent from Reviewable.io -->

2018-07-22 12:19 UTC, TriKriSta commented
What is wrong in the commit message?

2018-07-23 08:20 UTC, anthonybilinski commented
I think the problem was that travis-ci does a shallow clone so couldn't see that that commit it failed on was a merge. I restarted CI now that some new commits were pushed to master and it has passed the commit message check.

Unfortunately it looks like those new commits on master caused a small conflict with your branch. Could you please rebase your changes, resolving the conflict and update the PR.

2018-07-23 16:59 UTC, Talkless commented
On 7/19/18 9:49 PM, TriKriSta wrote:
> ----------------------------------------------------------------------------------------------------
> 
> /.travis/build-ubuntu-14-04.sh, line 56 at r4 
> <https://reviewable.io/reviews/qtox/qtox/5191#-LGtayAx-JIr7C-bGU54:-LHnrOOTAr4xoPiTb_YK:bhmpvhm> 
> (raw file 
> <https://github.com/qtox/qtox/blob/ea8bbfd8a531faa6ff06900a6db367757ddaa66a/.travis/build-ubuntu-14-04.sh#L56>):/
> 
> /Previously, sudden6 wrote…/
> 
>     In principle I'd be ok with updating the minimum required Qt version, but can you provide the
>     reason why we need Qt 5.6 now?
> 
> for functions QVector::rbegin() and QVector::rend()

Sorry, my bad.

2018-07-23 17:00 UTC, Talkless commented
On 7/21/18 12:58 AM, sudden6 wrote:
> AFAICT this looks pretty good now, I'll do some more intense testing and wait for the lgtm of 
> @Talkless

I would like to do some testing.

2018-07-23 17:01 UTC, Talkless commented
There are some sizing issues. "X" sems too small and date choice button text does not fit. I have KDE desktop with changed DPI to 141 (so my eyes doesn't bleed):
![qtox_search_sizing](https://user-images.githubusercontent.com/292191/43091570-f0cb923a-8e99-11e8-89b9-fb38fb0a2c4c.png)

2018-07-23 17:08 UTC, Talkless commented
Date search doesn't seem right. It finds after date even if I selected "before":
![qtox_search_date](https://user-images.githubusercontent.com/292191/43091919-f6511954-8e9a-11e8-8f57-350e3f8bd8f8.png)

Built on Debian Stretch with Qt 5.7.1

2018-07-23 17:19 UTC, TriKriSta commented
@Talkless Does it find "test" immediately after pressing the "start" button?

2018-07-23 17:27 UTC, Talkless commented
@TriKriSta It finds some older "test" entry not visible in the screenshot first. Pressing any of arrow button jumps to the next "text" which is out of time range.

2018-07-23 17:43 UTC, TriKriSta commented
@Talkless  Does chat have another word "test"? Maybe search didn't find anything, and after pressing any of arrow button it starts a search from the end. Maybe I need to add a message "Nothing found" if the search didn't find anything.

2018-07-24 17:04 UTC, Talkless commented
@TriKriSta  I guess it's misunderstanding from my side. It's only setting up _start_ position of the search, it does _not limit_ entries to be found. Not sure if this means "not intuitive enough".

It would be nice if maintainers would try to look how "right" does it "feel".

2018-07-24 17:05 UTC, Talkless commented
I would suggest to change "Start searching:" "with the first" and "with the end" to more... "correct" style. I am no English expect, but it doesn't read right. Maybe "from the beginning" and "from the end" or something that other IM clients or text editors use.

2018-07-24 18:58 UTC, sudden6 commented
> It would be nice if maintainers would try to look how "right" does it "feel".

uhhm, I'd rather leave this decision up to someone more user focused than me...

2018-07-24 20:23 UTC, TriKriSta commented
will it be better? Start searching: (from the end, from the beginning, after this date, before this date)
And if nothing found, show a message: "The text could not be found.”
That is, if nothing is found in accordance with the settings, show the message, and don't start the search from the beginning.

2018-07-25 16:06 UTC, Talkless commented
>  Start searching: (from the end, from the beginning, after this date, before this date)

I would drop "this" making "after date", "before date".

Yeah, mentioning that it had failed to find from selected range would be nice.

And please try something with the sizes as for the first screenshot. Arrow button icons are really too small, compared to cogwheel on the left.

2018-07-27 01:03 UTC, tox-user commented
>here are some sizing issues. "X" sems too small and date choice button text does not fit.

>And please try something with the sizes as for the first screenshot. Arrow button icons are really too small, compared to cogwheel on the left.

I think it might be a bug that has nothing to do with this PR. I reported it in the past and I'm still getting it in qTox 1.16 but it only happens with those two buttons. Only some people have this problem. If I remember correctly it was system dependent. @anthonybilinski might remember some more details about it.

2018-07-27 01:06 UTC, tox-user commented
I remember I had a similar problem in my full screen video PR. Some icons appeared too small for me even though they were the right size for others. If I remember correctly @Diadlo somehow fixed it by modifying the svg file.

2018-08-06 08:46 UTC, Talkless reviewed
> *[Reviewable](https://reviewable.io/reviews/qtox/qtox/5191)* status: 0 of 1 LGTMs obtained

___
*[src/widget/searchform.h, line 85 at r10](https://reviewable.io/reviews/qtox/qtox/5191#-LJDOc8k51FisCVaKEnm:-LJDOc8k51FisCVaKEnn:b-z5e2mp) ([raw file](https://github.com/qtox/qtox/blob/4253301c5606637c8b1beae082f922af10eb365a/src/widget/searchform.h#L85)):*
> ```objc
> 
> public slots:
>     void showMessageNotFound(const bool searchUp);
> ```

Consider using `enum class SearchDirection` or simiar, instead of boolean. It would be more clear for the readers in call sites.
___
*[src/widget/searchform.cpp, line 29 at r10](https://reviewable.io/reviews/qtox/qtox/5191#-LJDPWx_Adp3BCL-CmAB:-LJDPWx_Adp3BCL-CmAC:bkpwv11) ([raw file](https://github.com/qtox/qtox/blob/4253301c5606637c8b1beae082f922af10eb365a/src/widget/searchform.cpp#L29)):*
> ```cpp
> #include <QKeyEvent>
> 
> const QString STATE_NAME[] = {
> ```

consider using std::array<> instead if you care about C++11'ism.


<!-- Sent from Reviewable.io -->

2018-08-06 09:04 UTC, Talkless commented
Icons are much better now:
![start_searching](https://user-images.githubusercontent.com/292191/43707316-51e9dfc8-9957-11e8-8722-b6318010db1b.png)

Though I am still confused, why does it find that old message at first try. If I click "down" arrow, it does say that text could not be found (that's ok), but not sure why this message was found.

2018-08-06 09:05 UTC, Talkless reviewed
> *[Reviewable](https://reviewable.io/reviews/qtox/qtox/5191)* status: 0 of 1 LGTMs obtained

___
*[src/widget/form/searchsettingsform.ui, line 41 at r10](https://reviewable.io/reviews/qtox/qtox/5191#-LJDTrdA4p1JuLOzHdVY:-LJDTrdBAH4KTH44iLD5:bc08ea6) ([raw file](https://github.com/qtox/qtox/blob/4253301c5606637c8b1beae082f922af10eb365a/src/widget/form/searchsettingsform.ui#L41)):*
> ```XML
>       <widget class="QLabel" name="label">
>        <property name="text">
>         <string>Start searching:</string>
> ```

I believe shorter "Start search:" would also work here.


<!-- Sent from Reviewable.io -->

2018-08-06 15:39 UTC, tox-user commented
Or simply "search:".

2018-08-08 18:43 UTC, TriKriSta reviewed
> *[Reviewable](https://reviewable.io/reviews/qtox/qtox/5191)* status: 0 of 1 LGTMs obtained

___
*[src/widget/searchform.h, line 85 at r10](https://reviewable.io/reviews/qtox/qtox/5191#-LJDOc8k51FisCVaKEnm:-LJPqCoz1NL3OPwPAYCu:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/4253301c5606637c8b1beae082f922af10eb365a/src/widget/searchform.h#L85)):*
<details><summary><i>Previously, Talkless (Vincas Dargis) wrote…</i></summary><blockquote>

Consider using `enum class SearchDirection` or simiar, instead of boolean. It would be more clear for the readers in call sites.
</blockquote></details>

Done.
___
*[src/widget/searchform.cpp, line 29 at r10](https://reviewable.io/reviews/qtox/qtox/5191#-LJDPWx_Adp3BCL-CmAB:-LJPqE5yESqj3kzcEdHu:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/4253301c5606637c8b1beae082f922af10eb365a/src/widget/searchform.cpp#L29)):*
<details><summary><i>Previously, Talkless (Vincas Dargis) wrote…</i></summary><blockquote>

consider using std::array<> instead if you care about C++11'ism.
</blockquote></details>

Done.
___
*[src/widget/form/searchsettingsform.ui, line 41 at r10](https://reviewable.io/reviews/qtox/qtox/5191#-LJDTrdA4p1JuLOzHdVY:-LJPqFKa3Kk5DGDrFhcg:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/4253301c5606637c8b1beae082f922af10eb365a/src/widget/form/searchsettingsform.ui#L41)):*
<details><summary><i>Previously, Talkless (Vincas Dargis) wrote…</i></summary><blockquote>

I believe shorter "Start search:" would also work here.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2018-08-08 18:46 UTC, TriKriSta commented
I left "Start search" not "Search" because this setting defines a start search and not the time frame

2018-08-09 07:57 UTC, Talkless reviewed
> *[Reviewable](https://reviewable.io/reviews/qtox/qtox/5191)* status: 0 of 1 LGTMs obtained

___
*[src/widget/searchform.h, line 85 at r10](https://reviewable.io/reviews/qtox/qtox/5191#-LJDOc8k51FisCVaKEnm:-LJSehpY9woSg_EHTKKu:bmkeuuf) ([raw file](https://github.com/qtox/qtox/blob/4253301c5606637c8b1beae082f922af10eb365a/src/widget/searchform.h#L85)):*
<details><summary><i>Previously, TriKriSta wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Enums really shoudn't be passed via reference, as bool or int woudn't be.
___
*[src/widget/searchform.cpp, line 154 at r11](https://reviewable.io/reviews/qtox/qtox/5191#-LJSeq2s8cMjpjT77aVs:-LJSeq2t-lONquO0s87i:bl5i78o) ([raw file](https://github.com/qtox/qtox/blob/dce3715d0711e1603290a3fc671947cbfe91b9b4/src/widget/searchform.cpp#L154)):*
> ```cpp
> void SearchForm::setStateName(QPushButton *btn, ToolButtonState state)
> {
>     const unsigned long index = static_cast<unsigned long>(state);
> ```

Since type is mentioned on the right side already, this could be:
```
const auto index =  static_cast<unsigned long>(state);
```
___
*[src/widget/form/genericchatform.cpp, line 633 at r11](https://reviewable.io/reviews/qtox/qtox/5191#-LJSfxzV-b9soBUVETpk:-LJSfxzV-b9soBUVETpl:bqdqnz2) ([raw file](https://github.com/qtox/qtox/blob/dce3715d0711e1603290a3fc671947cbfe91b9b4/src/widget/form/genericchatform.cpp#L633)):*
> ```cpp
>     }
> 
>     bool searchUp = (direction == SearchDirection::Up);
> ```

`const bool`


<!-- Sent from Reviewable.io -->

2018-08-09 08:16 UTC, Talkless reviewed
Works fine for me after latest changes. I'll give my LGTM after final commens are resolved.

> *[Reviewable](https://reviewable.io/reviews/qtox/qtox/5191#-:-LJShtkV59Sh5xEqRoWV:b-32aro9)* status: 0 of 1 LGTMs obtained

___
*[src/widget/searchtypes.h, line 54 at r11](https://reviewable.io/reviews/qtox/qtox/5191#-LJSjiETDBmCeXQF791f:-LJSjiETDBmCeXQF791g:bxpf4zj) ([raw file](https://github.com/qtox/qtox/blob/dce3715d0711e1603290a3fc671947cbfe91b9b4/src/widget/searchtypes.h#L54)):*
> ```objc
>      * @return new phrase for search
>      */
>     static QString generateFilterWordsOnly(const QString &phrase) {
> ```

I kinda doubt we need a this function in searchtypes.h. Since it's used only in `genericchatform.cpp`, it could be moved into it. Note that genericchatrform.cpp already has anonymous namespace.
```
namespace {
namespace detail {
   QString generateFilterWorksOnly(const QString &phrase) // no need for "static", because it's inside anonymous namespace already
}
}
```


<!-- Sent from Reviewable.io -->

2018-08-09 16:27 UTC, TriKriSta reviewed
> *[Reviewable](https://reviewable.io/reviews/qtox/qtox/5191)* status: 0 of 1 LGTMs obtained

___
*[src/widget/searchform.h, line 85 at r10](https://reviewable.io/reviews/qtox/qtox/5191#-LJDOc8k51FisCVaKEnm:-LJUUx354mWr6h_TLOBk:byblbz) ([raw file](https://github.com/qtox/qtox/blob/4253301c5606637c8b1beae082f922af10eb365a/src/widget/searchform.h#L85)):*
<details><summary><i>Previously, Talkless (Vincas Dargis) wrote…</i></summary><blockquote>

Enums really shoudn't be passed via reference, as bool or int woudn't be.
</blockquote></details>

I deleted references
___
*[src/widget/searchform.cpp, line 154 at r11](https://reviewable.io/reviews/qtox/qtox/5191#-LJSeq2s8cMjpjT77aVs:-LJUV6Bi4IuUTwJxR2d1:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/dce3715d0711e1603290a3fc671947cbfe91b9b4/src/widget/searchform.cpp#L154)):*
<details><summary><i>Previously, Talkless (Vincas Dargis) wrote…</i></summary><blockquote>

Since type is mentioned on the right side already, this could be:
```
const auto index =  static_cast<unsigned long>(state);
```
</blockquote></details>

Done.
___
*[src/widget/searchtypes.h, line 54 at r11](https://reviewable.io/reviews/qtox/qtox/5191#-LJSjiETDBmCeXQF791f:-LJUV76lEEjEc17m4g--:b8o5xxo) ([raw file](https://github.com/qtox/qtox/blob/dce3715d0711e1603290a3fc671947cbfe91b9b4/src/widget/searchtypes.h#L54)):*
<details><summary><i>Previously, Talkless (Vincas Dargis) wrote…</i></summary><blockquote>

I kinda doubt we need a this function in searchtypes.h. Since it's used only in `genericchatform.cpp`, it could be moved into it. Note that genericchatrform.cpp already has anonymous namespace.
```
namespace {
namespace detail {
   QString generateFilterWorksOnly(const QString &phrase) // no need for "static", because it's inside anonymous namespace already
}
}
```


</blockquote></details>

generateFilterWordsOnly is used in history.cpp too
___
*[src/widget/form/genericchatform.cpp, line 633 at r11](https://reviewable.io/reviews/qtox/qtox/5191#-LJSfxzV-b9soBUVETpk:-LJUT7i-5FzZQNxpvsRL:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/dce3715d0711e1603290a3fc671947cbfe91b9b4/src/widget/form/genericchatform.cpp#L633)):*
<details><summary><i>Previously, Talkless (Vincas Dargis) wrote…</i></summary><blockquote>

`const bool`
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2018-08-09 16:55 UTC, Talkless reviewed
> *[Reviewable](https://reviewable.io/reviews/qtox/qtox/5191)* status: 0 of 1 LGTMs obtained

___
*[src/widget/searchform.h, line 85 at r10](https://reviewable.io/reviews/qtox/qtox/5191#-LJDOc8k51FisCVaKEnm:-LJUbGrh9aiquSQb8jNX:b-qfxksy) ([raw file](https://github.com/qtox/qtox/blob/4253301c5606637c8b1beae082f922af10eb365a/src/widget/searchform.h#L85)):*
<details><summary><i>Previously, TriKriSta wrote…</i></summary><blockquote>

I deleted references
</blockquote></details>

no need for const too here.


<!-- Sent from Reviewable.io -->

2018-08-09 16:59 UTC, TriKriSta reviewed
> *[Reviewable](https://reviewable.io/reviews/qtox/qtox/5191)* status: 0 of 1 LGTMs obtained

___
*[src/widget/searchform.h, line 85 at r10](https://reviewable.io/reviews/qtox/qtox/5191#-LJDOc8k51FisCVaKEnm:-LJUbwzECS6HmG2Xaoqa:b7sv47w) ([raw file](https://github.com/qtox/qtox/blob/4253301c5606637c8b1beae082f922af10eb365a/src/widget/searchform.h#L85)):*
<details><summary><i>Previously, Talkless (Vincas Dargis) wrote…</i></summary><blockquote>

no need for const too here.
</blockquote></details>

no reference, no const, use only "SearchDirection direction" ?


<!-- Sent from Reviewable.io -->

2018-08-09 17:02 UTC, Talkless reviewed
> *[Reviewable](https://reviewable.io/reviews/qtox/qtox/5191)* status: 0 of 1 LGTMs obtained

___
*[src/widget/searchform.h, line 85 at r10](https://reviewable.io/reviews/qtox/qtox/5191#-LJDOc8k51FisCVaKEnm:-LJUcyTl0FGM75YKuu6A:b2nign6) ([raw file](https://github.com/qtox/qtox/blob/4253301c5606637c8b1beae082f922af10eb365a/src/widget/searchform.h#L85)):*
<details><summary><i>Previously, TriKriSta wrote…</i></summary><blockquote>

no reference? no const, use only "SearchDirection direction" ?
</blockquote></details>

yes


<!-- Sent from Reviewable.io -->

2018-08-09 17:08 UTC, Talkless reviewed
> *[Reviewable](https://reviewable.io/reviews/qtox/qtox/5191)* status: 0 of 1 LGTMs obtained

___
*[src/widget/searchform.h, line 83 at r12](https://reviewable.io/reviews/qtox/qtox/5191#-LJUdrxr99SAefhQ0qdX:-LJUdrxr99SAefhQ0qdY:bu1p9x) ([raw file](https://github.com/qtox/qtox/blob/89016942a159eed92cf7f01afbd60dd77ea98b17/src/widget/searchform.h#L83)):*
this const is too over-kill'ish.
See https://github.com/isocpp/CppCoreGuidelines/blob/master/CppCoreGuidelines.md#con1-by-default-make-objects-immutable

> Function arguments are rarely mutated, but also rarely declared const. To avoid confusion and lots of false positives, don't enforce this rule for function arguments.

Const pointer or reference does have usefull semantic, but too verbose for simple value parameters.


<!-- Sent from Reviewable.io -->

2018-08-09 17:11 UTC, TriKriSta reviewed
> *[Reviewable](https://reviewable.io/reviews/qtox/qtox/5191)* status: 0 of 1 LGTMs obtained

___
*[src/widget/searchform.h, line 85 at r10](https://reviewable.io/reviews/qtox/qtox/5191#-LJDOc8k51FisCVaKEnm:-LJUec337IqZRRSvqXPc:b-6favql) ([raw file](https://github.com/qtox/qtox/blob/4253301c5606637c8b1beae082f922af10eb365a/src/widget/searchform.h#L85)):*
<details><summary><i>Previously, Talkless (Vincas Dargis) wrote…</i></summary><blockquote>

yes
</blockquote></details>

does "SearchDirection direction" use in only showMessageNotFound or all functions?


<!-- Sent from Reviewable.io -->

2018-08-09 17:27 UTC, Talkless reviewed
> *[Reviewable](https://reviewable.io/reviews/qtox/qtox/5191)* status: 0 of 1 LGTMs obtained

___
*[src/widget/searchform.h, line 85 at r10](https://reviewable.io/reviews/qtox/qtox/5191#-LJDOc8k51FisCVaKEnm:-LJUiAkG5UTXC0-rc7rL:bh935pk) ([raw file](https://github.com/qtox/qtox/blob/4253301c5606637c8b1beae082f922af10eb365a/src/widget/searchform.h#L85)):*
<details><summary><i>Previously, TriKriSta wrote…</i></summary><blockquote>

does "SearchDirection direction" use in only showMessageNotFound or all functions?
</blockquote></details>

Yes, const is not needed for any enum parameter in any function, if that's what are question about.


<!-- Sent from Reviewable.io -->

2018-08-09 17:47 UTC, TriKriSta reviewed
> *[Reviewable](https://reviewable.io/reviews/qtox/qtox/5191)* status: 0 of 1 LGTMs obtained

___
*[src/widget/searchform.h, line 83 at r12](https://reviewable.io/reviews/qtox/qtox/5191#-LJUdrxr99SAefhQ0qdX:-LJUn-xO99kubHOo5fhE:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/89016942a159eed92cf7f01afbd60dd77ea98b17/src/widget/searchform.h#L83)):*
<details><summary><i>Previously, Talkless (Vincas Dargis) wrote…</i></summary><blockquote>

this const is too over-kill'ish.
See https://github.com/isocpp/CppCoreGuidelines/blob/master/CppCoreGuidelines.md#con1-by-default-make-objects-immutable

> Function arguments are rarely mutated, but also rarely declared const. To avoid confusion and lots of false positives, don't enforce this rule for function arguments.

Const pointer or reference does have usefull semantic, but too verbose for simple value parameters.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2018-08-09 17:51 UTC, Talkless reviewed
Thanks @TriKriSta for all the work! That's enough fixing for me:  <img class="emoji" title=":lgtm_strong:" alt=":lgtm_strong:" align="absmiddle" src="https://reviewable.io/lgtm_strong.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/qtox/qtox/5191#-:-LJUnxQj-gIjSzCjCi6x:bq4yw7x)* status: :shipit: complete! 1 of 1 LGTMs obtained



<!-- Sent from Reviewable.io -->

2018-08-09 17:51 UTC, Talkless reviewed
<img class="emoji" title=":lgtm_strong:" alt=":lgtm_strong:" align="absmiddle" src="https://reviewable.io/lgtm_strong.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/qtox/qtox/5191#-:-LJUoEGd7PMym2mDCjUT:b-jbsf8z)* status: :shipit: complete! 1 of 1 LGTMs obtained



<!-- Sent from Reviewable.io -->

2018-08-10 12:15 UTC, tox-user commented
Good job @TriKriSta I don't think I would have the patience for this long review :)

2018-08-10 14:45 UTC, sudden6 reviewed
<img class="emoji" title=":lgtm_strong:" alt=":lgtm_strong:" align="absmiddle" src="https://reviewable.io/lgtm_strong.png" height="20" width="61"/> too, good work!

> *[Reviewable](https://reviewable.io/reviews/qtox/qtox/5191#-:-LJZI1Pa9cU4t1ljant9:b-rclm66)* status: :shipit: complete! 2 of 1 LGTMs obtained



<!-- Sent from Reviewable.io -->

2018-08-13 19:01 UTC, TriKriSta commented
Don't the tests work due to a problem in the code or due to a problem in the tests?

2018-08-13 20:20 UTC, anthonybilinski commented
Looks like a problem with the CI, it's compiling away then gets stopped because of too much output:
```
/build/qt-everywhere-opensource-src-5.9.6/qtbase/bin/qmake -install qinstall /build/qt-everywhere-opensource-src-5.9.6/qtbase/src/widgets/kernel/qgesture.h /workspace/i686/dep-cache/libqt5/include/QtWidgets/qgesture.h


The log length has exceeded the limit of 4 MB (this usually means that the test suite is raising the same exception over and over).

The job has been terminated
```

I'll restart it in case there's some transient reason for more output this time, otherwise we might have to make our windows build less verbose.

2018-08-15 12:47 UTC, merged

2018-08-15 23:56 UTC, jakieoymj-github commented
Well done, I like it very much.