docs: add to CONTRIBUTING.md Git config line for forcing singning tags
qTox/qTox pull request #5275
Opened 2018-07-27 18:29 UTC by zetok

Also change git config from global, to local, specific to repo, since
signing all commits in every project committed to might not be desirable
for some people, as GPG-signing usually involves typing in password,
which is a slowdown.

Partially addresses cause of #5125 and #5274.

- [x] Commits follow our [git commit guidelines](https://github.com/qTox/qTox/blob/master/CONTRIBUTING.md#git-commit-guidelines)

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qtox/qtox/5275)

2018-07-27 18:45 UTC, anthonybilinski requested changes
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/qtox/qtox/5275)* status: 0 of 1 LGTMs obtained

___
*[CONTRIBUTING.md, line 376 at r1](https://reviewable.io/reviews/qtox/qtox/5275#-LIS2lqM5tgQ4tX_qifj:-LIS2lqM5tgQ4tX_qifk:b-v1vuc7) ([raw file](https://github.com/qtox/qtox/blob/a88e6e4690729967416b375c6726c1642ee20af1/CONTRIBUTING.md#L376)):*
> ```Markdown
> git config --local commit.gpgsign true
> # also force signing tags
> git config --local tag.forceSignAnnotated true
> ```

MAINTAINING.md should be updated to mention that signing tags is required as well.


<!-- Sent from Reviewable.io -->

2018-08-17 17:33 UTC, zetok reviewed
> *[Reviewable](https://reviewable.io/reviews/qtox/qtox/5275)* status: 0 of 1 LGTMs obtained

___
*[CONTRIBUTING.md, line 376 at r1](https://reviewable.io/reviews/qtox/qtox/5275#-LIS2lqM5tgQ4tX_qifj:-LK7vXdW3_F-qpeCMgXN:b-tbv5uc) ([raw file](https://github.com/qtox/qtox/blob/a88e6e4690729967416b375c6726c1642ee20af1/CONTRIBUTING.md#L376)):*
<details><summary><i>Previously, anthonybilinski (Anthony Bilinski) wrote…</i></summary><blockquote>

MAINTAINING.md should be updated to mention that signing tags is required as well.
</blockquote></details>

Well, MAINTAINING.md already states that, not only on top pointing at CONTRIBUTING.md's git config, but also in every relevant section that requires signing; in case of tags, there's even an example command to use for [tagging](https://github.com/qTox/qTox/blob/8e182b7dfdb7df94e42751155cfdd3386ca7a8d5/MAINTAINING.md#tagging-scheme). If I've missed something, could you point out specific place?


<!-- Sent from Reviewable.io -->

2018-08-29 18:04 UTC, anthonybilinski approved these changes
> *[Reviewable](https://reviewable.io/reviews/qtox/qtox/5275)* status: 0 of 1 LGTMs obtained

___
*[CONTRIBUTING.md, line 376 at r1](https://reviewable.io/reviews/qtox/qtox/5275#-LIS2lqM5tgQ4tX_qifj:-LL5qt9a-Xipepz2SuO0:b9c7825) ([raw file](https://github.com/qtox/qtox/blob/a88e6e4690729967416b375c6726c1642ee20af1/CONTRIBUTING.md#L376)):*
That's true, I missed the part in the signing section and the rest of the sections about commits/PR don't relate to signing.

https://github.com/qTox/qTox/blob/master/MAINTAINING.md#gpg-signing
>are required to use GPG to sign commits & merges.

could be updated, but fine either way.


<!-- Sent from Reviewable.io -->

2018-08-29 18:05 UTC, anthonybilinski requested changes
> *[Reviewable](https://reviewable.io/reviews/qtox/qtox/5275)* status: :shipit: complete! 1 of 1 LGTMs obtained

___
*[CONTRIBUTING.md, line 376 at r1](https://reviewable.io/reviews/qtox/qtox/5275#-LIS2lqM5tgQ4tX_qifj:-LL5r2hu5tXm9vcpggIX:b-uwkowd) ([raw file](https://github.com/qtox/qtox/blob/a88e6e4690729967416b375c6726c1642ee20af1/CONTRIBUTING.md#L376)):*
<details><summary><i>Previously, anthonybilinski (Anthony Bilinski) wrote…</i></summary><blockquote>

That's true, I missed the part in the signing section and the rest of the sections about commits/PR don't relate to signing.

https://github.com/qTox/qTox/blob/master/MAINTAINING.md#gpg-signing
>are required to use GPG to sign commits & merges.

could be updated, but fine either way.

</blockquote></details>

<img class="emoji" title=":lgtm_strong:" alt=":lgtm_strong:" align="absmiddle" src="https://reviewable.io/lgtm_strong.png" height="20" width="61"/> 


<!-- Sent from Reviewable.io -->

2018-08-29 18:06 UTC, anthonybilinski approved these changes
> *[Reviewable](https://reviewable.io/reviews/qtox/qtox/5275)* status: :shipit: complete! 1 of 1 LGTMs obtained



<!-- Sent from Reviewable.io -->

2018-10-05 06:36 UTC, merged