Feat/notify2
qTox/qTox pull request #5351
Opened 2018-09-23 20:12 UTC by sudden6

Limited set of changes from #5227 that only build notification support on Linux.

- [ ] Commits follow our [git commit guidelines](https://github.com/qTox/qTox/blob/master/CONTRIBUTING.md#git-commit-guidelines)

2019-02-09 20:23 UTC, sudden6 commented
@anthonybilinski I rebased this and I think we can merge it.

2019-03-21 09:12 UTC, anthonybilinski requested changes
> Reviewed 15 of 15 files at r1.
> *[Reviewable](https://reviewable.io/reviews/qtox/qtox/5351)* status: 0 of 1 LGTMs obtained (waiting on @anthonybilinski)

___
*[CMakeLists.txt, line 654 at r1](https://reviewable.io/reviews/qtox/qtox/5351#-LaUW9f2BcO9APunTsYg:-LaUW9f2BcO9APunTsYh:b2fze1g) ([raw file](https://github.com/qtox/qtox/blob/bab655f46962ac58ef8aa7c590425a1a4765227d/CMakeLists.txt#L654)):*
> ```CMake
> endif()
> 
> if (${DESKTOP_NOTIFICATIONS})
> ```

does it make sense to enable desktop notifications if the optional deps are found, instead of also requiring a non-default arg?
___
*[simple_make.sh, line 2 at r1](https://reviewable.io/reviews/qtox/qtox/5351#-LaUUULHAVheXdjFqUsU:-LaUUULHAVheXdjFqUsV:b-o2hjhy) ([raw file](https://github.com/qtox/qtox/blob/bab655f46962ac58ef8aa7c590425a1a4765227d/simple_make.sh#L2)):*
> ```Shell
> #!/usr/bin/env bash
> ```

why is simple_make.sh changed?
___
*[appimage/build.sh, line 59 at r1](https://reviewable.io/reviews/qtox/qtox/5351#-LaUTHHSAhVGNCpkUec2:-LaUTHHSAhVGNCpkUec3:b1195ja) ([raw file](https://github.com/qtox/qtox/blob/bab655f46962ac58ef8aa7c590425a1a4765227d/appimage/build.sh#L59)):*
> ```Shell
> libgtk2.0-dev libopenal-dev libopus-dev libqrencode-dev libqt5opengl5-dev \
> libqt5svg5-dev libsodium-dev libtool libvpx-dev libxss-dev \
> qt5-default qttools5-dev qttools5-dev-tools qtdeclarative5-dev
> ```

is this large package change related to snore? is this needed?
___
*[appimage/build.sh, line 102 at r1](https://reviewable.io/reviews/qtox/qtox/5351#-LaUUP7M3SoizZKgPYyJ:-LaUUP7M3SoizZKgPYyK:b-4373s8) ([raw file](https://github.com/qtox/qtox/blob/bab655f46962ac58ef8aa7c590425a1a4765227d/appimage/build.sh#L102)):*
> ```Shell
> rm -rf ./_build
> mkdir -p ./_build
> ```

what's the purpose of these build changes?
___
*[src/persistence/settings.cpp, line 191 at r1](https://reviewable.io/reviews/qtox/qtox/5351#-LaURuyIEfbdlnuWjD5r:-LaURuyIEfbdlnuWjD5s:b-o1hzkx) ([raw file](https://github.com/qtox/qtox/blob/bab655f46962ac58ef8aa7c590425a1a4765227d/src/persistence/settings.cpp#L191)):*
> ```cpp
>         showWindow = s.value("showWindow", true).toBool();
>         notify = s.value("notify", true).toBool();
>         desktopNotify = s.value("desktopNotify", false).toBool();
> ```

why default to false? If the user has snore, these should be an overall improvement to basic alert, but if we initialize to false it will be saved that way even as our custom notifications improve
___
*[src/platform/desktop_notifications/desktopnotify.cpp, line 28 at r1](https://reviewable.io/reviews/qtox/qtox/5351#-LaUJGqZCZlhL5--IP7e:-LaUJGqZCZlhL5--IP7f:b-ulze6w) ([raw file](https://github.com/qtox/qtox/blob/bab655f46962ac58ef8aa7c590425a1a4765227d/src/platform/desktop_notifications/desktopnotify.cpp#L28)):*
> ```cpp
>     if (old == nullptr) {
>         return NotificationPtr(
>             new Snore::Notification(snoreApp, Snore::Alert(), title, text, snoreIcon));
> ```

why create Snore::Notifications as pointers, store them as members, only to dereference the pointer to pass it into Snore? why not just make a Notification and pass that into Snore, without storing it as a member?
___
*[src/platform/desktop_notifications/desktopnotify.cpp, line 48 at r1](https://reviewable.io/reviews/qtox/qtox/5351#-LaUM-nU9vJR-Z8PRpoB:-LaUM-nU9vJR-Z8PRpoC:b-tcswwz) ([raw file](https://github.com/qtox/qtox/blob/bab655f46962ac58ef8aa7c590425a1a4765227d/src/platform/desktop_notifications/desktopnotify.cpp#L48)):*
> ```cpp
>         return;
>     }
>     groupInvite = std::move(newNote);
> ```

why is the group message notification saved to `groupInvite` instead of `groupMessage`?
___
*[src/platform/desktop_notifications/desktopnotify.cpp, line 48 at r1](https://reviewable.io/reviews/qtox/qtox/5351#-LaUMAqr0avL19ZMSUVI:-LaUMAqr0avL19ZMSUVJ:b-eb4wkz) ([raw file](https://github.com/qtox/qtox/blob/bab655f46962ac58ef8aa7c590425a1a4765227d/src/platform/desktop_notifications/desktopnotify.cpp#L48)):*
> ```cpp
>         return;
>     }
>     groupInvite = std::move(newNote);
> ```

why no Snore::broadcastNotification only in this case?
___
*[src/platform/desktop_notifications/desktopnotify.cpp, line 65 at r1](https://reviewable.io/reviews/qtox/qtox/5351#-LaUMN4kEQ1tljHIQj7I:-LaUMN4kEQ1tljHIQj7J:b-y733eb) ([raw file](https://github.com/qtox/qtox/blob/bab655f46962ac58ef8aa7c590425a1a4765227d/src/platform/desktop_notifications/desktopnotify.cpp#L65)):*
> ```cpp
>         return;
>     }
>     friendMessage = std::move(newNote);
> ```

same, why friendMessage?
___
*[src/platform/desktop_notifications/desktopnotify.cpp, line 83 at r1](https://reviewable.io/reviews/qtox/qtox/5351#-LaULjcO02YhOLqX_9L3:-LaULjcQ65S24xM2RgCh:b-y733eb) ([raw file](https://github.com/qtox/qtox/blob/bab655f46962ac58ef8aa7c590425a1a4765227d/src/platform/desktop_notifications/desktopnotify.cpp#L83)):*
> ```cpp
>         return;
>     }
>     friendMessage = std::move(newNote);
> ```

same, why friendMessage?
___
*[src/platform/desktop_notifications/desktopnotify.cpp, line 98 at r1](https://reviewable.io/reviews/qtox/qtox/5351#-LaUFJUE-tkwT3oW4cSE:-LaUFJUF559okoOpA_sJ:b-rg33lr) ([raw file](https://github.com/qtox/qtox/blob/bab655f46962ac58ef8aa7c590425a1a4765227d/src/platform/desktop_notifications/desktopnotify.cpp#L98)):*
> ```cpp
>     NotificationPtr newNote = createNotification(title, text);
>     if (!newNote) {
>         qDebug() << "Failed to allocate friend message notification";
> ```

bump up severity of log?


<!-- Sent from Reviewable.io -->

2019-03-21 09:19 UTC, anthonybilinski requested changes
> *[Reviewable](https://reviewable.io/reviews/qtox/qtox/5351)* status: 0 of 1 LGTMs obtained (waiting on @anthonybilinski)

___
*[src/widget/widget.cpp, line 1717 at r1](https://reviewable.io/reviews/qtox/qtox/5351#-LaUXIa-Cs4YvlGdFpj4:-LaUXIa-Cs4YvlGdFpj5:b-3ipy4u) ([raw file](https://github.com/qtox/qtox/blob/bab655f46962ac58ef8aa7c590425a1a4765227d/src/widget/widget.cpp#L1717)):*
> ```cpp
>             ++unreadGroupInvites;
>             groupInvitesUpdate();
>             newMessageAlert(window(), isActiveWindow(), true, true);
> ```

newMessageAlert() can still call QApplication::alert, which at least on gnome3 sends its own notification, resulting in 2 notifications for the same thing. Alert also handles making the icon flash orange or whatever OS-specific impl, but it looks like if I remove the alert() call that still happens, thanks to Snore


<!-- Sent from Reviewable.io -->

2019-03-22 16:20 UTC, sudden6 reviewed
> *[Reviewable](https://reviewable.io/reviews/qtox/qtox/5351)* status: 0 of 1 LGTMs obtained (waiting on @anthonybilinski)

___
*[CMakeLists.txt, line 654 at r1](https://reviewable.io/reviews/qtox/qtox/5351#-LaUW9f2BcO9APunTsYg:-Laa55BK5uyp0rEso0mX:by96oos) ([raw file](https://github.com/qtox/qtox/blob/bab655f46962ac58ef8aa7c590425a1a4765227d/CMakeLists.txt#L654)):*
<details><summary><i>Previously, anthonybilinski (Anthony Bilinski) wrote…</i></summary><blockquote>

does it make sense to enable desktop notifications if the optional deps are found, instead of also requiring a non-default arg?
</blockquote></details>

I want this to be disabled by default until it has gone through some testing. Do you think we should make it default enabled?
___
*[simple_make.sh, line 2 at r1](https://reviewable.io/reviews/qtox/qtox/5351#-LaUUULHAVheXdjFqUsU:-Laa5aRoDrct_e1XgEav:b-jx54na) ([raw file](https://github.com/qtox/qtox/blob/bab655f46962ac58ef8aa7c590425a1a4765227d/simple_make.sh#L2)):*
<details><summary><i>Previously, anthonybilinski (Anthony Bilinski) wrote…</i></summary><blockquote>

why is simple_make.sh changed?
</blockquote></details>

adding snorenotify as optional dependency here would cause more complicated code in this script, so I decided to not use it for our AppImage builds anymore and reverted the changes here that were just for the AppImage build.
___
*[appimage/build.sh, line 59 at r1](https://reviewable.io/reviews/qtox/qtox/5351#-LaUTHHSAhVGNCpkUec2:-Laa5rX6EOAJ9GmXqSrk:b-7tmsiq) ([raw file](https://github.com/qtox/qtox/blob/bab655f46962ac58ef8aa7c590425a1a4765227d/appimage/build.sh#L59)):*
<details><summary><i>Previously, anthonybilinski (Anthony Bilinski) wrote…</i></summary><blockquote>

is this large package change related to snore? is this needed?
</blockquote></details>

See above, made the AppImage build independent of `simple_make.sh`
___
*[appimage/build.sh, line 102 at r1](https://reviewable.io/reviews/qtox/qtox/5351#-LaUUP7M3SoizZKgPYyJ:-Laa5xGM5yjcB6hWTz4Q:bb7od0r) ([raw file](https://github.com/qtox/qtox/blob/bab655f46962ac58ef8aa7c590425a1a4765227d/appimage/build.sh#L102)):*
<details><summary><i>Previously, anthonybilinski (Anthony Bilinski) wrote…</i></summary><blockquote>

what's the purpose of these build changes?
</blockquote></details>

same
___
*[src/persistence/settings.cpp, line 191 at r1](https://reviewable.io/reviews/qtox/qtox/5351#-LaURuyIEfbdlnuWjD5r:-Laa6tNR0LaNlVtNw_ar:baoj42o) ([raw file](https://github.com/qtox/qtox/blob/bab655f46962ac58ef8aa7c590425a1a4765227d/src/persistence/settings.cpp#L191)):*
<details><summary><i>Previously, anthonybilinski (Anthony Bilinski) wrote…</i></summary><blockquote>

why default to false? If the user has snore, these should be an overall improvement to basic alert, but if we initialize to false it will be saved that way even as our custom notifications improve
</blockquote></details>

Changed to default enabled.
___
*[src/platform/desktop_notifications/desktopnotify.cpp, line 28 at r1](https://reviewable.io/reviews/qtox/qtox/5351#-LaUJGqZCZlhL5--IP7e:-Laa6wibEPpWOgSnhoVx:bamfisf) ([raw file](https://github.com/qtox/qtox/blob/bab655f46962ac58ef8aa7c590425a1a4765227d/src/platform/desktop_notifications/desktopnotify.cpp#L28)):*
<details><summary><i>Previously, anthonybilinski (Anthony Bilinski) wrote…</i></summary><blockquote>

why create Snore::Notifications as pointers, store them as members, only to dereference the pointer to pass it into Snore? why not just make a Notification and pass that into Snore, without storing it as a member?
</blockquote></details>

Simplified the code a lot, not sure what  I was thinking there
___
*[src/platform/desktop_notifications/desktopnotify.cpp, line 48 at r1](https://reviewable.io/reviews/qtox/qtox/5351#-LaUM-nU9vJR-Z8PRpoB:-LaaB58-Bt_A14-OweZZ:bnonp43) ([raw file](https://github.com/qtox/qtox/blob/bab655f46962ac58ef8aa7c590425a1a4765227d/src/platform/desktop_notifications/desktopnotify.cpp#L48)):*
<details><summary><i>Previously, anthonybilinski (Anthony Bilinski) wrote…</i></summary><blockquote>

why is the group message notification saved to `groupInvite` instead of `groupMessage`?
</blockquote></details>

done, was a bug
___
*[src/platform/desktop_notifications/desktopnotify.cpp, line 48 at r1](https://reviewable.io/reviews/qtox/qtox/5351#-LaUMAqr0avL19ZMSUVI:-LaaB7GM9CzG_x2DC-dL:bnonp43) ([raw file](https://github.com/qtox/qtox/blob/bab655f46962ac58ef8aa7c590425a1a4765227d/src/platform/desktop_notifications/desktopnotify.cpp#L48)):*
<details><summary><i>Previously, anthonybilinski (Anthony Bilinski) wrote…</i></summary><blockquote>

why no Snore::broadcastNotification only in this case?
</blockquote></details>

done, was a bug
___
*[src/platform/desktop_notifications/desktopnotify.cpp, line 65 at r1](https://reviewable.io/reviews/qtox/qtox/5351#-LaUMN4kEQ1tljHIQj7I:-LaaB8zUEfodJ3cDAU95:bnonp43) ([raw file](https://github.com/qtox/qtox/blob/bab655f46962ac58ef8aa7c590425a1a4765227d/src/platform/desktop_notifications/desktopnotify.cpp#L65)):*
<details><summary><i>Previously, anthonybilinski (Anthony Bilinski) wrote…</i></summary><blockquote>

same, why friendMessage?
</blockquote></details>

done, was a bug
___
*[src/platform/desktop_notifications/desktopnotify.cpp, line 83 at r1](https://reviewable.io/reviews/qtox/qtox/5351#-LaULjcO02YhOLqX_9L3:-LaaBErL30uJ3-lvrEs7:bnonp43) ([raw file](https://github.com/qtox/qtox/blob/bab655f46962ac58ef8aa7c590425a1a4765227d/src/platform/desktop_notifications/desktopnotify.cpp#L83)):*
<details><summary><i>Previously, anthonybilinski (Anthony Bilinski) wrote…</i></summary><blockquote>

same, why friendMessage?
</blockquote></details>

done, was a bug
___
*[src/platform/desktop_notifications/desktopnotify.cpp, line 98 at r1](https://reviewable.io/reviews/qtox/qtox/5351#-LaUFJUE-tkwT3oW4cSE:-LaaBGG63puz9a8JpNsR:b-hfpv0l) ([raw file](https://github.com/qtox/qtox/blob/bab655f46962ac58ef8aa7c590425a1a4765227d/src/platform/desktop_notifications/desktopnotify.cpp#L98)):*
<details><summary><i>Previously, anthonybilinski (Anthony Bilinski) wrote…</i></summary><blockquote>

bump up severity of log?
</blockquote></details>

removed
___
*[src/widget/widget.cpp, line 1717 at r1](https://reviewable.io/reviews/qtox/qtox/5351#-LaUXIa-Cs4YvlGdFpj4:-LaaBYXNEs0rhDL5Dus0:br4wyo1) ([raw file](https://github.com/qtox/qtox/blob/bab655f46962ac58ef8aa7c590425a1a4765227d/src/widget/widget.cpp#L1717)):*
<details><summary><i>Previously, anthonybilinski (Anthony Bilinski) wrote…</i></summary><blockquote>

newMessageAlert() can still call QApplication::alert, which at least on gnome3 sends its own notification, resulting in 2 notifications for the same thing. Alert also handles making the icon flash orange or whatever OS-specific impl, but it looks like if I remove the alert() call that still happens, thanks to Snore
</blockquote></details>

At this moment it's intended to flash the window + notification, for more fine grained control I think we have to make some major internal changes so I considered this out of scope for this PR.


<!-- Sent from Reviewable.io -->

2019-03-22 17:05 UTC, sudden6 commented
note: I'll probably clean up the history before merging

2019-03-22 22:44 UTC, anthonybilinski requested changes
> Reviewed 3 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/qtox/qtox/5351)* status: 0 of 1 LGTMs obtained (waiting on @anthonybilinski)

___
*[CMakeLists.txt, line 654 at r1](https://reviewable.io/reviews/qtox/qtox/5351#-LaUW9f2BcO9APunTsYg:-LabYSep7nwTi6v6qNtV:bhfzg99) ([raw file](https://github.com/qtox/qtox/blob/bab655f46962ac58ef8aa7c590425a1a4765227d/CMakeLists.txt#L654)):*
<details><summary><i>Previously, sudden6 wrote…</i></summary><blockquote>

I want this to be disabled by default until it has gone through some testing. Do you think we should make it default enabled?
</blockquote></details>

ok that seems reasonable, if we decide to change it to default in the future it will be an easy transition.
___
*[src/platform/desktop_notifications/desktopnotify.h, line 29 at r2](https://reviewable.io/reviews/qtox/qtox/5351#-LabZ0lhCIBEBaB8Q2eD:-LabZ0lhCIBEBaB8Q2eE:b-7nbqfe) ([raw file](https://github.com/qtox/qtox/blob/5f04e4f267717f4f430a4a2cedeffce5cb262f36/src/platform/desktop_notifications/desktopnotify.h#L29)):*
> ```objc
>     Snore::Notification groupMessage = {};
>     Snore::Notification friendRequest = {};
>     Snore::Notification friendMessage = {};
> ```

this is nicer, but I still don't understand why these need to be state of the class and then copied into snore. Couldn't for exmaple notifyGroupMessage create a notification from createNotification on its local stack, and move that directly into broadcastNotification, without ever touching class state?
___
*[src/widget/widget.cpp, line 1717 at r1](https://reviewable.io/reviews/qtox/qtox/5351#-LaUXIa-Cs4YvlGdFpj4:-LabZf3_-GVW8Wt9Ec7t:bh58vfd) ([raw file](https://github.com/qtox/qtox/blob/bab655f46962ac58ef8aa7c590425a1a4765227d/src/widget/widget.cpp#L1717)):*
<details><summary><i>Previously, sudden6 wrote…</i></summary><blockquote>

At this moment it's intended to flash the window + notification, for more fine grained control I think we have to make some major internal changes so I considered this out of scope for this PR.
</blockquote></details>

understandable, I'm not looking for an expansion of scope, I'm just saying that with your PR, enabling snore notifications doesn't disable all our QApplication::alert notification system, so two notifications for each event are received by the user.


<!-- Sent from Reviewable.io -->

2019-03-23 22:36 UTC, sudden6 reviewed
> *[Reviewable](https://reviewable.io/reviews/qtox/qtox/5351)* status: 0 of 1 LGTMs obtained (waiting on @anthonybilinski)

___
*[CMakeLists.txt, line 654 at r1](https://reviewable.io/reviews/qtox/qtox/5351#-LaUW9f2BcO9APunTsYg:-LaggCE63B58PqsFozeX:b-hgjhf4) ([raw file](https://github.com/qtox/qtox/blob/bab655f46962ac58ef8aa7c590425a1a4765227d/CMakeLists.txt#L654)):*
<details><summary><i>Previously, anthonybilinski (Anthony Bilinski) wrote…</i></summary><blockquote>

ok that seems reasonable, if we decide to change it to default in the future it will be an easy transition.
</blockquote></details>

ok, yeah that was the plan
___
*[src/platform/desktop_notifications/desktopnotify.h, line 29 at r2](https://reviewable.io/reviews/qtox/qtox/5351#-LabZ0lhCIBEBaB8Q2eD:-LaggI5b5T6fCrqljLIe:bs4uog6) ([raw file](https://github.com/qtox/qtox/blob/5f04e4f267717f4f430a4a2cedeffce5cb262f36/src/platform/desktop_notifications/desktopnotify.h#L29)):*
<details><summary><i>Previously, anthonybilinski (Anthony Bilinski) wrote…</i></summary><blockquote>

this is nicer, but I still don't understand why these need to be state of the class and then copied into snore. Couldn't for exmaple notifyGroupMessage create a notification from createNotification on its local stack, and move that directly into broadcastNotification, without ever touching class state?
</blockquote></details>

I think I was planing to much ahead here, simplified.
___
*[src/widget/widget.cpp, line 1717 at r1](https://reviewable.io/reviews/qtox/qtox/5351#-LaUXIa-Cs4YvlGdFpj4:-LaggP645-ypdTpY0hWC:b-eo190j) ([raw file](https://github.com/qtox/qtox/blob/bab655f46962ac58ef8aa7c590425a1a4765227d/src/widget/widget.cpp#L1717)):*
<details><summary><i>Previously, anthonybilinski (Anthony Bilinski) wrote…</i></summary><blockquote>

understandable, I'm not looking for an expansion of scope, I'm just saying that with your PR, enabling snore notifications doesn't disable all our QApplication::alert notification system, so two notifications for each event are received by the user.
</blockquote></details>

ok, I'm aware of this drawback, but don't intend to fix it, especially since either window flashing or desktop notifications can be disabled by the user.


<!-- Sent from Reviewable.io -->

2019-03-24 08:37 UTC, anthonybilinski requested changes
> Reviewed 1 of 15 files at r1, 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/qtox/qtox/5351)* status: 0 of 1 LGTMs obtained (waiting on @anthonybilinski)

___
*[simple_make.sh, line 41 at r3](https://reviewable.io/reviews/qtox/qtox/5351#-LahSsl60oK-KRenIse-:-LahSsl60oK-KRenIse0:b-jh95zb) ([raw file](https://github.com/qtox/qtox/blob/c0f493b6b82433005872246a0aa19aa1053aac30/simple_make.sh#L41)):*
> ```Shell
>     fi
> 
>     sudo apt-get install $APT_FLAGS "${apt_packages[@]}"
> ```

don't the list of packages still need to be passed to apt-get, like they were before the change you're reversing in f7345e4db264a5681490b9094981a65cac68d317 and  64a7c24b2b5ad11a6df5dbb11da6e3aa7c0fd6f3?
___
*[appimage/build.sh, line 109 at r3](https://reviewable.io/reviews/qtox/qtox/5351#-LaipUY37SSrCs31Dk_6:-LaipUY37SSrCs31Dk_7:b-4ajysf) ([raw file](https://github.com/qtox/qtox/blob/b664901606bf07b29d8a22b065af200f4d28fc81/appimage/build.sh#L109)):*
> ```Shell
> cmake -DDESKTOP_NOTIFICATIONS=True ../
> 
> make
> ```

`make` two lines in a row?
___
*[src/platform/desktop_notifications/desktopnotify.cpp, line 40 at r3](https://reviewable.io/reviews/qtox/qtox/5351#-LahRiW1EnHBuWGnMxza:-LahRiW20xD80vKShhpu:bryp1ow) ([raw file](https://github.com/qtox/qtox/blob/b664901606bf07b29d8a22b065af200f4d28fc81/src/platform/desktop_notifications/desktopnotify.cpp#L40)):*
> ```cpp
> }
> 
> void DesktopNotify::notifyFriendRequest()
> ```

these 4 notify functions are completely common except for the title. What do  you think about moving everything but the title into a private notify(title) function, and having each public API just call that and pass in the title for the given notification type?
___
*[src/widget/widget.cpp, line 1717 at r1](https://reviewable.io/reviews/qtox/qtox/5351#-LaUXIa-Cs4YvlGdFpj4:-LaiqB5j30tqDs-ipWzq:b-ohlmm2) ([raw file](https://github.com/qtox/qtox/blob/bab655f46962ac58ef8aa7c590425a1a4765227d/src/widget/widget.cpp#L1717)):*
<details><summary><i>Previously, sudden6 wrote…</i></summary><blockquote>

ok, I'm aware of this drawback, but don't intend to fix it, especially since either window flashing or desktop notifications can be disabled by the user.
</blockquote></details>

see github comment with images
___
*[src/widget/form/settings/userinterfaceform.cpp, line 271 at r3](https://reviewable.io/reviews/qtox/qtox/5351#-LahQ8faAwvonOlXAkYj:-LahQ8faAwvonOlXAkYk:b5bcglz) ([raw file](https://github.com/qtox/qtox/blob/b664901606bf07b29d8a22b065af200f4d28fc81/src/widget/form/settings/userinterfaceform.cpp#L271)):*
> ```cpp
> }
> 
> void UserInterfaceForm::on_notify_stateChanged()
> ```

desktop notifications' enable should be toggled here as well, since it is a subset of Notify in UI, and only functions if Notify is selected in code.


<!-- Sent from Reviewable.io -->

2019-03-24 08:37 UTC, anthonybilinski commented
Sorry to keep going back to this, but just to be clear, when I compile with snore and enable desktop notifications, this is the popup notification I see on a new message (the QApplication::alert default one):
![snore-enabled-default-popup](https://user-images.githubusercontent.com/10469203/54873843-87cb5f00-4d9c-11e9-9991-911280e71703.png)
And then in the message tray, I see both the snore notification and the Qt notification:
![snore-enabled-original](https://user-images.githubusercontent.com/10469203/54873844-87cb5f00-4d9c-11e9-92f2-906ef2ca63d6.png)

The user unchecking "Notify" has more effects than just removing the Qt alert, so AFAIK there's no way for the user to just use desktop notifications.

If I add a check in Widget::newMessageAlert to not use QApplication::alert if desktop notifications are being used:
```
diff --git a/src/widget/widget.cpp b/src/widget/widget.cpp
index 308ea663..89c7ee92 100644
--- a/src/widget/widget.cpp
+++ b/src/widget/widget.cpp
@@ -1446,7 +1446,13 @@ bool Widget::newMessageAlert(QWidget* currentWindow, bool isActive, bool sound,
 
         if (settings.getNotify()) {
             if (inactiveWindow) {
+#if DESKTOP_NOTIFICATIONS
+                if (!settings.getDesktopNotify()) {
+                    QApplication::alert(currentWindow);
+                }
+#else
                 QApplication::alert(currentWindow);
+#endif
                 eventFlag = true;
             }
             bool isBusy = Nexus::getCore()->getStatus() == Status::Busy;
```

Then I see only the Qt notification if "Notify via desktop notifications" is unchecked:
![snore-desktop-disabled](https://user-images.githubusercontent.com/10469203/54873840-87cb5f00-4d9c-11e9-9c89-0d6d1b4ccfc0.png)
And only the Snore notification if "Notify via desktop notifications" is checked:
![snore-desktop-enabled](https://user-images.githubusercontent.com/10469203/54873842-87cb5f00-4d9c-11e9-8661-b03334508684.png)

which is what I originally expected.

2019-03-24 10:59 UTC, sudden6 reviewed
> *[Reviewable](https://reviewable.io/reviews/qtox/qtox/5351)* status: 0 of 1 LGTMs obtained (waiting on @anthonybilinski)

___
*[simple_make.sh, line 41 at r3](https://reviewable.io/reviews/qtox/qtox/5351#-LahSsl60oK-KRenIse-:-LajLa3qC8qSxaX5AS9M:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/c0f493b6b82433005872246a0aa19aa1053aac30/simple_make.sh#L41)):*
<details><summary><i>Previously, anthonybilinski (Anthony Bilinski) wrote…</i></summary><blockquote>

don't the list of packages still need to be passed to apt-get, like they were before the change you're reversing in f7345e4db264a5681490b9094981a65cac68d317 and  64a7c24b2b5ad11a6df5dbb11da6e3aa7c0fd6f3?
</blockquote></details>

Done.
___
*[appimage/build.sh, line 109 at r3](https://reviewable.io/reviews/qtox/qtox/5351#-LaipUY37SSrCs31Dk_6:-LajFD5MCD64VqWkgdUM:b-9v4df1) ([raw file](https://github.com/qtox/qtox/blob/b664901606bf07b29d8a22b065af200f4d28fc81/appimage/build.sh#L109)):*
<details><summary><i>Previously, anthonybilinski (Anthony Bilinski) wrote…</i></summary><blockquote>

`make` two lines in a row?
</blockquote></details>

one is `make` one is `make install`, I like to keep them separated  because it's easier to read the logs then
___
*[src/platform/desktop_notifications/desktopnotify.cpp, line 40 at r3](https://reviewable.io/reviews/qtox/qtox/5351#-LahRiW1EnHBuWGnMxza:-LajLjIwBJKj6PIJ8Seb:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/b664901606bf07b29d8a22b065af200f4d28fc81/src/platform/desktop_notifications/desktopnotify.cpp#L40)):*
<details><summary><i>Previously, anthonybilinski (Anthony Bilinski) wrote…</i></summary><blockquote>

these 4 notify functions are completely common except for the title. What do  you think about moving everything but the title into a private notify(title) function, and having each public API just call that and pass in the title for the given notification type?
</blockquote></details>

Done.
___
*[src/widget/form/settings/userinterfaceform.cpp, line 271 at r3](https://reviewable.io/reviews/qtox/qtox/5351#-LahQ8faAwvonOlXAkYj:-LajLlhC3L6hgcEqXqaL:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/b664901606bf07b29d8a22b065af200f4d28fc81/src/widget/form/settings/userinterfaceform.cpp#L271)):*
<details><summary><i>Previously, anthonybilinski (Anthony Bilinski) wrote…</i></summary><blockquote>

desktop notifications' enable should be toggled here as well, since it is a subset of Notify in UI, and only functions if Notify is selected in code.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2019-03-24 11:00 UTC, sudden6 commented
Now I understand what you mean by "two notifications"!

I don't get any notification on `alert()` on KDE, just the window blinking so I was a bit confused until now. Implemented your suggested change. Thanks for your patience :)

2019-03-24 20:54 UTC, anthonybilinski approved these changes
<img class="emoji" title=":lgtm_strong:" alt=":lgtm_strong:" align="absmiddle" src="https://reviewable.io/lgtm_strong.png" height="20" width="61"/>

> Reviewed 5 of 5 files at r4.
> *[Reviewable](https://reviewable.io/reviews/qtox/qtox/5351#-:-LalJ5Zp1lB8IGyz0Eox:b-jbsf8z)* status: :shipit: complete! 1 of 1 LGTMs obtained



<!-- Sent from Reviewable.io -->

2019-03-24 21:43 UTC, merged