Autoaccept file limit
qTox/qTox pull request #5373
Opened 2018-10-06 06:28 UTC by sphaerophoria

- [x ] Commits follow our [git commit guidelines](https://github.com/qTox/qTox/blob/master/CONTRIBUTING.md#git-commit-guidelines)

As discussed in #5348 it would be desirable to have a way to limit autoaccept to files under a certain size. This PR implements that.

No UI changes to the chatlog, just an extra item in the general settings pane
![image](https://user-images.githubusercontent.com/1069811/46568222-1a169e00-c8f6-11e8-934b-b543c8c56929.png)

Ran the following tests
* Ensure default value is 20MB (up for discussion, just seemed like a sane limit to me)
* Send file above 20M and below 20M, only below 20M should be auto accepted
* Change value to 5
* Send file above 5M and below 5M, only file below 5M should be auto accepted
* restart qtox
* Send file above 5M and below 5M, only file below 5M should be auto accepted
* Set value to 0
* Send a really large file, should be auto accepted

2018-10-06 21:27 UTC, sudden6 approved these changes
<img class="emoji" title=":lgtm_strong:" alt=":lgtm_strong:" align="absmiddle" src="https://reviewable.io/lgtm_strong.png" height="20" width="61"/>

> Reviewed 6 of 6 files at r1.
> *[Reviewable](https://reviewable.io/reviews/qtox/qtox/5373#-:-LOAGinN8lxnw_7DxUwZ:b-jbsf8z)* status: :shipit: complete! 1 of 1 LGTMs obtained



<!-- Sent from Reviewable.io -->

2018-10-08 21:21 UTC, sudden6 commented
@anthonybilinski @Diadlo please also review, since this is probably the beginning of a major change series.

2018-10-09 05:19 UTC, Diadlo requested changes
<img class="emoji" title=":lgtm_strong:" alt=":lgtm_strong:" align="absmiddle" src="https://reviewable.io/lgtm_strong.png" height="20" width="61"/> 

> Reviewed 5 of 6 files at r1.
> *[Reviewable](https://reviewable.io/reviews/qtox/qtox/5373#-:-LOMFuR_C_eEdvi3nKJi:b-uwkowd)* status: :shipit: complete! 2 of 1 LGTMs obtained

___
*[src/persistence/settings.cpp, line 180 at r1](https://reviewable.io/reviews/qtox/qtox/5373#-LOMEntaB2AQz2zkDTmY:-LOMEntaB2AQz2zkDTmZ:b-gbkyif) ([raw file](https://github.com/qtox/qtox/blob/727b47bb4b5001de7d6da6f9705cafbc12104870/src/persistence/settings.cpp#L180)):*
> ```cpp
>         notifySound =
>             s.value("notifySound", true)
>                 .toBool(); // note: notifySound and busySound UI elements are now under UI settings
> ```

AFAIK the comment was added a long time ago, when settings UI was redesigned. The comment can be deleted and line reformatted (same for the line below)
___
*[src/persistence/settings.cpp, line 190 at r1](https://reviewable.io/reviews/qtox/qtox/5373#-LOMFCpADOzSrhc07fov:-LOMFCpADOzSrhc07fow:b-z7a5fo) ([raw file](https://github.com/qtox/qtox/blob/727b47bb4b5001de7d6da6f9705cafbc12104870/src/persistence/settings.cpp#L190)):*
> ```cpp
>                                                              QStandardPaths::LocateDirectory))
>                                   .toString();
>         autoAcceptMaxSize = static_cast<size_t>(s.value("autoAcceptMaxSize", 20 << 20).toLongLong());
> ```

Please, add comment that `20 << 20` is `20Mb`. Is it?)


<!-- Sent from Reviewable.io -->

2018-10-09 05:20 UTC, Diadlo approved these changes
Small notes. For the rest <img class="emoji" title=":lgtm_strong:" alt=":lgtm_strong:" align="absmiddle" src="https://reviewable.io/lgtm_strong.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/qtox/qtox/5373#-:-LOMG4IF2Vn204zuW_J-:brmnwyp)* status: :shipit: complete! 2 of 1 LGTMs obtained



<!-- Sent from Reviewable.io -->

2018-10-09 06:20 UTC, sphaerophoria reviewed
> *[Reviewable](https://reviewable.io/reviews/qtox/qtox/5373)* status: :shipit: complete! 2 of 1 LGTMs obtained

___
*[src/persistence/settings.cpp, line 180 at r1](https://reviewable.io/reviews/qtox/qtox/5373#-LOMEntaB2AQz2zkDTmY:-LOMSlcs69U3dmAlTPFe:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/727b47bb4b5001de7d6da6f9705cafbc12104870/src/persistence/settings.cpp#L180)):*
<details><summary><i>Previously, Diadlo (Polshakov Dmitry) wrote…</i></summary><blockquote>

AFAIK the comment was added a long time ago, when settings UI was redesigned. The comment can be deleted and line reformatted (same for the line below)
</blockquote></details>

Done.
___
*[src/persistence/settings.cpp, line 190 at r1](https://reviewable.io/reviews/qtox/qtox/5373#-LOMFCpADOzSrhc07fov:-LOMT1iCDRkYgX-1uohT:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/727b47bb4b5001de7d6da6f9705cafbc12104870/src/persistence/settings.cpp#L190)):*
<details><summary><i>Previously, Diadlo (Polshakov Dmitry) wrote…</i></summary><blockquote>

Please, add comment that `20 << 20` is `20Mb`. Is it?)
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2018-10-09 06:43 UTC, sphaerophoria commented
@sudden6 something went wrong in the build script, can we kick off a new CI check? (Sorry I don't remember where the last discussion on this was had and I remember you had some concerns about close + reopen to kick off build)

2018-10-09 08:32 UTC, sudden6 commented
@sphaerophoria done, you can trigger a rebuild by somehow changing the commit hash and then doing a force push. Example: add empty line, force push, remove to restore old state, force push to this branch.

2018-10-11 17:46 UTC, anthonybilinski approved these changes
> Reviewed 5 of 6 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/qtox/qtox/5373)* status: :shipit: complete! 2 of 1 LGTMs obtained

___
*[src/persistence/settings.cpp, line 180 at r1](https://reviewable.io/reviews/qtox/qtox/5373#-LOMEntaB2AQz2zkDTmY:-LOZD2Yf00IpaqwCixSK:brebllt) ([raw file](https://github.com/qtox/qtox/blob/727b47bb4b5001de7d6da6f9705cafbc12104870/src/persistence/settings.cpp#L180)):*
<details><summary><i>Previously, sphaerophoria wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Comment was added because the setting groups correspond to the settings UI pages, so it's odd that notifySound and busySound are under setting group "General" but settings page "UI". I'm not sure this comment should be removed since that still is (and probably always will be) the case.


<!-- Sent from Reviewable.io -->

2018-10-12 03:25 UTC, sphaerophoria reviewed
> *[Reviewable](https://reviewable.io/reviews/qtox/qtox/5373)* status: :shipit: complete! 2 of 1 LGTMs obtained

___
*[src/persistence/settings.cpp, line 180 at r1](https://reviewable.io/reviews/qtox/qtox/5373#-LOMEntaB2AQz2zkDTmY:-LOaIVyd-rQn9S44--A5:b-5kckdb) ([raw file](https://github.com/qtox/qtox/blob/727b47bb4b5001de7d6da6f9705cafbc12104870/src/persistence/settings.cpp#L180)):*
<details><summary><i>Previously, anthonybilinski (Anthony Bilinski) wrote…</i></summary><blockquote>

Comment was added because the setting groups correspond to the settings UI pages, so it's odd that notifySound and busySound are under setting group "General" but settings page "UI". I'm not sure this comment should be removed since that still is (and probably always will be) the case.
</blockquote></details>

I misunderstood why the comment was there. I agree with Anthony, reverting change.


<!-- Sent from Reviewable.io -->

2018-10-12 18:20 UTC, anthonybilinski approved these changes
<img class="emoji" title=":lgtm_strong:" alt=":lgtm_strong:" align="absmiddle" src="https://reviewable.io/lgtm_strong.png" height="20" width="61"/>

> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/qtox/qtox/5373#-:-LOdVWO8DDERiNz32oSI:b-jbsf8z)* status: :shipit: complete! 3 of 1 LGTMs obtained



<!-- Sent from Reviewable.io -->

2018-10-12 21:29 UTC, merged