Integrate Paths class into qTox code
qTox/qTox pull request #5440
Opened 2018-11-19 15:24 UTC by sudden6

- [ ] Commits follow our [git commit guidelines](https://github.com/qTox/qTox/blob/master/CONTRIBUTING.md#git-commit-guidelines)

This PR provides the integration for the Paths module in the existing code. I decided to pass `Paths` via a getter function through the `Settings` class in order to keep the amount of changes manageable.

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qtox/qtox/5440)

2018-11-20 04:25 UTC, Diadlo requested changes

2018-11-20 04:25 UTC, Diadlo commented on src/persistence/profile.cpp
> +QStringList Profile::getFilesByExt(QString directory, QString extension)
const reerence

2018-11-20 04:25 UTC, Diadlo commented on src/persistence/profile.cpp
> +    return Settings::getInstance().getPaths().getProfilesDir() % name;
I think it's better to add ` + ".ini"` here and reimplement `getDbPath` using `Settings::getInstance().getPaths()` (i.e. without `getProfilePath`) and move it closer to each other

2018-11-20 04:25 UTC, Diadlo commented on src/persistence/settings.cpp
> +    Settings* s = new Settings{paths};
Why not?
```
settings = new Settings{paths};
return settings;
```

2018-11-20 04:25 UTC, Diadlo commented on src/persistence/settings.cpp
> +        notifySound =
Could comment be moved on the previous line (before `notifySound`) to avoid a lot of line breaks?

2018-11-20 04:25 UTC, Diadlo commented on src/persistence/settings.cpp
> +    return QFileInfo{settingsFile}.dir().absolutePath() + QDir::separator();
Maybe move this logic in `Paths`?

2018-11-20 04:25 UTC, Diadlo commented on src/widget/form/chatform.cpp
> +    filepath = QString("qTox_Image_%1.png")
`+=`?

2018-11-20 04:25 UTC, Diadlo commented on src/persistence/profile.cpp
> +    return Settings::getInstance().getPaths().getToxSaveDir() % name % ".tox";
And maybe move in `Paths`? Also used in `ProfileImporter`

2018-11-20 04:25 UTC, Diadlo commented on src/persistence/settings.cpp
> +    // TODO(sudden6): to be removed
Portable mode now removed?

2018-11-20 21:51 UTC, sudden6 commented on src/persistence/profile.cpp
> +    return Settings::getInstance().getPaths().getProfilesDir() % name;
I'd prefer to do this later to keep the number of changes under control here.

2018-11-20 21:51 UTC, sudden6 commented on src/persistence/profile.cpp
> +    return Settings::getInstance().getPaths().getToxSaveDir() % name % ".tox";
Same

2018-11-20 21:52 UTC, sudden6 commented on src/persistence/settings.cpp
> +    return QFileInfo{settingsFile}.dir().absolutePath() + QDir::separator();
Same

2018-11-20 21:52 UTC, sudden6 commented on src/persistence/settings.cpp
> +    // TODO(sudden6): to be removed
Moved to `Paths` and changed a bit. Current portable mode is horribly broken because it always writes to the user directory.

2018-11-21 09:38 UTC, sudden6 commented on src/persistence/settings.cpp
> +    Settings* s = new Settings{paths};
done

2018-11-21 09:38 UTC, sudden6 commented on src/persistence/settings.cpp
> +        notifySound =
Done

2018-11-21 09:39 UTC, sudden6 commented on src/widget/form/chatform.cpp
> +    filepath = QString("qTox_Image_%1.png")
Done

2018-11-21 09:39 UTC, sudden6 commented on src/persistence/profile.cpp
> +QStringList Profile::getFilesByExt(QString directory, QString extension)
Done

2018-11-21 09:48 UTC, Diadlo commented on src/persistence/profile.cpp
> +    return Settings::getInstance().getPaths().getProfilesDir() % name;
Ok. But both methods already touched

2018-11-21 09:51 UTC, Diadlo requested changes
> Reviewed 10 of 14 files at r1, 4 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/qtox/qtox/5440)* status: 0 of 1 LGTMs obtained

___
*[src/persistence/settings.cpp, line 788 at r1](https://reviewable.io/reviews/qtox/qtox/5440#-LRgZksI98cmRyHe4sYy-r1-788:-LRpfSAH3tQ-w5PyTRbJ:bhl5nck) ([raw file](https://github.com/qtox/qtox/blob/8ab3a449e1377ec0039616cd7696c12dd7d3be14/src/persistence/settings.cpp#L788)):*
<details><summary><i>Previously, sudden6 wrote…</i></summary><blockquote>

Moved to `Paths` and changed a bit. Current portable mode is horribly broken because it always writes to the user directory.
</blockquote></details>

But nothing is passed in `Paths` constructor. So it's impossible to run qTox portable


<!-- Sent from Reviewable.io -->

2018-11-21 12:11 UTC, sudden6 reviewed
> *[Reviewable](https://reviewable.io/reviews/qtox/qtox/5440)* status: 0 of 1 LGTMs obtained

___
*[src/persistence/settings.cpp, line 788 at r1](https://reviewable.io/reviews/qtox/qtox/5440#-LRgZksI98cmRyHe4sYy-r1-788:-LRqAOt33H6eYD_qtX6U:b-2nwfjx) ([raw file](https://github.com/qtox/qtox/blob/8ab3a449e1377ec0039616cd7696c12dd7d3be14/src/persistence/settings.cpp#L788)):*
<details><summary><i>Previously, Diadlo (Polshakov Dmitry) wrote…</i></summary><blockquote>

But nothing is passed in `Paths` constructor. So it's impossible to run qTox
</blockquote></details>

qTox will automatically run in portable mode if it finds a `qtox.ini` file besides the executable

In the future I want to add a command line switch to start in portable mode


<!-- Sent from Reviewable.io -->

2018-11-22 06:34 UTC, Diadlo approved these changes
<img class="emoji" title=":lgtm_strong:" alt=":lgtm_strong:" align="absmiddle" src="https://reviewable.io/lgtm_strong.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/qtox/qtox/5440#-:-LRu71Kj0Z4XXk7b6ijd:b-jbsf8z)* status: :shipit: complete! 1 of 1 LGTMs obtained



<!-- Sent from Reviewable.io -->

2018-12-05 04:54 UTC, anthonybilinski commented
I've pushed the upstream branch `path_rework` so that we can merge this change before the backwards compatible upgrade part is done, unblocking @sphaerophoria's multiple PRs that also touch paths. Once your upgrade code is done, we can merge `path_rework` back into `master`, so that `master` remains in a working state, as we discussed a couple days ago, @sudden6. I've set the base branch of this PR to `path_rework`, which causes change in diff since it is currently equal to `master`.

2018-12-05 05:31 UTC, anthonybilinski approved these changes
<img class="emoji" title=":lgtm_strong:" alt=":lgtm_strong:" align="absmiddle" src="https://reviewable.io/lgtm_strong.png" height="20" width="61"/>

> Reviewed 10 of 14 files at r1, 4 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/qtox/qtox/5440#-:-LSwqIa16t8lw0VA048N:b-jbsf8z)* status: :shipit: complete! 2 of 1 LGTMs obtained

___
*[src/persistence/profile.cpp, line 108 at r2](https://reviewable.io/reviews/qtox/qtox/5440#-LSwloWu0erQA29NOypO:-LSwloWu0erQA29NOypP:b-wumxoy) ([raw file](https://github.com/qtox/qtox/blob/80ee2bc68b1a6aac13e35c4b47f2b7cfb3bd7fdd/src/persistence/profile.cpp#L108)):*
> ```cpp
> QString Profile::getToxSavePath(const QString &name)
> {
>     return Settings::getInstance().getPaths().getToxSaveDir() % name % ".tox";
> ```

I agree with Diadlo here. It's confusing that getProfilePath and getToxSavePath act differently. I think getProfilePath should also include the extension. It's only called in 4 places (plus one special place where we get db path but call getProfilePath) per my index, so doesn't seem like it would cause a lot of new changes. If you disagree still feel free to merge, I won't block the PR on this.


<!-- Sent from Reviewable.io -->

2018-12-05 05:55 UTC, anthonybilinski commented
@sudden6 don't forget to merge to `path_rework` instead of `master` :)

2018-12-05 22:03 UTC, sudden6 commented
@anthonybilinski done

2018-12-05 22:03 UTC, closed without merging