feat(core): print a chat log entry when a user joins/leaves the group
qTox/qTox pull request #5469
Opened 2018-12-22 00:40 UTC by Monsterovich

![default](https://user-images.githubusercontent.com/3750982/50368574-dd704f80-0592-11e9-885e-09981d30a17c.png)

2018-12-22 23:26 UTC, sudden6 commented
___
*[src/widget/form/groupchatform.cpp, line 330 at r1](https://reviewable.io/reviews/qtox/qtox/5469#-LUND_7L5pDMIYT4BLjY:-LUND_7L5pDMIYT4BLjZ:b9pzftg) ([raw file](https://github.com/qtox/qtox/blob/48d8b3b6ceaa72eb9e45ff82e6bec893e8bc4081/src/widget/form/groupchatform.cpp#L330)):*
> ```cpp
>     for (const auto& peerPk : peers.keys()) {
>         const QString name = peers.value(peerPk);
>         // ignore weird issue: when user joins the group, the name is empty, then it's renamed to normal nickname (why?)
> ```

IIRC the Tox protocol allows empty nicknames and the nickname is only sent after joining, usually we display the public key instead of the empty string,
Not sure if it would be better to display two messages: 1. " 123FABC... joined" and then a message like "123FABC is now named tox-user1"?


<!-- Sent from Reviewable.io -->

2018-12-22 23:26 UTC, sudden6 commented
___
*[src/widget/form/groupchatform.cpp, line 323 at r1](https://reviewable.io/reviews/qtox/qtox/5469#-LUNDSj5-n40wQVp6BQu:-LUNDSj5-n40wQVp6BQv:b8ewgl) ([raw file](https://github.com/qtox/qtox/blob/48d8b3b6ceaa72eb9e45ff82e6bec893e8bc4081/src/widget/form/groupchatform.cpp#L323)):*
> ```cpp
>     if (groupLast.isEmpty())
>     {
>         groupLast = group->getPeerList();
> ```

why get the peer list again here and not use `peers`?


<!-- Sent from Reviewable.io -->

2018-12-22 23:27 UTC, sudden6 reviewed
Your coding style doesn't match the qTox style, please reformat. you can use `tools/format-code.sh` and commit only the files you changed to fix that.

> *[Reviewable](https://reviewable.io/reviews/qtox/qtox/5469#-:-LUNEQKf-et2EG7o7OjG:bfhz6m)* status: 0 of 1 LGTMs obtained



<!-- Sent from Reviewable.io -->

2018-12-23 00:24 UTC, Monsterovich commented
>why get the peer list again here and not use peers?

What? I use them below in "for" loop.

2018-12-23 00:24 UTC, Monsterovich commented
>Your coding style doesn't match the qTox style, please reformat. you can use tools/format-code.sh and commit only the files you changed to fix that.

Fixed it manually. Do not merge it. I have to fix one issue with nicknames.

2018-12-23 10:35 UTC, sudden6 commented
> What? I use them below in "for" loop.

A few lines above the for loop. You should probably take a look at the reviewable page (button in your first commit) to get the context for the comments.

2018-12-23 13:00 UTC, Monsterovich commented
I have one issue: when user changes the nickname, it's not changed on other clients:

![default](https://user-images.githubusercontent.com/3750982/50383801-625a8680-06c3-11e9-85b8-cfe92eb095e0.png)


```
[12:56:53.494 UTC] core/core.cpp:508 : Debug: "Group 0 peerlist changed"
[12:56:53.495 UTC] widget/form/groupchatform.cpp:329 : Debug: "name: Monsterovich"
[12:56:53.495 UTC] widget/form/groupchatform.cpp:329 : Debug: "name: <Пусто>"
[12:56:53.544 UTC] core/core.cpp:516 : Debug: "Group 0, Peer 1, name changed to wow"
[12:56:53.546 UTC] widget/form/groupchatform.cpp:329 : Debug: "name: Monsterovich"
[12:56:53.546 UTC] widget/form/groupchatform.cpp:329 : Debug: "name: wow"
[12:57:18.544 UTC] core/core.cpp:516 : Debug: "Group 0, Peer 1, name changed to wow2"
[12:57:18.546 UTC] widget/form/groupchatform.cpp:329 : Debug: "name: Monsterovich"
[12:57:18.546 UTC] widget/form/groupchatform.cpp:329 : Debug: "name: wow"
```

2018-12-23 18:44 UTC, sudden6 commented
Does `wow` have an alias set in your friends list? (Even if you didn't set one, verify this, there was a bug setting aliases, or try with two completely fresh profiles.)

Else I suspect a bug in this function or generally this file: https://github.com/qTox/qTox/blob/master/src/model/group.cpp#L45

2018-12-25 20:04 UTC, Monsterovich commented
How can I refresh this list of users in group by group id?

![default](https://user-images.githubusercontent.com/3750982/50426229-f3328d00-0890-11e9-8b78-ccedf391a368.png)

2018-12-26 06:13 UTC, Diadlo commented
@Monsterovich It should be done automatically somehow like this: 

`Widget::createGroup` connects `Core::usernameSet` to `Group::setSelfName`. "local user has changed its nickname" -> `Core::setUsername` -> `emit Core::usernameSet` -> `Group::regeneratePeerList()` -> `emit Group::userListChanged`

Not sure, what is the best way to update names on alias change. `Friend::setAlias` -> `emit Friend::displayedNameChanged`, but who should regenerate group peer list? In our current bad architecture you can place it in `Widget` or `Nexus`, IDK. Just take all groups from `GroupList::getAllGroups` and regenerate all peer list. It's not quite efficient, but probably the best way for now

2018-12-26 16:33 UTC, Monsterovich commented
![1](https://user-images.githubusercontent.com/3750982/50451437-af955d00-093c-11e9-87ce-1539c138aef0.png)
![3](https://user-images.githubusercontent.com/3750982/50451439-b623d480-093c-11e9-8e68-8329e2cec0b6.png)

Works as intended. You can merge it. :)

2018-12-26 22:36 UTC, sudden6 commented
@Diadlo do you want to review and merge this PR?

2018-12-27 06:25 UTC, Diadlo requested changes

2018-12-27 06:25 UTC, Diadlo commented on src/widget/form/groupchatform.cpp
> +        }
Our code style says, that should be `} else {`

2018-12-27 06:25 UTC, Diadlo commented on src/nexus.cpp
> +    connect(core, &Core::usernameSet, widget, &Widget::refreshPeerListsLocal);
Just a note, not for this PR, but for The Plan™

Probably logic of groups update should be moved in the new `ContactManager` class. Or something like this.

2018-12-27 10:49 UTC, Monsterovich commented on src/widget/form/groupchatform.cpp
> +        }
Done.

2018-12-27 11:01 UTC, Diadlo approved these changes
<img class="emoji" title=":lgtm_strong:" alt=":lgtm_strong:" align="absmiddle" src="https://reviewable.io/lgtm_strong.png" height="20" width="61"/>

> Reviewed 1 of 2 files at r1, 8 of 9 files at r2, 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/qtox/qtox/5469#-:-LUjJozY6JVCiRdILpu2:b-jbsf8z)* status: :shipit: complete! 1 of 1 LGTMs obtained



<!-- Sent from Reviewable.io -->

2019-01-04 12:42 UTC, Monsterovich commented
Will you merge it?

2019-01-04 13:57 UTC, merged

2019-01-04 13:59 UTC, sudden6 commented
Done