feat(build): remove timestamps from build to allow reproducible builds
qTox/qTox pull request #5524
Opened 2019-01-25 08:19 UTC by anthonybilinski

avoid Qt embedding timestamps into translations after copying .ts to .qm to work towards reproducible builds. Now reproducible locally as long as there is absolutely no change to environment.

- [ ] Commits follow our [git commit guidelines](https://github.com/qTox/qTox/blob/master/CONTRIBUTING.md#git-commit-guidelines)

2019-01-25 10:12 UTC, sudden6 requested changes
> Reviewed 1 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/qtox/qtox/5524)* status: 0 of 1 LGTMs obtained

___
*[CMakeLists.txt, line 107 at r1](https://reviewable.io/reviews/qtox/qtox/5524#-LX3UbNQ2PN6akJOoVs-:-LX3UbNS566MwXftzBLM:b-7npcj) ([raw file](https://github.com/qtox/qtox/blob/80101a75537b853fbbe0622d82b7e04c219d2fc4/CMakeLists.txt#L107)):*
> ```CMake
> include(Dependencies)
> 
> if(NOT Qt5Widgets_VERSION VERSION_LESS "5.9")
> ```

simplify with the usage of `VERSION_GREATER`? also use spaces instead of tabs


<!-- Sent from Reviewable.io -->

2019-01-25 16:58 UTC, anthonybilinski reviewed
> *[Reviewable](https://reviewable.io/reviews/qtox/qtox/5524)* status: 0 of 1 LGTMs obtained

___
*[CMakeLists.txt, line 107 at r1](https://reviewable.io/reviews/qtox/qtox/5524#-LX3UbNQ2PN6akJOoVs-:-LX4wEre7sK2QGFx9mrU:b-g4clax) ([raw file](https://github.com/qtox/qtox/blob/80101a75537b853fbbe0622d82b7e04c219d2fc4/CMakeLists.txt#L107)):*
<details><summary><i>Previously, sudden6 wrote…</i></summary><blockquote>

simplify with the usage of `VERSION_GREATER`? also use spaces instead of tabs
</blockquote></details>

cmake didn't add `GREATER_EQUAL` until 3.7 and a strict GREATER isn't logically equivalent.
Spacing fixed.


<!-- Sent from Reviewable.io -->

2019-01-25 21:55 UTC, sudden6 approved these changes
<img class="emoji" title=":lgtm_strong:" alt=":lgtm_strong:" align="absmiddle" src="https://reviewable.io/lgtm_strong.png" height="20" width="61"/>

> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/qtox/qtox/5524#-:-LX6-ZK02JXqvpCHkUB-:b-jbsf8z)* status: :shipit: complete! 1 of 1 LGTMs obtained



<!-- Sent from Reviewable.io -->

2019-01-28 16:15 UTC, anthonybilinski commented
I removed -Wdate-time since it looks like it was only added in gcc 4.9.

2019-01-28 17:44 UTC, sudden6 commented
maybe we can conditionally enable it using cmake?

2019-01-29 08:00 UTC, anthonybilinski commented
Done, now locally I have:
```-- CMAKE_CXX_FLAGS:  -std=c++11 -fno-exceptions -fno-rtti -Wstrict-overflow -Wstrict-aliasing -Werror -Wdate-time -fstack-protector-all -Wstack-protector -pthread -pthread```
and Travis (Ubuntu 14.04, GCC 4.8.x) has:
```-- CMAKE_CXX_FLAGS:  -std=c++11 -fno-exceptions -fno-rtti -Wstrict-overflow -Wstrict-aliasing -Werror -fstack-protector-all -Wstack-protector```

2019-01-29 08:07 UTC, sudden6 approved these changes
perfect <img class="emoji" title=":lgtm_strong:" alt=":lgtm_strong:" align="absmiddle" src="https://reviewable.io/lgtm_strong.png" height="20" width="61"/> 

> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/qtox/qtox/5524#-:-LXNdWF-6jrWpXSy80dI:bv02i5i)* status: :shipit: complete! 1 of 1 LGTMs obtained



<!-- Sent from Reviewable.io -->

2019-01-29 08:46 UTC, merged