Add Apparmor profile
qTox/qTox pull request #5577
Opened 2019-03-17 14:06 UTC by Talkless

Introduce AppArmor profile increaced security in Linux, reducing simplest attack vectors.

AppArmor profiles where developed on various distros - Debian Strech and Debian Buster (Sid) with KDE/Gnome, Ubuntu 18.04, openSUSE Tumbleweed, and maybe more configurations I do not recall.

Closes #5484

- [ x] Commits follow our [git commit guidelines](https://github.com/qTox/qTox/blob/master/CONTRIBUTING.md#git-commit-guidelines)

2019-03-18 19:38 UTC, sudden6 commented
Do you have anything who can review the AppArmor part?

2019-03-18 19:53 UTC, Talkless commented
@sudden6 I'll try to find someone from AppArmor community.

2019-03-18 19:54 UTC, setharnold commented
This looks good; the profiles are pretty loose but should still provide some protection from a subverted process.

Thanks

2019-03-18 19:56 UTC, Talkless commented
@setharnold Loose you mean writing to (almost) whole home, or something else?

2019-03-18 20:08 UTC, Talkless commented
I will update 
```
  network tcp,
  network udp,
``` 
into more strict rules in coming days.

2019-03-18 21:27 UTC, sudden6 requested changes
Looks good besides the tiny formatting issues.

Please also rebase onto latest master, else CI will cause problems.

> Reviewed 7 of 8 files at r1.
> *[Reviewable](https://reviewable.io/reviews/qtox/qtox/5577#-:-LaHgepRBMdpJfBUPxs1:b-nhbih3)* status: 0 of 1 LGTMs obtained

___
*[security/apparmor/README.md, line 1 at r1](https://reviewable.io/reviews/qtox/qtox/5577#-LaHgB9qA4Qqv2VQYn0V:-LaHgB9qA4Qqv2VQYn0W:b1ou008) ([raw file](https://github.com/qtox/qtox/blob/87d734e9564f188019e8409127e05eb30455dd99/security/apparmor/README.md#L1)):*
> ```Markdown
> # Hardening qTox with AppArmor
> ```

Please reformat this file to 80 chars per line and move all links to the bottom like in README.md. (Links do not need to adhere to 80 chars)
___
*[security/apparmor/README.md, line 11 at r1](https://reviewable.io/reviews/qtox/qtox/5577#-LaHf3wb-GqDkwIVdIpl:-LaHf3wc-1SZWhdEU1S8:b-orjtqr) ([raw file](https://github.com/qtox/qtox/blob/87d734e9564f188019e8409127e05eb30455dd99/security/apparmor/README.md#L11)):*
> ```Markdown
> Consider using additional security measures like [Firejail](https://firejail.wordpress.com/) to improve security even more.
> 
> Please also note that not all distributions has full AppArmor feature set available. For example, Debian (at least up to Debian 10 (buster)) does not have network, DBus mediation available. Also, X Server, shared user configuration files (like `~/.config/QtProject.conf`, caches, etc), opening web links via unconfined browsers introduces additional attack vectors, too. So please be cautious even with number of security measures applied.
> ```

`all distributions have`
___
*[security/apparmor/README.md, line 54 at r1](https://reviewable.io/reviews/qtox/qtox/5577#-LaHfOoO5hRCTFipbEkc:-LaHfOoO5hRCTFipbEkd:bef9vxw) ([raw file](https://github.com/qtox/qtox/blob/87d734e9564f188019e8409127e05eb30455dd99/security/apparmor/README.md#L54)):*
> ```Markdown
> ```
> 
> If OK it's marked as `(enforce)`. `uncofined` means AppArmor profile is not attached to the process, no confinement is being applied.
> ```

typo `unconfined`


<!-- Sent from Reviewable.io -->

2019-03-18 21:28 UTC, sudden6 commented
@setharnold thank you for taking a look

2019-03-25 18:13 UTC, Talkless reviewed
> *[Reviewable](https://reviewable.io/reviews/qtox/qtox/5577)* status: 0 of 1 LGTMs obtained (waiting on @sudden6)

___
*[security/apparmor/README.md, line 1 at r1](https://reviewable.io/reviews/qtox/qtox/5577#-LaHgB9qA4Qqv2VQYn0V:-Laq2bK6Ds3U0CPTABlE:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/87d734e9564f188019e8409127e05eb30455dd99/security/apparmor/README.md#L1)):*
<details><summary><i>Previously, sudden6 wrote…</i></summary><blockquote>

Please reformat this file to 80 chars per line and move all links to the bottom like in README.md. (Links do not need to adhere to 80 chars)
</blockquote></details>

Done.
___
*[security/apparmor/README.md, line 11 at r1](https://reviewable.io/reviews/qtox/qtox/5577#-LaHf3wb-GqDkwIVdIpl:-Laq2d0Y968I_oncXefm:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/87d734e9564f188019e8409127e05eb30455dd99/security/apparmor/README.md#L11)):*
<details><summary><i>Previously, sudden6 wrote…</i></summary><blockquote>

`all distributions have`
</blockquote></details>

Done.
___
*[security/apparmor/README.md, line 54 at r1](https://reviewable.io/reviews/qtox/qtox/5577#-LaHfOoO5hRCTFipbEkc:-Laq2e_GCnEPWE-S3l9T:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/87d734e9564f188019e8409127e05eb30455dd99/security/apparmor/README.md#L54)):*
<details><summary><i>Previously, sudden6 wrote…</i></summary><blockquote>

typo `unconfined`
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2019-03-25 18:17 UTC, Talkless reviewed
One commit `fix(apparmor): backport kde abstraction` stars with lovercase `b`, should I fix that @sudden6 ?

> *[Reviewable](https://reviewable.io/reviews/qtox/qtox/5577#-:-Laq3Kr3E3gHcYr3QAm8:b-8z69c3)* status: 0 of 1 LGTMs obtained (waiting on @sudden6)



<!-- Sent from Reviewable.io -->

2019-03-25 19:13 UTC, sudden6 approved these changes
> One commit fix(apparmor): backport kde abstraction stars with lovercase b, should I fix that @sudden6 ?
No, that's not a problem.

<img class="emoji" title=":lgtm_strong:" alt=":lgtm_strong:" align="absmiddle" src="https://reviewable.io/lgtm_strong.png" height="20" width="61"/> 

> Reviewed 4 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/qtox/qtox/5577#-:-LaqGD_k1yt6a1nSro8X:bfeeb7q)* status: :shipit: complete! 1 of 1 LGTMs obtained



<!-- Sent from Reviewable.io -->

2019-03-26 16:52 UTC, merged