[Refactor] Dialogs
qTox/qTox pull request #5670
Opened 2019-05-17 12:05 UTC by Diadlo

Move more logic from the `FriendWidget` and `GroupWidget` into the corresponding model `Chatroom` classes.
Reduce the usage of `ContentDialogManager` singleton.

2019-05-21 18:55 UTC, sudden6 requested changes
> Reviewed 7 of 14 files at r1.
> *[Reviewable](https://reviewable.io/reviews/qtox/qtox/5670)* status: 0 of 1 LGTMs obtained

___
*[src/model/dialogs/idialogs.h, line 33 at r1](https://reviewable.io/reviews/qtox/qtox/5670#-LfQj6hg2luh2uqoyqGX:-LfQj6hh8V-940sWU7Wm:b-cgbmyg) ([raw file](https://github.com/qtox/qtox/blob/667afd7fde603a777edb90bc7f2c244efa710f21/src/model/dialogs/idialogs.h#L33)):*
> ```objc
>     virtual bool isContactActive(const ContactId& contactId) const = 0;
> 
>     virtual void removeFriend(const ToxPk& friendPk) = 0;
> ```

Would it be possible to do this in one method `removeContact(const ContactId& contact)` using `qobject_cast`? I think this would reduce the complexity
___
*[src/model/dialogs/idialogsmanager.h, line 31 at r1](https://reviewable.io/reviews/qtox/qtox/5670#-LfQjO9N4CHUyY_sRCON:-LfQjO9ODzPg6tIJ58kR:bs2cfuh) ([raw file](https://github.com/qtox/qtox/blob/667afd7fde603a777edb90bc7f2c244efa710f21/src/model/dialogs/idialogsmanager.h#L31)):*
> ```objc
> {
> public:
>     virtual IDialogs* getFriendDialogs(const ToxPk& friendPk) const = 0;
> ```

Same as above, should be possible to have one method.


<!-- Sent from Reviewable.io -->

2019-05-23 06:24 UTC, Diadlo reviewed
> *[Reviewable](https://reviewable.io/reviews/qtox/qtox/5670)* status: 0 of 1 LGTMs obtained

___
*[src/model/dialogs/idialogs.h, line 33 at r1](https://reviewable.io/reviews/qtox/qtox/5670#-LfQj6hg2luh2uqoyqGX:-LfYKbCT7n12tKBUXajd:byfqkon) ([raw file](https://github.com/qtox/qtox/blob/667afd7fde603a777edb90bc7f2c244efa710f21/src/model/dialogs/idialogs.h#L33)):*
<details><summary><i>Previously, sudden6 wrote…</i></summary><blockquote>

Would it be possible to do this in one method `removeContact(const ContactId& contact)` using `qobject_cast`? I think this would reduce the complexity
</blockquote></details>

Why? I don't see any reason to do it, it's just overcomplicating code.

While the caller knows the type, it can select the needed method (I can use the same name to create overload). One method can be used when (if) `ContentDialog` will store contacts as a list of `Contact`.
___
*[src/model/dialogs/idialogsmanager.h, line 31 at r1](https://reviewable.io/reviews/qtox/qtox/5670#-LfQjO9N4CHUyY_sRCON:-LfYM2VX3wLhw8euYR77:bcgtfmn) ([raw file](https://github.com/qtox/qtox/blob/667afd7fde603a777edb90bc7f2c244efa710f21/src/model/dialogs/idialogsmanager.h#L31)):*
<details><summary><i>Previously, sudden6 wrote…</i></summary><blockquote>

Same as above, should be possible to have one method.
</blockquote></details>

For what?


<!-- Sent from Reviewable.io -->

2019-05-28 12:01 UTC, Diadlo commented
@sudden6 ping

2019-05-28 18:32 UTC, sudden6 requested changes
> *[Reviewable](https://reviewable.io/reviews/qtox/qtox/5670)* status: 0 of 1 LGTMs obtained

___
*[src/model/dialogs/idialogs.h, line 33 at r1](https://reviewable.io/reviews/qtox/qtox/5670#-LfQj6hg2luh2uqoyqGX:-LfzhML8EpfzQKblfeLI:b-pwvalb) ([raw file](https://github.com/qtox/qtox/blob/667afd7fde603a777edb90bc7f2c244efa710f21/src/model/dialogs/idialogs.h#L33)):*
<details><summary><i>Previously, Diadlo (Polshakov Dmitry) wrote…</i></summary><blockquote>

Why? I don't see any reason to do it, it's just overcomplicating code.

While the caller knows the type, it can select the needed method (I can use the same name to create overload). One method can be used when (if) `ContentDialog` will store contacts as a list of `Contact`.
</blockquote></details>

I just don't see a reason why we would invent a common base class `ContactId` and then never use it. AFAICT both methods should do the same, just the type is different, so why not eliminate the difference?


<!-- Sent from Reviewable.io -->

2019-05-29 06:36 UTC, Diadlo reviewed
> *[Reviewable](https://reviewable.io/reviews/qtox/qtox/5670)* status: 0 of 1 LGTMs obtained

___
*[src/model/dialogs/idialogs.h, line 33 at r1](https://reviewable.io/reviews/qtox/qtox/5670#-LfQj6hg2luh2uqoyqGX:-Lg1Ee_R6e72OmkEJMKW:b-jauiwn) ([raw file](https://github.com/qtox/qtox/blob/667afd7fde603a777edb90bc7f2c244efa710f21/src/model/dialogs/idialogs.h#L33)):*
<details><summary><i>Previously, sudden6 wrote…</i></summary><blockquote>

I just don't see a reason why we would invent a common base class `ContactId` and then never use it. AFAICT both methods should do the same, just the type is different, so why not eliminate the difference?
</blockquote></details>

Remove two methods, with two different logics. Instead create one method, which accepts parent class and checks subclass and does the same two different logics? Is it correct? If so, don't you think this is strange?
I think until we can't implement common logic for all `Contact` subclasses, there is no reason to merge these methods. I will be absolutely in favor when we can


<!-- Sent from Reviewable.io -->

2019-06-19 06:38 UTC, Diadlo commented
@sudden6 ping

2019-06-19 09:22 UTC, sudden6 approved these changes
> Reviewed 7 of 14 files at r1, 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/qtox/qtox/5670)* status: 0 of 1 LGTMs obtained

___
*[src/model/dialogs/idialogs.h, line 33 at r1](https://reviewable.io/reviews/qtox/qtox/5670#-LfQj6hg2luh2uqoyqGX:-Lhj1aHZBfksEkPkMIrd:by08ztt) ([raw file](https://github.com/qtox/qtox/blob/667afd7fde603a777edb90bc7f2c244efa710f21/src/model/dialogs/idialogs.h#L33)):*
<details><summary><i>Previously, Diadlo (Polshakov Dmitry) wrote…</i></summary><blockquote>

Remove two methods, with two different logics. Instead create one method, which accepts parent class and checks subclass and does the same two different logics? Is it correct? If so, don't you think this is strange?
I think until we can't implement common logic for all `Contact` subclasses, there is no reason to merge these methods. I will be absolutely in favor when we can
</blockquote></details>

ok, if you are sure this is the better way I won't object


<!-- Sent from Reviewable.io -->

2019-06-19 09:22 UTC, sudden6 approved these changes
<img class="emoji" title=":lgtm_strong:" alt=":lgtm_strong:" align="absmiddle" src="https://reviewable.io/lgtm_strong.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/qtox/qtox/5670#-:-Lhj1loU1ulWSaHJCjde:b-jbsf8z)* status: :shipit: complete! 1 of 1 LGTMs obtained



<!-- Sent from Reviewable.io -->

2019-06-19 10:15 UTC, merged