refactor(audio): Remove Audio singleton
qTox/qTox pull request #5671
Opened 2019-05-18 17:12 UTC by sudden6

This commit finally removes the Audio singleton and allocates the audio
backend in main.cpp.

- [ ] Commits follow our [git commit guidelines](https://github.com/qTox/qTox/blob/master/CONTRIBUTING.md#git-commit-guidelin

2019-05-18 21:51 UTC, sudden6 commented
I don't know why GCC on Travis chokes on this line: https://github.com/qTox/qTox/pull/5671/commits/80391e722a68378f129c05d59f55100517e0aa1f#diff-3a5539a58bb648d719803eb1ecd38ffaL34

My local GCC8 does not, please help.

2019-05-19 04:17 UTC, Diadlo commented
@sudden6 Try to use assignment in the constructor body, but not init-list

2019-05-19 04:31 UTC, Diadlo commented
@sudden6 It's GCC [bug](https://gcc.gnu.org/bugzilla/show_bug.cgi?id=50025)
As a current workaround, you can use the pointer with "TODO: Use reference".

2019-05-19 06:18 UTC, Diadlo requested changes
> Reviewed 22 of 22 files at r1.
> *[Reviewable](https://reviewable.io/reviews/qtox/qtox/5671)* status: 0 of 1 LGTMs obtained

___
*[src/main.cpp, line 362 at r1](https://reviewable.io/reviews/qtox/qtox/5671#-LfDh-RW9eDiPFku87ee:-LfDh-RW9eDiPFku87ef:b4b8upf) ([raw file](https://github.com/qtox/qtox/blob/80391e722a68378f129c05d59f55100517e0aa1f/src/main.cpp#L362)):*
> ```cpp
>     Nexus& nexus = Nexus::getInstance();
>     // TODO(sudden6): remove once we get rid of Nexus
>     nexus.audio = audio.get();
> ```

Very dirty hack :/
Maybe at least pass `audio` in `nexts.start()`? It will block starting without audio init
Or if you plan to fix it in the nearest future, leaf as is.
___
*[src/audio/audio.cpp, line 34 at r1](https://reviewable.io/reviews/qtox/qtox/5671#-LfDhohGB4DFzdhKiDZ_:-LfDhohGB4DFzdhKiDZa:b-70xnix) ([raw file](https://github.com/qtox/qtox/blob/80391e722a68378f129c05d59f55100517e0aa1f/src/audio/audio.cpp#L34)):*
> ```cpp
>  * @return Audio backend selection based on settings
>  */
> std::unique_ptr<IAudioControl> Audio::makeAudio(IAudioSettings& settings)
> ```

Do we require restart qtox to reinit audio?
___
*[src/audio/iaudiocontrol.h, line 123 at r1](https://reviewable.io/reviews/qtox/qtox/5671#-LfDjJ6z5Px0Dq8ZpRD7:-LfDjJ6z5Px0Dq8ZpRD8:bnvoiih) ([raw file](https://github.com/qtox/qtox/blob/80391e722a68378f129c05d59f55100517e0aa1f/src/audio/iaudiocontrol.h#L123)):*
> ```objc
>     // Public default audio settings
>     // Samplerate for Tox calls and sounds
>     static constexpr uint32_t AUDIO_SAMPLE_RATE = 48000;
> ```

src/audio/backend/openal2.cpp:162 uses `AUDIO_SAMPLE_RATE` because `Audio` was parent of `OpenAL2`. Now it's moved into `IAudioControl`, so `OpenAL2` should be fixed


<!-- Sent from Reviewable.io -->

2019-05-21 19:40 UTC, sudden6 reviewed
> *[Reviewable](https://reviewable.io/reviews/qtox/qtox/5671)* status: 0 of 1 LGTMs obtained

___
*[src/main.cpp, line 362 at r1](https://reviewable.io/reviews/qtox/qtox/5671#-LfDh-RW9eDiPFku87ee:-LfQtsiV0MDJa060H1vv:b-a9g3zf) ([raw file](https://github.com/qtox/qtox/blob/80391e722a68378f129c05d59f55100517e0aa1f/src/main.cpp#L362)):*
<details><summary><i>Previously, Diadlo (Polshakov Dmitry) wrote…</i></summary><blockquote>

Very dirty hack :/
Maybe at least pass `audio` in `nexts.start()`? It will block starting without audio init
Or if you plan to fix it in the nearest future, leaf as is.
</blockquote></details>

My first thought was also to pass it via `nexus.start()` but it is needed in some other code path too
___
*[src/audio/audio.cpp, line 34 at r1](https://reviewable.io/reviews/qtox/qtox/5671#-LfDhohGB4DFzdhKiDZ_:-LfQu3li6NMaM1zhVeNw:b-kctq26) ([raw file](https://github.com/qtox/qtox/blob/80391e722a68378f129c05d59f55100517e0aa1f/src/audio/audio.cpp#L34)):*
<details><summary><i>Previously, Diadlo (Polshakov Dmitry) wrote…</i></summary><blockquote>

Do we require restart qtox to reinit audio?
</blockquote></details>

yes, switching the audio backend during runtime is not possible with the current setup either
___
*[src/audio/iaudiocontrol.h, line 123 at r1](https://reviewable.io/reviews/qtox/qtox/5671#-LfDjJ6z5Px0Dq8ZpRD7:-LfQuA6bEITjqistJ_xn:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/80391e722a68378f129c05d59f55100517e0aa1f/src/audio/iaudiocontrol.h#L123)):*
<details><summary><i>Previously, Diadlo (Polshakov Dmitry) wrote…</i></summary><blockquote>

src/audio/backend/openal2.cpp:162 uses `AUDIO_SAMPLE_RATE` because `Audio` was parent of `OpenAL2`. Now it's moved into `IAudioControl`, so `OpenAL2` should be fixed
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2019-05-21 19:41 UTC, sudden6 commented
@sphaerophoria thanks, changing `audio{audio}` to `audio(audio)` did the trick to fix the build.

2019-05-22 05:03 UTC, Diadlo requested changes
> Reviewed 7 of 7 files at r2.
> *[Reviewable](https://reviewable.io/reviews/qtox/qtox/5671)* status: 0 of 1 LGTMs obtained

___
*[src/widget/widget.cpp, line 445 at r2](https://reviewable.io/reviews/qtox/qtox/5671#-LfSuI6h7u8VcQ1IkwzM:-LfSuI6h7u8VcQ1IkwzN:b1wbcyk) ([raw file](https://github.com/qtox/qtox/blob/22362d29400a3bc1684d227e355feb52fd28c9de/src/widget/widget.cpp#L445)):*
> ```cpp
>     }
> 
>     const QString assetSuffix =
> ```

Seems like here is different logic now.
Befoew:
```
eventIcon == true: assertSuffix = "event"
eventIcon == false: assertSuffix = getAssetSuffix(status)
```
After:
```
eventIcon == true: assertSuffix = getAssetSuffix(status) + "_event"
eventIcon == false: assertSuffix = getAssetSuffix(status)
```

Is it correct?


<!-- Sent from Reviewable.io -->

2019-05-22 07:37 UTC, sudden6 commented
Yes, this is correct, it's from https://github.com/qTox/qTox/commit/17048c9cc4b3f9ee58924637e57573e285ffa8ee#diff-39d71983c1fc16a6b3191ee87174baaeL444 because I rebased on master.

2019-05-22 08:08 UTC, Diadlo approved these changes
<img class="emoji" title=":lgtm_strong:" alt=":lgtm_strong:" align="absmiddle" src="https://reviewable.io/lgtm_strong.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/qtox/qtox/5671#-:-LfT_TY6CcPZwzzDGWIq:b-jbsf8z)* status: :shipit: complete! 1 of 1 LGTMs obtained



<!-- Sent from Reviewable.io -->

2019-05-22 08:40 UTC, merged