[WIP] edit load history
qTox/qTox pull request #5672
Opened 2019-05-19 21:35 UTC by TriKriSta

- [ ] Commits follow our [git commit guidelines](https://github.com/qTox/qTox/blob/master/CONTRIBUTING.md#git-commit-guidelines)

1. load history at scrolling chat
2. edit function "Load chat history..."

![Screenshot_20190520_003023](https://user-images.githubusercontent.com/2956022/57988422-c9277480-7a96-11e9-9a34-3571397a5659.png)

2019-06-18 21:14 UTC, sudden6 requested changes
> Reviewed 12 of 25 files at r1.
> *[Reviewable](https://reviewable.io/reviews/qtox/qtox/5672)* status: 0 of 1 LGTMs obtained

___
*[src/chatlog/chatlog.cpp, line 371 at r1](https://reviewable.io/reviews/qtox/qtox/5672#-LhgHKUU36f83kAaqnEg:-LhgHKUV7mc4_wxbIKIr:b-u55hvi) ([raw file](https://github.com/qtox/qtox/blob/1ce2a715a1309f5f830e6d088d910476c97a2a51/src/chatlog/chatlog.cpp#L371)):*
> ```cpp
>     bool stickToBtm = stickToBottom();
> 
>     if (canRemove) {
> ```

use `&&` instead of nested if?
___
*[src/chatlog/chatlog.cpp, line 395 at r1](https://reviewable.io/reviews/qtox/qtox/5672#-LhgHNyo0tJ4UtCD4ucX:-LhgHNyo0tJ4UtCD4ucY:b-skfgnv) ([raw file](https://github.com/qtox/qtox/blob/1ce2a715a1309f5f830e6d088d910476c97a2a51/src/chatlog/chatlog.cpp#L395)):*
> ```cpp
> void ChatLog::insertChatlineAtBottom(const QList<ChatLine::Ptr>& newLines)
> {
>     if (newLines.isEmpty())
> ```

braces
___
*[src/chatlog/chatlog.cpp, line 403 at r1](https://reviewable.io/reviews/qtox/qtox/5672#-LhgI1mc4y4rdCV9oMy_:-LhgI1mc4y4rdCV9oMya:b-u55hvi) ([raw file](https://github.com/qtox/qtox/blob/1ce2a715a1309f5f830e6d088d910476c97a2a51/src/chatlog/chatlog.cpp#L403)):*
> ```cpp
>     const int excessSize = (free >= 0) ? 0 : (-1)*free;
> 
>     if (canRemove) {
> ```

use `&&` instead of nested if?
___
*[src/chatlog/chatlog.cpp, line 418 at r1](https://reviewable.io/reviews/qtox/qtox/5672#-LhgKOXK7mtORXVHu0LL:-LhgKOXK7mtORXVHu0LM:b-p4ph7i) ([raw file](https://github.com/qtox/qtox/blob/1ce2a715a1309f5f830e6d088d910476c97a2a51/src/chatlog/chatlog.cpp#L418)):*
> ```cpp
>     layout(lines.last()->getRow(), lines.size(), useableWidth());
> 
>     if (!visibleLines.isEmpty()) {
> ```

don't invert this condition and swap branches
___
*[src/chatlog/chatlog.cpp, line 458 at r1](https://reviewable.io/reviews/qtox/qtox/5672#-LhgKWuSCUTDxEzlleC8:-LhgKWuT-yfQYBwbpzkW:b-u55hvi) ([raw file](https://github.com/qtox/qtox/blob/1ce2a715a1309f5f830e6d088d910476c97a2a51/src/chatlog/chatlog.cpp#L458)):*
> ```cpp
>         l->setRow(i++);
>         combLines.push_back(l);
>         if (canRemove) {
> ```

use `&&` instead of nested if?
___
*[src/chatlog/chatlog.cpp, line 713 at r1](https://reviewable.io/reviews/qtox/qtox/5672#-LhgKfibBTAeRY0fMB-x:-LhgKficCWzKnf4ItTVa:b-9pk5od) ([raw file](https://github.com/qtox/qtox/blob/1ce2a715a1309f5f830e6d088d910476c97a2a51/src/chatlog/chatlog.cpp#L713)):*
> ```cpp
> void ChatLog::removeLowerDateLineIfNeed(const QDate &date)
> {
>     if (!lines.isEmpty()) {
> ```

use return on `if (lines.isEmpty())` to avoid deep nesting?
___
*[src/chatlog/chatlog.cpp, line 729 at r1](https://reviewable.io/reviews/qtox/qtox/5672#-LhgL84vE_t7KZ0wZvm2:-LhgL84vE_t7KZ0wZvm3:b-skfgnv) ([raw file](https://github.com/qtox/qtox/blob/1ce2a715a1309f5f830e6d088d910476c97a2a51/src/chatlog/chatlog.cpp#L729)):*
> ```cpp
> int64_t ChatLog::lowerId() const
> {
>     if (lines.empty())
> ```

braces
___
*[src/chatlog/chatlog.cpp, line 730 at r1](https://reviewable.io/reviews/qtox/qtox/5672#-LhgLFRq6q7FefsqD2b4:-LhgLFRq6q7FefsqD2b5:bk6zcpg) ([raw file](https://github.com/qtox/qtox/blob/1ce2a715a1309f5f830e6d088d910476c97a2a51/src/chatlog/chatlog.cpp#L730)):*
> ```cpp
> {
>     if (lines.empty())
>         return -1;
> ```

Please define a constant for the not set id instead of using `-1` everywhere
___
*[src/chatlog/chatlog.cpp, line 744 at r1](https://reviewable.io/reviews/qtox/qtox/5672#-LhgLNWRB03i0h-uxRNH:-LhgLNWS9LRWBTaBxz1L:b-skfgnv) ([raw file](https://github.com/qtox/qtox/blob/1ce2a715a1309f5f830e6d088d910476c97a2a51/src/chatlog/chatlog.cpp#L744)):*
> ```cpp
> int64_t ChatLog::upperId() const
> {
>     if (lines.empty())
> ```

braces
___
*[src/chatlog/chatlog.cpp, line 759 at r1](https://reviewable.io/reviews/qtox/qtox/5672#-LhgLWR9-IGbO1QsE4hs:-LhgLWR9-IGbO1QsE4ht:b-skfgnv) ([raw file](https://github.com/qtox/qtox/blob/1ce2a715a1309f5f830e6d088d910476c97a2a51/src/chatlog/chatlog.cpp#L759)):*
> ```cpp
> QDateTime ChatLog::getFirstTime() const
> {
>     if (lines.empty())
> ```

braces
___
*[src/chatlog/chatlog.cpp, line 774 at r1](https://reviewable.io/reviews/qtox/qtox/5672#-LhgLaO06YVj2QO4U9tR:-LhgLaO06YVj2QO4U9tS:bcc80p7) ([raw file](https://github.com/qtox/qtox/blob/1ce2a715a1309f5f830e6d088d910476c97a2a51/src/chatlog/chatlog.cpp#L774)):*
> ```cpp
> QDateTime ChatLog::getLatestTime() const
> {
>     if (!lines.isEmpty()) {
> ```

use early return
___
*[src/widget/form/chatform.cpp, line 304 at r1](https://reviewable.io/reviews/qtox/qtox/5672#-LhgObzgDyFs9pAYRltD:-LhgObzgDyFs9pAYRltE:bon79dy) ([raw file](https://github.com/qtox/qtox/blob/1ce2a715a1309f5f830e6d088d910476c97a2a51/src/widget/form/chatform.cpp#L304)):*
> ```cpp
> 
>     insertChatMessage(
>         ChatMessage::createFileTransferMessage(name, file, true, -1, QDateTime::currentDateTime()));
> ```

As said above, replace this "magic value" by a named constant
___
*[src/widget/form/chatform.cpp, line 349 at r1](https://reviewable.io/reviews/qtox/qtox/5672#-LhgOgukCTDqeVwyiXHm:-LhgOgukCTDqeVwyiXHn:bb7od0r) ([raw file](https://github.com/qtox/qtox/blob/1ce2a715a1309f5f830e6d088d910476c97a2a51/src/widget/form/chatform.cpp#L349)):*
> ```cpp
> 
>     ChatMessage::Ptr msg =
>         ChatMessage::createFileTransferMessage(name, file, false, -1, QDateTime::currentDateTime());
> ```

same
___
*[src/widget/form/chatform.cpp, line 605 at r1](https://reviewable.io/reviews/qtox/qtox/5672#-LhgP0qT6q1WnI9Cq6fL:-LhgP0qT6q1WnI9Cq6fM:bljsygd) ([raw file](https://github.com/qtox/qtox/blob/1ce2a715a1309f5f830e6d088d910476c97a2a51/src/widget/form/chatform.cpp#L605)):*
> ```cpp
>     const bool isSearch = searchInText(phrase, parameter, SearchDirection::Down);
> 
>     if (!isSearch) {
> ```

early return?
___
*[src/widget/form/chatform.cpp, line 786 at r1](https://reviewable.io/reviews/qtox/qtox/5672#-LhgPHhC8GPRAH8aT6Hv:-LhgPHhC8GPRAH8aT6Hw:b-m7ukfi) ([raw file](https://github.com/qtox/qtox/blob/1ce2a715a1309f5f830e6d088d910476c97a2a51/src/widget/form/chatform.cpp#L786)):*
> ```cpp
>     QString pk = f->getPublicKey().toString();
>     QList<History::HistMessage> msgs = history->getChatHistoryLower(pk, getFirstTime());
>     if (!msgs.isEmpty()) {
> ```

early return
___
*[src/widget/form/chatform.cpp, line 787 at r1](https://reviewable.io/reviews/qtox/qtox/5672#-LhgQuEX-J9bqOmJ-6n1:-LhgQuEX-J9bqOmJ-6n2:b-ua7kyv) ([raw file](https://github.com/qtox/qtox/blob/1ce2a715a1309f5f830e6d088d910476c97a2a51/src/widget/form/chatform.cpp#L787)):*
> ```cpp
>     QList<History::HistMessage> msgs = history->getChatHistoryLower(pk, getFirstTime());
>     if (!msgs.isEmpty()) {
>         msgs = deleteDuplicate(msgs, true);
> ```

Wouldn't it be possible to load only the correct range of messages instead of deleting duplicates afterwards?
___
*[src/widget/form/chatform.cpp, line 798 at r1](https://reviewable.io/reviews/qtox/qtox/5672#-LhgPJwqDJsJfK28QEgF:-LhgPJwr5lD2h_jAtCIB:b-m7ukfi) ([raw file](https://github.com/qtox/qtox/blob/1ce2a715a1309f5f830e6d088d910476c97a2a51/src/widget/form/chatform.cpp#L798)):*
> ```cpp
>     QString pk = f->getPublicKey().toString();
>     QList<History::HistMessage> msgs = history->getChatHistoryUpper(pk, getLatestTime());
>     if (!msgs.isEmpty()) {
> ```

early return
___
*[src/widget/form/chatform.cpp, line 849 at r1](https://reviewable.io/reviews/qtox/qtox/5672#-LhgPPeSCJxBY88XnEQA:-LhgPPeSCJxBY88XnEQB:b-m7ukfi) ([raw file](https://github.com/qtox/qtox/blob/1ce2a715a1309f5f830e6d088d910476c97a2a51/src/widget/form/chatform.cpp#L849)):*
> ```cpp
>     }
> 
>     if (!msgs.isEmpty()) {
> ```

early return
___
*[src/widget/form/loadhistorydialog.cpp, line 73 at r1](https://reviewable.io/reviews/qtox/qtox/5672#-LhgQXF17edA1QjMvYF1:-LhgQXF17edA1QjMvYF2:b-brv5i6) ([raw file](https://github.com/qtox/qtox/blob/1ce2a715a1309f5f830e6d088d910476c97a2a51/src/widget/form/loadhistorydialog.cpp#L73)):*
> ```cpp
> }
> 
> void LoadHistoryDialog::turnSearchMode()
> ```

Why not execute this in the constructor?


<!-- Sent from Revi [...]

2019-06-19 16:48 UTC, TriKriSta reviewed
> *[Reviewable](https://reviewable.io/reviews/qtox/qtox/5672)* status: 0 of 1 LGTMs obtained

___
*[src/chatlog/chatlog.cpp, line 371 at r1](https://reviewable.io/reviews/qtox/qtox/5672#-LhgHKUU36f83kAaqnEg:-LhkbWYIDtkcTn_xQrg4:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/1ce2a715a1309f5f830e6d088d910476c97a2a51/src/chatlog/chatlog.cpp#L371)):*
<details><summary><i>Previously, sudden6 wrote…</i></summary><blockquote>

use `&&` instead of nested if?
</blockquote></details>

Done.
___
*[src/chatlog/chatlog.cpp, line 395 at r1](https://reviewable.io/reviews/qtox/qtox/5672#-LhgHNyo0tJ4UtCD4ucX:-LhkbXuT2f3f3YW5dg4b:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/1ce2a715a1309f5f830e6d088d910476c97a2a51/src/chatlog/chatlog.cpp#L395)):*
<details><summary><i>Previously, sudden6 wrote…</i></summary><blockquote>

braces
</blockquote></details>

Done.
___
*[src/chatlog/chatlog.cpp, line 403 at r1](https://reviewable.io/reviews/qtox/qtox/5672#-LhgI1mc4y4rdCV9oMy_:-LhkbfmT8hLdVS8wBBq1:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/1ce2a715a1309f5f830e6d088d910476c97a2a51/src/chatlog/chatlog.cpp#L403)):*
<details><summary><i>Previously, sudden6 wrote…</i></summary><blockquote>

use `&&` instead of nested if?
</blockquote></details>

Done.
___
*[src/chatlog/chatlog.cpp, line 418 at r1](https://reviewable.io/reviews/qtox/qtox/5672#-LhgKOXK7mtORXVHu0LL:-LhkbhPa5EjZ0OslhtOe:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/1ce2a715a1309f5f830e6d088d910476c97a2a51/src/chatlog/chatlog.cpp#L418)):*
<details><summary><i>Previously, sudden6 wrote…</i></summary><blockquote>

don't invert this condition and swap branches
</blockquote></details>

Done.
___
*[src/chatlog/chatlog.cpp, line 458 at r1](https://reviewable.io/reviews/qtox/qtox/5672#-LhgKWuSCUTDxEzlleC8:-Lhkbj-j0UJU-yziH2Ix:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/1ce2a715a1309f5f830e6d088d910476c97a2a51/src/chatlog/chatlog.cpp#L458)):*
<details><summary><i>Previously, sudden6 wrote…</i></summary><blockquote>

use `&&` instead of nested if?
</blockquote></details>

Done.
___
*[src/chatlog/chatlog.cpp, line 713 at r1](https://reviewable.io/reviews/qtox/qtox/5672#-LhgKfibBTAeRY0fMB-x:-LhkboY42oh0n7qtjqGQ:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/1ce2a715a1309f5f830e6d088d910476c97a2a51/src/chatlog/chatlog.cpp#L713)):*
<details><summary><i>Previously, sudden6 wrote…</i></summary><blockquote>

use return on `if (lines.isEmpty())` to avoid deep nesting?
</blockquote></details>

Done.
___
*[src/chatlog/chatlog.cpp, line 729 at r1](https://reviewable.io/reviews/qtox/qtox/5672#-LhgL84vE_t7KZ0wZvm2:-LhkbpPJDluIpUil7WYx:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/1ce2a715a1309f5f830e6d088d910476c97a2a51/src/chatlog/chatlog.cpp#L729)):*
<details><summary><i>Previously, sudden6 wrote…</i></summary><blockquote>

braces
</blockquote></details>

Done.
___
*[src/chatlog/chatlog.cpp, line 730 at r1](https://reviewable.io/reviews/qtox/qtox/5672#-LhgLFRq6q7FefsqD2b4:-Lhkbqsr1lKgXBdnrjR3:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/1ce2a715a1309f5f830e6d088d910476c97a2a51/src/chatlog/chatlog.cpp#L730)):*
<details><summary><i>Previously, sudden6 wrote…</i></summary><blockquote>

Please define a constant for the not set id instead of using `-1` everywhere
</blockquote></details>

Done.
___
*[src/chatlog/chatlog.cpp, line 744 at r1](https://reviewable.io/reviews/qtox/qtox/5672#-LhgLNWRB03i0h-uxRNH:-Lhkbrd0AX10Wjmvq9qd:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/1ce2a715a1309f5f830e6d088d910476c97a2a51/src/chatlog/chatlog.cpp#L744)):*
<details><summary><i>Previously, sudden6 wrote…</i></summary><blockquote>

braces
</blockquote></details>

Done.
___
*[src/chatlog/chatlog.cpp, line 759 at r1](https://reviewable.io/reviews/qtox/qtox/5672#-LhgLWR9-IGbO1QsE4hs:-LhkbsCwA-Ti4vL4eyCT:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/1ce2a715a1309f5f830e6d088d910476c97a2a51/src/chatlog/chatlog.cpp#L759)):*
<details><summary><i>Previously, sudden6 wrote…</i></summary><blockquote>

braces
</blockquote></details>

Done.
___
*[src/chatlog/chatlog.cpp, line 774 at r1](https://reviewable.io/reviews/qtox/qtox/5672#-LhgLaO06YVj2QO4U9tR:-Lhkbtvg7sm1SkQrTzx_:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/1ce2a715a1309f5f830e6d088d910476c97a2a51/src/chatlog/chatlog.cpp#L774)):*
<details><summary><i>Previously, sudden6 wrote…</i></summary><blockquote>

use early return
</blockquote></details>

Done.
___
*[src/widget/form/chatform.cpp, line 304 at r1](https://reviewable.io/reviews/qtox/qtox/5672#-LhgObzgDyFs9pAYRltD:-Lhkbx9hB3IRLKnCKJK9:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/1ce2a715a1309f5f830e6d088d910476c97a2a51/src/widget/form/chatform.cpp#L304)):*
<details><summary><i>Previously, sudden6 wrote…</i></summary><blockquote>

As said above, replace this "magic value" by a named constant
</blockquote></details>

Done.
___
*[src/widget/form/chatform.cpp, line 349 at r1](https://reviewable.io/reviews/qtox/qtox/5672#-LhgOgukCTDqeVwyiXHm:-LhkbxV979tYuNFVvvtk:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/1ce2a715a1309f5f830e6d088d910476c97a2a51/src/widget/form/chatform.cpp#L349)):*
<details><summary><i>Previously, sudden6 wrote…</i></summary><blockquote>

same
</blockquote></details>

Done.
___
*[src/widget/form/chatform.cpp, line 605 at r1](https://reviewable.io/reviews/qtox/qtox/5672#-LhgP0qT6q1WnI9Cq6fL:-Lhkby6a9wDOiwJiFaVl:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/1ce2a715a1309f5f830e6d088d910476c97a2a51/src/widget/form/chatform.cpp#L605)):*
<details><summary><i>Previously, sudden6 wrote…</i></summary><blockquote>

early return?
</blockquote></details>

Done.
___
*[src/widget/form/chatform.cpp, line 786 at r1](https://reviewable.io/reviews/qtox/qtox/5672#-LhgPHhC8GPRAH8aT6Hv:-LhkbyYf0OKMACgvvLu7:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/1ce2a715a1309f5f830e6d088d910476c97a2a51/src/widget/form/chatform.cpp#L786)):*
<details><summary><i>Previously, sudden6 wrote…</i></summary><blockquote>

early return
</blockquote></details>

Done.
___
*[src/widget/form/chatform.cpp, line 787 at r1](https://reviewable.io/reviews/qtox/qtox/5672#-LhgQuEX-J9bqOmJ-6n1:-Lhkc1lKDPFKIHWsJSt8:bkh3d2o) ([raw file](https://github.com/qtox/qtox/blob/1ce2a715a1309f5f830e6d088d910476c97a2a51/src/widget/form/chatform.cpp#L787)):*
> Wouldn't it be possible to load only the correct range of messages instead of deleting duplicates afterwards?
We can, but this is harder, We must add parameter "id" in  requests for db
___
*[src/widget/form/chatform.cpp, line 798 at r1](https://reviewable.io/reviews/qtox/qtox/5672#-LhgPJwqDJsJfK28QEgF:-Lhkbz-f7TF6pqqtaTR6:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/1ce2a715a1309f5f830e6d088d910476c97a2a51/src/widget/form/chatform.cpp#L798)):*
<details><summary><i>Previously, sudden6 wrote…</i></summary><blockquote>

early return
</blockquote></details>

Done.
___
*[src/widget/form/chatform.cpp, line 849 at r1](https://reviewable.io/reviews/qtox/qtox/5672#-LhgPPeSCJxBY88XnEQA:-Lhkbzc-2XPZLcgbPcyK:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/1ce2a715a1309f5f830e6d088d910476c97a2a51/src/widget/form/chatform.cpp#L849)):*
<details><summary><i>Previously, sudden6 wrote…</i></summary><blockquote>

early return
</blockquote></details>

Done.
___
*[src/widget/form/loadhistorydialog.cpp, line 73 at r1](https://reviewable.io/reviews/qtox/qtox/5672#-LhgQXF17edA1QjMvYF1:-LhkcsgKCpLA1dPwyPUs:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/1ce2a715a1309f5f830e6d088d910476c97a2a51/src/widget/form/loadhistorydialog.cpp#L73)):*
<details><summary><i>Previously, sudden6 wrote…</i></summary><blockquote>

Why not execute this in the constructor?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2019-06-20 12:29 UTC, sudden6 requested changes
> Reviewed 6 of 25 files at r1, 6 of 7 files at r2.
> *[Reviewable](https://reviewable.io/reviews/qtox/qtox/5672)* status: 0 of 1 LGTMs obtained

___
*[src/chatlog/chatlog.cpp, line 730 at r1](https://reviewable.io/reviews/qtox/qtox/5672#-LhgLFRq6q7FefsqD2b4:-LhomUM30Qny-hRx7bD9:bs8j6dz) ([raw file](https://github.com/qtox/qtox/blob/1ce2a715a1309f5f830e6d088d910476c97a2a51/src/chatlog/chatlog.cpp#L730)):*
<details><summary><i>Previously, TriKriSta wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Please choose a better name for the constant, e.g. `EMPTY_LINE_ID`, `DEF_LINE_ID` doesn't really describe the purpose of the constant.
___
*[src/chatlog/chatlog.cpp, line 737 at r2](https://reviewable.io/reviews/qtox/qtox/5672#-LhomnKB6_0wh3udDh9m:-LhomnKB6_0wh3udDh9n:b-mlx63d) ([raw file](https://github.com/qtox/qtox/blob/bc1d357983149a1ce5d227014872197d65751659/src/chatlog/chatlog.cpp#L737)):*
> ```cpp
>     for (int i = 0; i < lines.size(); ++i) {
>         auto id = lines.at(i).get()->getId();
>         if (id > -1) {
> ```

wouldn't `id != DEF_LINE_ID` be better here? what if the constant is changed to some other value?
___
*[src/persistence/history.cpp, line 761 at r2](https://reviewable.io/reviews/qtox/qtox/5672#-LhonROe1r0ob65moGBD:-LhonROe1r0ob65moGBE:bpn0k2z) ([raw file](https://github.com/qtox/qtox/blob/bc1d357983149a1ce5d227014872197d65751659/src/persistence/history.cpp#L761)):*
> ```cpp
>  * @param to End of period to fetch.
>  * @param numMessages max number of messages to fetch.
>  * @param useDesk if true use last messages else begin
> ```

did you intend to name this `useDesc` for "Descending" here?
___
*[src/widget/form/chatform.cpp, line 787 at r1](https://reviewable.io/reviews/qtox/qtox/5672#-LhgQuEX-J9bqOmJ-6n1:-LhoquU155HH8JTmov8l:b2vqirl) ([raw file](https://github.com/qtox/qtox/blob/1ce2a715a1309f5f830e6d088d910476c97a2a51/src/widget/form/chatform.cpp#L787)):*
<details><summary><i>Previously, TriKriSta wrote…</i></summary><blockquote>

> Wouldn't it be possible to load only the correct range of messages instead of deleting duplicates afterwards?
We can, but this is harder, We must add parameter "id" in  requests for db
</blockquote></details>

I think it should be possible to write a SQL query for the db where we pass the first or last message currently displayed and it will return the next e.g. 100 messages, what do you think?
___
*[src/widget/form/chatform.cpp, line 854 at r2](https://reviewable.io/reviews/qtox/qtox/5672#-LhooKd14YuEBIg0Eq5j:-LhooKd14YuEBIg0Eq5k:b7uu56y) ([raw file](https://github.com/qtox/qtox/blob/bc1d357983149a1ce5d227014872197d65751659/src/widget/form/chatform.cpp#L854)):*
> ```cpp
> 
>     QList<History::HistMessage> msgs;
>     bool onTop;
> ```

Maybe rewrite to `bool onTop =  loadType == LoadHistoryDialog::from` and then use the variable in the `if`? Seems cleaner too me
___
*[src/widget/form/chatform.cpp, line 1271 at r2](https://reviewable.io/reviews/qtox/qtox/5672#-Lhop8PTD62zhobMEhe-:-Lhop8PTD62zhobMEhe0:b6u6pkr) ([raw file](https://github.com/qtox/qtox/blob/bc1d357983149a1ce5d227014872197d65751659/src/widget/form/chatform.cpp#L1271)):*
> ```cpp
>     bool isDel = true;
>     while (isDel) {
>         bool b = onTop ? histMessage.last().id.get() >= id : histMessage.first().id.get() <= id;
> ```

`b` isn't really a descriptive variable name, what does it do?
___
*[src/widget/form/loadhistorydialog.cpp, line 73 at r1](https://reviewable.io/reviews/qtox/qtox/5672#-LhgQXF17edA1QjMvYF1:-LhopgBM8iQHg07659FE:b-adfmja) ([raw file](https://github.com/qtox/qtox/blob/1ce2a715a1309f5f830e6d088d910476c97a2a51/src/widget/form/loadhistorydialog.cpp#L73)):*
<details><summary><i>Previously, TriKriSta wrote…</i></summary><blockquote>

Done.
</blockquote></details>

The name of the method doesn't really make sense in English, do you mean 'enableSearchMode'?


<!-- Sent from Reviewable.io -->

2019-06-20 13:30 UTC, sudden6 commented
@TriKriSta you might put your work on hold until #5703 is merged. It changes many internal things and might even make it easier to add the features from this PR.

2019-06-20 13:59 UTC, TriKriSta commented
> @TriKriSta you might put your work on hold until #5703 is merged. It changes many internal things and might even make it easier to add the features from this PR.

@sudden6 ok. Do I need to merge the master branch in this PR after?

2019-06-20 14:59 UTC, sudden6 commented
A rebase is probably the cleaner option, but lets wait until the relevant parts are in master.

2019-06-21 19:13 UTC, sudden6 commented
@TriKriSta the other PR is merged

2019-06-27 19:38 UTC, TriKriSta reviewed
> *[Reviewable](https://reviewable.io/reviews/qtox/qtox/5672)* status: 0 of 1 LGTMs obtained

___
*[src/chatlog/chatlog.cpp, line 737 at r2](https://reviewable.io/reviews/qtox/qtox/5672#-LhomnKB6_0wh3udDh9m:-LiPR6fV1lpjUiJGSbua:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/bc1d357983149a1ce5d227014872197d65751659/src/chatlog/chatlog.cpp#L737)):*
<details><summary><i>Previously, sudden6 wrote…</i></summary><blockquote>

wouldn't `id != DEF_LINE_ID` be better here? what if the constant is changed to some other value?
</blockquote></details>

Done.
___
*[src/persistence/history.cpp, line 761 at r2](https://reviewable.io/reviews/qtox/qtox/5672#-LhonROe1r0ob65moGBD:-LiPRFNS0EqsHWA9GDUi:b-am2za9) ([raw file](https://github.com/qtox/qtox/blob/bc1d357983149a1ce5d227014872197d65751659/src/persistence/history.cpp#L761)):*
<details><summary><i>Previously, sudden6 wrote…</i></summary><blockquote>

did you intend to name this `useDesc` for "Descending" here?
</blockquote></details>

yes, but it doesn't use now
___
*[src/widget/form/chatform.cpp, line 787 at r1](https://reviewable.io/reviews/qtox/qtox/5672#-LhgQuEX-J9bqOmJ-6n1:-LiPQqSQ4bxFAyNnl2EA:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/1ce2a715a1309f5f830e6d088d910476c97a2a51/src/widget/form/chatform.cpp#L787)):*
<details><summary><i>Previously, sudden6 wrote…</i></summary><blockquote>

I think it should be possible to write a SQL query for the db where we pass the first or last message currently displayed and it will return the next e.g. 100 messages, what do you think?
</blockquote></details>

Done.
___
*[src/widget/form/chatform.cpp, line 854 at r2](https://reviewable.io/reviews/qtox/qtox/5672#-LhooKd14YuEBIg0Eq5j:-LiPQs5CAoKKK5Du1G0t:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/bc1d357983149a1ce5d227014872197d65751659/src/widget/form/chatform.cpp#L854)):*
<details><summary><i>Previously, sudden6 wrote…</i></summary><blockquote>

Maybe rewrite to `bool onTop =  loadType == LoadHistoryDialog::from` and then use the variable in the `if`? Seems cleaner too me
</blockquote></details>

Done.
___
*[src/widget/form/chatform.cpp, line 1271 at r2](https://reviewable.io/reviews/qtox/qtox/5672#-Lhop8PTD62zhobMEhe-:-LiPQt83B-zPtkaDGoqu:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/bc1d357983149a1ce5d227014872197d65751659/src/widget/form/chatform.cpp#L1271)):*
<details><summary><i>Previously, sudden6 wrote…</i></summary><blockquote>

`b` isn't really a descriptive variable name, what does it do?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2019-06-27 22:07 UTC, sudden6 commented
This PR causes a crash for me:

```
1   raise                                                                                                                                                                                                                                                                                                      0x7fffeed06120 
2   abort                                                                                                                                                                                                                                                                                                      0x7fffeed07701 
3   ??                                                                                                                                                                                                                                                                                                         0x7fffef898f0f 
4   ??                                                                                                                                                                                                                                                                                                         0x7fffef8a48f8 
5   std::terminate()                                                                                                                                                                                                                                                                                           0x7fffef8a4943 
6   SessionChatLog::at                                                                                                                                                                                                                                                                sessionchatlog.cpp  124  0x7c958c       
7   ChatHistory::at                                                                                                                                                                                                                                                                   chathistory.cpp     132  0x7d4997       
8   GenericChatForm::needsToHideName                                                                                                                                                                                                                                                  genericchatform.cpp 548  0x8498b1       
9   GenericChatForm::renderMessages(NamedType<unsigned long, ChatLogIdxTag, Orderable, UnderlyingAddable, UnitlessDifferencable, Incrementable>, NamedType<unsigned long, ChatLogIdxTag, Orderable, UnderlyingAddable, UnitlessDifferencable, Incrementable>, std::function<void ()>) genericchatform.cpp 1032 0x84c3e2       
10  GenericChatForm::loadHistoryFrom                                                                                                                                                                                                                                                  genericchatform.cpp 703  0x84a650       
11  GenericChatForm::loadHistoryUpper                                                                                                                                                                                                                                                 genericchatform.cpp 1088 0x84ca98       
12  QtPrivate::FunctorCall<QtPrivate::IndexesList<>, QtPrivate::List<>, void, void (GenericChatForm:: *)()>::call(void (GenericChatForm:: *)(), GenericChatForm *, void * *)                                                                                                          qobjectdefs_impl.h  136  0x71e7ba       
13  QtPrivate::FunctionPointer<void (GenericChatForm:: *)()>::call<QtPrivate::List<>, void>(void (GenericChatForm:: *)(), GenericChatForm *, void * *)                                                                                                                                qobjectdefs_impl.h  169  0x71b091       
14  QtPrivate::QSlotObject<void (GenericChatForm:: *)(), QtPrivate::List<>, void>::impl(int, QtPrivate::QSlotObjectBase *, QObject *, void * *, bool *)                                                                                                                               qobject_impl.h      120  0x7159ff       
15  QMetaObject::activate(QObject *, int, int, void * *)                                                                                                                                                                                                                                                       0x7fffefe8915c 
16  ChatLog::loadHistoryUpper                                                                                                                                                                                                                                                         moc_chatlog.cpp     220  0x729de0       
17  ChatLog::checkVisibility                                                                                                                                                                                                                                                          chatlog.cpp         768  0x76aff7       
18  ChatLog::wheelEvent                                                                                                                                                                                                                                                               chatlog.cpp         976  0x76bef7       
19  QWidget::event(QEvent *)                                                                                                                                                                                                                                                                                   0x7ffff0fabcd8 
20  QFrame::event(QEvent *)             
... <Mehr>                                                                                                                                                                                                                                                                                                                    
```

During this crash I sent many messages in rapid succession from another client to this one. After scrolling up and down I got the posted backtrace.

2019-07-14 20:31 UTC, sudden6 requested changes
Tested and besides this bit of debug code left in the PR it <img class="emoji" title=":lgtm_strong:" alt=":lgtm_strong:" align="absmiddle" src="https://reviewable.io/lgtm_strong.png" height="20" width="61"/> 

> Reviewed 13 of 24 files at r3, 8 of 11 files at r4.
> *[Reviewable](https://reviewable.io/reviews/qtox/qtox/5672#-:-LjmAgFH8_Chc03J2hL_:bh0boem)* status: :shipit: complete! 1 of 1 LGTMs obtained

___
*[src/chatlog/chatlog.cpp, line 807 at r4](https://reviewable.io/reviews/qtox/qtox/5672#-LjmAG6C7JZeUyl6p-8u:-LjmAG6E16kW3W63ceKB:bav8yst) ([raw file](https://github.com/qtox/qtox/blob/d59608489298dc248d3488c948a1b9cbfcc5eb97/src/chatlog/chatlog.cpp#L807)):*
> ```cpp
> 
>     if (causedWheelEvent) {
>         qDebug() << "causedWheelEvent";
> ```

Was this some debug code or is it intended for master? It seems to cause a lot of log spam
___
*[src/widget/form/genericchatform.cpp, line 696 at r4](https://reviewable.io/reviews/qtox/qtox/5672#-LjmA_zW9UW2a7Ot4ata:-LjmA_zX4nLkc1Z63XkJ:b1r5vyp) ([raw file](https://github.com/qtox/qtox/blob/d59608489298dc248d3488c948a1b9cbfcc5eb97/src/widget/form/genericchatform.cpp#L696)):*
> ```cpp
>     int add = DEF_NUM_MSG_TO_LOAD;
>     if (begin.get() + DEF_NUM_MSG_TO_LOAD > chatLog.getNextIdx().get()) {
>         auto aTest = chatLog.getNextIdx().get();
> ```

also debug code?


<!-- Sent from Reviewable.io -->

2019-07-14 20:50 UTC, TriKriSta reviewed
> *[Reviewable](https://reviewable.io/reviews/qtox/qtox/5672)* status: :shipit: complete! 1 of 1 LGTMs obtained

___
*[src/chatlog/chatlog.cpp, line 807 at r4](https://reviewable.io/reviews/qtox/qtox/5672#-LjmAG6C7JZeUyl6p-8u:-LjmEx5G8msux_l5oiyT:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/d59608489298dc248d3488c948a1b9cbfcc5eb97/src/chatlog/chatlog.cpp#L807)):*
<details><summary><i>Previously, sudden6 wrote…</i></summary><blockquote>

Was this some debug code or is it intended for master? It seems to cause a lot of log spam
</blockquote></details>

Done.
___
*[src/widget/form/genericchatform.cpp, line 696 at r4](https://reviewable.io/reviews/qtox/qtox/5672#-LjmA_zW9UW2a7Ot4ata:-LjmEzvo8wgsQ46WUiiT:bb7s9zc) ([raw file](https://github.com/qtox/qtox/blob/d59608489298dc248d3488c948a1b9cbfcc5eb97/src/widget/form/genericchatform.cpp#L696)):*
<details><summary><i>Previously, sudden6 wrote…</i></summary><blockquote>

also debug code?
</blockquote></details>

yes


<!-- Sent from Reviewable.io -->

2019-07-15 06:46 UTC, sudden6 commented
Will merge once we fix the CI for Mac

2019-07-22 14:50 UTC, sudden6 commented
@TriKriSta please rebase your PR on the lastest master so that TravisCI passes again

2019-07-22 20:35 UTC, TriKriSta commented
@sudden6 I did rebase

2019-07-22 20:50 UTC, merged