feat(build): use delta update for AppImages
qTox/qTox pull request #5690
Opened 2019-05-27 21:52 UTC by antony-jr

This PR implements the delta updater as mentioned in #5643 for qTox AppImages. The delta updater is only used for AppImage builds and does not break the source code for other platforms. This delta updater is integrated along with UpdateCheck class and uses the existing UI for notifying the update available button. Without the CMake build options , the delta updater library is never touched.

2019-05-27 22:50 UTC, nurupo reviewed
> *[Reviewable](https://reviewable.io/reviews/qtox/qtox/5690)* status: 0 of 1 LGTMs obtained

___
*[CMakeLists.txt, line 669 at r1](https://reviewable.io/reviews/qtox/qtox/5690#-LfvQW_D5k97gKX5DAZS:-LfvQW_D5k97gKX5DAZT:bqdxx0i) ([raw file](https://github.com/qtox/qtox/blob/aa564879eb880684a687a5846498b34c2ab4d4a0/CMakeLists.txt#L669)):*
> ```CMake
> 	    message(STATUS "not using AppImageUpdaterBridge")
>     endif()
> ```

Don't use tabs.
___
*[CMakeLists.txt, line 712 at r1](https://reviewable.io/reviews/qtox/qtox/5690#-LfvQl5058jgJV8Qxq4y:-LfvQl5058jgJV8Qxq4z:b-c3q7nz) ([raw file](https://github.com/qtox/qtox/blob/aa564879eb880684a687a5846498b34c2ab4d4a0/CMakeLists.txt#L712)):*
> ```CMake
> 
> if(APPIMAGE_UPDATER_BRIDGE_BUILD_DIR AND APPIMAGE_UPDATER_BRIDGE_SRC_DIR AND UPDATE_CHECK)
> target_link_libraries(${PROJECT_NAME}_static
> ```

Body of the if-statement should be indented.
___
*[CMakeLists.txt, line 717 at r1](https://reviewable.io/reviews/qtox/qtox/5690#-LfvR01C0jLSvFt578WS:-LfvR01C0jLSvFt578WT:b-x1j62x) ([raw file](https://github.com/qtox/qtox/blob/aa564879eb880684a687a5846498b34c2ab4d4a0/CMakeLists.txt#L717)):*
> ```CMake
>   ${APPIMAGE_UPDATER_BRIDGE_BUILD_DIR}/libAppImageUpdaterBridge.a)
> else()
> target_link_libraries(${PROJECT_NAME}_static
> ```

Same -- body of the if-statement should be indented.
___
*[appimage/build.sh, line 44 at r1](https://reviewable.io/reviews/qtox/qtox/5690#-LfvRGDR8jyu9gq6VSgu:-LfvRGDR8jyu9gq6VSgv:bgpu9iz) ([raw file](https://github.com/qtox/qtox/blob/aa564879eb880684a687a5846498b34c2ab4d4a0/appimage/build.sh#L44)):*
> ```Shell
> readonly LDQT_BIN="/usr/lib/x86_64-linux-gnu/qt5/bin/linuxdeployqt"
> # aitool binary
> readonly AITOOL_BIN="/usr/lib/x86_64-linux-gnu/"
> ```

This doesn't point to a binary. Also, I don't see it being used anywhere in this PR's diff.
___
*[appimage/build.sh, line 103 at r1](https://reviewable.io/reviews/qtox/qtox/5690#-LfvOQ5M6xdFiKj7e82F:-LfvOQ5M6xdFiKj7e82G:b-569yn) ([raw file](https://github.com/qtox/qtox/blob/aa564879eb880684a687a5846498b34c2ab4d4a0/appimage/build.sh#L103)):*
> ```Shell
> # build aub into a static library and later use it in 
> # qTox
> git clone "$AUB_GIT" "$AUB_SRC_DIR"
> ```

Did you forget to cd into `$AUB_SRC_DIR`? Otherwise that `cmake ..` below doesn't make much sense to me.
___
*[appimage/build.sh, line 103 at r1](https://reviewable.io/reviews/qtox/qtox/5690#-LfvOg1mB1DX8EyltAxj:-LfvOg1mB1DX8EyltAxk:b-eigs80) ([raw file](https://github.com/qtox/qtox/blob/aa564879eb880684a687a5846498b34c2ab4d4a0/appimage/build.sh#L103)):*
> ```Shell
> # build aub into a static library and later use it in 
> # qTox
> git clone "$AUB_GIT" "$AUB_SRC_DIR"
> ```

Also needs to checkout a specific tag instead of using the default branch.
___
*[appimage/build.sh, line 162 at r1](https://reviewable.io/reviews/qtox/qtox/5690#-LfvOwCs5YCFIPT6shBd:-LfvOwCt0s8IZSjRtig6:b-uwp6o3) ([raw file](https://github.com/qtox/qtox/blob/aa564879eb880684a687a5846498b34c2ab4d4a0/appimage/build.sh#L162)):*
> ```Shell
> export PKG_CONFIG_PATH=/deps/lib/pkgconfig/
> 
> # This is aitool not qTox , do not add qTox build options here
> ```

This comment seems unnecessary.
___
*[appimage/build-appimage.sh, line 60 at r1](https://reviewable.io/reviews/qtox/qtox/5690#-LfvPY-d-a9UZBI1kdd_:-LfvPY-d-a9UZBI1kdda:b3fmzye) ([raw file](https://github.com/qtox/qtox/blob/aa564879eb880684a687a5846498b34c2ab4d4a0/appimage/build-appimage.sh#L60)):*
> ```Shell
> else
>     docker run --rm \
> 	-e TRAVIS_REPO_SLUG \
> ```

I don't see this being used anywhere as far as this PR diff goes. Am I missing something?

Also, don't use tabs.
___
*[src/net/updatecheck.cpp, line 52 at r1](https://reviewable.io/reviews/qtox/qtox/5690#-LfvTmqiCxEXLAhSQkIA:-LfvTmqiCxEXLAhSQkIB:bvimcjc) ([raw file](https://github.com/qtox/qtox/blob/aa564879eb880684a687a5846498b34c2ab4d4a0/src/net/updatecheck.cpp#L52)):*
> ```cpp
>     : settings(settings)
> {
>     updateTimer.start(1000 * 60 * 60 * 24 /* 1 day */); 
> ```

Don't add trailing space.
___
*[src/net/updatecheck.cpp, line 58 at r1](https://reviewable.io/reviews/qtox/qtox/5690#-LfvRvdx-D_7qprjKXyj:-LfvRvdx-D_7qprjKXyk:bz8msbs) ([raw file](https://github.com/qtox/qtox/blob/aa564879eb880684a687a5846498b34c2ab4d4a0/src/net/updatecheck.cpp#L58)):*
> ```cpp
> #else
>     connect(&revisioner , &AppImageDeltaRevisioner::updateAvailable , this , &UpdateCheck::handleUpdate);
>     connect(&revisioner , &AppImageDeltaRevisioner::error , this , &UpdateCheck::updateCheckFailed , Qt::DirectConnection);
> ```

Inconsistent code style with the rest of qTox -- there should be no space before commas.
___
*[src/net/updatecheck.cpp, line 81 at r1](https://reviewable.io/reviews/qtox/qtox/5690#-LfvSMqK05pr_yxYOFen:-LfvSMqK05pr_yxYOFeo:b-ez51hb) ([raw file](https://github.com/qtox/qtox/blob/aa564879eb880684a687a5846498b34c2ab4d4a0/src/net/updatecheck.cpp#L81)):*
> ```cpp
> void UpdateCheck::initUpdate()
> {
>     if(!updateDialog.isNull()){
> ```

Inconsistent code style with the rest of qTox -- there should be a space after `if` and before `{`.
___
*[src/net/updatecheck.cpp, line 83 at r1](https://reviewable.io/reviews/qtox/qtox/5690#-LfvS8A--1xbJyL2DP_E:-LfvS8A--1xbJyL2DP_F:bqdxx0i) ([raw file](https://github.com/qtox/qtox/blob/aa564879eb880684a687a5846498b34c2ab4d4a0/src/net/updatecheck.cpp#L83)):*
> ```cpp
>     if(!updateDialog.isNull()){
> 	    updateDialog->init();
> 	    return;
> ```

Don't use tabs.
___
*[src/net/updatecheck.cpp, line 89 at r1](https://reviewable.io/reviews/qtox/qtox/5690#-LfvS93M85HnU3R8rkl9:-LfvS93M85HnU3R8rklA:bqdxx0i) ([raw file](https://github.com/qtox/qtox/blob/aa564879eb880684a687a5846498b34c2ab4d4a0/src/net/updatecheck.cpp#L89)):*
> ```cpp
> 		AppImageUpdaterDialog::ShowFinishedDialog |
> 		AppImageUpdaterDialog::ShowUpdateConfirmationDialog |
> 		AppImageUpdaterDialog::ShowErrorDialog;
> ```

Don't use tabs.
___
*[src/net/updatecheck.cpp, line 95 at r1](https://reviewable.io/reviews/qtox/qtox/5690#-LfvS9um623rV0L_c7CG:-LfvS9um623rV0L_c7CH:bqdxx0i) ([raw file](https://github.com/qtox/qtox/blob/aa564879eb880684a687a5846498b34c2ab4d4a0/src/net/updatecheck.cpp#L95)):*
> ```cpp
>     disconnect(&revisioner , &AppImageDeltaRevisioner::error , this , &UpdateCheck::updateCheckFailed);
>     connect(updateDialog.data() , &AppImageUpdaterDialog::quit , QApplication::instance() , &QApplication::quit ,
> 	    Qt::QueuedConnection);
> ```

Don't use tabs.
___
*[src/net/updatecheck.cpp, line 98 at r1](https://reviewable.io/reviews/qtox/qtox/5690#-LfvShRe9aTptERRcjgm:-LfvShRe9aTptERRcjgn:bz8msbs) ([raw file](https://github.com/qtox/qtox/blob/aa564879eb880684a687a5846498b34c2ab4d4a0/src/net/updatecheck.cpp#L98)):*
> ```cpp
>     connect(updateDialog.data() , &AppImageUpdaterDialog::canceled , this , &UpdateCheck::handleUpdateEnd);
>     connect(updateDialog.data() , &AppImageUpdaterDialog::finished , this , &UpdateCheck::handleUpdateEnd);
>     connect(updateDialog.data() , &AppImageUpdaterDialog::error , this , &UpdateCheck::handleUpdateEnd); 
> ```

Inconsistent code style with the rest of qTox -- there should be no space before commas.
___
*[src/net/updatecheck.cpp, line 145 at r1](https://reviewable.io/reviews/qtox/qtox/5690#-LfvTwzH82AbnkWv-z60:-LfvTwzI5ELtymRfD4b0:b-rjse3v) ([raw file](https://github.com/qtox/qtox/blob/aa564879eb880684a687a5846498b34c2ab4d4a0/src/net/updatecheck.cpp#L145)):*
> ```cpp
> }
> #else
> void UpdateCheck::handleUpdate(bool aval){
> ```

Inconsistent code style with the rest of qTox -- `{` should start on new line.
___
*[src/net/updatecheck.cpp, line 146 at r1](https://reviewable.io/reviews/qtox/qtox/5690#-LfvU0lQ04X-VJAxCzAW:-LfvU0lQ04X-VJAxCzAX:b-ez51hb) ([raw file](https://github.com/qtox/qtox/blob/aa564879eb880684a687a5846498b34c2ab4d4a0/src/net/updatecheck.cpp#L146)):*
> ```cpp
> #else
> void UpdateCheck::handleUpdate(bool aval){
> 	if(aval){
> ```

Inconsistent code style with the rest of qTox -- there should be a space after `if` and before `{`.
__ [...]

2019-05-27 22:57 UTC, nurupo commented
Where does it check for the delta updates? I see that

```C++
const QString versionUrl{QStringLiteral("https://api.github.com/repos/qTox/qTox/releases/latest")};
```

is ifdefed out and I don't see any other obvious URLs in the PR diff.

Also, does it verify the update somehow? PGP/Ed25519 signature check?

@sudden6 do Windows updates get verified?

2019-05-27 23:01 UTC, nurupo reviewed
> *[Reviewable](https://reviewable.io/reviews/qtox/qtox/5690)* status: 0 of 1 LGTMs obtained

___
*[appimage/build.sh, line 103 at r1](https://reviewable.io/reviews/qtox/qtox/5690#-LfvOQ5M6xdFiKj7e82F:-LfvWoV09xFaXTKbmuQ7:b-6u83oc) ([raw file](https://github.com/qtox/qtox/blob/aa564879eb880684a687a5846498b34c2ab4d4a0/appimage/build.sh#L103)):*
<details><summary><i>Previously, nurupo wrote…</i></summary><blockquote>

Did you forget to cd into `$AUB_SRC_DIR`? Otherwise that `cmake ..` below doesn't make much sense to me.
</blockquote></details>

Ah, I see what you did here.


<!-- Sent from Reviewable.io -->

2019-05-28 04:07 UTC, antony-jr commented
> is ifdefed out and I don't see any other obvious URLs in the PR diff.

@nurupo the update information is directly embedded in the AppImage. The library automatically detects and loads that information if it is run inside a AppImage else results in error.

The AppImage update information has the link to the .zsync meta file which has the **SHA1** sum of the latest upstream AppImage released by you. We simply compare these SHA1 hashes to know if we have a update. No need for versions. (Since its really troublesome)


**The update information is stored in the ```.updinfo``` elf header section of the AppImage.**

Fore more information , please see the specification [here](https://github.com/AppImage/AppImageSpec/blob/master/draft.md#update-information)

2019-05-28 07:27 UTC, antony-jr commented
@nurupo Can I get the artifacts for this PR build ? I really need to test the resultant AppImage from travsi-ci

2019-05-28 17:28 UTC, antony-jr commented
@nurupo could you review this PR again please ?  I think I've changed the source according to your previous reviews. Also **do I need to squash all commits ?**

2019-05-28 17:50 UTC, nurupo commented
There are still tabs in C++ code and CMake, and ` , ` in C++ code. Also, why do you use `eval` in the bash script to move files and remove a directory?

2019-05-28 18:15 UTC, antony-jr reviewed
> *[Reviewable](https://reviewable.io/reviews/qtox/qtox/5690)* status: 0 of 1 LGTMs obtained

___
*[appimage/build.sh, line 44 at r1](https://reviewable.io/reviews/qtox/qtox/5690#-LfvRGDR8jyu9gq6VSgu:-LfzdkCv0mC9DfNHPAFE:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/aa564879eb880684a687a5846498b34c2ab4d4a0/appimage/build.sh#L44)):*
<details><summary><i>Previously, nurupo wrote…</i></summary><blockquote>

This doesn't point to a binary. Also, I don't see it being used anywhere in this PR's diff.
</blockquote></details>

Done.
___
*[appimage/build.sh, line 103 at r1](https://reviewable.io/reviews/qtox/qtox/5690#-LfvOg1mB1DX8EyltAxj:-LfzdcsjC_1HXLMJ3Thr:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/aa564879eb880684a687a5846498b34c2ab4d4a0/appimage/build.sh#L103)):*
<details><summary><i>Previously, nurupo wrote…</i></summary><blockquote>

Also needs to checkout a specific tag instead of using the default branch.
</blockquote></details>

Done.
___
*[appimage/build.sh, line 162 at r1](https://reviewable.io/reviews/qtox/qtox/5690#-LfvOwCs5YCFIPT6shBd:-LfzdjIX7TtIMfV8X8ce:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/aa564879eb880684a687a5846498b34c2ab4d4a0/appimage/build.sh#L162)):*
<details><summary><i>Previously, nurupo wrote…</i></summary><blockquote>

This comment seems unnecessary.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2019-05-28 18:26 UTC, antony-jr reviewed
> *[Reviewable](https://reviewable.io/reviews/qtox/qtox/5690)* status: 0 of 1 LGTMs obtained

___
*[appimage/build-appimage.sh, line 60 at r1](https://reviewable.io/reviews/qtox/qtox/5690#-LfvPY-d-a9UZBI1kdd_:-Lfzf5ICBPgr3B01CBzu:bnilbl5) ([raw file](https://github.com/qtox/qtox/blob/aa564879eb880684a687a5846498b34c2ab4d4a0/appimage/build-appimage.sh#L60)):*
<details><summary><i>Previously, nurupo wrote…</i></summary><blockquote>

I don't see this being used anywhere as far as this PR diff goes. Am I missing something?

Also, don't use tabs.
</blockquote></details>

It is used to write the file name of the uploaded qTox AppImage in the .zsync meta file.
___
*[src/net/updatecheck.cpp, line 52 at r1](https://reviewable.io/reviews/qtox/qtox/5690#-LfvTmqiCxEXLAhSQkIA:-LfzfJMtAPoPKCxRTiXI:b-qukvg0) ([raw file](https://github.com/qtox/qtox/blob/aa564879eb880684a687a5846498b34c2ab4d4a0/src/net/updatecheck.cpp#L52)):*
<details><summary><i>Previously, nurupo wrote…</i></summary><blockquote>

Don't add trailing space.
</blockquote></details>

I don't quite get you here ?
___
*[src/net/updatecheck.cpp, line 81 at r1](https://reviewable.io/reviews/qtox/qtox/5690#-LfvSMqK05pr_yxYOFen:-LfzfoCe6sKYZnP_xoTR:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/aa564879eb880684a687a5846498b34c2ab4d4a0/src/net/updatecheck.cpp#L81)):*
<details><summary><i>Previously, nurupo wrote…</i></summary><blockquote>

Inconsistent code style with the rest of qTox -- there should be a space after `if` and before `{`.
</blockquote></details>

Done.
___
*[src/net/updatecheck.cpp, line 83 at r1](https://reviewable.io/reviews/qtox/qtox/5690#-LfvS8A--1xbJyL2DP_E:-LfzfrEc2kMPbN3D1FvP:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/aa564879eb880684a687a5846498b34c2ab4d4a0/src/net/updatecheck.cpp#L83)):*
<details><summary><i>Previously, nurupo wrote…</i></summary><blockquote>

Don't use tabs.
</blockquote></details>

Done.
___
*[src/net/updatecheck.cpp, line 89 at r1](https://reviewable.io/reviews/qtox/qtox/5690#-LfvS93M85HnU3R8rkl9:-LfzfsJC5AvYP8bNOI_K:bcahjre) ([raw file](https://github.com/qtox/qtox/blob/aa564879eb880684a687a5846498b34c2ab4d4a0/src/net/updatecheck.cpp#L89)):*
<details><summary><i>Previously, nurupo wrote…</i></summary><blockquote>

Don't use tabs.
</blockquote></details>

Done. I have only used spaces.
___
*[src/net/updatecheck.cpp, line 95 at r1](https://reviewable.io/reviews/qtox/qtox/5690#-LfvS9um623rV0L_c7CG:-Lfzfy_143nJ8BEuMtnF:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/aa564879eb880684a687a5846498b34c2ab4d4a0/src/net/updatecheck.cpp#L95)):*
<details><summary><i>Previously, nurupo wrote…</i></summary><blockquote>

Don't use tabs.
</blockquote></details>

Done.
___
*[src/net/updatecheck.cpp, line 98 at r1](https://reviewable.io/reviews/qtox/qtox/5690#-LfvShRe9aTptERRcjgm:-Lfzg2JM9x42rMjCaQmY:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/aa564879eb880684a687a5846498b34c2ab4d4a0/src/net/updatecheck.cpp#L98)):*
<details><summary><i>Previously, nurupo wrote…</i></summary><blockquote>

Inconsistent code style with the rest of qTox -- there should be no space before commas.
</blockquote></details>

Done.
___
*[src/net/updatecheck.cpp, line 145 at r1](https://reviewable.io/reviews/qtox/qtox/5690#-LfvTwzH82AbnkWv-z60:-Lfzg4jt1zPsQB2lE1Sq:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/aa564879eb880684a687a5846498b34c2ab4d4a0/src/net/updatecheck.cpp#L145)):*
<details><summary><i>Previously, nurupo wrote…</i></summary><blockquote>

Inconsistent code style with the rest of qTox -- `{` should start on new line.
</blockquote></details>

Done.
___
*[src/net/updatecheck.cpp, line 146 at r1](https://reviewable.io/reviews/qtox/qtox/5690#-LfvU0lQ04X-VJAxCzAW:-Lfzg5Q1CQCX0MrUFEwy:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/aa564879eb880684a687a5846498b34c2ab4d4a0/src/net/updatecheck.cpp#L146)):*
<details><summary><i>Previously, nurupo wrote…</i></summary><blockquote>

Inconsistent code style with the rest of qTox -- there should be a space after `if` and before `{`.
</blockquote></details>

Done.
___
*[src/net/updatecheck.cpp, line 152 at r1](https://reviewable.io/reviews/qtox/qtox/5690#-LfvSkYe2Raas0wkPqlj:-Lfzg6nzDHWCgFwZLLB9:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/aa564879eb880684a687a5846498b34c2ab4d4a0/src/net/updatecheck.cpp#L152)):*
<details><summary><i>Previously, nurupo wrote…</i></summary><blockquote>

Don't use tabs.
</blockquote></details>

Done.
___
*[src/net/updatecheck.cpp, line 155 at r1](https://reviewable.io/reviews/qtox/qtox/5690#-LfvU7-K5P5R7KIatr0K:-LfzgAcj5LZNy7CzvboW:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/aa564879eb880684a687a5846498b34c2ab4d4a0/src/net/updatecheck.cpp#L155)):*
<details><summary><i>Previously, nurupo wrote…</i></summary><blockquote>

Inconsistent code style with the rest of qTox -- `{` should start on new line.
</blockquote></details>

Done.
___
*[src/net/updatecheck.cpp, line 158 at r1](https://reviewable.io/reviews/qtox/qtox/5690#-LfvSlN42kliYrAmje5D:-LfzgBhnDsINALzXDRxl:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/aa564879eb880684a687a5846498b34c2ab4d4a0/src/net/updatecheck.cpp#L158)):*
<details><summary><i>Previously, nurupo wrote…</i></summary><blockquote>

Don't use tabs.
</blockquote></details>

Done.
___
*[src/net/updatecheck.cpp, line 158 at r1](https://reviewable.io/reviews/qtox/qtox/5690#-LfvUB7KDxzBAWO6InDT:-LfzgFTF1eTu4v9vIe2S:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/aa564879eb880684a687a5846498b34c2ab4d4a0/src/net/updatecheck.cpp#L158)):*
<details><summary><i>Previously, nurupo wrote…</i></summary><blockquote>

Inconsistent code style with the rest of qTox -- there should be no space before commas.
</blockquote></details>

Done.
___
*[src/widget/form/settings/aboutform.cpp, line 78 at r1](https://reviewable.io/reviews/qtox/qtox/5690#-LfvQ8qk-k3qLiUIzMO0:-LfzgGdN4JZJJOUmDTmZ:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/aa564879eb880684a687a5846498b34c2ab4d4a0/src/widget/form/settings/aboutform.cpp#L78)):*
<details><summary><i>Previously, nurupo wrote…</i></summary><blockquote>

This seems unnecessary.
</blockquote></details>

Done.
___
*[src/widget/form/settings/aboutform.cpp, line 100 at r1](https://reviewable.io/reviews/qtox/qtox/5690#-LfvTWcqD3Dxq5yn1BZj:-LfzgJPX6FqUaoAHG13p:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/aa564879eb880684a687a5846498b34c2ab4d4a0/src/widget/form/settings/aboutform.cpp#L100)):*
<details><summary><i>Previously, nurupo wrote…</i></summary><blockquote>

Don't remove spacing randomly.
</blockquote></details>

Done.
___
*[src/widget/form/settings/aboutform.cpp, line 104 at r1](https://reviewable.io/reviews/qtox/qtox/5690#-LfvTAhz6V1zVwjYZlxq:-LfzgK816zL2YGYOYNMM:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/aa564879eb880684a687a5846498b34c2ab4d4a0/src/widget/form/settings/aboutform.cpp#L104)):*
<details><summary><i>Previously, nurupo wrote…</i></summary><blockquote>

Don't use tabs.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2019-05-28 19:42 UTC, antony-jr commented
@nurupo Okay I have used ```clang-format -i --style=file``` command to format the style for all the files that I have changed. Do I still have issues with the coding style ?

2019-05-29 02:28 UTC, antony-jr reviewed
> *[Reviewable](https://reviewable.io/reviews/qtox/qtox/5690)* status: 0 of 1 LGTMs obtained

___
*[CMakeLists.txt, line 669 at r1](https://reviewable.io/reviews/qtox/qtox/5690#-LfvQW_D5k97gKX5DAZS:-Lg0PRzQDcdpkJBK27Eq:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/aa564879eb880684a687a5846498b34c2ab4d4a0/CMakeLists.txt#L669)):*
<details><summary><i>Previously, nurupo wrote…</i></summary><blockquote>

Don't use tabs.
</blockquote></details>

Done.
___
*[CMakeLists.txt, line 712 at r1](https://reviewable.io/reviews/qtox/qtox/5690#-LfvQl5058jgJV8Qxq4y:-Lg0PTwRDFQ326ev-nIV:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/aa564879eb880684a687a5846498b34c2ab4d4a0/CMakeLists.txt#L712)):*
<details><summary><i>Previously, nurupo wrote…</i></summary><blockquote>

Body of the if-statement should be indented.
</blockquote></details>

Done.
___
*[CMakeLists.txt, line 717 at r1](https://reviewable.io/reviews/qtox/qtox/5690#-LfvR01C0jLSvFt578WS:-Lg0PVBZ-Z5f7qXIvXR1:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/aa564879eb880684a687a5846498b34c2ab4d4a0/CMakeLists.txt#L717)):*
<details><summary><i>Previously, nurupo wrote…</i></summary><blockquote>

Same -- body of the if-statement should be indented.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2019-05-29 02:29 UTC, antony-jr reviewed
<img class="emoji" title=":lgtm_strong:" alt=":lgtm_strong:" align="absmiddle" src="https://reviewable.io/lgtm_strong.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/qtox/qtox/5690#-:-Lg0PpsH05cixTQf9VRc:b-jbsf8z)* status: :shipit: complete! 1 of 1 LGTMs obtained



<!-- Sent from Reviewable.io -->

2019-05-29 04:26 UTC, antony-jr reviewed
> *[Reviewable](https://reviewable.io/reviews/qtox/qtox/5690)* status: :shipit: complete! 1 of 1 LGTMs obtained

___
*[src/net/updatecheck.cpp, line 58 at r1](https://reviewable.io/reviews/qtox/qtox/5690#-LfvRvdx-D_7qprjKXyj:-Lg0pZYl1yhDTHyEc0Da:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/aa564879eb880684a687a5846498b34c2ab4d4a0/src/net/updatecheck.cpp#L58)):*
<details><summary><i>Previously, nurupo wrote…</i></summary><blockquote>

Inconsistent code style with the rest of qTox -- there should be no space before commas.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2019-05-29 04:54 UTC, antony-jr commented
Here is the AppImage from the PR build , https://transfer.sh/GOKvV/qTox-x86_64.AppImage (expires in 13 days) and the feature should like this -> https://github.com/qTox/qTox/issues/5643#issuecomment-496628038

2019-05-30 06:58 UTC, antony-jr commented
anyone ? Does this PR require changes ?

2019-06-01 16:08 UTC, nurupo reviewed
> Reviewed 2 of 9 files at r1, 1 of 5 files at r2, 5 of 6 files at r4, 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/qtox/qtox/5690)* status: :shipit: complete! 1 of 1 LGTMs obtained

___
*[appimage/build-appimage.sh, line 64 at r5](https://reviewable.io/reviews/qtox/qtox/5690#-LgImyHoDSgmcdruroqP:-LgImyHoDSgmcdruroqQ:b-gz4inn) ([raw file](https://github.com/qtox/qtox/blob/f281732beab1a8a935ca16d344953d16fd041862/appimage/build-appimage.sh#L64)):*
> ```Shell
>            -v $PWD/output:/output \
>            debian:stretch-slim \
>            /bin/bash -c "/qtox/appimage/build.sh"
> ```

Arguments are not aligned with the docker command above, you have added extra 3 spaces to all of them.
___
*[appimage/build-appimage.sh, line 77 at r5](https://reviewable.io/reviews/qtox/qtox/5690#-LgIlgdA1VnT9oRyNaIn:-LgIlgdA1VnT9oRyNaIo:b-88s9jt) ([raw file](https://github.com/qtox/qtox/blob/f281732beab1a8a935ca16d344953d16fd041862/appimage/build-appimage.sh#L77)):*
> ```Shell
>     # This meta file will be used by appimage updater
>     mv ./output/*.AppImage.zsync "$OUTFILE".zsync
>     
> ```

Trailing space.
___
*[src/net/updatecheck.cpp, line 52 at r1](https://reviewable.io/reviews/qtox/qtox/5690#-LfvTmqiCxEXLAhSQkIA:-LgIlsBX1pDFH6Y_hzQP:bwvkqc3) ([raw file](https://github.com/qtox/qtox/blob/aa564879eb880684a687a5846498b34c2ab4d4a0/src/net/updatecheck.cpp#L52)):*
<details><summary><i>Previously, antony-jr (Antony jr) wrote…</i></summary><blockquote>

I don't quite get you here ?
</blockquote></details>

There was a space right after `;`. It's gone now though.


<!-- Sent from Reviewable.io -->

2019-06-01 16:15 UTC, nurupo commented
Btw, I'm mostly just sanity-checking code through Reviewable. @sudden6 and/or @anthonybilinski would need to check that the code changes actually make sense, test running the binary and so on. Maybe even check AppImageUpdaterBridge's code to see if it does anything fishy, as an update compromise would be a huge issue. AFAIK @sudden6 is away for a few days and @anthonybilinski is probably busy with something else, so it might take some time before they get to review the PR.

2019-06-01 17:09 UTC, antony-jr commented
> Maybe even check AppImageUpdaterBridge's code to see if it does anything fishy, as an update compromise would be a huge issue.

Feel free to do that.  But here is the process of the entire update.

**Note**: All network operations are through proxy given in settings.

* Get .zsync meta file from github which is uploaded by travis-ci when deployed.
* The zsync meta file has the relative url of the original file and other such info.
* The zsync meta file also contains the checksum for all blocks of the original file , these blocks can be 1024 bytes or 4096 bytes.
* Each block has a weak rolling checksum (in our case modified version adler-32 as used in rsync) and a strong checksum(in our case MD4)
* The zsync algorithm is applied to reduce the size of the meta file small as possible. See http://zsync.moria.org.uk/paper/ (Like reduce the hash length of MD4 using probability) (Also find the optimal size for weak-checksum using erasure code , refer coding and information theory for that)

* Now we check for update by computing the SHA1 hash of the local file on disk and comparing it with the one that is given in the downloaded .zsync meta file from qTox github releases.

* The SHA1 hash does not match then we conclude that there exists an update.

* Note that this is syncing and not update which has advantage that we don't need to worry about versioning , it is guaranteed to do the update if qTox AppImage on the latest tag on github is changed from what we have locally.

* Now if the user wants to update then we compute the rolling checksum for the local file and compare it with the rolling checksum in the .zsync meta file , if weak checksum does not match then we compute the strong checksum for that block and check it with its respective MD4 hash in the .zsync meta file. If both strong and weak checksum mismatches then we mark that block as needed. If it does not mismatch then this block is placed in the correct position as the original file.(the latest qTox AppImage)

* Now the required blocks are converted into **HTTP range requests**. These HTTP ranges are requested to the file uploaded to github. (The latest qTox AppImage).

* After downloading each block range , it is then again compared with the strong and weak checksums , if they mismatch then the update will fail eventually in later stages if not retried.

* Now when all required block ranges are downloaded and written successfully , we finally compute a SHA1 hash of the temporary file which is under construction and compare it with the one given in the .zsync meta file.

* If the SHA1 hash mismatches then the update fails and all temporary files are deleted.

* Now optionally you can sign the qTox AppImage which can be checked by the library , but that would depend on system installed version of **gpg2 or gpg** program. So for now I have not implemented that part but eventually will(without using system installed gpg program). But the official library itself uses the system installed gpg to check the signature. They use subprocess to communicate with the system installed gpg program to verify the GPG signatures of the old AppImage and newly downloaded AppImage.

2019-06-01 17:11 UTC, antony-jr commented
> Btw, I'm mostly just sanity-checking code through Reviewable.

That is really crucial than anything else. @nurupo Thank you for taking your time to review my code. It really helps.

2019-07-07 15:38 UTC, antony-jr commented
does this PR need any changes? Why is this getting stalled?

2019-07-07 15:51 UTC, probonopd commented
Where can the AppImage be downloaded for testing? I see in the log file that it is uploaded to transfer.sh somewhere...

2019-07-07 15:52 UTC, antony-jr commented
> Where can the AppImage be downloaded for testing? I see in the log file that it is uploaded to transfer.sh somewhere...

@probonopd I forget to add the trick to show the output of curl so I think we need to add it to this PR to get it. Give me a minute.

2019-07-07 16:39 UTC, probonopd commented
Wow, this takes a really long time to build...

2019-07-07 16:42 UTC, antony-jr commented
> Wow, this takes a really long time to build...

It usually doesn't but I think Circle CI is building Qt from source so its gonna take a while. I'm not aware of the build changes after this PR, I assume we don't have any cache since this is an old PR.

2019-07-07 16:45 UTC, probonopd commented
> Circle CI is building Qt from source

Wow... the whole of Qt?! Why?

2019-07-07 16:49 UTC, antony-jr commented
> Wow... the whole of Qt?! Why?

in qTox, they build everything from source to avoid anyone from tampering the source, I think. They even build all AppImage tools from source. They really don't use any prebuilt stuff other than what the distro gives through their package managers.

2019-07-07 17:36 UTC, antony-jr commented
Travis-CI is always waiting for status to be reported when all other jobs are successfully finished!!! please fix this. @probonopd We can't do anything for now.

2019-07-07 17:42 UTC, antony-jr reviewed
> *[Reviewable](https://reviewable.io/reviews/qtox/qtox/5690)* status: :shipit: complete! 1 of 1 LGTMs obtained

___
*[src/net/updatecheck.cpp, line 52 at r1](https://reviewable.io/reviews/qtox/qtox/5690#-LfvTmqiCxEXLAhSQkIA:-LjCWqQu4SPcWghT7nrm:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/aa564879eb880684a687a5846498b34c2ab4d4a0/src/net/updatecheck.cpp#L52)):*
<details><summary><i>Previously, nurupo wrote…</i></summary><blockquote>

There was a space right after `;`. It's gone now though.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2019-07-07 22:19 UTC, nurupo commented
>Wow... the whole of Qt?! Why?

Not the whole of Qt, just the required components - mostly QtBase. It also builds OpenSSL for Qt to use, SQLCipher, FFmpeg, Openal-soft, Filteraudio, QREncode, Exif, Opus, Sodium, VPX, Toxcore and NSIS. This is all done only for Windows qTox builds, since we cross-compile to Windows from Linux (from Debian Stretch to be precise). For Linux builds we try to keep building to minimal and re-use packages from Debian, building only things not available (e.g. appimage) or which are broken (libsqlcipher is) in Debian, so Linux builds usually don't take as long as Windows ones do.

Also, the build results of Windows qTox dependencies are cached when they are ran on Travis-CI/Circle-CI so that they don't have to be rebuilt on every single git push, they get rebuilt only when Travis-CI/Circle-CI's cache expires or when someone changes the Windows build script. While I'm a lot more familiar with Travis-CI than Circle-CI, my guess as to why Circle-CI has rebuilt Windows dependencies, including Qt, when @antony-jr pushed his last commit is because the cache simply expired, the last commit in this PR was over 30 days ago.

As @antony-jr has said, we try to use only trusted sources for qTox dependencies. In general we trust Debian packages to be non-malicious, which is why we produce Linux and Windows builds in Debian docker containers. Obviously, Debian provides no pre-built Windows packages, so for the Windows build of qTox we use the second best option - trusting the original source code to be non-malicious and cross-compiling everything from source on a Debian system, while making sure we get the source code from trusted places and pin the source by version+hash so that the build would fail if someone changes the source code from under us.

2019-07-08 12:09 UTC, antony-jr commented
> While I'm a lot more familiar with Travis-CI than Circle-CI,

@nurupo Then can you explain why Travis-CI is always waiting for status to be reported ?? any Ideas.

2019-07-08 20:31 UTC, nurupo commented
Sounds like Travis-CI failed to report the build result to GitHub.

2019-07-08 20:38 UTC, nurupo commented
A simple Google search finds that [Travis-CI had authentication issues with GitHub recently](https://travis-ci.community/t/known-issue-travis-ci-reports-expected-waiting-for-status-to-be-reported-on-the-github-status-api-but-the-status-never-arrives/1154/20).

2019-07-09 12:25 UTC, antony-jr commented
> A simple Google search finds that Travis-CI had authentication issues with GitHub recently.

Any ideas to fix this issue? should I just wait , I even triggered a change but travis-CI never runs the build for this PR(only?).

2019-07-09 21:12 UTC, sudden6 requested changes
Sorry, I started a review, but only was able to finish it now.

I think the changes are mostly ok.

Is it possible to test the update process before merging to master? Can you write down the steps to do it?

> *[Reviewable](https://reviewable.io/reviews/qtox/qtox/5690#-:-LhMci9rBsQ6qBs2lDwD:b45zgkp)* status: :shipit: complete! 1 of 1 LGTMs obtained

___
*[appimage/build.sh, line 191 at r6](https://reviewable.io/reviews/qtox/qtox/5690#-LhMd6bo9rpspW4o1Cy6:-LhMd6bp1th5kKxwP0He:b-5uifq3) ([raw file](https://github.com/qtox/qtox/blob/4f18f6f787a3b39298428f2ad4d7411b0afd1db6/appimage/build.sh#L191)):*
> ```Shell
>     eval "$AITOOL_BIN -u \"$UPDATE_INFO\" $QTOX_APP_DIR qTox-$TRAVIS_TAG.x86_64.AppImage"
> else
>     eval "$AITOOL_BIN -u \"$UPDATE_INFO\" $QTOX_APP_DIR qTox-x86_64.AppImage"
> ```

it would be nice to include the short commit hash here so we can distinguish the builds
___
*[appimage/build-appimage.sh, line 84 at r6](https://reviewable.io/reviews/qtox/qtox/5690#-LhMdFSJEs1ZLtQ3mdFx:-LhMdFSKDVCvoDL7B0XH:b-9dv8a5) ([raw file](https://github.com/qtox/qtox/blob/4f18f6f787a3b39298428f2ad4d7411b0afd1db6/appimage/build-appimage.sh#L84)):*
> ```Shell
> else
>     # upload PR builds to test them.
>     curl --upload-file "./output/qTox-x86_64.AppImage" "https://transfer.sh/qTox-x86_64.AppImage"
> ```

I think it would also make sense here to include the commit hash, idk if `transfer.sh` allows that much storage though


<!-- Sent from Reviewable.io -->

2019-07-10 03:29 UTC, nurupo commented
___
*[appimage/build-appimage.sh, line 85 at r9](https://reviewable.io/reviews/qtox/qtox/5690#-LjOvLBZEgijVQ4Z-y9L:-LjOvLB_-DLclftp20SB:b-toyrop) ([raw file](https://github.com/qtox/qtox/blob/b03e5f48f7b4e08410ea0bc0de414b8863c23c99/appimage/build-appimage.sh#L85)):*
> ```Shell
>     # upload PR builds to test them.
>     echo "Uploading AppImage to transfer.sh"
>     curl --upload-file "./output/qTox-x86_64.AppImage" "https://transfer.sh/qTox-x86_64.AppImage" > ./upload
> ```

It would also make sense to print out sha256 of `qTox-x86_64.AppImage` in here, so that you could verify that you have downloaded the right one.


<!-- Sent from Reviewable.io -->

2019-07-10 03:41 UTC, nurupo reviewed
> *[Reviewable](https://reviewable.io/reviews/qtox/qtox/5690)* status: :shipit: complete! 1 of 1 LGTMs obtained

___
*[appimage/build-appimage.sh, line 82 at r9](https://reviewable.io/reviews/qtox/qtox/5690#-LjOvMqe5z1zX-lc33vL:-LjOvMqe5z1zX-lc33vM:b-m4yl8h) ([raw file](https://github.com/qtox/qtox/blob/b03e5f48f7b4e08410ea0bc0de414b8863c23c99/appimage/build-appimage.sh#L82)):*
> ```Shell
> 
>     sha256sum "$OUTFILE" > "$OUTFILE".sha256
> else
> ```

This uploads qTox AppImage to `https://transfer.sh` every time there was no git tag pushed. This is way too often as we already have [nightly builds](https://github.com/qtox/qTox-nightly-releases/releases) that include AppImage. We want to restrict this `transfer.sh` uploading only to PRs, and then I wonder if it's really that useful to litter `transfer.sh` with huge binaries that will almost never be downloaded, as PRs see a lot of rebasing going on.


<!-- Sent from Reviewable.io -->

2019-07-10 03:44 UTC, antony-jr commented
> We want to restrict this transfer.sh uploading only to PRs, and then I wonder if it's really that useful to litter transfer.sh with huge binaries that will almost never be downloaded, as PRs see a lot of rebasing going on.

@nurupo That's my concern too but some kind of flag to do the upload would be nice. Or this is not required if nightly builds are uploaded with .zsync meta file to github.

2019-07-10 03:54 UTC, antony-jr commented
We can have a flag inside the AppImage build script, during the PR testing we turn this flag on and commit it and get the AppImage result on transfer.sh, when done testing with the PR we turn this flag off and squash all commits together, does that sound good @nurupo ?

2019-07-10 06:17 UTC, antony-jr commented
@nurupo I've made preparation for nightly to use this update feature too(or else update available button will be enabled when you use a nightly version since it points to the other repo). You have to change this line https://github.com/qTox/qTox/blob/b445031912ae943d7580ea21f6813e9f71bc03ee/.travis.yml#L170 to this 

``` 
    - cp -a ./nightly-appimage/* "$ARTIFACTS_DIR"
```

This is because the AppImage update information has to point to the correct release tag in the correct repo. **For now I've commented out those lines which creates a new AppImage for the nightly appimage with update information which points to ```CIRP_GITHUB_REPO_SLUG``` environmental variable with ```ci-master-latest``` as the release tag**.

**We just have to un-comment those lines and copy from ./nightly-appimage dir to artifacts dir after this PR is merged**

And still Travis-CI is not working. The build is never attempted.

2019-07-10 07:27 UTC, nurupo commented
>We want to restrict this transfer.sh uploading only to PRs, and then I wonder if it's really that useful to litter transfer.sh with huge binaries that will almost never be downloaded, as PRs see a lot of rebasing going on.

Another thing regarding whether it's useful is that anyone submitting a PR that edits qTox's code has to build and test their changes locally before submitting them anyway, so you very rarely want Travis-CI to build an AppImage for you.

>That's my concern too but some kind of flag to do the upload would be nice.

I'd say just comment out uploading to `transfer.sh`. If someone opens a PR and needs it, they could make a temporary commit that uncomments it.

>We can have a flag inside the AppImage build script, during the PR testing we turn this flag on and commit it and get the AppImage result on transfer.sh, when done testing with the PR we turn this flag off and squash all commits together, does that sound good

Sounds good to me, but it's really for @sudden6 to decide as he will likely be the one merging (I don't have write access to the repo).

2019-07-10 07:34 UTC, antony-jr commented
> Another thing regarding whether it's useful is that anyone submitting a PR that edits qTox's code has to build and test their changes locally before submitting them anyway, so you very rarely want Travis-CI to build an AppImage for you.

Sometimes its better this way, Its really hard to build everything from scratch. Installing docker and other stuff. This way we can see the logs and try the result since everything is public. Also travis-CI is faster and the build is not wasted.

2019-07-10 07:40 UTC, nurupo reviewed
> *[Reviewable](https://reviewable.io/reviews/qtox/qtox/5690)* status: :shipit: complete! 1 of 1 LGTMs obtained

___
*[appimage/build-appimage.sh, line 54 at r10](https://reviewable.io/reviews/qtox/qtox/5690#-LjPoqW-A6Bz23mg1R-j:-LjPoqW-A6Bz23mg1R-k:bi8fs8t) ([raw file](https://github.com/qtox/qtox/blob/15e5df5972ad6e5bca8eb3b72f5a8dde49ad1f70/appimage/build-appimage.sh#L54)):*
> ```Shell
> 
> mkdir -p ./output
> mkdir -p ./nightly-appimage # AppImages specially made for nightly release.
> ```

There is no need for this `nightly-appimage` directory. [Nightly is put in the same `$PWD/output` directory](https://github.com/qTox/qTox/blob/b6ba2e330a361629f0bda922184f5138676be92d/.travis.yml#L164-L175). Nightly build is just a regular build. You can detect if a build is nightly by checking if `$TRAVIS_EVENT_TYPE` is set to `"cron"`, as we create nightly builds only in Travis-CI Cron builds.
___
*[appimage/build-appimage.sh, line 68 at r10](https://reviewable.io/reviews/qtox/qtox/5690#-LjPoGLM9Syoom2vHu57:-LjPoGLM9Syoom2vHu58:b-l3q0ww) ([raw file](https://github.com/qtox/qtox/blob/15e5df5972ad6e5bca8eb3b72f5a8dde49ad1f70/appimage/build-appimage.sh#L68)):*
> ```Shell
> else
>     docker run --rm \
>         -e GIT_HASH \
> ```

You probably want to use `TRAVIS_COMMIT` here.
___
*[appimage/build-appimage.sh, line 69 at r10](https://reviewable.io/reviews/qtox/qtox/5690#-LjPmPwx7JAPFFBFWQ8V:-LjPmPwx7JAPFFBFWQ8W:b-9vaw5i) ([raw file](https://github.com/qtox/qtox/blob/15e5df5972ad6e5bca8eb3b72f5a8dde49ad1f70/appimage/build-appimage.sh#L69)):*
> ```Shell
>     docker run --rm \
>         -e GIT_HASH \
> 	-e CIRP_GITHUB_REPO_SLUG \
> ```

Use spaces instead of tabs.
___
*[appimage/build-appimage.sh, line 87 at r10](https://reviewable.io/reviews/qtox/qtox/5690#-LjPmKpKA6DnARMMxRNo:-LjPmKpKA6DnARMMxRNp:b-88s9jt) ([raw file](https://github.com/qtox/qtox/blob/15e5df5972ad6e5bca8eb3b72f5a8dde49ad1f70/appimage/build-appimage.sh#L87)):*
> ```Shell
>     # extension.
>     readonly OUTFILE=./output/qTox-"$TRAVIS_TAG".x86_64.AppImage
>  
> ```

Trailing space.
___
*[appimage/build-appimage.sh, line 94 at r10](https://reviewable.io/reviews/qtox/qtox/5690#-LjPmGiu3_UIWOYHRx7X:-LjPmGiu3_UIWOYHRx7Y:b-88s9jt) ([raw file](https://github.com/qtox/qtox/blob/15e5df5972ad6e5bca8eb3b72f5a8dde49ad1f70/appimage/build-appimage.sh#L94)):*
> ```Shell
>     sha256sum "$OUTFILE" > "$OUTFILE".sha256
> else
>     if [ "$UPLOAD_PR_APPIMAGE" == "True" ] 
> ```

Trailing space.
___
*[appimage/build-appimage.sh, line 102 at r10](https://reviewable.io/reviews/qtox/qtox/5690#-LjPm5XD0FSfUz1AYphe:-LjPm5XD0FSfUz1AYphf:b-9vaw5i) ([raw file](https://github.com/qtox/qtox/blob/15e5df5972ad6e5bca8eb3b72f5a8dde49ad1f70/appimage/build-appimage.sh#L102)):*
> ```Shell
>         echo -n "$(cat ./upload)\\n" >> ./uploaded-to
>         rm -rf ./upload ./uploaded-to
> 	sha256sum "./output/qTox-$GIT_HASH-x86_64.AppImage"
> ```

Use spaces instead of tabs.


<!-- Sent from Reviewable.io -->

2019-07-10 07:44 UTC, antony-jr commented
> There is no need for this nightly-appimage directory. Nightly is put in the same $PWD/output directory. Nightly build is just a regular build. You can detect if a build is nightly by checking if $TRAVIS_EVENT_TYPE is set to "cron", as we create nightly builds only in Travis-CI Cron builds.

I just needed to change the update information to point to qTox/qTox-nightly-releases when nightly build is made or else this will always trigger update since the SHA1 hash of the nightly and the stable latest may differ.

2019-07-10 08:02 UTC, nurupo commented
>I just needed to change the update information to point to qTox/qTox-nightly-releases when nightly build is made or else this will always trigger update since the SHA1 hash of the nightly and the stable latest may differ.

I was talking about the `nightly-appimage` directory. There is no need for it, just get the AppImage from the `output`. There is no separate nightly AppImage file, it's always just a single AppImage file in the `output` directory.

As far as the update information - yes, it should use `ci-master-latest` tag from `qTox/qTox-nightly-releases`, you got that right, there is no issue with that, I wasn't talking about that.

2019-07-10 08:05 UTC, antony-jr commented
>  There is no separate nightly AppImage file, it's always just a single AppImage file in the output directory.

Yep. I got it.

2019-07-10 08:22 UTC, antony-jr reviewed
> *[Reviewable](https://reviewable.io/reviews/qtox/qtox/5690)* status: :shipit: complete! 1 of 1 LGTMs obtained

___
*[appimage/build.sh, line 191 at r6](https://reviewable.io/reviews/qtox/qtox/5690#-LhMd6bo9rpspW4o1Cy6:-LjPxvtI4pT2EmtSiNqg:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/4f18f6f787a3b39298428f2ad4d7411b0afd1db6/appimage/build.sh#L191)):*
<details><summary><i>Previously, sudden6 wrote…</i></summary><blockquote>

it would be nice to include the short commit hash here so we can distinguish the builds
</blockquote></details>

Done.
___
*[appimage/build-appimage.sh, line 84 at r6](https://reviewable.io/reviews/qtox/qtox/5690#-LhMdFSJEs1ZLtQ3mdFx:-LjPyMQO7q4wiChNBatk:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/4f18f6f787a3b39298428f2ad4d7411b0afd1db6/appimage/build-appimage.sh#L84)):*
<details><summary><i>Previously, sudden6 wrote…</i></summary><blockquote>

I think it would also make sense here to include the commit hash, idk if `transfer.sh` allows that much storage though
</blockquote></details>

Done.
___
*[appimage/build-appimage.sh, line 82 at r9](https://reviewable.io/reviews/qtox/qtox/5690#-LjOvMqe5z1zX-lc33vL:-LjPyJEi8-Q6yhq_lz90:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/b03e5f48f7b4e08410ea0bc0de414b8863c23c99/appimage/build-appimage.sh#L82)):*
<details><summary><i>Previously, nurupo wrote…</i></summary><blockquote>

This uploads qTox AppImage to `https://transfer.sh` every time there was no git tag pushed. This is way too often as we already have [nightly builds](https://github.com/qtox/qTox-nightly-releases/releases) that include AppImage. We want to restrict this `transfer.sh` uploading only to PRs, and then I wonder if it's really that useful to litter `transfer.sh` with huge binaries that will almost never be downloaded, as PRs see a lot of rebasing going on.
</blockquote></details>

Done.
___
*[appimage/build-appimage.sh, line 85 at r9](https://reviewable.io/reviews/qtox/qtox/5690#-LjOvLBZEgijVQ4Z-y9L:-LjPyNw_0wKHPk-IWBYg:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/b03e5f48f7b4e08410ea0bc0de414b8863c23c99/appimage/build-appimage.sh#L85)):*
<details><summary><i>Previously, nurupo wrote…</i></summary><blockquote>

It would also make sense to print out sha256 of `qTox-x86_64.AppImage` in here, so that you could verify that you have downloaded the right one.
</blockquote></details>

Done.
___
*[appimage/build-appimage.sh, line 54 at r10](https://reviewable.io/reviews/qtox/qtox/5690#-LjPoqW-A6Bz23mg1R-j:-LjPy50B2R0avsDVIAcs:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/15e5df5972ad6e5bca8eb3b72f5a8dde49ad1f70/appimage/build-appimage.sh#L54)):*
<details><summary><i>Previously, nurupo wrote…</i></summary><blockquote>

There is no need for this `nightly-appimage` directory. [Nightly is put in the same `$PWD/output` directory](https://github.com/qTox/qTox/blob/b6ba2e330a361629f0bda922184f5138676be92d/.travis.yml#L164-L175). Nightly build is just a regular build. You can detect if a build is nightly by checking if `$TRAVIS_EVENT_TYPE` is set to `"cron"`, as we create nightly builds only in Travis-CI Cron builds.
</blockquote></details>

Done.
___
*[appimage/build-appimage.sh, line 68 at r10](https://reviewable.io/reviews/qtox/qtox/5690#-LjPoGLM9Syoom2vHu57:-LjPy78K1g8JcjdOKM7K:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/15e5df5972ad6e5bca8eb3b72f5a8dde49ad1f70/appimage/build-appimage.sh#L68)):*
<details><summary><i>Previously, nurupo wrote…</i></summary><blockquote>

You probably want to use `TRAVIS_COMMIT` here.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2019-07-10 08:41 UTC, antony-jr reviewed
> *[Reviewable](https://reviewable.io/reviews/qtox/qtox/5690)* status: :shipit: complete! 1 of 1 LGTMs obtained

___
*[appimage/build-appimage.sh, line 64 at r5](https://reviewable.io/reviews/qtox/qtox/5690#-LgImyHoDSgmcdruroqP:-LjQ11drCWBkufRHA3eX:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/f281732beab1a8a935ca16d344953d16fd041862/appimage/build-appimage.sh#L64)):*
<details><summary><i>Previously, nurupo wrote…</i></summary><blockquote>

Arguments are not aligned with the docker command above, you have added extra 3 spaces to all of them.
</blockquote></details>

Done.
___
*[appimage/build-appimage.sh, line 102 at r10](https://reviewable.io/reviews/qtox/qtox/5690#-LjPm5XD0FSfUz1AYphe:-LjQ17Qh6In_Sk1AQfAJ:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/15e5df5972ad6e5bca8eb3b72f5a8dde49ad1f70/appimage/build-appimage.sh#L102)):*
<details><summary><i>Previously, nurupo wrote…</i></summary><blockquote>

Use spaces instead of tabs.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2019-07-10 09:04 UTC, antony-jr reviewed
> *[Reviewable](https://reviewable.io/reviews/qtox/qtox/5690)* status: :shipit: complete! 1 of 1 LGTMs obtained

___
*[appimage/build-appimage.sh, line 77 at r5](https://reviewable.io/reviews/qtox/qtox/5690#-LgIlgdA1VnT9oRyNaIn:-LjQ6iDd6BROtvCOy7nA:b1ihuv0) ([raw file](https://github.com/qtox/qtox/blob/f281732beab1a8a935ca16d344953d16fd041862/appimage/build-appimage.sh#L77)):*
<details><summary><i>Previously, nurupo wrote…</i></summary><blockquote>

Trailing space.
</blockquote></details>

Done?. (How do you find trailing spaces?)
___
*[appimage/build-appimage.sh, line 69 at r10](https://reviewable.io/reviews/qtox/qtox/5690#-LjPmPwx7JAPFFBFWQ8V:-LjQ70bTBqk0gS2JmmDR:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/15e5df5972ad6e5bca8eb3b72f5a8dde49ad1f70/appimage/build-appimage.sh#L69)):*
<details><summary><i>Previously, nurupo wrote…</i></summary><blockquote>

Use spaces instead of tabs.
</blockquote></details>

Done.
___
*[appimage/build-appimage.sh, line 87 at r10](https://reviewable.io/reviews/qtox/qtox/5690#-LjPmKpKA6DnARMMxRNo:-LjQ6tUd-v9Bfk3qYasW:b-ekrlii) ([raw file](https://github.com/qtox/qtox/blob/15e5df5972ad6e5bca8eb3b72f5a8dde49ad1f70/appimage/build-appimage.sh#L87)):*
<details><summary><i>Previously, nurupo wrote…</i></summary><blockquote>

Trailing space.
</blockquote></details>

Done???.
___
*[appimage/build-appimage.sh, line 94 at r10](https://reviewable.io/reviews/qtox/qtox/5690#-LjPmGiu3_UIWOYHRx7X:-LjQ6xoE0Obx6vmCCoHc:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/15e5df5972ad6e5bca8eb3b72f5a8dde49ad1f70/appimage/build-appimage.sh#L94)):*
<details><summary><i>Previously, nurupo wrote…</i></summary><blockquote>

Trailing space.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2019-07-10 09:17 UTC, antony-jr commented
Hmm... Now circle-ci is also failing temporarily because it can't fetch some debian packages.

```
Err:1 http://security.debian.org/debian-security stretch/updates InRelease
  Temporary failure resolving 'security.debian.org'
Err:2 http://deb.debian.org/debian stretch InRelease
  Temporary failure resolving 'deb.debian.org'
Err:3 http://deb.debian.org/debian stretch-updates InRelease
  Temporary failure resolving 'deb.debian.org'
```

@nurupo do you have any ideas on fixing travis-CI. Is travis-CI not working only for this PR? I really like to test the PR build.

2019-07-10 10:39 UTC, antony-jr commented
@probonopd For now I've built the AppImage in a separate repo , you can get the AppImages here -> https://github.com/antony-jr/qTox-PR5690/releases 

Also @nurupo ```$TRAVIS_COMMIT``` is big , do I need to trim it to 7 characters?

2019-07-10 13:35 UTC, antony-jr commented
This is how you test the update process,

Download the AppImage(with the updater) from https://github.com/antony-jr/qTox-PR5690/releases (for now) and execute the following commands

```
 $ chmod +x ./qTox-*-x86_64.AppImage
 $ ./qTox-*-x86_64.AppImage # go to settings->about , it should say qTox is up to date
 $ # exit the App
 $ echo "some changes to change SHA1" >> qTox-*-x86_64.AppImage
 $ ./qTox-*-x86_64.AppImage # you should see the update available button in about.
```

2019-07-10 13:45 UTC, antony-jr commented
Don't merge yet, I need to trim the TRAVIS_COMMIT and some sanity checks on the lib.

2019-07-10 14:34 UTC, antony-jr commented
The previous commit did something so its not gonna look good. Please wait.

2019-07-10 21:42 UTC, nurupo commented
>How do you find trailing spaces?

I just check though Reviewable, it displays whitespace. Most code editors can be configured to display whitespace too, as well as to automatically remove any trailing white space in a file when you save it, as well as insert N number of spaces instead of a tab when the TAB key is pressed.

>@nurupo do you have any ideas on fixing travis-CI. Is travis-CI not working only for this PR? I really like to test the PR build.

Nope, no idea what's wrong with Travis-CI, never had it stop tracking a PR before.

>Also @nurupo $TRAVIS_COMMIT is big , do I need to trim it to 7 characters?

I noticed that `qTox-*x86_64.AppImage` already has git hash in its file name in [nightly releases](https://github.com/qtox/qTox-nightly-releases/releases), e.g. `qTox-b445031-x86_64.AppImage`, so something is already setting it?

2019-07-10 21:46 UTC, nurupo commented
>I noticed that qTox-*x86_64.AppImage already has git hash in its file name in nightly releases, e.g. qTox-b445031-x86_64.AppImage, so something is already setting it?

Found it, linuxdeployqt adds the git hash into the AppImage filename when producing the `qTox-*x86_64.AppImage` file: https://github.com/qTox/qTox/blob/04a9bc46f4513a4c01138cd3adcad6c51938b756/appimage/build.sh#L60-L63

2019-07-10 21:55 UTC, sudden6 commented
> Nope, no idea what's wrong with Travis-CI, never had it stop tracking a PR before.

I had, only solution I came up with was to copy the branch and open a new PR with it. Close and re-open didn't work.

In this case though it may be because of the merge conflict github displays for `widget.h`.

@nurupo Do you want to finish the review of this PR? Then I would merge it as soon as you give the lgtm

@antony-jr I tried to test like you said, but with `qTox-ae9511d793e027959e6c111d33e0a96cb4479126-x86_64.AppImage` (build: https://travis-ci.org/antony-jr/qTox-PR5690/builds/556860435) from your repository, the update available button doesn't show up.

2019-07-10 22:09 UTC, nurupo commented
>@nurupo Do you want to finish the review of this PR? Then I would merge it as soon as you give the lgtm

The only thing I'm reviewing is the bash script, well, apart from commenting on inconsistent code formatting / white space usage, which was also in CMakeLists.txt and the C++ code.

I'm relying on you to check everything else, e.g. that the C++ code makes sense and that you have looked into AppImageUpdaterBridge's code to make sure it can't hijack updates, for example.

>In this case though it may be because of the merge conflict github displays for widget.h.

Not sure if a merge conflict would prevent Travis-CI from running, afterall Travis-CI doesn't need to be concerned with merge conflicts, it's supposed to run the code from the PR, not merge it with master and then run.

I have opened this thread https://travis-ci.community/t/travis-ci-stopped-tracking-building-a-pr/4159, maybe we could get BanzaiMan or someone else to look into this.

2019-07-11 01:22 UTC, antony-jr commented
> @antony-jr I tried to test like you said, but with qTox-ae9511d793e027959e6c111d33e0a96cb4479126-x86_64.AppImage (build: https://travis-ci.org/antony-jr/qTox-PR5690/builds/556860435) from your repository, the update available button doesn't show up.

It takes a while to show up so wait up to 20 seconds(this is how the update check was designed, even without this lib it would take that much time because it has to do some http(s) requests). Did you echo some garbage data to differ the SHA1 hash between the local and the remote.

```
 $ echo "some garbage data" >> qTox-*-x86_64.AppImage
```

> AppImageUpdaterBridge's code to make sure it can't hijack updates

What does that mean? I don't get it. If you want to hijack the update then you have to change the update information using appimagetool which changes the SHA1 hash and GPG signs. But it can definitely update to a backdoor version of qTox(if the update information points to one) if you do that then **Its same as editing the source and redistributing with backdoor which would also change SHA1 hash and GPG signs.** 

For now I've a lot of ways to modify the official qTox(or any qt application for that matter) without touching the source or recompiling it but just adding a single plugin(which also loads automatically to any Qt application) to inject a key logging code(or even access the programs memory) which can also send that directly to my e-mail or a web server. **In conclusion, updates are not the only ones which can do harm to the program, there are limitless possibilities on attacking a Qt application without the update feature but if the user is little smart he/she could check the SHA256 hash or the GPG signs published on the official website or github(again this can be compromised too).**

2019-07-11 03:18 UTC, nurupo commented
>@nurupo What does that mean?

It means to make sure there is no backdoor in it. It's not meant to be a personal attack on you, it's just a security precaution.

>If you want to hijack the update then you have to change the update information using appimagetool which changes the SHA1 hash and GPG signs.

Or, for example, AppImageUpdaterBridge could just update itself to evilcorp.example/qTox.AppImage without doing any SHA1 or GPG verification what so ever.

>updates are not the only ones which can do harm to the program, there are limitless possibilities on attacking a Qt application

Of course they are not the only ones, no one is arguing otherwise. However, this doesn't mean that we shouldn't verify updater's code, or do you disagree with that?

2019-07-11 03:38 UTC, antony-jr commented
>  However, this doesn't mean that we shouldn't verify updater's code, or do you disagree with that?

I'm not discouraging you to check it but its rather a tedious work. At best its wise to monitor the network when the updater is running, this way you can tell what the updater actually does.

> Or, for example, AppImageUpdaterBridge could just update itself to evilcorp.example/qTox.AppImage without doing any SHA1 or GPG verification what so ever.

Yep. But even if it does that the SHA1 and GPG of the new evilcorp/qTox.AppImage will have different SHA256 hash than the one published on the website and github.

**Maybe as an extra precaution, make the users check the SHA256 and GPG signs of the newly created AppImage manually?**(But I can still assure you that the update will fail if the remote SHA1 and the newly created AppImage SHA1 does not match, its how the zsync algorithm works) But I can't save you if you distribute an AppImage with an update information pointing to evilcorp.com/qTox.AppImage

**So in conclusion, Do not mess with the update information, make sure you point it to the right location.**

>  It's not meant to be a personal attack on you, it's just a security precaution.

@nurupo Actually no offense was intended. Sorry if you got that wrong.

2019-07-13 11:16 UTC, antony-jr commented
@sudden6 I'm going to close this PR and then open a new one. This way the merge conflict and travis-ci should be fixed.(Also a lot of useless commits will also be gone).

2019-07-13 11:16 UTC, closed without merging