fix: bug with the program crash after invite in a group
qTox/qTox pull request #5693
Opened 2019-06-06 17:51 UTC by TriKriSta

- [ ] Commits follow our [git commit guidelines](https://github.com/qTox/qTox/blob/master/CONTRIBUTING.md#git-commit-guidelines)

2019-06-07 12:03 UTC, sudden6 commented
@anthonybilinski you could reliably reproduce this problem, can you review this PR?

2019-06-09 10:53 UTC, anthonybilinski requested changes
This does indeed fix 5570 for me. Fantastic!

> Reviewed 13 of 13 files at r1.
> *[Reviewable](https://reviewable.io/reviews/qtox/qtox/5693#-:-LgvRW0655SM07MmpQ3j:b-opts9a)* status: 0 of 1 LGTMs obtained

*[a discussion](https://reviewable.io/reviews/qtox/qtox/5693#-LgvqTnj1v3s-jgwV48e:-LgvqTnj1v3s-jgwV48f:b-gg0w6g) (no related file):*
Could you add some more detail to your commit messages? i.e. what the bugs were, how the changes fix them? The first line is limited in length, but think of that as the title. More detail can be added on further lines. It isn't obvious to me how this fixes the bug even after reviewing.

---
___
*[src/chatlog/chatlog.h, line 58 at r1](https://reviewable.io/reviews/qtox/qtox/5693#-LgvTdne1QzT_hRfOKqd:-LgvTdne1QzT_hRfOKqe:b-f2xu2b) ([raw file](https://github.com/qtox/qtox/blob/eb0d491961a075eff05745103301ed023ec3d810/src/chatlog/chatlog.h#L58)):*
> ```objc
>     void fontChanged(const QFont& font);
>     void reloadTheme();
>     void setShowed(const bool isShow);
> ```

some naming consistency would be good between setShowed, isShow, isShown, plus some grammar fixes.

isShown seems fine for the member, for the setter and getter either "show" and "hide" or "setShown", for the arg in setter "_isShown" could be used to avoid shadowing the member, "isShow" is grammatically incorrect.
___
*[src/chatlog/chatlog.h, line 101 at r1](https://reviewable.io/reviews/qtox/qtox/5693#-LgvnOh-BX79YPaGqmpj:-LgvnOh-BX79YPaGqmpk:b-xt92bs) ([raw file](https://github.com/qtox/qtox/blob/eb0d491961a075eff05745103301ed023ec3d810/src/chatlog/chatlog.h#L101)):*
> ```objc
>     void scrollToBottom();
>     void startResizeWorker();
>     void partialRefresh(const bool stickToBtm, int start = -1);
> ```

this function could be made private since it's only called from within t hen class itself.
___
*[src/chatlog/chatlog.cpp, line 465 at r1](https://reviewable.io/reviews/qtox/qtox/5693#-LgvpLMe0UBCrLYhADYn:-LgvpLMf5WzfYdFXljDF:bb4xhkz) ([raw file](https://github.com/qtox/qtox/blob/eb0d491961a075eff05745103301ed023ec3d810/src/chatlog/chatlog.cpp#L465)):*
> ```cpp
> }
> 
> void ChatLog::partialRefresh(const bool stickToBtm, int start)
> ```

it's not very obvious to me what "start" means in this API, I think "fromLine" would be read more clearly, e.g. "layout from line 5"
___
*[src/chatlog/chatlog.cpp, line 468 at r1](https://reviewable.io/reviews/qtox/qtox/5693#-Lgvp9IU2uyhzjGXK3Ny:-Lgvp9IU2uyhzjGXK3Nz:b-8r3zul) ([raw file](https://github.com/qtox/qtox/blob/eb0d491961a075eff05745103301ed023ec3d810/src/chatlog/chatlog.cpp#L468)):*
> ```cpp
> {
>     if (start == -1) {
>         start = lines.last()->getRow();
> ```

instead of passing in -1 and using lines.last()->getRow(), can you just pass in lines.last()->getRow() directly? that way the confusing magic -1 value doesn't need to be used.
___
*[src/core/contactid.h, line 29 at r1](https://reviewable.io/reviews/qtox/qtox/5693#-LgvhfBt2pr7dk_3npVi:-LgvhfBt2pr7dk_3npVj:b-og26k8) ([raw file](https://github.com/qtox/qtox/blob/eb0d491961a075eff05745103301ed023ec3d810/src/core/contactid.h#L29)):*
> ```objc
>     bool isEmpty() const;
>     virtual int getSize() const = 0;
>     virtual Type type() const = 0;
> ```

An interface (ContactId) should be able to be used generically, regardless of its derived class . Asking ContactId "what are you, _really?_" defeats the purpose of using ContactId.

I see that in Widget you want to know the type of the contact since our friend chatforms and group chatforms are stored separately, but you can accomplish the same thing (Widget knowing the last open chatform) by having Widget remember the last used chatform, instead of by adding type() to ContactId.
___
*[src/core/groupid.h, line 16 at r1](https://reviewable.io/reviews/qtox/qtox/5693#-LgvlGgi5Fw8BH3XRneG:-LgvlGgi5Fw8BH3XRneH:bb7od0r) ([raw file](https://github.com/qtox/qtox/blob/eb0d491961a075eff05745103301ed023ec3d810/src/core/groupid.h#L16)):*
> ```objc
>     explicit GroupId(const uint8_t* rawId);
>     int getSize() const override;
>     Type type() const override final;
> ```

same
___
*[src/core/groupid.cpp, line 63 at r1](https://reviewable.io/reviews/qtox/qtox/5693#-LgvlHqTB9qfPe5F5Rea:-LgvlHqTB9qfPe5F5Reb:bb7od0r) ([raw file](https://github.com/qtox/qtox/blob/eb0d491961a075eff05745103301ed023ec3d810/src/core/groupid.cpp#L63)):*
> ```cpp
> }
> 
> ContactId::Type GroupId::type() const
> ```

same
___
*[src/core/toxpk.h, line 16 at r1](https://reviewable.io/reviews/qtox/qtox/5693#-LgvlIau27H0fN3DpI2Z:-LgvlIau27H0fN3DpI2_:bb7od0r) ([raw file](https://github.com/qtox/qtox/blob/eb0d491961a075eff05745103301ed023ec3d810/src/core/toxpk.h#L16)):*
> ```objc
>     explicit ToxPk(const uint8_t* rawId);
>     int getSize() const override;
>     Type type() const override final;
> ```

same
___
*[src/core/toxpk.cpp, line 63 at r1](https://reviewable.io/reviews/qtox/qtox/5693#-LgvlJMZ2gpvTbuHioO4:-LgvlJMZ2gpvTbuHioO5:bb7od0r) ([raw file](https://github.com/qtox/qtox/blob/eb0d491961a075eff05745103301ed023ec3d810/src/core/toxpk.cpp#L63)):*
> ```cpp
> }
> 
> ContactId::Type ToxPk::type() const
> ```

same
___
*[src/widget/widget.h, line 330 at r1](https://reviewable.io/reviews/qtox/qtox/5693#-LgvnYDu4C00O4Ko1kE7:-LgvnYDu4C00O4Ko1kE8:b-ffa6qn) ([raw file](https://github.com/qtox/qtox/blob/eb0d491961a075eff05745103301ed023ec3d810/src/widget/widget.h#L330)):*
> ```objc
>     Core* core = nullptr;
> 
>     ContactId *currentId{nullptr};
> ```

could be changed to a GenericChatForm*? see below.
___
*[src/widget/widget.cpp, line 535 at r1](https://reviewable.io/reviews/qtox/qtox/5693#-Lgviwfl5gLA6GXz7EBi:-Lgviwfm7MAwbHPxoIQR:b-dvlbo5) ([raw file](https://github.com/qtox/qtox/blob/eb0d491961a075eff05745103301ed023ec3d810/src/widget/widget.cpp#L535)):*
> ```cpp
> 
>     if (currentId != nullptr) {
>         delete currentId;
> ```

avoid manual memory management (new, delete). Use either smart pointers like std::unique_ptr, or references to reduce common bugs like memory leaks.
___
*[src/widget/widget.cpp, line 1216 at r1](https://reviewable.io/reviews/qtox/qtox/5693#-Lgvm0AfDIYEfJ8UYtV2:-Lgvm0AfDIYEfJ8UYtV3:bjiwjxe) ([raw file](https://github.com/qtox/qtox/blob/eb0d491961a075eff05745103301ed023ec3d810/src/widget/widget.cpp#L1216)):*
> ```cpp
>         hideMainForms(widget);
> 
>         if (currentId != nullptr) {
> ```

isn't really what you want here is to know the current chatform that is visible, so you get setShown(false) on the old one, and setShown(true) on the new one? If so can you just store `GenericChatForm* currentForm` as a member, then here instead of checking type, just `currentForm->setShown(false)` and `form->setShown(true)`?
___
*[src/widget/widget.cpp, line 1217 at r1](https://reviewable.io/reviews/qtox/qtox/5693#-LgvmfKZ0SReJaZpodH9:-LgvmfKZ0SReJaZpodHA:bwwg2s1) ([raw file](https://github.com/qtox/qtox/blob/eb0d491961a075eff05745103301ed023ec3d810/src/widget/widget.cpp#L1217)):*
> ```cpp
> 
>         if (currentId != nullptr) {
>             if (currentId->type() == ContactId::Friend) {
> ```

generally if you have a chunk of code like this serving a particular purpose, it's a good candidate to split into its own function, even if it's only used once. If my above comment is true, that may not be necessary since it could be reduced to 2 lines.
___
*[src/widget/form/genericchatform.h, line 87 at r1](https://reviewable.io/reviews/qtox/qtox/5693#-Lgvh0noEkEPao03EWbt:-Lgvh0noEkEPao03EWbu:b-i0nvu8) ([raw file](https://github.com/qtox/qtox/blob/eb0d491961a075eff05745103301ed023ec3d810/src/widget/form/genericchatform.h#L87)):*
> ```objc
>     QDateTime getLatestTime() const;
>     QDateTime getFirstTime() const;
>     void setShowed(const bool isShow);
> ```

setShown, _isShown
___
*[src/widget/form/genericchatform.cpp, line 298 at r1](https://reviewable.io/reviews/qtox/qtox/5693#-Lgvh7jF8DIivv7sCqxC:-Lgvh7jF8DIivv7sCqxD:b-i0nvu8) ([raw file](https://github.com/qtox/qtox/blob/eb0d491961a075eff05745103301ed023ec3d810/src/wi [...]

2019-06-09 10:56 UTC, anthonybilinski requested changes
> *[Reviewable](https://reviewable.io/reviews/qtox/qtox/5693)* status: 0 of 1 LGTMs obtained

*[a discussion](https://reviewable.io/reviews/qtox/qtox/5693#-LgvsKVu6lC9kxuv-3UU:-LgvsKVu6lC9kxuv-3UV:bw0pozr) (no related file):*
For the ticket fix message, github seems to only pick up on it in the commit message instead of in the PR title. Could you add the "Fix #5570" into the commit message so that it automatically links to that issue?

---


<!-- Sent from Reviewable.io -->

2019-06-09 14:27 UTC, TriKriSta reviewed
> *[Reviewable](https://reviewable.io/reviews/qtox/qtox/5693)* status: 0 of 1 LGTMs obtained

*[a discussion](https://reviewable.io/reviews/qtox/qtox/5693#-LgvqTnj1v3s-jgwV48e:-Lgwc_UWCG9h9oomSesG:b-896fix) (no related file):*
<details><summary><i>Previously, anthonybilinski (Anthony Bilinski) wrote…</i></summary><blockquote>

Could you add some more detail to your commit messages? i.e. what the bugs were, how the changes fix them? The first line is limited in length, but think of that as the title. More detail can be added on further lines. It isn't obvious to me how this fixes the bug even after reviewing.
</blockquote></details>

Done.

---
*[a discussion](https://reviewable.io/reviews/qtox/qtox/5693#-LgvsKVu6lC9kxuv-3UU:-LgwcZmj6CnfCul_kMxO:b-896fix) (no related file):*
<details><summary><i>Previously, anthonybilinski (Anthony Bilinski) wrote…</i></summary><blockquote>

For the ticket fix message, github seems to only pick up on it in the commit message instead of in the PR title. Could you add the "Fix #5570" into the commit message so that it automatically links to that issue?
</blockquote></details>

Done.

---
___
*[src/chatlog/chatlog.h, line 58 at r1](https://reviewable.io/reviews/qtox/qtox/5693#-LgvTdne1QzT_hRfOKqd:-LgwcatK0GOJkHP2d3_r:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/eb0d491961a075eff05745103301ed023ec3d810/src/chatlog/chatlog.h#L58)):*
<details><summary><i>Previously, anthonybilinski (Anthony Bilinski) wrote…</i></summary><blockquote>

some naming consistency would be good between setShowed, isShow, isShown, plus some grammar fixes.

isShown seems fine for the member, for the setter and getter either "show" and "hide" or "setShown", for the arg in setter "_isShown" could be used to avoid shadowing the member, "isShow" is grammatically incorrect.
</blockquote></details>

Done.
___
*[src/chatlog/chatlog.h, line 101 at r1](https://reviewable.io/reviews/qtox/qtox/5693#-LgvnOh-BX79YPaGqmpj:-LgwcDgP193DrAj4kWc1:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/eb0d491961a075eff05745103301ed023ec3d810/src/chatlog/chatlog.h#L101)):*
<details><summary><i>Previously, anthonybilinski (Anthony Bilinski) wrote…</i></summary><blockquote>

this function could be made private since it's only called from within t hen class itself.
</blockquote></details>

Done.
___
*[src/chatlog/chatlog.cpp, line 465 at r1](https://reviewable.io/reviews/qtox/qtox/5693#-LgvpLMe0UBCrLYhADYn:-LgwcFbNB1fCijfEJFW3:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/eb0d491961a075eff05745103301ed023ec3d810/src/chatlog/chatlog.cpp#L465)):*
<details><summary><i>Previously, anthonybilinski (Anthony Bilinski) wrote…</i></summary><blockquote>

it's not very obvious to me what "start" means in this API, I think "fromLine" would be read more clearly, e.g. "layout from line 5"
</blockquote></details>

Done.
___
*[src/chatlog/chatlog.cpp, line 468 at r1](https://reviewable.io/reviews/qtox/qtox/5693#-Lgvp9IU2uyhzjGXK3Ny:-LgwcFAlDcNlAJBjHJGX:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/eb0d491961a075eff05745103301ed023ec3d810/src/chatlog/chatlog.cpp#L468)):*
<details><summary><i>Previously, anthonybilinski (Anthony Bilinski) wrote…</i></summary><blockquote>

instead of passing in -1 and using lines.last()->getRow(), can you just pass in lines.last()->getRow() directly? that way the confusing magic -1 value doesn't need to be used.
</blockquote></details>

Done.
___
*[src/core/contactid.h, line 29 at r1](https://reviewable.io/reviews/qtox/qtox/5693#-LgvhfBt2pr7dk_3npVi:-LgwcJ_XEFHRavLo190_:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/eb0d491961a075eff05745103301ed023ec3d810/src/core/contactid.h#L29)):*
<details><summary><i>Previously, anthonybilinski (Anthony Bilinski) wrote…</i></summary><blockquote>

An interface (ContactId) should be able to be used generically, regardless of its derived class . Asking ContactId "what are you, _really?_" defeats the purpose of using ContactId.

I see that in Widget you want to know the type of the contact since our friend chatforms and group chatforms are stored separately, but you can accomplish the same thing (Widget knowing the last open chatform) by having Widget remember the last used chatform, instead of by adding type() to ContactId.
</blockquote></details>

Done.
___
*[src/core/groupid.h, line 16 at r1](https://reviewable.io/reviews/qtox/qtox/5693#-LgvlGgi5Fw8BH3XRneG:-LgwcKU0E6LMf-0Z2V0s:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/eb0d491961a075eff05745103301ed023ec3d810/src/core/groupid.h#L16)):*
<details><summary><i>Previously, anthonybilinski (Anthony Bilinski) wrote…</i></summary><blockquote>

same
</blockquote></details>

Done.
___
*[src/core/groupid.cpp, line 63 at r1](https://reviewable.io/reviews/qtox/qtox/5693#-LgvlHqTB9qfPe5F5Rea:-LgwcL6--necBtjjaGOu:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/eb0d491961a075eff05745103301ed023ec3d810/src/core/groupid.cpp#L63)):*
<details><summary><i>Previously, anthonybilinski (Anthony Bilinski) wrote…</i></summary><blockquote>

same
</blockquote></details>

Done.
___
*[src/core/toxpk.h, line 16 at r1](https://reviewable.io/reviews/qtox/qtox/5693#-LgvlIau27H0fN3DpI2Z:-LgwcLiw9s0A_xgTt-HF:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/eb0d491961a075eff05745103301ed023ec3d810/src/core/toxpk.h#L16)):*
<details><summary><i>Previously, anthonybilinski (Anthony Bilinski) wrote…</i></summary><blockquote>

same
</blockquote></details>

Done.
___
*[src/core/toxpk.cpp, line 63 at r1](https://reviewable.io/reviews/qtox/qtox/5693#-LgvlJMZ2gpvTbuHioO4:-LgwcMLa6ioDFHljNOOE:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/eb0d491961a075eff05745103301ed023ec3d810/src/core/toxpk.cpp#L63)):*
<details><summary><i>Previously, anthonybilinski (Anthony Bilinski) wrote…</i></summary><blockquote>

same
</blockquote></details>

Done.
___
*[src/widget/widget.h, line 330 at r1](https://reviewable.io/reviews/qtox/qtox/5693#-LgvnYDu4C00O4Ko1kE7:-LgwcNZo8N0eqIypcjIM:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/eb0d491961a075eff05745103301ed023ec3d810/src/widget/widget.h#L330)):*
<details><summary><i>Previously, anthonybilinski (Anthony Bilinski) wrote…</i></summary><blockquote>

could be changed to a GenericChatForm*? see below.
</blockquote></details>

Done.
___
*[src/widget/widget.cpp, line 535 at r1](https://reviewable.io/reviews/qtox/qtox/5693#-Lgviwfl5gLA6GXz7EBi:-LgwcOfK8jQbNsedrj7A:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/eb0d491961a075eff05745103301ed023ec3d810/src/widget/widget.cpp#L535)):*
<details><summary><i>Previously, anthonybilinski (Anthony Bilinski) wrote…</i></summary><blockquote>

avoid manual memory management (new, delete). Use either smart pointers like std::unique_ptr, or references to reduce common bugs like memory leaks.
</blockquote></details>

Done.
___
*[src/widget/widget.cpp, line 1216 at r1](https://reviewable.io/reviews/qtox/qtox/5693#-Lgvm0AfDIYEfJ8UYtV2:-LgwcQJ315erxUVtmuVa:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/eb0d491961a075eff05745103301ed023ec3d810/src/widget/widget.cpp#L1216)):*
<details><summary><i>Previously, anthonybilinski (Anthony Bilinski) wrote…</i></summary><blockquote>

isn't really what you want here is to know the current chatform that is visible, so you get setShown(false) on the old one, and setShown(true) on the new one? If so can you just store `GenericChatForm* currentForm` as a member, then here instead of checking type, just `currentForm->setShown(false)` and `form->setShown(true)`?
</blockquote></details>

Done.
___
*[src/widget/widget.cpp, line 1217 at r1](https://reviewable.io/reviews/qtox/qtox/5693#-LgvmfKZ0SReJaZpodH9:-LgwcQoK9wh5LfBR88M_:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/eb0d491961a075eff05745103301ed023ec3d810/src/widget/widget.cpp#L1217)):*
<details><summary><i>Previously, anthonybilinski (Anthony Bilinski) wrote…</i></summary><blockquote>

generally if you have a chunk of code like this serving a particular [...]

2019-06-11 08:38 UTC, anthonybilinski requested changes
> Reviewed 11 of 11 files at r2.
> *[Reviewable](https://reviewable.io/reviews/qtox/qtox/5693)* status: 0 of 1 LGTMs obtained

*[a discussion](https://reviewable.io/reviews/qtox/qtox/5693#-LgvqTnj1v3s-jgwV48e:-Lh4YEwcE2W4j8fJ7djO:b-2c53b6) (no related file):*
<details><summary><i>Previously, TriKriSta wrote…</i></summary><blockquote>

Done.
</blockquote></details>

I don't see any more information in the commit messages. The only functional change I see in this PR is that layout of the chatlog is not updated on new message when it's not present, and that the entire chatlog is laid out once it's shown. With a commit message like "fix: bug with the program crash after invite in a group" I don't understand what the bug was or how it was fixed.

Note that you can update existing commit messages without having to add new commits in git using `git rebase -i HEAD~3` (for last 3 commits), changing "pick" to "reword", then modifying the commit message. More info: https://stackoverflow.com/questions/179123/how-to-modify-existing-unpushed-commit-messages

---
*[a discussion](https://reviewable.io/reviews/qtox/qtox/5693#-Lh4d72u3ICh5ZzFiTZ9:-Lh4d72u3ICh5ZzFiTZA:b2csvxc) (no related file):*
With this change I no longer hit https://github.com/qTox/qTox/issues/5570 when clicking a group, but I now sometimes hit the same bug wit the same backtrace when clicking on a friend:
```
Thread 1 "qtox" hit Catchpoint 1 (signal SIGSEGV), 0x00007ffff4e82a05 in ?? () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
(gdb) bt
#0  0x00007ffff4e82a05 in  () at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#1  0x00007ffff4e82b23 in  () at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#2  0x00007ffff4e0e79f in QWidgetPrivate::inheritStyle() () at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#3  0x00007ffff4e1eea8 in QWidget::setParent(QWidget*, QFlags<Qt::WindowType>) () at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#4  0x00007ffff4dfc33b in QLayout::addChildWidget(QWidget*) () at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#5  0x00007ffff4dfc34f in QLayout::addWidget(QWidget*) () at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#6  0x00005555558f4bce in GenericChatForm::show(ContentLayout*) (this=0x555557f4dff0, contentLayout=0x5555565e6670)
    at /home/abilinski/builds/qTox/src/widget/form/genericchatform.cpp:330
#7  0x0000555555800018 in Widget::openDialog(GenericChatroomWidget*, bool) (this=0x555555fe3220, widget=0x555557c495f0, newWindow=false)
    at /home/abilinski/builds/qTox/src/widget/widget.cpp:1214
#8  0x00005555557ffbf7 in Widget::onChatroomWidgetClicked(GenericChatroomWidget*) (this=0x555555fe3220, widget=0x555557c495f0)
    at /home/abilinski/builds/qTox/src/widget/widget.cpp:1151
#9  0x000055555581ff76 in QtPrivate::FunctorCall<QtPrivate::IndexesList<0>, QtPrivate::List<GenericChatroomWidget*>, void, void (Widget::*)(GenericChatroomWidget*)>::call(void (Widget::*)(GenericChatroomWidget*), Widget*, void**) (f=
    (void (Widget::*)(class Widget * const, class GenericChatroomWidget *)) 0x5555557ffbc0 <Widget::onChatroomWidgetClicked(GenericChatroomWidget*)>, o=0x555555fe3220, arg=0x7fffffffcef0) at /usr/include/x86_64-linux-gnu/qt5/QtCore/qobjectdefs_impl.h:152
#10 0x000055555581df51 in QtPrivate::FunctionPointer<void (Widget::*)(GenericChatroomWidget*)>::call<QtPrivate::List<GenericChatroomWidget*>, void>(void (Widget::*)(GenericChatroomWidget*), Widget*, void**) (f=
    (void (Widget::*)(class Widget * const, class GenericChatroomWidget *)) 0x5555557ffbc0 <Widget::onChatroomWidgetClicked(GenericChatroomWidget*)>, o=0x555555fe3220, arg=0x7fffffffcef0) at /usr/include/x86_64-linux-gnu/qt5/QtCore/qobjectdefs_impl.h:185
#11 0x000055555581a707 in QtPrivate::QSlotObject<void (Widget::*)(GenericChatroomWidget*), QtPrivate::List<GenericChatroomWidget*>, void>::impl(int, QtPrivate::QSlotObjectBase*, QObject*, void**, bool*) (which=1, this_=0x55555808cbf0, r=0x555555fe3220, a=0x7fffffffcef0, ret=0x0)
    at /usr/include/x86_64-linux-gnu/qt5/QtCore/qobjectdefs_impl.h:414
#12 0x00007ffff4442563 in QMetaObject::activate(QObject*, int, int, void**) () at /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#13 0x0000555555843a5c in GenericChatroomWidget::chatroomWidgetClicked(GenericChatroomWidget*) (this=0x555557c495f0, _t1=0x555557c495f0)
    at /home/abilinski/builds/qTox/_build/qtox_static_autogen/WFD7YQQOTJ/moc_genericchatroomwidget.cpp:269
#14 0x000055555595df96 in GenericChatroomWidget::mouseReleaseEvent(QMouseEvent*) (this=0x555557c495f0, event=0x7fffffffd160)
    at /home/abilinski/builds/qTox/src/widget/genericchatroomwidget.cpp:190
#15 0x00007ffff4e1db58 in QWidget::event(QEvent*) () at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#16 0x00007ffff4ec26ce in QFrame::event(QEvent*) () at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#17 0x00007ffff4dde551 in QApplicationPrivate::notify_helper(QObject*, QEvent*) () at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#18 0x00007ffff4de5b77 in QApplication::notify(QObject*, QEvent*) () at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#19 0x00007ffff44188e9 in QCoreApplication::notifyInternal2(QObject*, QEvent*) () at /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#20 0x00007ffff4de4ebf in QApplicationPrivate::sendMouseEvent(QWidget*, QMouseEvent*, QWidget*, QWidget*, QWidget**, QPointer<QWidget>&, bool, bool) () at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#21 0x00007ffff4e3857b in  () at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#22 0x00007ffff4e3b53f in  () at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#23 0x00007ffff4dde551 in QApplicationPrivate::notify_helper(QObject*, QEvent*) () at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#24 0x00007ffff4de5930 in QApplication::notify(QObject*, QEvent*) () at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#25 0x00007ffff44188e9 in QCoreApplication::notifyInternal2(QObject*, QEvent*) () at /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#26 0x00007ffff47eec6c in QGuiApplicationPrivate::processMouseEvent(QWindowSystemInterfacePrivate::MouseEvent*) () at /usr/lib/x86_64-linux-gnu/libQt5Gui.so.5
#27 0x00007ffff47f0075 in QGuiApplicationPrivate::processWindowSystemEvent(QWindowSystemInterfacePrivate::WindowSystemEvent*) () at /usr/lib/x86_64-linux-gnu/libQt5Gui.so.5
#28 0x00007ffff47ca05b in QWindowSystemInterface::sendWindowSystemEvents(QFlags<QEventLoop::ProcessEventsFlag>) () at /usr/lib/x86_64-linux-gnu/libQt5Gui.so.5
#29 0x00007fffe557767a in  () at /usr/lib/x86_64-linux-gnu/libQt5XcbQpa.so.5
#30 0x00007ffff5d66aae in g_main_context_dispatch () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#31 0x00007ffff5d66d48 in  () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#32 0x00007ffff5d66ddc in g_main_context_iteration () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#33 0x00007ffff446c047 in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () at /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#34 0x00007ffff44175bb in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () at /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#35 0x00007ffff441f5e2 in QCoreApplication::exec() () at /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#36 0x000055555574deb3 in main(int, char**) (argc=3, argv=0x7fffffffdf58) at /home/abilinski/builds/qTox/src/main.cpp:379
```

This makes me think the underlying issue wasn't fixed, but maybe some order of execution, timing, or memory layout changed from your PR, which changed when the issue occurs. What do you think the root cause of the issue is? Why do you think this PR fixes it?

---
___
*[src/widget/widget.h, line 330 at r1](https://reviewable.io/reviews/qtox/qtox/5693#-LgvnYDu4C00O4Ko1kE7:-Lh4TeJTAbZVJnDj2ETr:b7x2j7v) ([raw file](https://github.com/qtox/qtox/blob/eb0d491961a075eff05745103301ed023ec3d810/src/widget/widget.h#L330)):*
<details><summary><i>Previously, TriKriSta wrote…</i></summary><blockquote>

Done.
</blockquote></details>

my  comments are getting a bit out of scope since this is existing code, but generally std::shared_ptr should only be used in case [...]

2019-06-12 14:24 UTC, TriKriSta reviewed
> *[Reviewable](https://reviewable.io/reviews/qtox/qtox/5693)* status: 0 of 1 LGTMs obtained

*[a discussion](https://reviewable.io/reviews/qtox/qtox/5693#-LgvqTnj1v3s-jgwV48e:-LhB3BlA7bP2zfK55h0f:bcpwc6v) (no related file):*
<details><summary><i>Previously, anthonybilinski (Anthony Bilinski) wrote…</i></summary><blockquote>

I don't see any more information in the commit messages. The only functional change I see in this PR is that layout of the chatlog is not updated on new message when it's not present, and that the entire chatlog is laid out once it's shown. With a commit message like "fix: bug with the program crash after invite in a group" I don't understand what the bug was or how it was fixed.

Note that you can update existing commit messages without having to add new commits in git using `git rebase -i HEAD~3` (for last 3 commits), changing "pick" to "reword", then modifying the commit message. More info: https://stackoverflow.com/questions/179123/how-to-modify-existing-unpushed-commit-messages
</blockquote></details>

I changed the type of committee from fix to feat

---
___
*[src/widget/widget.h, line 330 at r1](https://reviewable.io/reviews/qtox/qtox/5693#-LgvnYDu4C00O4Ko1kE7:-LhB3Hi-56kHYztVDlzx:b-nv73r6) ([raw file](https://github.com/qtox/qtox/blob/eb0d491961a075eff05745103301ed023ec3d810/src/widget/widget.h#L330)):*
<details><summary><i>Previously, anthonybilinski (Anthony Bilinski) wrote…</i></summary><blockquote>

my  comments are getting a bit out of scope since this is existing code, but generally std::shared_ptr should only be used in cases where it's not clear who owns the resource, so it's not clear when it will stop existing. If there is a clear owner, std::unique_ptr allows that owner to control the lifetime of the resource, and hand out raw pointers from that unique pointer to users of the resource that it knows will only exist for the time that the unique_ptr is valid.

The two maps of `chatForms` and `groupChatForms` both create, own, and delete their forms, so should really be holding unique_ptrs, and currentForm could be a raw underlying pointer from the std::unique_ptr with .get(), because it's guaranteed Widget's form map will outlive currentForm's use. This then shows clearly that the map owns the form, and the currentForm is only pointing to those forms, instead of with std::shared_ptr where it appears that both the map and currentForm share ownership and that either could be the last reference, which isn't really true.

This isn't a mandatory change, just a note. If you don't feel like changing it I'll add a clean-up commit on top before merge :P
</blockquote></details>

if I will use std::unique_ptr how will I know what the current chat was deleted? 
___
*[src/widget/form/genericchatform.h, line 87 at r2](https://reviewable.io/reviews/qtox/qtox/5693#-Lh4Wpfc3n6S-Y12_i8z:-LhB2xVc9QQk6k-XQ7Nm:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/575daa739309d253e6ee1535876e85849034e207/src/widget/form/genericchatform.h#L87)):*
<details><summary><i>Previously, anthonybilinski (Anthony Bilinski) wrote…</i></summary><blockquote>

isShow -> isShown
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2019-06-18 21:15 UTC, TriKriSta commented
@Kribylet #5697 is had in only this branch or in master too?

2019-06-26 10:34 UTC, Kribylet commented
At the time of writing #5697 was present in master and in this PR. I am unable to check again now because this PR doesn't cleanly rebase onto the master.

2019-07-03 08:34 UTC, sudden6 commented
@anthonybilinski is this PR made obsolete by your fix in #5730 ?

2019-07-03 09:54 UTC, anthonybilinski commented
From my testing this didn't prevent the crash, just changed when it occurred. #5730 seems to avoid the crash in all cases for me at least.

In a private chat with @TriKriSta he mentioned this could still be useful as performance optimization since it saves updating the GUI for chatlogs that aren't selected. I'm not sure if this is really a savings if the chatforms have to then be updated when they're selected - are we just postponing background work for when the user clicks a chat? If so that seems like it would increase UI delay? @TriKriSta do you think this still has merit if the crash is already worked around? Can you explain how?

2019-07-03 10:07 UTC, sudden6 commented
If it prevents needless UI updates for unselected chatlogs it might make sense, e.g. only the last refresh is then done when selecting the chatlog. If all updates then have to be applied when the chatlog becomes visible I see no point.

2019-07-03 10:21 UTC, TriKriSta commented
Only current chat is updated in this branch. here all updates then don't have to be applied.
also, this branch forbid scrolling notcurrent chat, and then you return in chat you get to the place where you finished reading, not to the end.
but I need to check it, after merge #5672 because they have conflicts.

2019-09-06 11:11 UTC, Chiitoo commented
I don't see this mentioned yet (might easily have missed it), but while this seems to fix the "large enough blocks of text will not be automatically scrolled to the end of the message" issue, such blocks will "cover" the current date area until another message is entered.

2019-09-06 13:58 UTC, Chiitoo commented
Screenshot of the date issue as requested by sudd3n6 (dark theme with its own issues here highlights this one nicely(?)).

This is with Qt 5.13.1 (git 5.13 branch master).

From top to bottom:

1. Normal status, with some messages sent, including on "two-liner".
2. Message with enough of newlines that top up the view.
3. Chat scrolled a bit triggers the date to return.

![2019-09-06-qtox_chatform_issue-01](https://user-images.githubusercontent.com/9367616/64433300-d9577400-d0c6-11e9-9048-e94c2c1e0f30.png)

2019-09-06 14:41 UTC, TriKriSta commented
@Chiitoo maybe pull request what fixed the problem with scrolling was merge in only v1.17-dev branch.
Can you check branch v1.17-dev?

2019-09-06 18:15 UTC, anthonybilinski commented
`v1.17-dev` is being merged back to `master` routinely. Currently there are no changes in `v1.17-dev` not in `master`, but it is good to make sure @Chiitoo is running past badef48c3a860c391439d0f82718d8acf10f252e on `v1.17-dev` or 8a210d524bb14df4e59f7df543e1f8e8f6594ffa on master, to include https://github.com/qTox/qTox/pull/5777

2019-09-06 19:42 UTC, TriKriSta commented
@Chiitoo If do you mean problem with hidden current date after send big message? this problem isn't this pull request

2019-09-06 21:20 UTC, sudden6 commented
It could be that the date hiding issue was masked by the bug where auto scrolling is broken, since without this PR the message hiding the date doesn't scroll enough.

2019-09-06 21:29 UTC, Chiitoo commented
I was adding these change on top of the current git master, though yeah, trying it just now, I /can/ make it happen with current master only, too, but it's not as easy indeed.  Not entirely sure what triggers it and when (so indeed, certainly not caused by this PR itself).

2019-09-06 21:32 UTC, Chiitoo commented
(At the time of writing, git master being at 8a210d52.)

2019-09-06 21:50 UTC, TriKriSta commented
but the master branch has the same bug.
and with perfect behavior, the current date should not be displayed

2019-09-06 21:56 UTC, sudden6 commented
>  and with perfect behavior, the current date should not be displayed

Huh? I thought that's intentional that the current date is floating always at the top?

2019-09-06 21:59 UTC, sudden6 approved these changes
After testing this seems to fix auto scrolling as promised and the bug with the date seems to be only uncovered and not caused by this, so <img class="emoji" title=":lgtm_strong:" alt=":lgtm_strong:" align="absmiddle" src="https://reviewable.io/lgtm_strong.png" height="20" width="61"/> 

> Reviewed 8 of 13 files at r3.
> *[Reviewable](https://reviewable.io/reviews/qtox/qtox/5693#-:-Lo7_Xac4jzf-f5dBRRf:b9w1wf4)* status: :shipit: complete! 1 of 1 LGTMs obtained



<!-- Sent from Reviewable.io -->

2019-09-06 22:00 UTC, TriKriSta commented
if you start a chat where there were no messages for the current date, you will not see the current date on top. you will see it only after restart program

2019-09-06 22:05 UTC, sudden6 commented
> if you start a chat where there were no messages for the current date, you will not see the current date on top. you will see it only after restart program

ah ok, this seems like a rather minor bug tho.

2019-10-11 11:30 UTC, Chiitoo commented
/poke

Aside from the conflicts, what's the status here?

2019-10-11 12:35 UTC, anthonybilinski commented
1. sorry for leaving this for so long - I'll rebase and resolve the merge conflicts.
2. the bug fix of auto-scrolling seems mixed in with other changes, for v1.17 release, it would be best if the bug fix could be by itself with as little impact on other parts as possible.
    1. for example, changing the behaviour of opening a chat (before: chat opened at the same scroll position, now: chat opens at the bottom). I don't think this is a desirable change, and also seems unrelated to the scroll issue.
    2. the whole concept of not updating the GUI when the chat isn't shown also seems unrelated to the scroll issue - but is maybe a good idea? I don't think Qt would do any GUI updating when the pane isn't shown anyway, but it might save us some layout work? If this has a good reason to be changed, I think it should be part of a change separate from scroll bugfix.

I'd rather not merge to the release branch as is, since the widespread changes could introduce new bugs - but we definitely need the scroll fix for the release. @TriKriSta could you try to isolate the scroll fix with as few other changes as possible, and submit that as a purely bugfix PR? Then not updating the GUI when the chatform isn't selected, and scrolling to the bottom of the chat each time it's opened can be justified and continue on this PR?

I'll rebase this change in the next couple of days so that you don't have to deal with all the merge conflicts that have been created by this being stuck for so long.

2019-10-11 12:47 UTC, TriKriSta commented
Ok, I will isolate the scroll fix. But I can do it no earlier than Tuesday

2019-10-11 12:54 UTC, anthonybilinski commented
Thanks :). I've rebased your branch to master tip.

2019-10-12 19:33 UTC, anthonybilinski commented
I closed and re-opened the PR to workaround a Travis CI issue.

2019-10-15 10:54 UTC, TriKriSta commented
I created a fix pull request (#5889)

2019-12-02 22:30 UTC, closed without merging