fix(offlinemsg): Fix offline message dispatching on history load
qTox/qTox pull request #5735
Opened 2019-07-01 07:24 UTC by sphaerophoria

Fixes #5734 

I apologize, this path had several bugs. I remember testing this case but I either touched the code more since then or just remembered incorrectly.

Fixes are
* Fix callback hookup order in ChatHistory
* Add correct call to SessionChatLog to insert an unfinished message
* Fix incorrect logic in parsing History database response

2019-07-01 17:33 UTC, sudden6 commented
Do you think it would be possible to add a test case so that this won't happen again?

2019-07-01 17:55 UTC, sphaerophoria commented
Yeah I was thinking about that. I wouldn't want to mock History I think, since that's where a lot of the bug potential could come from. I think the easiest thing to do would be to alter RawDatabase to somehow let us work with a database in ram that we can seed with whatever we want. I'm not sure if our sql lib allows that though.

2019-07-01 20:47 UTC, Diadlo requested changes
I don't understand, why you don't want to mock `History`? Because it can be the root of some bugs? If so, it doesn't matter for `ChatHistory` test. But how to test `History` it's interesting question

> Reviewed 4 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/qtox/qtox/5735#-:-LijHCQj06AyZRXx0djG:b-e6pise)* status: 0 of 1 LGTMs obtained

___
*[src/model/chathistory.cpp, line 385 at r1](https://reviewable.io/reviews/qtox/qtox/5735#-LijGZ1XE5TvStXzugVY:-LijGZ1Y3SiGgmuYBBob:b55mdq9) ([raw file](https://github.com/qtox/qtox/blob/dc25183bffede1469a199f871281d6568da0e5fb/src/model/chathistory.cpp#L385)):*
> ```cpp
> 
>             if (isComplete) {
>                 auto chatLogMessage = ChatLogMessage{true, processedMessage};
> ```

Looks like the first line of `if` and `else` are the ~same
`auto chatLogMessage = ChatLogMessage{isComplete, processedMessage};`


<!-- Sent from Reviewable.io -->

2019-07-01 20:49 UTC, Diadlo approved these changes
> *[Reviewable](https://reviewable.io/reviews/qtox/qtox/5735)* status: 0 of 1 LGTMs obtained

___
*[src/model/sessionchatlog.h, line 51 at r1](https://reviewable.io/reviews/qtox/qtox/5735#-LijI1Bg00qVELSTfDEr:-LijI1Bg00qVELSTfDEs:b-f735x9) ([raw file](https://github.com/qtox/qtox/blob/dc25183bffede1469a199f871281d6568da0e5fb/src/model/sessionchatlog.h#L51)):*
> ```objc
>     void insertCompleteMessageAtIdx(ChatLogIdx idx, ToxPk sender, QString senderName,
>                                     ChatLogMessage message);
>     void insertIncompleteMessageAtIdx(ChatLogIdx idx, ToxPk sender, QString senderName,
> ```

const reference for this function and the previous
___
*[src/persistence/history.cpp, line 630 at r1](https://reviewable.io/reviews/qtox/qtox/5735#-LijI7-i5AtKHYb0-8ux:-LijI7-i5AtKHYb0-8uy:bsw3iuk) ([raw file](https://github.com/qtox/qtox/blob/e7e6bff318a995cf4fe80b7660a67a4148053046/src/persistence/history.cpp#L630)):*
> ```cpp
>         auto display_name = QString::fromUtf8(row[4].toByteArray().replace('\0', ""));
>         auto sender_key = row[5].toString();
>         if (row[6].isNull()) {
> ```

Why now it can't be null?


<!-- Sent from Reviewable.io -->

2019-08-02 22:16 UTC, sudden6 commented
@sphaerophoria can you rebase?

2019-08-05 22:29 UTC, anthonybilinski commented
I'm going to close this pending further investigation, accidentally running it on my main profile just dumped a bunch of chat logs to the wrong friends.

2019-08-05 22:29 UTC, closed without merging

2019-08-05 22:57 UTC, jessica181920 commented
I strongly suggest we branch pre-refactor for 1.17 as this is a pretty severe issue jeopardizing the security of qTox, and the refactor is too buggy to ship in its current state.

And please do yourself a favor and never run this PR on your real tox profile.

2019-08-08 17:59 UTC, anthonybilinski commented
The problem is that e607e6ecb48e559ccd86b92a2f6d7dd453a41d11 has a bug in its SQL select. I don't know SQL very well so this terminoogy is going to be bad. Although the new `History::getMessagesForFriend` correctly joins, the new `History::getUnsentMessagesForFriend`, instead of joining all tables on ids and adding WHERE chat.public_key = arg, joins most tables on ids, but also joins peers table on arg public_key. I think the resultant table is every offline message without restriction, stuck together with peers entries matching the arg public_key. Changing back to the WHERE logic like above works, or otherwise joining both on id and also on pubic key should work.

I'll rebase this PR and update it with the fix + some testing tonight, and then hopefully re-open.

2019-08-09 04:43 UTC, anthonybilinski commented
This PR has been rebased to master tip and on top of a message selection fix, to avoid the above problem. I'll address remaining review comments and continuing the review here: https://github.com/qTox/qTox/pull/5773.