fix(chatform): crash after opening chat in new window
qTox/qTox pull request #5746
Opened 2019-07-11 13:43 UTC by bodwok

When you open a chat in a new window, the application crashes after a while 
OS: Ubuntu 16.04 x64
Qt: 5.5, 5.8

Steps to reproduce:

1. Immediately after start qTox open chat in new window
2. Wait a few seconds

Apparently using a reference to a local object resulted in segfault
This PR fixes it

2019-07-11 20:15 UTC, Kribylet approved these changes
Looks good to me!

Fixes #5697 #5732

Partially resolves #5673 (No segfault, name still not shown)

2019-07-13 16:34 UTC, sudden6 approved these changes
<img class="emoji" title=":lgtm_strong:" alt=":lgtm_strong:" align="absmiddle" src="https://reviewable.io/lgtm_strong.png" height="20" width="61"/>

> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/qtox/qtox/5746#-:-LjgAuLR8Euo4Hku28aX:b-jbsf8z)* status: :shipit: complete! 1 of 1 LGTMs obtained



<!-- Sent from Reviewable.io -->

2019-07-22 14:49 UTC, sudden6 commented
@bodwok please rebase your PR on the lastest master so that TravisCI passes again

2019-07-22 20:51 UTC, anthonybilinski requested changes
> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/qtox/qtox/5746)* status: :shipit: complete! 1 of 1 LGTMs obtained

*[a discussion](https://reviewable.io/reviews/qtox/qtox/5746#-LkQOYWe2ujtJKi240OU:-LkQOYWe2ujtJKi240OV:bj5zdvd) (no related file):*
What's the bug and what is this fixing? The PR says that "Apparently using a reference to a local object resulted in segfault", but the changes _start_ using a reference?

Is this fixing some lifetime bug by using a lifetime extension through const reference? If so - I don't think that a weird C++ spec oddity should be the basis for a fix. Instead can we maintain lifetime in a deliberate way (if that's even the bug)?

---


<!-- Sent from Reviewable.io -->

2019-07-29 13:01 UTC, closed without merging

2019-07-29 13:22 UTC, bodwok commented
> @bodwok please rebase your PR on the lastest master so that TravisCI passes again

I'm created new PR, sorry for delay

2019-07-29 15:20 UTC, bodwok commented
> > Reviewed 2 of 2 files at r1.
> > _[Reviewable](https://reviewable.io/reviews/qtox/qtox/5746)_ status: :shipit: complete! 1 of 1 LGTMs obtained
> 
> _[a discussion](https://reviewable.io/reviews/qtox/qtox/5746#-LkQOYWe2ujtJKi240OU:-LkQOYWe2ujtJKi240OV:bj5zdvd) (no related file):_
> What's the bug and what is this fixing? The PR says that "Apparently using a reference to a local object resulted in segfault", but the changes _start_ using a reference?
> 
> Is this fixing some lifetime bug by using a lifetime extension through const reference? If so - I don't think that a weird C++ spec oddity should be the basis for a fix. Instead can we maintain lifetime in a deliberate way (if that's even the bug)?

Sorry for the inaccuracy (I'm use translator)

The "contactWidgets" key has type: "const ContactId&"

In the case of code execution:
```
{
    auto friendPk = frnd->getPublicKey(); //1
    contactWidgets[friendPk] = friendWidget; //2
} //3
```

1. created new local object ContactId
2. placed in QHash friendWidget value with the key-reference on local friendPk 
3. local friendPk destructed and in QHash has reference on the destructed object

In the future when use this reference will segfault

For example:
`auto widget = contactWidgets.value(contactId)`
will call `ContactId::operator==` that use a reference on the destroyed object and segfault receive

2019-07-29 15:27 UTC, bodwok commented
> > @bodwok please rebase your PR on the lastest master so that TravisCI passes again
> 
> I'm created new PR, sorry for delay

Oops again blocked

2019-07-30 20:15 UTC, anthonybilinski commented
Ah great, thanks for the explanation. That makes sense.

> I'm created new PR, sorry for delay

By the way if you force push to your branch that you created this PR from, this PR will be updated automatically, so creating a new PR shouldn't be required. It's not a big deal though, I'll continue review on #5753.