fix(login): show login screen when autologin fails
qTox/qTox pull request #5783
Opened 2019-08-12 20:21 UTC by Kribylet

This commit catches a case where loadProfile fails to load a profile, but qtox attempted to start without a profile anyway. Failure to load a profile automatically will now bring up the login screen.

Fixes #5781

- [ ] Commits follow our [git commit guidelines](https://github.com/qTox/qTox/blob/master/CONTRIBUTING.md#git-commit-guidelines)

2019-08-12 21:14 UTC, sudden6 approved these changes
<img class="emoji" title=":lgtm_strong:" alt=":lgtm_strong:" align="absmiddle" src="https://reviewable.io/lgtm_strong.png" height="20" width="61"/>

> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/qtox/qtox/5783#-:-Lm6ffy86-Y1FDa8XOcU:b-jbsf8z)* status: :shipit: complete! 1 of 1 LGTMs obtained



<!-- Sent from Reviewable.io -->

2019-08-13 06:45 UTC, sudden6 requested changes
> *[Reviewable](https://reviewable.io/reviews/qtox/qtox/5783)* status: :shipit: complete! 1 of 1 LGTMs obtained

___
*[src/main.cpp, line 348 at r1](https://reviewable.io/reviews/qtox/qtox/5783#-Lm8i8u34cl_lLE_L7se:-Lm8i8u34cl_lLE_L7sf:bycbec7) ([raw file](https://github.com/qtox/qtox/blob/fa88f0ee74a6d2212d402b1b98b4b66a1df4e466/src/main.cpp#L348)):*
> ```cpp
>         profile = Profile::loadProfile(profileName, QString(), settings);
>         if (!profile) {
>             QMessageBox::information(nullptr, "Error", "Failed to load profile automatically.");
> ```

The error message is not translateable, please wrap it in `tr(...)`


<!-- Sent from Reviewable.io -->

2019-08-13 06:45 UTC, sudden6 reviewed
<img class="emoji" title=":lgtm_cancel:" alt=":lgtm_cancel:" align="absmiddle" src="https://reviewable.io/lgtm_cancel.png" height="20" width="61"/> 

> *[Reviewable](https://reviewable.io/reviews/qtox/qtox/5783#-:-Lm8iIMA8_7zi5RtJooJ:b8b79qu)* status: 0 of 1 LGTMs obtained



<!-- Sent from Reviewable.io -->

2019-08-13 19:27 UTC, Kribylet reviewed
> *[Reviewable](https://reviewable.io/reviews/qtox/qtox/5783)* status: 0 of 1 LGTMs obtained

___
*[src/main.cpp, line 348 at r1](https://reviewable.io/reviews/qtox/qtox/5783#-Lm8i8u34cl_lLE_L7se:-LmBRohc4_ctenOoTOqk:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/fa88f0ee74a6d2212d402b1b98b4b66a1df4e466/src/main.cpp#L348)):*
<details><summary><i>Previously, sudden6 wrote…</i></summary><blockquote>

The error message is not translateable, please wrap it in `tr(...)`
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2019-08-13 20:25 UTC, sudden6 approved these changes
<img class="emoji" title=":lgtm_strong:" alt=":lgtm_strong:" align="absmiddle" src="https://reviewable.io/lgtm_strong.png" height="20" width="61"/>

> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/qtox/qtox/5783#-:-LmBdwcT1QAZ3q5gGmE9:b-jbsf8z)* status: :shipit: complete! 1 of 1 LGTMs obtained



<!-- Sent from Reviewable.io -->

2019-08-13 20:26 UTC, merged