fix(chatlog): out of bounds access when loading messages
qTox/qTox pull request #5806
Opened 2019-08-28 20:01 UTC by sudden6

We need to invalidate the selection when adding/removing lines from the
chatlog because the selection stores them as absolute indices.

A nicer solution would be to actually update the selection accordingly,
but this will be a major overhaul of the code.

- [ ] Commits follow our [git commit guidelines](https://github.com/qTox/qTox/blob/master/CONTRIBUTING.md#git-commit-guidelines)

2019-08-28 20:02 UTC, sudden6 commented
This could fix: #5769

2019-08-28 20:41 UTC, anthonybilinski requested changes
I think it would be better to shift the selection to maintain the same lines, if possible, instead of always clearing. removeFirsts gets called while just chatting, so you could have a selection of a few lines near the bottom, receive one message, then all of a sudden have your selection disapear, which I think would be pretty confusing.

Instead of shifting the indexes on removal/addition to top, we could instead use absolute chat line indexes like provided by IChatLog, so that indexes remain valid after the ChatLog is changed.

> *[Reviewable](https://reviewable.io/reviews/qtox/qtox/5806#-:-LnOwhlm2CtJsiW32ubf:b-q6fg3w)* status: 0 of 1 LGTMs obtained



<!-- Sent from Reviewable.io -->

2019-08-30 09:39 UTC, anthonybilinski commented
I pushed my implementation of the more complex fix here: https://github.com/qTox/qTox/pull/5811 - it handles out of access from both directions, and an existing bug that doesn't cause crashes of loading history causing the selection to jump to new messages.

2019-08-30 11:13 UTC, sudden6 commented
Closing in favor of #5811

2019-08-30 11:13 UTC, closed without merging