fix(chatform): Prevent date line oscillations maxing CPU
qTox/qTox pull request #5875
Opened 2019-10-12 22:14 UTC by sphaerophoria

The previous implementation of hiding the date line would cause 100% cpu
usage. When the date line was shown it would hide the top line, causing
the date line to be hidden again due to a state change in which dates
was visible.

This is a minimal patch to work around the issue by pretending the line
covered by the date line is the first visible line when the dateline is
shown

Fixes #5620

- [ ] Commits follow our [git commit guidelines](https://github.com/qTox/qTox/blob/master/CONTRIBUTING.md#git-commit-guidelines)

2019-10-13 05:49 UTC, anthonybilinski requested changes
> Reviewed 4 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/qtox/qtox/5875)* status: 0 of 1 LGTMs obtained

___
*[src/widget/form/genericchatform.h, line 120 at r1](https://reviewable.io/reviews/qtox/qtox/5875#-Lr2d44NDCm8upLJvhkV:-Lr2d44NDCm8upLJvhkW:b-8mcbzl) ([raw file](https://github.com/qtox/qtox/blob/738cfd58543374ee8be67240172293e005ef0e5e/src/widget/form/genericchatform.h#L120)):*
> ```objc
>     void searchFormShow();
>     void onSearchTriggered();
>     void updateShowDateInfo(const ChatLine::Ptr& prevLine, const ChatLine::Ptr& line);
> ```

could you update the arg name here to match the implementation? (line -> topLine)
___
*[src/widget/form/genericchatform.cpp, line 1207 at r1](https://reviewable.io/reviews/qtox/qtox/5875#-Lr2eBzWDZ0BDw-bxg8d:-Lr2eBzWDZ0BDw-bxg8e:b-2p0zv3) ([raw file](https://github.com/qtox/qtox/blob/738cfd58543374ee8be67240172293e005ef0e5e/src/widget/form/genericchatform.cpp#L1207)):*
> ```cpp
>     const auto date = getTime(effectiveTopLine);
> 
>     if (!date.isValid() || date.date() != QDate::currentDate()) {
> ```

why the change to this condition? don't we want to skip this block if date isn't valid?


<!-- Sent from Reviewable.io -->

2019-11-09 22:55 UTC, sphaerophoria reviewed
> *[Reviewable](https://reviewable.io/reviews/qtox/qtox/5875)* status: 0 of 1 LGTMs obtained

___
*[src/widget/form/genericchatform.h, line 120 at r1](https://reviewable.io/reviews/qtox/qtox/5875#-Lr2d44NDCm8upLJvhkV:-LtHNDQF4YL9G4c-wgjJ:bebrt1w) ([raw file](https://github.com/qtox/qtox/blob/738cfd58543374ee8be67240172293e005ef0e5e/src/widget/form/genericchatform.h#L120)):*
<details><summary><i>Previously, anthonybilinski (Anthony Bilinski) wrote…</i></summary><blockquote>

could you update the arg name here to match the implementation? (line -> topLine)
</blockquote></details>

Will do
___
*[src/widget/form/genericchatform.cpp, line 1207 at r1](https://reviewable.io/reviews/qtox/qtox/5875#-Lr2eBzWDZ0BDw-bxg8d:-LtHNAVvC83HglrWjBkw:b-66fajn) ([raw file](https://github.com/qtox/qtox/blob/738cfd58543374ee8be67240172293e005ef0e5e/src/widget/form/genericchatform.cpp#L1207)):*
<details><summary><i>Previously, anthonybilinski (Anthony Bilinski) wrote…</i></summary><blockquote>

why the change to this condition? don't we want to skip this block if date isn't valid?
</blockquote></details>

Whoops that's definitely a mistake, will fix


<!-- Sent from Reviewable.io -->

2019-11-09 23:15 UTC, sphaerophoria reviewed
> *[Reviewable](https://reviewable.io/reviews/qtox/qtox/5875)* status: 0 of 1 LGTMs obtained

___
*[src/widget/form/genericchatform.h, line 120 at r1](https://reviewable.io/reviews/qtox/qtox/5875#-Lr2d44NDCm8upLJvhkV:-LtHRv4Y5OzSHNKwjHOF:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/738cfd58543374ee8be67240172293e005ef0e5e/src/widget/form/genericchatform.h#L120)):*
<details><summary><i>Previously, sphaerophoria wrote…</i></summary><blockquote>

Will do
</blockquote></details>

Done.
___
*[src/widget/form/genericchatform.cpp, line 1207 at r1](https://reviewable.io/reviews/qtox/qtox/5875#-Lr2eBzWDZ0BDw-bxg8d:-LtHRw413ThhQYPjd2M-:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/738cfd58543374ee8be67240172293e005ef0e5e/src/widget/form/genericchatform.cpp#L1207)):*
<details><summary><i>Previously, sphaerophoria wrote…</i></summary><blockquote>

Whoops that's definitely a mistake, will fix
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2019-11-22 20:20 UTC, anthonybilinski approved these changes
<img class="emoji" title=":lgtm_strong:" alt=":lgtm_strong:" align="absmiddle" src="https://reviewable.io/lgtm_strong.png" height="20" width="61"/>

> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/qtox/qtox/5875#-:-LuJlOXeEsZUkPT5dRGl:b-jbsf8z)* status: :shipit: complete! 1 of 1 LGTMs obtained



<!-- Sent from Reviewable.io -->

2019-11-22 20:38 UTC, anthonybilinski requested changes
> *[Reviewable](https://reviewable.io/reviews/qtox/qtox/5875)* status: :shipit: complete! 1 of 1 LGTMs obtained

*[a discussion](https://reviewable.io/reviews/qtox/qtox/5875#-LuJpSioAw3N1SnVE2dS:-LuJpSioAw3N1SnVE2dT:bjsayd5) (no related file):*
CPU max problem is fixed, but if I grab the scroll bar and slowly scroll across the boundary, my scroll gets yanked around back and forth.. would this be easy to fix?

---


<!-- Sent from Reviewable.io -->

2019-11-24 01:26 UTC, anthonybilinski approved these changes
> *[Reviewable](https://reviewable.io/reviews/qtox/qtox/5875)* status: :shipit: complete! 1 of 1 LGTMs obtained

*[a discussion](https://reviewable.io/reviews/qtox/qtox/5875#-LuJpSioAw3N1SnVE2dS:-LuQ-aUwCIs1ikdfEKmP:b-il3l7p) (no related file):*
<details><summary><i>Previously, anthonybilinski (Anthony Bilinski) wrote…</i></summary><blockquote>

CPU max problem is fixed, but if I grab the scroll bar and slowly scroll across the boundary, my scroll gets yanked around back and forth.. would this be easy to fix?
</blockquote></details>

This "fighting the scrollbar" is reproducible before this change, and it doesn't get hit during just chatting, plus you can still yank the scrollbar past this point. Not required for this PR.

---


<!-- Sent from Reviewable.io -->

2019-11-24 01:28 UTC, merged