fix(loginScreen): unify loginScreen reject/closeEvent behavior
qTox/qTox pull request #5894
Opened 2019-10-16 17:54 UTC by Kribylet

Qt triggers reject instead of closeEvent when escape is pressed. This commit overrides the inherited QDialog::reject and calls LoginScreen::closeEvent, so behavior is unified.

- [ ] Commits follow our [git commit guidelines](https://github.com/qTox/qTox/blob/master/CONTRIBUTING.md#git-commit-guidelines)

2019-10-16 22:20 UTC, sudden6 commented
Our commit linting script complains about a too long commit title, forgotten line break?

2019-10-17 04:39 UTC, Kribylet commented
Fixed missing line break

2019-10-17 05:28 UTC, anthonybilinski requested changes
> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/qtox/qtox/5894)* status: 0 of 1 LGTMs obtained

___
*[src/widget/loginscreen.h, line 52 at r1](https://reviewable.io/reviews/qtox/qtox/5894#-LrN35vi0t6BRvfQJ_VC:-LrN35vi0t6BRvfQJ_VD:b-dd7yts) ([raw file](https://github.com/qtox/qtox/blob/1fff7f2b8ef4a2ecebf8d9eeb8e5c1cc17bdce05/src/widget/loginscreen.h#L52)):*
This is a bit out of scope of the bug fix, but, according to https://doc.qt.io/qt-5/qdialog.html#return-value-modal-dialogs:
> In order to modify your dialog's close behavior, you can reimplement the functions accept(), reject() or done(). The closeEvent() function should only be reimplemented to preserve the dialog's position or to override the standard close or reject behavior.

From the general description:
> Typically, to get the dialog to close and return the appropriate value, we connect a default button, e.g. OK, to the accept() slot and a Cancel button to the reject() slot. Alternatively you can call the done() slot with Accepted or Rejected.

What do you think about either calling done(Rejected)/done(Accepted) instead of 0/-1, or using the default `rejected` signal, but checking the return code against Accepted/Rejected instead of against 0/1? Then onProfileLoaded could be connected directly to `accept`, and `rejected` could be left unhandled - I think.


<!-- Sent from Reviewable.io -->

2019-10-18 07:45 UTC, Kribylet commented
Changed method of issue resolution. Commit title and description changed accordingly. This commit now changes LoginScreen return values to Qt standards (1 success, 0 failure) rather than traditional C values. This is a bit unsightly considering C standards are used elsewhere, but whenever referred to the appropriate enums should be in use, so it shouldn't be too bad. This has the benefit of catching special cases in the Qt implementation, like the one causing the referenced issue, and should be more robust.

2019-10-18 07:51 UTC, Kribylet reviewed
> *[Reviewable](https://reviewable.io/reviews/qtox/qtox/5894)* status: 0 of 1 LGTMs obtained

___
*[src/widget/loginscreen.h, line 52 at r1](https://reviewable.io/reviews/qtox/qtox/5894#-LrN35vi0t6BRvfQJ_VC:-LrSq39F75wihtE94fiz:bychrka) ([raw file](https://github.com/qtox/qtox/blob/1fff7f2b8ef4a2ecebf8d9eeb8e5c1cc17bdce05/src/widget/loginscreen.h#L52)):*
<details><summary><i>Previously, anthonybilinski (Anthony Bilinski) wrote…</i></summary><blockquote>

This is a bit out of scope of the bug fix, but, according to https://doc.qt.io/qt-5/qdialog.html#return-value-modal-dialogs:
> In order to modify your dialog's close behavior, you can reimplement the functions accept(), reject() or done(). The closeEvent() function should only be reimplemented to preserve the dialog's position or to override the standard close or reject behavior.

From the general description:
> Typically, to get the dialog to close and return the appropriate value, we connect a default button, e.g. OK, to the accept() slot and a Cancel button to the reject() slot. Alternatively you can call the done() slot with Accepted or Rejected.

What do you think about either calling done(Rejected)/done(Accepted) instead of 0/-1, or using the default `rejected` signal, but checking the return code against Accepted/Rejected instead of against 0/1? Then onProfileLoaded could be connected directly to `accept`, and `rejected` could be left unhandled - I think.
</blockquote></details>

This seems a more robust solution overall. Modified the PR accordingly. 


<!-- Sent from Reviewable.io -->

2019-10-18 21:33 UTC, anthonybilinski approved these changes
> Reviewed 4 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/qtox/qtox/5894)* status: 0 of 1 LGTMs obtained

___
*[src/nexus.cpp, line 171 at r2](https://reviewable.io/reviews/qtox/qtox/5894#-LrVmNDE1T1qxUv4FoHs:-LrVmNDE1T1qxUv4FoHt:b-5zduzk) ([raw file](https://github.com/qtox/qtox/blob/b5bd3c9361e26f39783ec4260b09e4e114af0b2f/src/nexus.cpp#L171)):*
> ```cpp
>         // Kriby: This will terminate the main application loop, necessary until we refactor
>         // away the split startup/return to login behavior.
>         qApp->quit();
> ```

why is this now required? was it also required before but we were missing it?


<!-- Sent from Reviewable.io -->

2019-10-18 23:01 UTC, Kribylet reviewed
> *[Reviewable](https://reviewable.io/reviews/qtox/qtox/5894)* status: 0 of 1 LGTMs obtained

___
*[src/nexus.cpp, line 171 at r2](https://reviewable.io/reviews/qtox/qtox/5894#-LrVmNDE1T1qxUv4FoHs:-LrW4Ci74pv7xTIe2yYd:bdu3baq) ([raw file](https://github.com/qtox/qtox/blob/b5bd3c9361e26f39783ec4260b09e4e114af0b2f/src/nexus.cpp#L171)):*
<details><summary><i>Previously, anthonybilinski (Anthony Bilinski) wrote…</i></summary><blockquote>

why is this now required? was it also required before but we were missing it?
</blockquote></details>

It was required previously, check the closeEvent diff in loginScreen. As the comment implies it is an artifact of how qTox handles the initial login as a special case (started first through loginscreen.exec(), but later loginscreens are spawned from the main application). I have tried to refactor this  previously but at the time I could not solve it easily. 


<!-- Sent from Reviewable.io -->

2019-10-18 23:17 UTC, anthonybilinski approved these changes
<img class="emoji" title=":lgtm_strong:" alt=":lgtm_strong:" align="absmiddle" src="https://reviewable.io/lgtm_strong.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/qtox/qtox/5894#-:-LrW9O4k0iI733OjS-m4:b-jbsf8z)* status: :shipit: complete! 1 of 1 LGTMs obtained



<!-- Sent from Reviewable.io -->

2019-10-18 23:30 UTC, anthonybilinski commented
I've cherry picked your change to the v1.17-dev branch and updated you fork, and changed the base for this PR so that the change will be included in the v1.17.x release(s), since it's a nice scoped bug fix.

2019-10-19 00:26 UTC, merged