refactor: remove AppImage update bridge
qTox/qTox pull request #5908
Opened 2019-10-22 23:10 UTC by sudden6

When re-evaluating our dependencies we decided that the update bridge
has a high potential for security issues because it's not widely used.
Additionally similar functionality is already present in qTox in the form of update notifications.

This should basically revert #5747, with the exception of still adding the update information into the AppImage so that external tools can use it.

@antony-jr FYI, @anthonybilinski and me re-evaluated the use of AppImageUpdate bridge and came to the conclusion that it's better to remove it.

- [ ] Commits follow our [git commit guidelines](https://github.com/qTox/qTox/blob/master/CONTRIBUTING.md#git-commit-guidelines)

2019-10-23 01:24 UTC, anthonybilinski commented
Just want to reiterate that this doesn't have to do with any specific issue we found in https://github.com/antony-jr/AppImageUpdaterBridge, just that using libraries that don't have wide adoption inherently has more risk because there are fewer eyes on the project, and we don't have the resources to review AppImageUpdaterBridge with the same scrutiny as qTox's code. Security software doesn't seem like the appropriate place to be early adopters on non-essential dependencies.

I still think it's an interesting project, and hope it goes on to be used by others :smiley:

2019-10-23 01:27 UTC, anthonybilinski commented
I also want to apologize to @antony-jr that you put in the work to integrate it with qTox recently and @nurupo for going through the review. We should have decided at that point before that work was done, instead of just a few months later.

2019-10-23 04:15 UTC, nurupo commented
No problem, I think that's a good decision.

2019-10-23 04:37 UTC, nurupo reviewed
> *[Reviewable](https://reviewable.io/reviews/qtox/qtox/5908)* status: 0 of 1 LGTMs obtained

___
*[appimage/build.sh, line 122 at r1](https://reviewable.io/reviews/qtox/qtox/5908#-LrqtbUv5jZaIQ5YjWMI:-LrqtbUv5jZaIQ5YjWMJ:bvbykf9) ([raw file](https://github.com/qtox/qtox/blob/6ac7c64c46db29cc5c73848008d9595c1f826ff9/appimage/build.sh#L122)):*
> ```Shell
> # need to build with -DDESKTOP_NOTIFICATIONS=True for snorenotify
> cmake -DDESKTOP_NOTIFICATIONS=True \
>       -DUPDATE_CHECK=True \
> ```

Is `UPDATE_CHECK` needed? It was added in the PR we are undoing.
___
*[appimage/build.sh, line 123 at r1](https://reviewable.io/reviews/qtox/qtox/5908#-Lrqp5xs6fdUx5aLtdi_:-Lrqp5xs6fdUx5aLtdia:b72urd7) ([raw file](https://github.com/qtox/qtox/blob/6ac7c64c46db29cc5c73848008d9595c1f826ff9/appimage/build.sh#L123)):*
> ```Shell
> cmake -DDESKTOP_NOTIFICATIONS=True \
>       -DUPDATE_CHECK=True \
>       -DAPPIMAGE_UPDATER_BRIDGE=True \
> ```

`APPIMAGE_UPDATER_BRIDGE` can be removed, since that option is gone now.


<!-- Sent from Reviewable.io -->

2019-10-23 04:44 UTC, antony-jr commented
> Is UPDATE_CHECK needed? It was added in the PR we are undoing.

@nurupo That was not added in the PR but was corrected in the PR. I think it was added by @anthonybilinski when adding the update notification. Without that flag the update available button would not show in the about form.

2019-11-05 00:27 UTC, anthonybilinski requested changes
> Reviewed 6 of 6 files at r1.
> *[Reviewable](https://reviewable.io/reviews/qtox/qtox/5908)* status: 0 of 1 LGTMs obtained

___
*[appimage/build.sh, line 122 at r1](https://reviewable.io/reviews/qtox/qtox/5908#-LrqtbUv5jZaIQ5YjWMI:-Lssw8uNCriE9fXO6ytH:b-4xcagk) ([raw file](https://github.com/qtox/qtox/blob/6ac7c64c46db29cc5c73848008d9595c1f826ff9/appimage/build.sh#L122)):*
<details><summary><i>Previously, nurupo wrote…</i></summary><blockquote>

Is `UPDATE_CHECK` needed? It was added in the PR we are undoing.
</blockquote></details>

I agee with @antony-jr's comment on github - UPDATE_CHECK is for the lightweight http check I added before, and anthony-jr just fixed it (I had it in the wrong place for appimage) in his autoupdate PR.
___
*[appimage/build.sh, line 123 at r1](https://reviewable.io/reviews/qtox/qtox/5908#-Lrqp5xs6fdUx5aLtdi_:-LssxCK9D5OH-56h-cye:b-pbdqz3) ([raw file](https://github.com/qtox/qtox/blob/6ac7c64c46db29cc5c73848008d9595c1f826ff9/appimage/build.sh#L123)):*
<details><summary><i>Previously, nurupo wrote…</i></summary><blockquote>

`APPIMAGE_UPDATER_BRIDGE` can be removed, since that option is gone now.
</blockquote></details>

Agreed.


<!-- Sent from Reviewable.io -->

2020-01-12 19:09 UTC, sudden6 reviewed
> *[Reviewable](https://reviewable.io/reviews/qtox/qtox/5908)* status: 0 of 1 LGTMs obtained

___
*[appimage/build.sh, line 122 at r1](https://reviewable.io/reviews/qtox/qtox/5908#-LrqtbUv5jZaIQ5YjWMI:-LyQ99Bj7iAwBKSLQa12:bpkfn5e) ([raw file](https://github.com/qtox/qtox/blob/6ac7c64c46db29cc5c73848008d9595c1f826ff9/appimage/build.sh#L122)):*
<details><summary><i>Previously, anthonybilinski (Anthony Bilinski) wrote…</i></summary><blockquote>

I agee with @antony-jr's comment on github - UPDATE_CHECK is for the lightweight http check I added before, and anthony-jr just fixed it (I had it in the wrong place for appimage) in his autoupdate PR.
</blockquote></details>

Yeah, the lightweight check should stay as it was before.
___
*[appimage/build.sh, line 123 at r1](https://reviewable.io/reviews/qtox/qtox/5908#-Lrqp5xs6fdUx5aLtdi_:-LyQ98mTE5L3SrrpY3IC:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/6ac7c64c46db29cc5c73848008d9595c1f826ff9/appimage/build.sh#L123)):*
<details><summary><i>Previously, anthonybilinski (Anthony Bilinski) wrote…</i></summary><blockquote>

Agreed.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-01-12 19:26 UTC, anthonybilinski approved these changes
<img class="emoji" title=":lgtm_strong:" alt=":lgtm_strong:" align="absmiddle" src="https://reviewable.io/lgtm_strong.png" height="20" width="61"/> 

> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/qtox/qtox/5908#-:-LyQD3Qk3tmEidchsDV7:b-uwkowd)* status: :shipit: complete! 1 of 1 LGTMs obtained



<!-- Sent from Reviewable.io -->

2020-01-13 08:56 UTC, antony-jr reviewed
<img class="emoji" title=":lgtm_strong:" alt=":lgtm_strong:" align="absmiddle" src="https://reviewable.io/lgtm_strong.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/qtox/qtox/5908#-:-LyT6_pO7hKUabZngxmr:b-jbsf8z)* status: :shipit: complete! 2 of 1 LGTMs obtained



<!-- Sent from Reviewable.io -->

2020-01-13 17:59 UTC, merged