Multipart messages
qTox/qTox pull request #5932
Opened 2019-11-17 21:50 UTC by sphaerophoria

# Multi-packet messages support

After months of talking about it I've finally taken the time to sit down and clean up the qTox integration of the toxext library to provide multi-packet messages support. Thanks @anthony for finally pushing me to sit down and get it done.

Toxcore has a limitation in that any messages bigger than a single UDP packet are not sendable. This is not fixable without adding more handshaking to the protocol which would break backwards compatibility with older toxcores. Unfortunately there is no versioning in the toxcore protocol so until they ship their first breaking change we cannot add any features.

For this reason I wrote a library ToxExt. ToxExt is a general purpose library that implements negotiation of extra features over the toxcore custom packet concept. This allows us to do a couple things
1. Implement new packet level features on top of the toxcore protocol without breaking compatibility with exsiting clients
2. Implement features a little more aggressively. Since all extensions are known to be optional if we find a bug in the feature we can just disable it with little harm done.

This PR implements the first of what are hopefully many more extensions to come.

For more info on the design of ToxExt please see https://github.com/toxext/toxext/blob/master/DESIGN.md

The message extension works by marking sequential packets with a "start"/"part"/"finish" marker. The extension library automatically splits a long message into a "start" packet, several "part" packets, and a "finish" packet. When packets are received by an extension they are cached in the library until a "finish" packet has been seen. When we see a "finish" packet qTox receives the full message and dispatches it through the normal channels.

This PR covers a lot of different areas. I feel like the feature would be unfinished/confusing to users without the following.

* UI element indicating a friend's extension support. This can be green/yellow/red and on hover will show which extensions are supported
* Friends now have a "Negotiating" state. When a friend goes online we try to send them a toxext packet to ask them what extensions they have. If they have toxext on the other end this should be quite quick. If they don't we wait one second before deciding that they won't answer us. In this state we treat them as offline (which I will explain in the next point).
* Offline messages in combination with extensions gets a little confusing. What should the behavior be if I send an extended message, my friend goes offline, and then comes back online without support for the extension? I've decided if the extension set is reduced we fail all messages currently in the offline message queue. This is because sometimes meaning of messages are affected by the ones around it. I wouldn't want to deliver some messages without their surrounding context
    * Since we can have multiple reasons for a message to not be delivered I've added a "reason" field to the broken message concept
* In our database we now store the required extension set needed to send each offline message. I do not think it's important for us to store extension requirements for messages that are already sent, we can just null out fields in the future that are not relevant due to the extensions not being available.

![extension_demo](https://user-images.githubusercontent.com/1069811/69014642-35e5d380-0941-11ea-8cd1-9f70abca5c7f.png)
![no_extension](https://user-images.githubusercontent.com/1069811/69014644-3a11f100-0941-11ea-949d-7696bce1db77.png)

## Testing done
* Large message received with friends that support extended messages
* Messages still split with friends that do not support extended messages
* Sending offline message does not use extensions
* Attempting to send a message to a friend with extension who crashes still sends messages with extension support
* Attempting to send a message to a friend with extension who crashes after reloading history still sends messages with extension support
* If a friend crashes and then boots a client without extension support all messages fail to send
* Unable to send messages while still negotiating extensions
  * This is intentional to force unsent extension messages to be sent before new messages
  * In theory we could not do this in the case where there are no unsent messages but I don't think it's worth the effort
* All unsent messages are not sent until extension negotiation is complete

Please bare with me, I've done a lot of self reviews and tried to keep it fairly reviewable, but it's likely that I missed something. After the 10th self review my eyes start to gloss over :P. Thorough reviews are welcomed and recommended.

2019-11-17 22:46 UTC, sudden6 commented
@sphaerophoria `find_package` and `add_dependency` only work if you provide some cmake files for toxext, use our custom `search_dependency` like c-toxcore: https://github.com/qTox/qTox/pull/5932/files#diff-dcf5891602b4162c36c2125c806639c5R154-R156

2019-11-17 22:48 UTC, sphaerophoria commented
@sudden6 The find_package macros are using generated cmake files from the toxext project. I'm still updating the build scripts to deal with it but locally a make/make install should be enough to get it working.

2019-11-17 22:48 UTC, sudden6 commented
ok then

2019-11-18 22:13 UTC, sudden6 commented
sending a long action message triggers an assert:

```
#0  0x00007ffff0fb5160 in raise () from /lib64/libc.so.6
#1  0x00007ffff0fb6741 in abort () from /lib64/libc.so.6
#2  0x00007ffff0fad75a in __assert_fail_base () from /lib64/libc.so.6
#3  0x00007ffff0fad7d2 in __assert_fail () from /lib64/libc.so.6
#4  0x00000000007fc9d5 in FriendMessageDispatcher::sendExtendedProcessedMessage(Message const&, std::function<void (bool)>) (this=0x77280f0, message=..., onOfflineMsgComplete=...)
    at /home/chr/build/sudden6/qTox/src/model/friendmessagedispatcher.cpp:145
#5  0x00000000007fc923 in FriendMessageDispatcher::sendProcessedMessage(Message const&, std::function<void (bool)>) (this=0x77280f0, message=..., onOfflineMsgComplete=...)
    at /home/chr/build/sudden6/qTox/src/model/friendmessagedispatcher.cpp:135
#6  0x00000000007fc30d in FriendMessageDispatcher::sendMessage (this=0x77280f0, isAction=true, content=...) at /home/chr/build/sudden6/qTox/src/model/friendmessagedispatcher.cpp:47
#7  0x0000000000893e17 in GenericChatForm::onSendTriggered (this=0x757c180) at /home/chr/build/sudden6/qTox/src/widget/form/genericchatform.cpp:541
```

Sending a too long action message should not kill qTox, it should do one of those things instead:
- send the long action message
- split the long action message (I think this current behavior, not sure if that's good UX though)
- send the long action message as normal message
- don't send the message and mark it as broken (IMO the least desirable solution)

2019-11-18 22:36 UTC, sudden6 requested changes
> Reviewed 58 of 58 files at r1.
> *[Reviewable](https://reviewable.io/reviews/qtox/qtox/5932)* status: 0 of 1 LGTMs obtained

___
*[.travis/build-ubuntu-16-04.sh, line 149 at r1](https://reviewable.io/reviews/qtox/qtox/5932#-Lu-M_OREZXgb65qk7_V:-Lu-M_OS64dsYla1pjju:b-6mmkr9) ([raw file](https://github.com/qtox/qtox/blob/e94b16b2912349df473c82a0bd1c606b78ff2cc5/.travis/build-ubuntu-16-04.sh#L149)):*
> ```Shell
> cd ..
> 
> #toxext
> ```

style nit: space between `#` and name to match the rest of the file
___
*[.travis/build-ubuntu-16-04.sh, line 159 at r1](https://reviewable.io/reviews/qtox/qtox/5932#-Lu-MdE_6ewe-ej-Padt:-Lu-MdE_6ewe-ej-Padu:bb7od0r) ([raw file](https://github.com/qtox/qtox/blob/e94b16b2912349df473c82a0bd1c606b78ff2cc5/.travis/build-ubuntu-16-04.sh#L159)):*
> ```Shell
> cd ../../
> 
> #toxext_messages
> ```

same
___
*[osx/qTox-Mac-Deployer-ULTIMATE.sh, line 87 at r1](https://reviewable.io/reviews/qtox/qtox/5932#-Lu-N29p-VjcXgGVFyBO:-Lu-N29p-VjcXgGVFyBP:bto3z1j) ([raw file](https://github.com/qtox/qtox/blob/e94b16b2912349df473c82a0bd1c606b78ff2cc5/osx/qTox-Mac-Deployer-ULTIMATE.sh#L87)):*
> ```Shell
> 
> build_toxext() {
>     echo "Starting Toxext build and install"
> ```

IDK why the rest of the build script uses `fcho`, but we should use it everywhere or remove it everywhere
___
*[osx/qTox-Mac-Deployer-ULTIMATE.sh, line 92 at r1](https://reviewable.io/reviews/qtox/qtox/5932#-Lu-NKHk7fjLlqFscG6z:-Lu-NKHk7fjLlqFscG7-:b-vfk7yv) ([raw file](https://github.com/qtox/qtox/blob/e94b16b2912349df473c82a0bd1c606b78ff2cc5/osx/qTox-Mac-Deployer-ULTIMATE.sh#L92)):*
> ```Shell
> 
>     [[ $TRAVIS != true ]] \
>     && sleep 3
> ```

why the sleep command?
___
*[osx/qTox-Mac-Deployer-ULTIMATE.sh, line 110 at r1](https://reviewable.io/reviews/qtox/qtox/5932#-Lu-NNdiCOZD4aymCQfd:-Lu-NNdiCOZD4aymCQfe:b-vfk7yv) ([raw file](https://github.com/qtox/qtox/blob/e94b16b2912349df473c82a0bd1c606b78ff2cc5/osx/qTox-Mac-Deployer-ULTIMATE.sh#L110)):*
> ```Shell
> 
>     [[ $TRAVIS != true ]] \
>     && sleep 3
> ```

why the sleep command?
___
*[osx/qTox-Mac-Deployer-ULTIMATE.sh, line 249 at r1](https://reviewable.io/reviews/qtox/qtox/5932#-Lu-NWiv4azorD1QB6wC:-Lu-NWiv4azorD1QB6wD:bkii0p3) ([raw file](https://github.com/qtox/qtox/blob/e94b16b2912349df473c82a0bd1c606b78ff2cc5/osx/qTox-Mac-Deployer-ULTIMATE.sh#L249)):*
> ```Shell
>     fi
> 
>     # toxcore build
> ```

wrong comment
___
*[osx/qTox-Mac-Deployer-ULTIMATE.sh, line 264 at r1](https://reviewable.io/reviews/qtox/qtox/5932#-Lu-NY8K2a7T1Hr5BFCh:-Lu-NY8K2a7T1Hr5BFCi:bkii0p3) ([raw file](https://github.com/qtox/qtox/blob/e94b16b2912349df473c82a0bd1c606b78ff2cc5/osx/qTox-Mac-Deployer-ULTIMATE.sh#L264)):*
> ```Shell
>     fi
> 
>     # toxcore build
> ```

wrong comment
___
*[src/core/coreext.h, line 57 at r1](https://reviewable.io/reviews/qtox/qtox/5932#-Lu-ONtrDAdOIzQAf8WM:-Lu-ONtrDAdOIzQAf8WN:bf2vgdl) ([raw file](https://github.com/qtox/qtox/blob/e94b16b2912349df473c82a0bd1c606b78ff2cc5/src/core/coreext.h#L57)):*
> ```objc
> 
>     /**
>      * See documentatino of ICoreExtPacket
> ```

typo, `documentation`
___
*[src/core/coreext.h, line 86 at r1](https://reviewable.io/reviews/qtox/qtox/5932#-Lu-Te4x4ANEV3Ex5mpg:-Lu-Te4x4ANEV3Ex5mph:b4kx5de) ([raw file](https://github.com/qtox/qtox/blob/e94b16b2912349df473c82a0bd1c606b78ff2cc5/src/core/coreext.h#L86)):*
> ```objc
>     private:
>         bool hasBeenSent = false;
>         ToxExtensionMessages* toxExtMessages;
> ```

It is unclear to me why `toxExtMessages` and `packetList` don't need to be freed by `Packet`, can you please explain?
___
*[src/core/coreext.cpp, line 73 at r1](https://reviewable.io/reviews/qtox/qtox/5932#-Lu-UfxG2CTc2IsX-8tt:-Lu-UfxG2CTc2IsX-8tu:b-o5gw9h) ([raw file](https://github.com/qtox/qtox/blob/e94b16b2912349df473c82a0bd1c606b78ff2cc5/src/core/coreext.cpp#L73)):*
> ```cpp
>         assert(false);
>         qWarning() << "Invalid use of CoreExt::Packet";
>         return UINT64_MAX;
> ```

Please document the special return value
___
*[src/core/coreext.cpp, line 90 at r1](https://reviewable.io/reviews/qtox/qtox/5932#-Lu-Uupj7kxJmabnP9QL:-Lu-Uupj7kxJmabnP9QM:btvnvik) ([raw file](https://github.com/qtox/qtox/blob/e94b16b2912349df473c82a0bd1c606b78ff2cc5/src/core/coreext.cpp#L90)):*
> ```cpp
>         qWarning() << "Failed to send packet";
>     }
>     hasBeenSent = true;
> ```

why set `hasBeenSent` to `true` if the packet failed to send? At least needs a comment
___
*[src/core/coreext.cpp, line 96 at r1](https://reviewable.io/reviews/qtox/qtox/5932#-Lu-V9Pl5zM3jKVrPijJ:-Lu-V9Pl5zM3jKVrPijK:b-rr21q7) ([raw file](https://github.com/qtox/qtox/blob/e94b16b2912349df473c82a0bd1c606b78ff2cc5/src/core/coreext.cpp#L96)):*
> ```cpp
> void CoreExt::onFriendStatusChanged(uint32_t friendId, Status::Status status)
> {
>     if (status != Status::Status::Offline) {
> ```

This will trigger negotiations when the status changes are `Online -> Away` or `Online->Busy`and some others too, is this intended?
___
*[src/model/brokenmessagereason.h, line 24 at r1](https://reviewable.io/reviews/qtox/qtox/5932#-Lu-Vkt78nTlaVlf7CxP:-Lu-Vkt78nTlaVlf7CxQ:b-a1n8ki) ([raw file](https://github.com/qtox/qtox/blob/e94b16b2912349df473c82a0bd1c606b78ff2cc5/src/model/brokenmessagereason.h#L24)):*
> ```objc
> 
> // NOTE: Numbers are important here as this is cast to an int and persisted in the DB
> enum class BrokenMessageReason
> ```

if this can be cast to int, `int` should be the base type of the enum
___
*[src/model/chathistory.cpp, line 452 at r1](https://reviewable.io/reviews/qtox/qtox/5932#-Lu-WVOo8ZUm-AnfYxoA:-Lu-WVOo8ZUm-AnfYxoB:b6gocp0) ([raw file](https://github.com/qtox/qtox/blob/e94b16b2912349df473c82a0bd1c606b78ff2cc5/src/model/chathistory.cpp#L452)):*
> ```cpp
>         // attempted send time (which is whenever the it was initially inserted
>         // into history
>         auto dispatchId = (requiredExtensions.none())
> ```

why the extra `()`?
___
*[src/model/chathistory.cpp, line 484 at r1](https://reviewable.io/reviews/qtox/qtox/5932#-Lu-WqmA8dq6hL4xqHVu:-Lu-WqmA8dq6hL4xqHVv:buzri4x) ([raw file](https://github.com/qtox/qtox/blob/e94b16b2912349df473c82a0bd1c606b78ff2cc5/src/model/chathistory.cpp#L484)):*
> ```cpp
>         brokenMessages.erase(brokenMessageIt);
>     } else {
>         dispatchedMessageRowIdMap.insert(dispatchId, historyId);
> ```

you assert against this case, shouldn't there be at least a message that this case is not supposed to happen?
___
*[src/model/groupmessagedispatcher.cpp, line 70 at r1](https://reviewable.io/reviews/qtox/qtox/5932#-Lu-_6QS9DR9rt2GQfN-:-Lu-_6QT7sqE4RO8RtZw:b-mciydx) ([raw file](https://github.com/qtox/qtox/blob/e94b16b2912349df473c82a0bd1c606b78ff2cc5/src/model/groupmessagedispatcher.cpp#L70)):*
> ```cpp
> DispatchedMessageId GroupMessageDispatcher::sendExtendedMessage(const QString& content, ExtensionSet extensions)
> {
>     // Stub this api to immediately fail
> ```

this comment makes no sense to me, leftover?
___
*[src/widget/chatformheader.h, line 25 at r1](https://reviewable.io/reviews/qtox/qtox/5932#-Lu-bV3eAKcSsHl70OHz:-Lu-bV3eAKcSsHl70OI-:bwoch3i) ([raw file](https://github.com/qtox/qtox/blob/e94b16b2912349df473c82a0bd1c606b78ff2cc5/src/widget/chatformheader.h#L25)):*
> ```objc
> #include <QWidget>
> 
> #include "src/core/extension.h"
> ```

I'm not too happy about having to include such a low level class here, do you see any way around this?
___
*[src/widget/chatformheader.cpp, line 234 at r1](https://reviewable.io/reviews/qtox/qtox/5932#-Lu-bmqr8ly5TgoLd2s9:-Lu-bmqr8ly5TgoLd2sA:b-gayqhv) ([raw file](https://github.com/qtox/qtox/blob/e94b16b2912349df473c82a0bd1c606b78ff2cc5/src/widget/chatformheader.cpp#L234)):*
> ```cpp
> }
> 
> void ChatFormHeader::updateExtensionSupport(ExtensionSet extensions)
> ```

what do you think about making a dedicated UI element for displaying `ExtensionSet`? It would be easy to also include this in the `Details` page of a user/group. It would also basically force us t [...]

2019-11-18 22:38 UTC, sudden6 commented
Generally I'm also missing:

- update of INSTALL.md, especially the dependecies section
- maybe add a few sentences to the user manual explaining how the new icon works

2019-11-19 04:11 UTC, sphaerophoria reviewed
> *[Reviewable](https://reviewable.io/reviews/qtox/qtox/5932)* status: 0 of 1 LGTMs obtained

___
*[.travis/build-ubuntu-16-04.sh, line 149 at r1](https://reviewable.io/reviews/qtox/qtox/5932#-Lu-M_OREZXgb65qk7_V:-Lu0e1MdEUNJjWZ0e0Cj:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/e94b16b2912349df473c82a0bd1c606b78ff2cc5/.travis/build-ubuntu-16-04.sh#L149)):*
<details><summary><i>Previously, sudden6 wrote…</i></summary><blockquote>

style nit: space between `#` and name to match the rest of the file
</blockquote></details>

Done.
___
*[.travis/build-ubuntu-16-04.sh, line 159 at r1](https://reviewable.io/reviews/qtox/qtox/5932#-Lu-MdE_6ewe-ej-Padt:-Lu0e1dJATIjQ0XzxnaW:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/e94b16b2912349df473c82a0bd1c606b78ff2cc5/.travis/build-ubuntu-16-04.sh#L159)):*
<details><summary><i>Previously, sudden6 wrote…</i></summary><blockquote>

same
</blockquote></details>

Done.
___
*[osx/qTox-Mac-Deployer-ULTIMATE.sh, line 87 at r1](https://reviewable.io/reviews/qtox/qtox/5932#-Lu-N29p-VjcXgGVFyBO:-Lu0eG-fD9lXJWsOpyQT:b-p4q95s) ([raw file](https://github.com/qtox/qtox/blob/e94b16b2912349df473c82a0bd1c606b78ff2cc5/osx/qTox-Mac-Deployer-ULTIMATE.sh#L87)):*
<details><summary><i>Previously, sudden6 wrote…</i></summary><blockquote>

IDK why the rest of the build script uses `fcho`, but we should use it everywhere or remove it everywhere
</blockquote></details>

I just copied the build_toxcore script. The "pretty printing" looks kinda messed too :S
___
*[osx/qTox-Mac-Deployer-ULTIMATE.sh, line 92 at r1](https://reviewable.io/reviews/qtox/qtox/5932#-Lu-NKHk7fjLlqFscG6z:-Lu0e7JM40P-fMEGKoGI:bku428a) ([raw file](https://github.com/qtox/qtox/blob/e94b16b2912349df473c82a0bd1c606b78ff2cc5/osx/qTox-Mac-Deployer-ULTIMATE.sh#L92)):*
<details><summary><i>Previously, sudden6 wrote…</i></summary><blockquote>

why the sleep command?
</blockquote></details>

Not sure... copied from above
___
*[osx/qTox-Mac-Deployer-ULTIMATE.sh, line 110 at r1](https://reviewable.io/reviews/qtox/qtox/5932#-Lu-NNdiCOZD4aymCQfd:-Lu0fDwh8F1stNme099B:bku428a) ([raw file](https://github.com/qtox/qtox/blob/e94b16b2912349df473c82a0bd1c606b78ff2cc5/osx/qTox-Mac-Deployer-ULTIMATE.sh#L110)):*
<details><summary><i>Previously, sudden6 wrote…</i></summary><blockquote>

why the sleep command?
</blockquote></details>

Not sure... copied from above
___
*[osx/qTox-Mac-Deployer-ULTIMATE.sh, line 249 at r1](https://reviewable.io/reviews/qtox/qtox/5932#-Lu-NWiv4azorD1QB6wC:-Lu0fLuv4d8AyQjVoXlL:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/e94b16b2912349df473c82a0bd1c606b78ff2cc5/osx/qTox-Mac-Deployer-ULTIMATE.sh#L249)):*
<details><summary><i>Previously, sudden6 wrote…</i></summary><blockquote>

wrong comment
</blockquote></details>

Done.
___
*[osx/qTox-Mac-Deployer-ULTIMATE.sh, line 264 at r1](https://reviewable.io/reviews/qtox/qtox/5932#-Lu-NY8K2a7T1Hr5BFCh:-Lu0fMAq5yGyfyLB4Uip:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/e94b16b2912349df473c82a0bd1c606b78ff2cc5/osx/qTox-Mac-Deployer-ULTIMATE.sh#L264)):*
<details><summary><i>Previously, sudden6 wrote…</i></summary><blockquote>

wrong comment
</blockquote></details>

Done.
___
*[src/core/coreext.h, line 57 at r1](https://reviewable.io/reviews/qtox/qtox/5932#-Lu-ONtrDAdOIzQAf8WM:-Lu0fR0f7byKERuUgtNh:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/e94b16b2912349df473c82a0bd1c606b78ff2cc5/src/core/coreext.h#L57)):*
<details><summary><i>Previously, sudden6 wrote…</i></summary><blockquote>

typo, `documentation`
</blockquote></details>

Done.
___
*[src/core/coreext.h, line 86 at r1](https://reviewable.io/reviews/qtox/qtox/5932#-Lu-Te4x4ANEV3Ex5mpg:-Lu0fSlu4qgCyP8knpnY:bk4fnts) ([raw file](https://github.com/qtox/qtox/blob/e94b16b2912349df473c82a0bd1c606b78ff2cc5/src/core/coreext.h#L86)):*
<details><summary><i>Previously, sudden6 wrote…</i></summary><blockquote>

It is unclear to me why `toxExtMessages` and `packetList` don't need to be freed by `Packet`, can you please explain?
</blockquote></details>

ToxExtensionMessages* is a longstanding pointer to the CoreExt handle to the extension. This is retrieved on CoreExt construction and held until CoreExt destruction.  The packet just needs a handle to it to call tox_extension_messages_append.

The packetList doesn't need to be freed since toxext_send will do that for us
```
/**
 * Sends and frees an existing packet
 */
int toxext_send(struct ToxExtPacketList *packet);
```
___
*[src/core/coreext.cpp, line 73 at r1](https://reviewable.io/reviews/qtox/qtox/5932#-Lu-UfxG2CTc2IsX-8tt:-Lu0i2359HGHbFUva7FY:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/e94b16b2912349df473c82a0bd1c606b78ff2cc5/src/core/coreext.cpp#L73)):*
<details><summary><i>Previously, sudden6 wrote…</i></summary><blockquote>

Please document the special return value
</blockquote></details>

Done.
___
*[src/core/coreext.cpp, line 90 at r1](https://reviewable.io/reviews/qtox/qtox/5932#-Lu-Uupj7kxJmabnP9QL:-Lu0i5ss-p8KVlUi8Ww1:bpuw6qz) ([raw file](https://github.com/qtox/qtox/blob/e94b16b2912349df473c82a0bd1c606b78ff2cc5/src/core/coreext.cpp#L90)):*
<details><summary><i>Previously, sudden6 wrote…</i></summary><blockquote>

why set `hasBeenSent` to `true` if the packet failed to send? At least needs a comment
</blockquote></details>

The packet should have been freed whether or not the send actually was successful, so we need to flag that our packet abstraction is no longer valid
___
*[src/core/coreext.cpp, line 96 at r1](https://reviewable.io/reviews/qtox/qtox/5932#-Lu-V9Pl5zM3jKVrPijJ:-Lu0iPBL6GU9UUZOdYAa:b-ty7cs7) ([raw file](https://github.com/qtox/qtox/blob/e94b16b2912349df473c82a0bd1c606b78ff2cc5/src/core/coreext.cpp#L96)):*
<details><summary><i>Previously, sudden6 wrote…</i></summary><blockquote>

This will trigger negotiations when the status changes are `Online -> Away` or `Online->Busy`and some others too, is this intended?
</blockquote></details>

I think I figured it wasn't harmful and isn't worth the effort of caching the old state
___
*[src/model/brokenmessagereason.h, line 24 at r1](https://reviewable.io/reviews/qtox/qtox/5932#-Lu-Vkt78nTlaVlf7CxP:-Lu0iebG0DgmFZVrXbfz:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/e94b16b2912349df473c82a0bd1c606b78ff2cc5/src/model/brokenmessagereason.h#L24)):*
<details><summary><i>Previously, sudden6 wrote…</i></summary><blockquote>

if this can be cast to int, `int` should be the base type of the enum
</blockquote></details>

Done.
___
*[src/model/chathistory.cpp, line 452 at r1](https://reviewable.io/reviews/qtox/qtox/5932#-Lu-WVOo8ZUm-AnfYxoA:-Lu0ig4O5d5G4VPVd98V:bb7zxm7) ([raw file](https://github.com/qtox/qtox/blob/e94b16b2912349df473c82a0bd1c606b78ff2cc5/src/model/chathistory.cpp#L452)):*
<details><summary><i>Previously, sudden6 wrote…</i></summary><blockquote>

why the extra `()`?
</blockquote></details>

It's part of a ternary operator one line down. I usually flag ternary operators with a () to make them look more like an if statement, might just be a stylistic habit kinda thing. I can remove it if you'd like
___
*[src/model/chathistory.cpp, line 484 at r1](https://reviewable.io/reviews/qtox/qtox/5932#-Lu-WqmA8dq6hL4xqHVu:-Lu0is_w9oQJUi0bY_Kx:bhpvff4) ([raw file](https://github.com/qtox/qtox/blob/e94b16b2912349df473c82a0bd1c606b78ff2cc5/src/model/chathistory.cpp#L484)):*
<details><summary><i>Previously, sudden6 wrote…</i></summary><blockquote>

you assert against this case, shouldn't there be at least a message that this case is not supposed to happen?
</blockquote></details>

I don't assert against this case. I assert against isCompleted and isBroken both being true. This handles the case where neither of them were true
___
*[src/model/groupmessagedispatcher.cpp, line 70 at r1](https://reviewable.io/reviews/qtox/qtox/5932#-Lu-_6QS9DR9rt2GQfN-:-Lu0izAICJGKdrEm9LLK:b-5mhv3e) ([raw file](https://github.com/qtox/qtox/blob/e94b16b2912349df473c82a0bd1c606b78ff2cc5/src/model/groupmessagedispatcher.cpp#L70)):*
<detail [...]

2019-11-19 04:13 UTC, sphaerophoria commented
Alright pushed an update. I believe I've addressed everything I wanted to without further discussion.

I added a new test for the long action message case that was failing. I believe I also fixed an issue where contacts were not being sorted correctly due to the wrong status being emitted.

2019-11-19 16:19 UTC, sudden6 requested changes
> Reviewed 11 of 17 files at r2, 9 of 9 files at r4.
> *[Reviewable](https://reviewable.io/reviews/qtox/qtox/5932)* status: 0 of 1 LGTMs obtained

___
*[INSTALL.md, line 37 at r4](https://reviewable.io/reviews/qtox/qtox/5932#-Lu3NNlI4q96gSB3K5YA:-Lu3NNlJ8-IjytnQk11I:b-mptsh2) ([raw file](https://github.com/qtox/qtox/blob/ff76ae27a49ab8e6471d40f89cbba957c476eb96/INSTALL.md#L37)):*
> ```Markdown
> ## Dependencies
> 
> | Name          | Version     | Modules                                                  |
> ```

This table needs entries for toxext and extention messages
___
*[osx/qTox-Mac-Deployer-ULTIMATE.sh, line 87 at r1](https://reviewable.io/reviews/qtox/qtox/5932#-Lu-N29p-VjcXgGVFyBO:-Lu3Ne0VBxapzhNUAn85:b-y6l3n4) ([raw file](https://github.com/qtox/qtox/blob/e94b16b2912349df473c82a0bd1c606b78ff2cc5/osx/qTox-Mac-Deployer-ULTIMATE.sh#L87)):*
<details><summary><i>Previously, sphaerophoria wrote…</i></summary><blockquote>

I just copied the build_toxcore script. The "pretty printing" looks kinda messed too :S
</blockquote></details>

ok then, if it's used in the tox section too it's not really relevant for this PR
___
*[osx/qTox-Mac-Deployer-ULTIMATE.sh, line 92 at r1](https://reviewable.io/reviews/qtox/qtox/5932#-Lu-NKHk7fjLlqFscG6z:-Lu3Ns3L4VGA0iwnNnYL:b-y6l3n4) ([raw file](https://github.com/qtox/qtox/blob/e94b16b2912349df473c82a0bd1c606b78ff2cc5/osx/qTox-Mac-Deployer-ULTIMATE.sh#L92)):*
<details><summary><i>Previously, sphaerophoria wrote…</i></summary><blockquote>

Not sure... copied from above
</blockquote></details>

ok then, if it's used in the tox section too it's not really relevant for this PR
___
*[osx/qTox-Mac-Deployer-ULTIMATE.sh, line 110 at r1](https://reviewable.io/reviews/qtox/qtox/5932#-Lu-NNdiCOZD4aymCQfd:-Lu3NtY-1Mrzx4LzSRYf:b32wtd) ([raw file](https://github.com/qtox/qtox/blob/e94b16b2912349df473c82a0bd1c606b78ff2cc5/osx/qTox-Mac-Deployer-ULTIMATE.sh#L110)):*
<details><summary><i>Previously, sphaerophoria wrote…</i></summary><blockquote>

Not sure... copied from above
</blockquote></details>

ok
___
*[src/core/coreext.h, line 86 at r1](https://reviewable.io/reviews/qtox/qtox/5932#-Lu-Te4x4ANEV3Ex5mpg:-Lu3O6ngBRY-anoLY7nf:b-198fch) ([raw file](https://github.com/qtox/qtox/blob/e94b16b2912349df473c82a0bd1c606b78ff2cc5/src/core/coreext.h#L86)):*
<details><summary><i>Previously, sphaerophoria wrote…</i></summary><blockquote>

ToxExtensionMessages* is a longstanding pointer to the CoreExt handle to the extension. This is retrieved on CoreExt construction and held until CoreExt destruction.  The packet just needs a handle to it to call tox_extension_messages_append.

The packetList doesn't need to be freed since toxext_send will do that for us
```
/**
 * Sends and frees an existing packet
 */
int toxext_send(struct ToxExtPacketList *packet);
```

</blockquote></details>

ok, could you add short comments to these variables? This is to avoid someone thinking we have a memory leak and free them manually.
___
*[src/core/coreext.cpp, line 73 at r1](https://reviewable.io/reviews/qtox/qtox/5932#-Lu-UfxG2CTc2IsX-8tt:-Lu3OMGi-YxigSqrbtsh:b-dfadne) ([raw file](https://github.com/qtox/qtox/blob/e94b16b2912349df473c82a0bd1c606b78ff2cc5/src/core/coreext.cpp#L73)):*
<details><summary><i>Previously, sphaerophoria wrote…</i></summary><blockquote>

Done.
</blockquote></details>

I was hoping for a doxygen header with the special return value mentioned for `@return`
___
*[src/core/coreext.cpp, line 90 at r1](https://reviewable.io/reviews/qtox/qtox/5932#-Lu-Uupj7kxJmabnP9QL:-Lu3ObHj7ED_R9zGE7Md:b9of5e6) ([raw file](https://github.com/qtox/qtox/blob/e94b16b2912349df473c82a0bd1c606b78ff2cc5/src/core/coreext.cpp#L90)):*
<details><summary><i>Previously, sphaerophoria wrote…</i></summary><blockquote>

The packet should have been freed whether or not the send actually was successful, so we need to flag that our packet abstraction is no longer valid
</blockquote></details>

please add a comment for that
___
*[src/core/coreext.cpp, line 96 at r1](https://reviewable.io/reviews/qtox/qtox/5932#-Lu-V9Pl5zM3jKVrPijJ:-Lu3Ow-77vj0Zos_pDND:b-2myesf) ([raw file](https://github.com/qtox/qtox/blob/e94b16b2912349df473c82a0bd1c606b78ff2cc5/src/core/coreext.cpp#L96)):*
<details><summary><i>Previously, sphaerophoria wrote…</i></summary><blockquote>

I think I figured it wasn't harmful and isn't worth the effort of caching the old state
</blockquote></details>

IMO renegotiating that often is not a very good idea, it generates unnecessary traffic
___
*[src/model/chathistory.cpp, line 452 at r1](https://reviewable.io/reviews/qtox/qtox/5932#-Lu-WVOo8ZUm-AnfYxoA:-Lu3RW207J9Q8X5pHpNX:b-z2v6tg) ([raw file](https://github.com/qtox/qtox/blob/e94b16b2912349df473c82a0bd1c606b78ff2cc5/src/model/chathistory.cpp#L452)):*
<details><summary><i>Previously, sphaerophoria wrote…</i></summary><blockquote>

It's part of a ternary operator one line down. I usually flag ternary operators with a () to make them look more like an if statement, might just be a stylistic habit kinda thing. I can remove it if you'd like
</blockquote></details>

I have never seen this style and I don't think it's used in qTox, so I think it's better to remove them
___
*[src/model/chathistory.cpp, line 484 at r1](https://reviewable.io/reviews/qtox/qtox/5932#-Lu-WqmA8dq6hL4xqHVu:-Lu3SD1T2GYzs5JIhtAJ:b-z87oqo) ([raw file](https://github.com/qtox/qtox/blob/e94b16b2912349df473c82a0bd1c606b78ff2cc5/src/model/chathistory.cpp#L484)):*
<details><summary><i>Previously, sphaerophoria wrote…</i></summary><blockquote>

I don't assert against this case. I assert against isCompleted and isBroken both being true. This handles the case where neither of them were true
</blockquote></details>

ok, get it now
___
*[src/model/groupmessagedispatcher.cpp, line 70 at r1](https://reviewable.io/reviews/qtox/qtox/5932#-Lu-_6QS9DR9rt2GQfN-:-Lu3STAa2ivqtLQvK9MV:b-acdyxq) ([raw file](https://github.com/qtox/qtox/blob/e94b16b2912349df473c82a0bd1c606b78ff2cc5/src/model/groupmessagedispatcher.cpp#L70)):*
<details><summary><i>Previously, sphaerophoria wrote…</i></summary><blockquote>

This is stubbed. We don't do anything with the message for real we just immediately flag it as broken
</blockquote></details>

ok, to me `stub` means completely unimplemented so this was confusing
___
*[src/widget/chatformheader.h, line 25 at r1](https://reviewable.io/reviews/qtox/qtox/5932#-Lu-bV3eAKcSsHl70OHz:-Lu3PNZ1BfHBFuhsYhIa:b-58bnsn) ([raw file](https://github.com/qtox/qtox/blob/e94b16b2912349df473c82a0bd1c606b78ff2cc5/src/widget/chatformheader.h#L25)):*
<details><summary><i>Previously, sphaerophoria wrote…</i></summary><blockquote>

We could move the ExtensionSet definition somewhere else... I didn't realize we had a rule against this. I'm cool with leaving it too :man_shrugging:  up to you
</blockquote></details>

IDK if there's a rule for that, it just seems like bad software design to create dependencies in components that don't have a lot to do with each other.


<!-- Sent from Reviewable.io -->

2019-11-20 23:32 UTC, sudden6 commented
Contact sorting is still broken with v2 of this PR.

2019-11-22 09:16 UTC, anthonybilinski commented
Possibly for the same root cause of broken sorting, but https://github.com/qTox/qTox/issues/5400 seems 100% reproducible running this PR.

2019-11-23 20:40 UTC, sphaerophoria commented
@sudden6 do you happen to have a good repro for how contact sorting is wrong? I'm having trouble reproducing it on V2

2019-11-23 21:00 UTC, sphaerophoria commented
Found a bug where adding a new friend would always hit an uninitialized memory bug where isNegotiating would be true on construction of a friend. This resulted in us never timing out on negotiating with new friends and getting stuck in the "negotiating" state forever. Fix incoming in V3 with a fix for the call buttons as well

2019-11-23 21:43 UTC, sphaerophoria reviewed
> Reviewed 11 of 58 files at r1, 5 of 17 files at r2.
> *[Reviewable](https://reviewable.io/reviews/qtox/qtox/5932)* status: 0 of 1 LGTMs obtained

___
*[INSTALL.md, line 37 at r4](https://reviewable.io/reviews/qtox/qtox/5932#-Lu3NNlI4q96gSB3K5YA:-LuP9wYw6eMY075vgFjp:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/ff76ae27a49ab8e6471d40f89cbba957c476eb96/INSTALL.md#L37)):*
<details><summary><i>Previously, sudden6 wrote…</i></summary><blockquote>

This table needs entries for toxext and extention messages
</blockquote></details>

Done.
___
*[src/core/coreext.cpp, line 73 at r1](https://reviewable.io/reviews/qtox/qtox/5932#-Lu-UfxG2CTc2IsX-8tt:-LuP7gGI-7yLmaYKimS8:byo3nq7) ([raw file](https://github.com/qtox/qtox/blob/e94b16b2912349df473c82a0bd1c606b78ff2cc5/src/core/coreext.cpp#L73)):*
<details><summary><i>Previously, sudden6 wrote…</i></summary><blockquote>

I was hoping for a doxygen header with the special return value mentioned for `@return`
</blockquote></details>

Added it to the ICoreExtPacket documentation
___
*[src/core/coreext.cpp, line 90 at r1](https://reviewable.io/reviews/qtox/qtox/5932#-Lu-Uupj7kxJmabnP9QL:-LuP7yC-BojQMhFafLbj:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/e94b16b2912349df473c82a0bd1c606b78ff2cc5/src/core/coreext.cpp#L90)):*
<details><summary><i>Previously, sudden6 wrote…</i></summary><blockquote>

please add a comment for that
</blockquote></details>

Done.
___
*[src/core/coreext.cpp, line 96 at r1](https://reviewable.io/reviews/qtox/qtox/5932#-Lu-V9Pl5zM3jKVrPijJ:-LuP82GU1Si3EaAmxoH1:bsknw4o) ([raw file](https://github.com/qtox/qtox/blob/e94b16b2912349df473c82a0bd1c606b78ff2cc5/src/core/coreext.cpp#L96)):*
<details><summary><i>Previously, sudden6 wrote…</i></summary><blockquote>

IMO renegotiating that often is not a very good idea, it generates unnecessary traffic
</blockquote></details>

I agree, but I'd rather have the minor bandwidth increase on friend state change than have to cache the state of all friends localliy. It's only like a couple packets every state change which shouldn't even happen that often.
___
*[src/model/chathistory.cpp, line 452 at r1](https://reviewable.io/reviews/qtox/qtox/5932#-Lu-WVOo8ZUm-AnfYxoA:-LuP8ez084ZniYtOTJL6:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/e94b16b2912349df473c82a0bd1c606b78ff2cc5/src/model/chathistory.cpp#L452)):*
<details><summary><i>Previously, sudden6 wrote…</i></summary><blockquote>

I have never seen this style and I don't think it's used in qTox, so I think it's better to remove them
</blockquote></details>

Done.
___
*[src/widget/chatformheader.h, line 25 at r1](https://reviewable.io/reviews/qtox/qtox/5932#-Lu-bV3eAKcSsHl70OHz:-LuP8rrf1-sZRCz7Qsrd:bc0sw3y) ([raw file](https://github.com/qtox/qtox/blob/e94b16b2912349df473c82a0bd1c606b78ff2cc5/src/widget/chatformheader.h#L25)):*
<details><summary><i>Previously, sudden6 wrote…</i></summary><blockquote>

IDK if there's a rule for that, it just seems like bad software design to create dependencies in components that don't have a lot to do with each other.
</blockquote></details>

I don't really understand the problem, the concept of an extension has to be spread all the way from the bottom to the top. Is there a better place for me to put the extension definition? It's not like the CoreExt abstraction is leaking all the way up here


<!-- Sent from Reviewable.io -->

2019-11-23 22:39 UTC, sudden6 requested changes
> Reviewed 1 of 17 files at r2, 8 of 8 files at r5.
> *[Reviewable](https://reviewable.io/reviews/qtox/qtox/5932)* status: 0 of 1 LGTMs obtained

___
*[src/core/coreext.cpp, line 96 at r1](https://reviewable.io/reviews/qtox/qtox/5932#-Lu-V9Pl5zM3jKVrPijJ:-LuPO5My20kKPEqHEUXg:byyoi2q) ([raw file](https://github.com/qtox/qtox/blob/e94b16b2912349df473c82a0bd1c606b78ff2cc5/src/core/coreext.cpp#L96)):*
<details><summary><i>Previously, sphaerophoria wrote…</i></summary><blockquote>

I agree, but I'd rather have the minor bandwidth increase on friend state change than have to cache the state of all friends localliy. It's only like a couple packets every state change which shouldn't even happen that often.
</blockquote></details>

I think we have slight misunderstanding here. I'm just against re-negoiiating  on state changes where the friend doesn't actually go offline in between. e.g. `Busy` -> `Away`, there shouldn't be any need to resend or cache the toxext packets, since the friend never actually went offline.

You just need to rewrite this statement to trigger only on `Offline` -> `Online | Away | Busy`  while currently it triggers on `Online | Away | Busy` -> `Online | Away | Busy`. The current state of the friend should be available somewhere in qTox/Tox anyway so I don't think it's too much to avoid these needless packets.
___
*[src/core/coreext.cpp, line 92 at r5](https://reviewable.io/reviews/qtox/qtox/5932#-LuPO-Oh6qfbgehH5ce0:-LuPO-Oh6qfbgehH5ce1:b-bkaxer) ([raw file](https://github.com/qtox/qtox/blob/8b7dc0bf443c0ddf4e97c6990df3cc25ec604779/src/core/coreext.cpp#L92)):*
> ```cpp
>         qWarning() << "Failed to send packet";
>     }
>     // Indicate we've sent the packet ven on failure since our packetlist will
> ```

typo `even`


<!-- Sent from Reviewable.io -->

2019-11-23 23:46 UTC, sphaerophoria reviewed
> *[Reviewable](https://reviewable.io/reviews/qtox/qtox/5932)* status: 0 of 1 LGTMs obtained

___
*[src/core/coreext.cpp, line 96 at r1](https://reviewable.io/reviews/qtox/qtox/5932#-Lu-V9Pl5zM3jKVrPijJ:-LuPdq8r3islFz-LY_JM:b-fi9yre) ([raw file](https://github.com/qtox/qtox/blob/e94b16b2912349df473c82a0bd1c606b78ff2cc5/src/core/coreext.cpp#L96)):*
<details><summary><i>Previously, sudden6 wrote…</i></summary><blockquote>

I think we have slight misunderstanding here. I'm just against re-negoiiating  on state changes where the friend doesn't actually go offline in between. e.g. `Busy` -> `Away`, there shouldn't be any need to resend or cache the toxext packets, since the friend never actually went offline.

You just need to rewrite this statement to trigger only on `Offline` -> `Online | Away | Busy`  while currently it triggers on `Online | Away | Busy` -> `Online | Away | Busy`. The current state of the friend should be available somewhere in qTox/Tox anyway so I don't think it's too much to avoid these needless packets.
</blockquote></details>

I don't _think_ i misunderstand you, I think we just disagree.

I'm arguing that in order to only trigger on Offline -> X I'd have to cache the state of each friend in CoreExt since the signal from Friend only provides the new state. I'm arguing that the state changes between two online states (such as Away -> Busy) are not that frequent. On top of that the extra negotiation cost on each state change is so insignificant in my mind the effort of caching all friend state locally and the bugs that could occur from mismatched state is not worth the effort to save a couple bytes of traffic every once in a while.


<!-- Sent from Reviewable.io -->

2019-11-23 23:49 UTC, sphaerophoria reviewed
> *[Reviewable](https://reviewable.io/reviews/qtox/qtox/5932)* status: 0 of 1 LGTMs obtained

___
*[src/core/coreext.cpp, line 92 at r5](https://reviewable.io/reviews/qtox/qtox/5932#-LuPO-Oh6qfbgehH5ce0:-LuPeaKS9sx3WoH1AJfs:b44twt) ([raw file](https://github.com/qtox/qtox/blob/8b7dc0bf443c0ddf4e97c6990df3cc25ec604779/src/core/coreext.cpp#L92)):*
<details><summary><i>Previously, sudden6 wrote…</i></summary><blockquote>

typo `even`
</blockquote></details>

🤦


<!-- Sent from Reviewable.io -->

2019-11-24 11:37 UTC, sudden6 requested changes
> *[Reviewable](https://reviewable.io/reviews/qtox/qtox/5932)* status: 0 of 1 LGTMs obtained

___
*[src/core/coreext.cpp, line 96 at r1](https://reviewable.io/reviews/qtox/qtox/5932#-Lu-V9Pl5zM3jKVrPijJ:-LuSACPQ01GDURTti7i2:bjj2kiz) ([raw file](https://github.com/qtox/qtox/blob/e94b16b2912349df473c82a0bd1c606b78ff2cc5/src/core/coreext.cpp#L96)):*
> I don't think i misunderstand you, I think we just disagree.
yeah, I was wrong on the misunderstanding part it seems.

With the traffic thing I'm thinking mostly of mobile users on limited data/power, where each packet sent/received counts. For me, I think the problem of caching the friend state is easily solved, by e.g. extending the `friendStatusChanged(...)` signal to contain a `previousState` parameter. This information is easily available from c-toxcore with the `tox_friend_get_status(...)` function. As for bugs, I don't see any problem of introducing new bugs in existing functionality with that change. Worst case there will be bugs in this PR, which we can fix before merge.
___
*[src/widget/chatformheader.h, line 25 at r1](https://reviewable.io/reviews/qtox/qtox/5932#-Lu-bV3eAKcSsHl70OHz:-LuS8iGz6htNSxbxedAf:b-pu2mqo) ([raw file](https://github.com/qtox/qtox/blob/e94b16b2912349df473c82a0bd1c606b78ff2cc5/src/widget/chatformheader.h#L25)):*
> the concept of an extension has to be spread all the way from the bottom to the top

I don't quite agree with that, ideally the `ChatFormHeader` wouldn't need to know what an extension is, only the UI element visualizing the extensions. One way I could think of how to solve this would be to use `connect` to pass that info from the friend model directly to UI element visualizing the extension state.

The reasoning behind this is, that `ChatFormHeader` has nothing to do extensions at all, so why would it need to know what an extension even is? `ChatFormHeader` is just a collection of UI elements, with as little logic as possible. The Qt UI model allows us to forward state changes in the extension set directly to the UI displaying them, so we should use it.


<!-- Sent from Reviewable.io -->

2019-11-24 12:50 UTC, sudden6 commented
> @sudden6 do you happen to have a good repro for how contact sorting is wrong? I'm having trouble reproducing it on V2

No not really, it seems to happen over time on my main qTox instance when people go online/offline

2019-11-24 19:25 UTC, sphaerophoria reviewed
> *[Reviewable](https://reviewable.io/reviews/qtox/qtox/5932)* status: 0 of 1 LGTMs obtained

___
*[src/core/coreext.cpp, line 96 at r1](https://reviewable.io/reviews/qtox/qtox/5932#-Lu-V9Pl5zM3jKVrPijJ:-LuTrwvF6c4SWZ6TiTxA:b-r8dtua) ([raw file](https://github.com/qtox/qtox/blob/e94b16b2912349df473c82a0bd1c606b78ff2cc5/src/core/coreext.cpp#L96)):*
<details><summary><i>Previously, sudden6 wrote…</i></summary><blockquote>

> I don't think i misunderstand you, I think we just disagree.
yeah, I was wrong on the misunderstanding part it seems.

With the traffic thing I'm thinking mostly of mobile users on limited data/power, where each packet sent/received counts. For me, I think the problem of caching the friend state is easily solved, by e.g. extending the `friendStatusChanged(...)` signal to contain a `previousState` parameter. This information is easily available from c-toxcore with the `tox_friend_get_status(...)` function. As for bugs, I don't see any problem of introducing new bugs in existing functionality with that change. Worst case there will be bugs in this PR, which we can fix before merge.
</blockquote></details>

Yeah a previousState parameter makes a lot of sense... I'm okay with that. That cleans up some of the widget logic too
___
*[src/widget/chatformheader.h, line 25 at r1](https://reviewable.io/reviews/qtox/qtox/5932#-Lu-bV3eAKcSsHl70OHz:-LuTrHHz9zBTN-Zg_qZe:boax0y3) ([raw file](https://github.com/qtox/qtox/blob/e94b16b2912349df473c82a0bd1c606b78ff2cc5/src/widget/chatformheader.h#L25)):*
<details><summary><i>Previously, sudden6 wrote…</i></summary><blockquote>

> the concept of an extension has to be spread all the way from the bottom to the top

I don't quite agree with that, ideally the `ChatFormHeader` wouldn't need to know what an extension is, only the UI element visualizing the extensions. One way I could think of how to solve this would be to use `connect` to pass that info from the friend model directly to UI element visualizing the extension state.

The reasoning behind this is, that `ChatFormHeader` has nothing to do extensions at all, so why would it need to know what an extension even is? `ChatFormHeader` is just a collection of UI elements, with as little logic as possible. The Qt UI model allows us to forward state changes in the extension set directly to the UI displaying them, so we should use it.
</blockquote></details>

Ah so this is more of an argument about passthrough apis then? 

It's kinda tricky because ChatFormHeader doesn't really know whether or not it's in a friend call or a group call. In the case of a group call that's fine and we just leave the extension support off.

I prefer the way it is now over passing in a Friend pointer for ChatFormHeader to connect to that has to be a nullptr on group calls. I guess you could have an optional API where you optionally inject the friend late for it to connect to but I don't really think that's any cleaner than having the passthrough from ChatForm <-> ChatFormHeader <-> ExtensionStatus


<!-- Sent from Reviewable.io -->

2019-11-24 19:48 UTC, sphaerophoria commented
> > @sudden6 do you happen to have a good repro for how contact sorting is wrong? I'm having trouble reproducing it on V2
> 
> No not really, it seems to happen over time on my main qTox instance when people go online/offline

Alright well I guess I'll keep an eye out for it... I haven't seen it since V3 and I did fix a couple bad cases (uninitialized var on construction of Friend and wrong status emitted) that could result in the friend state not being quite right. Maybe it's been fixed 🤞

2019-11-24 19:50 UTC, sphaerophoria reviewed
> *[Reviewable](https://reviewable.io/reviews/qtox/qtox/5932)* status: 0 of 1 LGTMs obtained

___
*[src/core/coreext.cpp, line 96 at r1](https://reviewable.io/reviews/qtox/qtox/5932#-Lu-V9Pl5zM3jKVrPijJ:-LuTxSY0BZE3vGmpz0i7:b3kpap7) ([raw file](https://github.com/qtox/qtox/blob/e94b16b2912349df473c82a0bd1c606b78ff2cc5/src/core/coreext.cpp#L96)):*
<details><summary><i>Previously, sphaerophoria wrote…</i></summary><blockquote>

Yeah a previousState parameter makes a lot of sense... I'm okay with that. That cleans up some of the widget logic too
</blockquote></details>

Ah the signal comes from core, not coreext. I don't feel that strongly about not caching the state in CoreExt to avoid the extra negotiations so I've just done that. I for some reason got it into my head that that would be a riskier change than it was


<!-- Sent from Reviewable.io -->

2019-11-24 20:13 UTC, sphaerophoria commented
I've pushed a fix for users not being resorted correctly when going offline. TBH I'm not sure how this was ever correct but initial testing of letting a friend go offline/online a couple times indicates that it's a valid fix

2019-11-24 20:42 UTC, sudden6 commented
___
*[src/widget/chatformheader.h, line 25 at r1](https://reviewable.io/reviews/qtox/qtox/5932#-Lu-bV3eAKcSsHl70OHz:-LuU8KdJ7B2gb9K9yETo:bko9gf5) ([raw file](https://github.com/qtox/qtox/blob/e94b16b2912349df473c82a0bd1c606b78ff2cc5/src/widget/chatformheader.h#L25)):*
<details><summary><i>Previously, sphaerophoria wrote…</i></summary><blockquote>

Ah so this is more of an argument about passthrough apis then? 

It's kinda tricky because ChatFormHeader doesn't really know whether or not it's in a friend call or a group call. In the case of a group call that's fine and we just leave the extension support off.

I prefer the way it is now over passing in a Friend pointer for ChatFormHeader to connect to that has to be a nullptr on group calls. I guess you could have an optional API where you optionally inject the friend late for it to connect to but I don't really think that's any cleaner than having the passthrough from ChatForm <-> ChatFormHeader <-> ExtensionStatus
</blockquote></details>

I thought `ChatFormHeader` already new if it's in a friend or group chat, seems I was wrong. Then your reasoning that it's not really cleaner makes sense to me. I'm ok with the current approach.


<!-- Sent from Reviewable.io -->

2019-11-24 20:47 UTC, sudden6 requested changes
> Reviewed 3 of 3 files at r6.
> *[Reviewable](https://reviewable.io/reviews/qtox/qtox/5932)* status: 0 of 1 LGTMs obtained

___
*[src/core/coreext.cpp, line 96 at r1](https://reviewable.io/reviews/qtox/qtox/5932#-Lu-V9Pl5zM3jKVrPijJ:-LuU92m_-iNQuq01wDZo:bgkbcl1) ([raw file](https://github.com/qtox/qtox/blob/e94b16b2912349df473c82a0bd1c606b78ff2cc5/src/core/coreext.cpp#L96)):*
<details><summary><i>Previously, sphaerophoria wrote…</i></summary><blockquote>

Ah the signal comes from core, not coreext. I don't feel that strongly about not caching the state in CoreExt to avoid the extra negotiations so I've just done that. I for some reason got it into my head that that would be a riskier change than it was
</blockquote></details>

The solution seems good for this PR now. Maybe you can submit an additional PR adding the `previousState` parameter to the `friendStatusChanged` signal? AFAICT this seems to be a common use case.


<!-- Sent from Reviewable.io -->

2019-11-24 20:47 UTC, sudden6 approved these changes
> *[Reviewable](https://reviewable.io/reviews/qtox/qtox/5932)* status: 0 of 1 LGTMs obtained



<!-- Sent from Reviewable.io -->

2019-11-24 20:49 UTC, sudden6 commented
Mostly looks good to me now, I'll run it for another day to see if something turns up.

@anthonybilinski should I wait for your review too or just go ahead and merge when it's stable?

2019-11-24 21:05 UTC, sphaerophoria reviewed
> *[Reviewable](https://reviewable.io/reviews/qtox/qtox/5932)* status: 0 of 1 LGTMs obtained

___
*[src/core/coreext.cpp, line 96 at r1](https://reviewable.io/reviews/qtox/qtox/5932#-Lu-V9Pl5zM3jKVrPijJ:-LuUDWHpCmwr1akn9I9z:b8i3xaw) ([raw file](https://github.com/qtox/qtox/blob/e94b16b2912349df473c82a0bd1c606b78ff2cc5/src/core/coreext.cpp#L96)):*
<details><summary><i>Previously, sudden6 wrote…</i></summary><blockquote>

The solution seems good for this PR now. Maybe you can submit an additional PR adding the `previousState` parameter to the `friendStatusChanged` signal? AFAICT this seems to be a common use case.
</blockquote></details>

I think I heard @anthonybilinski had something in the pipeline for this already from the Friend abstraction perspective.


<!-- Sent from Reviewable.io -->

2019-11-25 09:04 UTC, anthonybilinski commented
> @anthonybilinski should I wait for your review too or just go ahead and merge when it's stable?

I'd like to hold off merging this for a bit. I think we should:
1) review, or have people with more protocol expertise review the protocol design. getting toxcore people involved in this would be good.
2) review the entirety of the library, since we'd be the first users of it, and since it's a new mandatory dependency. It has as many security implications as toxcore itself, since bugs could lead to remote code execution.
3) talk to other client maintainers to look for multi-client adoption, to avoid unnecessarily segmenting the features available between users

Also since this would be going to master, meaning it would be in v1.18.0 rather than v1.17.0 which has already branched, I don't think there's a rush to get it merged. I've talked with @sphaerophoria and he's on board with taking our time before merging.

2019-11-26 00:45 UTC, anthonybilinski reviewed
> *[Reviewable](https://reviewable.io/reviews/qtox/qtox/5932)* status: 0 of 1 LGTMs obtained

___
*[src/core/coreext.cpp, line 96 at r1](https://reviewable.io/reviews/qtox/qtox/5932#-Lu-V9Pl5zM3jKVrPijJ:-Lu_9bTv6iuR7MP4MCod:bcu9j8t) ([raw file](https://github.com/qtox/qtox/blob/e94b16b2912349df473c82a0bd1c606b78ff2cc5/src/core/coreext.cpp#L96)):*
<details><summary><i>Previously, sphaerophoria wrote…</i></summary><blockquote>

I think I heard @anthonybilinski had something in the pipeline for this already from the Friend abstraction perspective.
</blockquote></details>

Yes, https://github.com/qTox/qTox/pull/5930 includes a change to have a "onlineOffline" signal rather than just a status changed signal, which fixes a bug with OfflineMsgEngine re-sending messages when a friend changes between two online statuses. It could be reused for seeing when to negotiate, once that PR is merged (it's ready for review now :P )


<!-- Sent from Reviewable.io -->

2019-11-28 19:56 UTC, sudden6 commented
@sphaerophoria can you rebase this please? I'd like to continue to run it.

2019-11-29 02:33 UTC, sphaerophoria commented
Rebased, kinda funny there were some changes that @anthonybilinski and I made that were literally identical :D

2019-11-29 14:03 UTC, sudden6 commented
@sphaerophoria a new issue turned up:

```
**[14:01:32.701 UTC] persistence/db/rawdatabase.cpp:723 : Warning: Failed to prepare statement "ALTER TABLE faux_offline_pending ADD COLUMN required_extensions INTEGER NOT NULL DEFAULT 0;" and returned 1
[14:01:32.701 UTC] persistence/db/rawdatabase.cpp:725 : Warning: The full error is 1: duplicate column name: required_extensions
[14:01:32.711 UTC] persistence/history.cpp:265 : Critical: Failed to upgrade db to schema version  5  aborting
[14:01:32.712 UTC] nexus.cpp:86 : Debug: Starting up
```

This seems to be fallout from the rebase, because the profile was starting cleanly before.

2019-11-29 15:49 UTC, sphaerophoria commented
i think this is just because your db has fields that it wouldnt have in any
case on master. Anthony and I both changed the db versions. youre gonna
have to manually roll your db back to version 3 to let it run the schema
upgrade again :(

On Fri, Nov 29, 2019, 06:03 sudden6 <notifications@github.com> wrote:

> @sphaerophoria <https://github.com/sphaerophoria> a new issue turned up:
>
> **[14:01:32.701 UTC] persistence/db/rawdatabase.cpp:723 : Warning: Failed to prepare statement "ALTER TABLE faux_offline_pending ADD COLUMN required_extensions INTEGER NOT NULL DEFAULT 0;" and returned 1
> [14:01:32.701 UTC] persistence/db/rawdatabase.cpp:725 : Warning: The full error is 1: duplicate column name: required_extensions
> [14:01:32.711 UTC] persistence/history.cpp:265 : Critical: Failed to upgrade db to schema version  5  aborting
> [14:01:32.712 UTC] nexus.cpp:86 : Debug: Starting up
>
> This seems to be fallout from the rebase, because the profile was starting
> cleanly before.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/qTox/qTox/pull/5932?email_source=notifications&email_token=AAIFF47JXY4H2PHPUDPQ453QWEOLDA5CNFSM4JOL6GJ2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEFO55UQ#issuecomment-559800018>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAIFF465EQSMJ3QBQUKYUN3QWEOLDANCNFSM4JOL6GJQ>
> .
>

2019-11-29 15:52 UTC, sudden6 commented
ah, so Anthony has used 5 for his schema version and you too? Guess that's what I get for running a PR as main :P

2019-11-29 18:01 UTC, anthonybilinski commented
I used 4 which was the next number on master, and so did this PR. You can manually edit your db with `pragma user_version = 3` then run master which will upgrade with the sql index change and change user version to 4, then manually edit it to 5 and run this PR again. If you leave it at 4 and try to run this PR, it will try to upgrade a second time and fail like you're seeing.

2019-11-30 00:18 UTC, sudden6 commented
I just restored a backup, I don't think anything of value was lost.

2020-01-28 11:26 UTC, anthonybilinski commented
Rebased to master tip, had to resolve quite a few conflicts around Friend's negotiation status handling, which I changed quite a bit.

Now that licenses are in the projects I'll try a second time to get some toxcore guys to review them.

2020-01-29 08:07 UTC, anthonybilinski commented
I redid the rebase with a lot less changes needed with the friend/status conflicts.

2020-03-01 23:00 UTC, anthonybilinski commented
Rebased. I'll try to get at reviewing the library itself and then I think a merge would be alright. From the Toxcore guys asked on IRC, people seem generally supportive and like the protocol, but I don't think a full review of the library has been done yet.

2020-04-13 08:28 UTC, anthonybilinski commented
Rebased. Now that v1.17.0 release is wrapping up, I'll focus on reviewing toxext and this PR.

2020-08-26 11:41 UTC, anthonybilinski requested changes
> Reviewed 6 of 58 files at r1, 3 of 17 files at r2, 2 of 9 files at r4, 18 of 45 files at r7, 1 of 1 files at r8.
> *[Reviewable](https://reviewable.io/reviews/qtox/qtox/5932)* status: 0 of 1 LGTMs obtained

___
*[bootstrap.sh, line 238 at r8](https://reviewable.io/reviews/qtox/qtox/5932#-MFeUNUg8EFbae82o1a4:-MFeUNUh18fsu92zmUrq:b689dh3) ([raw file](https://github.com/qtox/qtox/blob/2441db95cad35fda008b73d3877118b5ccd5d716/bootstrap.sh#L238)):*
> ```Shell
>             INSTALL_TOX=false
>             shift
>         elif [ ${1} = "--with-sqlcipher" ]
> ```

"--with-sqlcipher" -> "--with-toxext"
___
*[bootstrap.sh, line 242 at r8](https://reviewable.io/reviews/qtox/qtox/5932#-MFeU8F_9vX4sSIe3pUa:-MFeU8F_9vX4sSIe3pUb:bd0q18x) ([raw file](https://github.com/qtox/qtox/blob/2441db95cad35fda008b73d3877118b5ccd5d716/bootstrap.sh#L242)):*
> ```Shell
>             INSTALL_TOXEXT=true
>             shift
>         elif [ ${1} = "--without-sqlcipher" ]
> ```

"--without-sqlcipher" -> "--without-toxext"
___
*[INSTALL.md, line 50 at r8](https://reviewable.io/reviews/qtox/qtox/5932#-MFeUg6z6z2NdPIUtT-E:-MFeUg6z6z2NdPIUtT-F:b6sv5bk) ([raw file](https://github.com/qtox/qtox/blob/2441db95cad35fda008b73d3877118b5ccd5d716/INSTALL.md#L50)):*
> ```Markdown
> | [snorenotify]            | >= 0.7.0    | optional dependency                                      |
> | [toxext]                 | >= 0.0.1    |                                                          |
> | [tox_extension_messages] | >= 0.0.1    |                                                          |
> ```

it looks like the "tox_extension_messages" line has one too many spaces in the "Name" column: 
![image.png](https://files.reviewableusercontent.io/images/reviewable/10469203/Wfx2YJ73fdFCzYMNyDpATJAy/image.png)
___
*[osx/qTox-Mac-Deployer-ULTIMATE.sh, line 253 at r8](https://reviewable.io/reviews/qtox/qtox/5932#-MFeWAx-EQ_hKNxh7ADv:-MFeWAx-EQ_hKNxh7ADw:b-t6ugon) ([raw file](https://github.com/qtox/qtox/blob/2441db95cad35fda008b73d3877118b5ccd5d716/osx/qTox-Mac-Deployer-ULTIMATE.sh#L253)):*
> ```Shell
>         build_toxext
>     else
>         fcho "If all went well you should now have all the tools needed to compile qTox!"
> ```

I think this line should only be printed once, moved outside of the toxcore block into its own !travis check, rather than being printed once per dependency.
___
*[osx/qTox-Mac-Deployer-ULTIMATE.sh, line 268 at r8](https://reviewable.io/reviews/qtox/qtox/5932#-MFeWQMnE7Co_WmTotLR:-MFeWQMo8EtyX1oVGNDp:bb7od0r) ([raw file](https://github.com/qtox/qtox/blob/2441db95cad35fda008b73d3877118b5ccd5d716/osx/qTox-Mac-Deployer-ULTIMATE.sh#L268)):*
> ```Shell
>         build_tox_extension_messages
>     else
>         fcho "If all went well you should now have all the tools needed to compile qTox!"
> ```

same
___
*[src/core/coreext.h, line 1 at r8](https://reviewable.io/reviews/qtox/qtox/5932#-MFeXFfo1tDnNaxjhmQs:-MFeXFfo1tDnNaxjhmQt:b-khs4oa) ([raw file](https://github.com/qtox/qtox/blob/2441db95cad35fda008b73d3877118b5ccd5d716/src/core/coreext.h#L1)):*
> ```objc
> #pragma once
> ```

copyright notice
___
*[src/core/coreext.cpp, line 1 at r8](https://reviewable.io/reviews/qtox/qtox/5932#-MFeXWej2Df4Q_A9fLvv:-MFeXWej2Df4Q_A9fLvw:b-khs4oa) ([raw file](https://github.com/qtox/qtox/blob/2441db95cad35fda008b73d3877118b5ccd5d716/src/core/coreext.cpp#L1)):*
> ```cpp
> #include "coreext.h"
> ```

copyright notice
___
*[src/core/extension.h, line 21 at r8](https://reviewable.io/reviews/qtox/qtox/5932#-MFeXaE03E7bf8iqWmbh:-MFeXaE03E7bf8iqWmbi:b-e70rpc) ([raw file](https://github.com/qtox/qtox/blob/2441db95cad35fda008b73d3877118b5ccd5d716/src/core/extension.h#L21)):*
> ```objc
> 
> #ifndef EXTENSION_H
> #define EXTENSION_H
> ```

pragma once
___
*[src/core/icoreextpacket.h, line 21 at r8](https://reviewable.io/reviews/qtox/qtox/5932#-MFeXi7M99nrTeGNLRee:-MFeXi7M99nrTeGNLRef:b-e70rpc) ([raw file](https://github.com/qtox/qtox/blob/2441db95cad35fda008b73d3877118b5ccd5d716/src/core/icoreextpacket.h#L21)):*
> ```objc
> 
> #ifndef ICORE_EXT_PACKET_H
> #define ICORE_EXT_PACKET_H
> ```

pragma once
___
*[src/model/brokenmessagereason.h, line 21 at r8](https://reviewable.io/reviews/qtox/qtox/5932#-MFeXlYsEmizfub87HcG:-MFeXlYsEmizfub87HcH:b-e70rpc) ([raw file](https://github.com/qtox/qtox/blob/2441db95cad35fda008b73d3877118b5ccd5d716/src/model/brokenmessagereason.h#L21)):*
> ```objc
> 
> #ifndef BROKEN_MESSAGE_REASON_H
> #define BROKEN_MESSAGE_REASON_H
> ```

pragma once
___
*[src/widget/extensionstatus.h, line 2 at r8](https://reviewable.io/reviews/qtox/qtox/5932#-MFeXrSa-kXTOP7xTqlt:-MFeXrSa-kXTOP7xTqlu:bhe6t2d) ([raw file](https://github.com/qtox/qtox/blob/2441db95cad35fda008b73d3877118b5ccd5d716/src/widget/extensionstatus.h#L2)):*
> ```objc
> /*
>     Copyright © 2015-2019 by The qTox Project Contributors
> ```

should be the start data of this work rather than the start date of qTox, e.g. 2019 or 2019-2020
___
*[src/widget/extensionstatus.h, line 21 at r8](https://reviewable.io/reviews/qtox/qtox/5932#-MFeXzcl-JJheL-gLm2q:-MFeXzcl-JJheL-gLm2r:b-e70rpc) ([raw file](https://github.com/qtox/qtox/blob/2441db95cad35fda008b73d3877118b5ccd5d716/src/widget/extensionstatus.h#L21)):*
> ```objc
> 
> #ifndef EXTENSION_STATUS_H
> #define EXTENSION_STATUS_H
> ```

pragma once
___
*[src/widget/extensionstatus.cpp, line 2 at r8](https://reviewable.io/reviews/qtox/qtox/5932#-MFeXxs-9lmOv0PcVkwc:-MFeXxs-9lmOv0PcVkwd:bomdio5) ([raw file](https://github.com/qtox/qtox/blob/2441db95cad35fda008b73d3877118b5ccd5d716/src/widget/extensionstatus.cpp#L2)):*
> ```cpp
> /*
>     Copyright © 2015-2019 by The qTox Project Contributors
> ```

start date should be 2019
___
*[src/widget/widget.cpp, line 1263 at r8](https://reviewable.io/reviews/qtox/qtox/5932#-MFeZQ2Y5i-cByi4rEwT:-MFeZQ2Y5i-cByi4rEwU:b-dn1xt0) ([raw file](https://github.com/qtox/qtox/blob/2441db95cad35fda008b73d3877118b5ccd5d716/src/widget/widget.cpp#L1263)):*
> ```cpp
>     if (!f) {
>         return;
>     }
> ```

since this now comes from `Friend`, is it possible that it's not in FriendList? should this be an assert rather than a silent return?
___
*[windows/cross-compile/build.sh, line 1080 at r7](https://reviewable.io/reviews/qtox/qtox/5932#-MFeSy1JEEFsLSl8UWSD:-MFeSy1JEEFsLSl8UWSE:bf82tg8) ([raw file](https://github.com/qtox/qtox/blob/2c20eb00e0e7d676659b9bf4017370c2fabdf240/windows/cross-compile/build.sh#L1080)):*
> ```Shell
>   rm -rf ./toxext*
> else
>   echo "Using cached build of Toxcore `cat $TOXEXT_PREFIX_DIR/done`"
> ```

should be "cached build of ToxExt"
___
*[windows/cross-compile/build.sh, line 1132 at r7](https://reviewable.io/reviews/qtox/qtox/5932#-MFeT6wv4-Rxl5ALc97e:-MFeT6wv4-Rxl5ALc97f:b-7c50d8) ([raw file](https://github.com/qtox/qtox/blob/2c20eb00e0e7d676659b9bf4017370c2fabdf240/windows/cross-compile/build.sh#L1132)):*
> ```Shell
>   rm -rf ./tox_extension_messages*
> else
>   echo "Using cached build of Toxcore `cat $TOX_EXTENSION_MESSAGES_PREFIX_DIR/done`"
> ```

should be "cached build of ToxExt Messages" (or something)


<!-- Sent from Reviewable.io -->

2020-08-27 03:07 UTC, anthonybilinski requested changes
> Reviewed 1 of 58 files at r1, 1 of 17 files at r2, 1 of 8 files at r5, 1 of 3 files at r6, 17 of 45 files at r7.
> *[Reviewable](https://reviewable.io/reviews/qtox/qtox/5932)* status: 0 of 1 LGTMs obtained

___
*[src/core/coreext.cpp, line 96 at r1](https://reviewable.io/reviews/qtox/qtox/5932#-Lu-V9Pl5zM3jKVrPijJ:-MFgZGSPEzpq56s-W1x-:bme8qfu) ([raw file](https://github.com/qtox/qtox/blob/e94b16b2912349df473c82a0bd1c606b78ff2cc5/src/core/coreext.cpp#L96)):*
<details><summary><i>Previously, anthonybilinski (Anthony Bilinski) wrote…</i></summary><blockquote>

Yes, https://github.com/qTox/qTox/pull/5930 includes a change to have a "onlineOffline" signal rather than just a status changed signal, which fixes a bug with OfflineMsgEngine re-sending messages when a friend changes between two online statuses. It could be reused for seeing when to negotiate, once that PR is merged (it's ready for review now :P )
</blockquote></details>

#5930 is in now, could this take advantage of it?
___
*[src/core/coreext.cpp, line 106 at r8](https://reviewable.io/reviews/qtox/qtox/5932#-MFgZ-M374xszVdh5bjH:-MFgZ-M47tu_qTw8vGz2:bympa1u) ([raw file](https://github.com/qtox/qtox/blob/2441db95cad35fda008b73d3877118b5ccd5d716/src/core/coreext.cpp#L106)):*
> ```cpp
>     currentStatuses[friendId] = status;
> 
>     // Uncondintional to protect against a newly constructed prevStatus
> ```

typo "Unconditional"? But also how is this condition unconditional :thinking:?
___
*[src/model/friend.cpp, line 162 at r8](https://reviewable.io/reviews/qtox/qtox/5932#-MFg_jJBEAw9k6eL7G-_:-MFg_jJBEAw9k6eL7G-a:b-r2op1o) ([raw file](https://github.com/qtox/qtox/blob/2441db95cad35fda008b73d3877118b5ccd5d716/src/model/friend.cpp#L162)):*
> ```cpp
> 
>     const bool wasOnline = Status::isOnline(getStatus());
>     if (friendStatus == s)
> ```

{} braces around if block plz
___
*[src/persistence/history.cpp, line 343 at r8](https://reviewable.io/reviews/qtox/qtox/5932#-MFhfg4s13qBoasKdYWP:-MFhfg4s13qBoasKdYWQ:bg5zyu3) ([raw file](https://github.com/qtox/qtox/blob/2441db95cad35fda008b73d3877118b5ccd5d716/src/persistence/history.cpp#L343)):*
> ```cpp
>                                                  dbSchema3to4, dbSchema4to5, dbSchema5to6};
> 
>     assert(databaseSchemaVersion < static_cast<int>(upgradeFns.size()));
> ```

could we also assert that `SCHEMA_VERSION == upgradeFns.size()`
___
*[src/persistence/history.cpp, line 847 at r8](https://reviewable.io/reviews/qtox/qtox/5932#-MFhhnLZ3uEtHBrKg6_Z:-MFhhnLZ3uEtHBrKg6__:bpqt7xa) ([raw file](https://github.com/qtox/qtox/blob/2441db95cad35fda008b73d3877118b5ccd5d716/src/persistence/history.cpp#L847)):*
> ```cpp
> 
>         if (row[7].isNull()) {
>             messages += {id,           messageState, ExtensionSet(), timestamp,        friend_key,
> ```

why is `ExtensionSet()` default constructed here? It seems like the message could be pending, in which case it could have an extension set saved in the faux_offline_pending table that isn't be read here? the required_extensions are read out in History::getUndeliveredMessagesForFriend, but History::getMessagesForFriend seems like it should return a superset of that function.


<!-- Sent from Reviewable.io -->

2020-08-27 09:23 UTC, anthonybilinski requested changes
> Reviewed 1 of 58 files at r1, 1 of 17 files at r2, 1 of 3 files at r6, 10 of 45 files at r7.
> *[Reviewable](https://reviewable.io/reviews/qtox/qtox/5932)* status: 0 of 1 LGTMs obtained

___
*[src/widget/widget.cpp, line 1451 at r8](https://reviewable.io/reviews/qtox/qtox/5932#-MFiqQf5CPAnbfJso8Uj:-MFiqQf62fZvlfjYcyGI:b-sr0sb6) ([raw file](https://github.com/qtox/qtox/blob/2441db95cad35fda008b73d3877118b5ccd5d716/src/widget/widget.cpp#L1451)):*
> ```cpp
>     }
> 
>     friendMessageDispatchers[f->getPublicKey()]->onExtMessageReceived(message);
> ```

could use `friendKey` here
___
*[src/widget/widget.cpp, line 1462 at r8](https://reviewable.io/reviews/qtox/qtox/5932#-MFiqVM07LxDfP0bdLSW:-MFiqVM07LxDfP0bdLSX:b-sr0sb6) ([raw file](https://github.com/qtox/qtox/blob/2441db95cad35fda008b73d3877118b5ccd5d716/src/widget/widget.cpp#L1462)):*
> ```cpp
>     }
> 
>     friendMessageDispatchers[f->getPublicKey()]->onExtReceiptReceived(receiptId);
> ```

could use `friendKey` here
___
*[test/model/messageprocessor_test.cpp, line 156 at r8](https://reviewable.io/reviews/qtox/qtox/5932#-MFiuC4f-op_V3Yywftf:-MFiuC4f-op_V3Yywftg:b-2qu2f1) ([raw file](https://github.com/qtox/qtox/blob/2441db95cad35fda008b73d3877118b5ccd5d716/test/model/messageprocessor_test.cpp#L156)):*
> ```cpp
>     QVERIFY(message.timestamp.isValid());
> }
> ```

could this test be extended to cover the new functionality of MessageProcessor?
___
*[test/persistence/offlinemsgengine_test.cpp, line 80 at r8](https://reviewable.io/reviews/qtox/qtox/5932#-MFj1wnb5HjZVZ1QhBEg:-MFj1wnb5HjZVZ1QhBEh:b-s8p3ds) ([raw file](https://github.com/qtox/qtox/blob/2441db95cad35fda008b73d3877118b5ccd5d716/test/persistence/offlinemsgengine_test.cpp#L80)):*
> ```cpp
>     QVERIFY(messagesToResend.size() == 1);
> 
>     offlineMsgEngine.addSentCoreMessage(ReceiptNum(0), Message(), completionFn);
> ```

`receipt` instead of `ReceiptNum(0)`?
___
*[test/persistence/offlinemsgengine_test.cpp, line 81 at r8](https://reviewable.io/reviews/qtox/qtox/5932#-MFj22J6320ETvWqyeKC:-MFj22J6320ETvWqyeKD:b-s8p3ds) ([raw file](https://github.com/qtox/qtox/blob/2441db95cad35fda008b73d3877118b5ccd5d716/test/persistence/offlinemsgengine_test.cpp#L81)):*
> ```cpp
> 
>     offlineMsgEngine.addSentCoreMessage(ReceiptNum(0), Message(), completionFn);
>     offlineMsgEngine.onReceiptReceived(ReceiptNum(0));
> ```

`receipt` instead of `ReceiptNum(0)`?


<!-- Sent from Reviewable.io -->

2020-08-27 23:57 UTC, sphaerophoria reviewed
Addressed some review comments and pushed a subset of the changes. Just want to make sure I don't lose track of work. Will split commit and test changes later.

> Reviewed 2 of 58 files at r1, 5 of 17 files at r2, 2 of 9 files at r4, 1 of 8 files at r5, 2 of 3 files at r6, 44 of 45 files at r7, 1 of 1 files at r8.
> *[Reviewable](https://reviewable.io/reviews/qtox/qtox/5932#-:-MFmLayh9hR2icVz5N9m:b-bvdjhm)* status: 0 of 1 LGTMs obtained

___
*[bootstrap.sh, line 238 at r8](https://reviewable.io/reviews/qtox/qtox/5932#-MFeUNUg8EFbae82o1a4:-MFm32275-dAuDm9Dsoo:b-s00oq2) ([raw file](https://github.com/qtox/qtox/blob/2441db95cad35fda008b73d3877118b5ccd5d716/bootstrap.sh#L238)):*
<details><summary><i>Previously, anthonybilinski (Anthony Bilinski) wrote…</i></summary><blockquote>

"--with-sqlcipher" -> "--with-toxext"
</blockquote></details>

:facepalm:
___
*[bootstrap.sh, line 242 at r8](https://reviewable.io/reviews/qtox/qtox/5932#-MFeU8F_9vX4sSIe3pUa:-MFm5ugO96xT1ZfrK3bF:b-s00oq2) ([raw file](https://github.com/qtox/qtox/blob/2441db95cad35fda008b73d3877118b5ccd5d716/bootstrap.sh#L242)):*
<details><summary><i>Previously, anthonybilinski (Anthony Bilinski) wrote…</i></summary><blockquote>

"--without-sqlcipher" -> "--without-toxext"
</blockquote></details>

:facepalm:
___
*[INSTALL.md, line 50 at r8](https://reviewable.io/reviews/qtox/qtox/5932#-MFeUg6z6z2NdPIUtT-E:-MFm72y01h1EDVAUyBnW:bgz6b7n) ([raw file](https://github.com/qtox/qtox/blob/2441db95cad35fda008b73d3877118b5ccd5d716/INSTALL.md#L50)):*
<details><summary><i>Previously, anthonybilinski (Anthony Bilinski) wrote…</i></summary><blockquote>

it looks like the "tox_extension_messages" line has one too many spaces in the "Name" column: 
![image.png](https://files.reviewableusercontent.io/images/reviewable/10469203/Wfx2YJ73fdFCzYMNyDpATJAy/image.png)

</blockquote></details>

It lines up for me
![image.png](https://files.reviewableusercontent.io/images/reviewable/1069811/QqGb_cWUctzSlAJHyJ_l4yk9/image.png)
___
*[osx/qTox-Mac-Deployer-ULTIMATE.sh, line 253 at r8](https://reviewable.io/reviews/qtox/qtox/5932#-MFeWAx-EQ_hKNxh7ADv:-MFm7Yp9BsuSAScBIZ_t:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/2441db95cad35fda008b73d3877118b5ccd5d716/osx/qTox-Mac-Deployer-ULTIMATE.sh#L253)):*
<details><summary><i>Previously, anthonybilinski (Anthony Bilinski) wrote…</i></summary><blockquote>

I think this line should only be printed once, moved outside of the toxcore block into its own !travis check, rather than being printed once per dependency.
</blockquote></details>

Done.
___
*[osx/qTox-Mac-Deployer-ULTIMATE.sh, line 268 at r8](https://reviewable.io/reviews/qtox/qtox/5932#-MFeWQMnE7Co_WmTotLR:-MFm7ZSGC9h1ZzASYQbL:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/2441db95cad35fda008b73d3877118b5ccd5d716/osx/qTox-Mac-Deployer-ULTIMATE.sh#L268)):*
<details><summary><i>Previously, anthonybilinski (Anthony Bilinski) wrote…</i></summary><blockquote>

same
</blockquote></details>

Done.
___
*[src/core/coreext.h, line 1 at r8](https://reviewable.io/reviews/qtox/qtox/5932#-MFeXFfo1tDnNaxjhmQs:-MFm7lktB3R_eMitUw40:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/2441db95cad35fda008b73d3877118b5ccd5d716/src/core/coreext.h#L1)):*
<details><summary><i>Previously, anthonybilinski (Anthony Bilinski) wrote…</i></summary><blockquote>

copyright notice
</blockquote></details>

Done.
___
*[src/core/coreext.cpp, line 96 at r1](https://reviewable.io/reviews/qtox/qtox/5932#-Lu-V9Pl5zM3jKVrPijJ:-MFmEJTS5joUNXK3abt0:bmgxzc2) ([raw file](https://github.com/qtox/qtox/blob/e94b16b2912349df473c82a0bd1c606b78ff2cc5/src/core/coreext.cpp#L96)):*
<details><summary><i>Previously, anthonybilinski (Anthony Bilinski) wrote…</i></summary><blockquote>

#5930 is in now, could this take advantage of it?
</blockquote></details>

Hm, I'm not really sure. It seems like Friend is an abstraction ontop of core, it seems kind of wrong to use Friend within CoreExt. What do you guys think?
___
*[src/core/coreext.cpp, line 1 at r8](https://reviewable.io/reviews/qtox/qtox/5932#-MFeXWej2Df4Q_A9fLvv:-MFm7nj67jMfw9dV-WOE:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/2441db95cad35fda008b73d3877118b5ccd5d716/src/core/coreext.cpp#L1)):*
<details><summary><i>Previously, anthonybilinski (Anthony Bilinski) wrote…</i></summary><blockquote>

copyright notice
</blockquote></details>

Done.
___
*[src/core/coreext.cpp, line 106 at r8](https://reviewable.io/reviews/qtox/qtox/5932#-MFgZ-M374xszVdh5bjH:-MFm7wJ66LMdvq3XA7Ex:bbg4aiv) ([raw file](https://github.com/qtox/qtox/blob/2441db95cad35fda008b73d3877118b5ccd5d716/src/core/coreext.cpp#L106)):*
<details><summary><i>Previously, anthonybilinski (Anthony Bilinski) wrote…</i></summary><blockquote>

typo "Unconditional"? But also how is this condition unconditional :thinking:?
</blockquote></details>

It took me a while, but I figured it out! We don't compare against prevStatus because prevStatus may be in a bad state. Updated comment
___
*[src/core/extension.h, line 21 at r8](https://reviewable.io/reviews/qtox/qtox/5932#-MFeXaE03E7bf8iqWmbh:-MFmFHttEhKbIy5ACqMU:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/2441db95cad35fda008b73d3877118b5ccd5d716/src/core/extension.h#L21)):*
<details><summary><i>Previously, anthonybilinski (Anthony Bilinski) wrote…</i></summary><blockquote>

pragma once
</blockquote></details>

Done.
___
*[src/core/icoreextpacket.h, line 21 at r8](https://reviewable.io/reviews/qtox/qtox/5932#-MFeXi7M99nrTeGNLRee:-MFmFLwf51S-IZ50E92X:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/2441db95cad35fda008b73d3877118b5ccd5d716/src/core/icoreextpacket.h#L21)):*
<details><summary><i>Previously, anthonybilinski (Anthony Bilinski) wrote…</i></summary><blockquote>

pragma once
</blockquote></details>

Done.
___
*[src/model/brokenmessagereason.h, line 21 at r8](https://reviewable.io/reviews/qtox/qtox/5932#-MFeXlYsEmizfub87HcG:-MFmFPTmAObFyvQdFz0-:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/2441db95cad35fda008b73d3877118b5ccd5d716/src/model/brokenmessagereason.h#L21)):*
<details><summary><i>Previously, anthonybilinski (Anthony Bilinski) wrote…</i></summary><blockquote>

pragma once
</blockquote></details>

Done.
___
*[src/model/friend.cpp, line 162 at r8](https://reviewable.io/reviews/qtox/qtox/5932#-MFg_jJBEAw9k6eL7G-_:-MFmFT0r3oO5FezxCLmi:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/2441db95cad35fda008b73d3877118b5ccd5d716/src/model/friend.cpp#L162)):*
<details><summary><i>Previously, anthonybilinski (Anthony Bilinski) wrote…</i></summary><blockquote>

{} braces around if block plz
</blockquote></details>

Done.
___
*[src/persistence/history.cpp, line 343 at r8](https://reviewable.io/reviews/qtox/qtox/5932#-MFhfg4s13qBoasKdYWP:-MFmH1tu4O-HsmnQGqYU:boj41qv) ([raw file](https://github.com/qtox/qtox/blob/2441db95cad35fda008b73d3877118b5ccd5d716/src/persistence/history.cpp#L343)):*
<details><summary><i>Previously, anthonybilinski (Anthony Bilinski) wrote…</i></summary><blockquote>

could we also assert that `SCHEMA_VERSION == upgradeFns.size()`
</blockquote></details>

Took me a while to get up to speed again on this one, but I think that seems reasonable.
___
*[src/persistence/history.cpp, line 847 at r8](https://reviewable.io/reviews/qtox/qtox/5932#-MFhhnLZ3uEtHBrKg6_Z:-MFmHj39EZ0Echd2xeRT:bd6y74x) ([raw file](https://github.com/qtox/qtox/blob/2441db95cad35fda008b73d3877118b5ccd5d716/src/persistence/history.cpp#L847)):*
<details><summary><i>Previously, anthonybilinski (Anthony Bilinski) wrote…</i></summary><blockquote>

why is `ExtensionSet()` default constructed here? It seems like the message could be pending, in which case it could have an extension set saved in the faux_offline_pending table that isn't be read here? the required_extensions are read out in History::getUndeliveredMessagesForFriend, but History::getMessagesForFriend seems like it should return a superset of that function.
</blockquote></details>

I think you're right, this seems like a m [...]

2020-08-28 02:41 UTC, anthonybilinski requested changes
> Reviewed 12 of 12 files at r9.
> *[Reviewable](https://reviewable.io/reviews/qtox/qtox/5932)* status: 0 of 1 LGTMs obtained

___
*[INSTALL.md, line 50 at r8](https://reviewable.io/reviews/qtox/qtox/5932#-MFeUg6z6z2NdPIUtT-E:-MFmudr70HDn9OA0thMy:bw7ulu7) ([raw file](https://github.com/qtox/qtox/blob/2441db95cad35fda008b73d3877118b5ccd5d716/INSTALL.md#L50)):*
<details><summary><i>Previously, sphaerophoria wrote…</i></summary><blockquote>

It lines up for me
![image.png](https://files.reviewableusercontent.io/images/reviewable/1069811/QqGb_cWUctzSlAJHyJ_l4yk9/image.png)

</blockquote></details>

Ah yeah looking it outside of reviewable it seems fine, maybe it's not properly monospaced here.
___
*[src/core/coreext.cpp, line 96 at r1](https://reviewable.io/reviews/qtox/qtox/5932#-Lu-V9Pl5zM3jKVrPijJ:-MFmujOw4Ale6Mt7c63T:b-atbh4x) ([raw file](https://github.com/qtox/qtox/blob/e94b16b2912349df473c82a0bd1c606b78ff2cc5/src/core/coreext.cpp#L96)):*
<details><summary><i>Previously, sphaerophoria wrote…</i></summary><blockquote>

Hm, I'm not really sure. It seems like Friend is an abstraction ontop of core, it seems kind of wrong to use Friend within CoreExt. What do you guys think?
</blockquote></details>

:thinking: good point.

I kind of feel like because Friend is a central model class, it being updated from Core and then read from anywhere else that needs it is still reasonable, even if it means CoreExt is reading from a higher level class when it's a low level class with that state already available. Having to re-do caching of old status and comparison seems unfortunate when our model already has that info in an available way.

Like is this  conceptually different from a GUI class getting a user event, updating the model, then the GUI responding in reaction to the model? That case seems fine to me, even though I'm unsure about this case.
___
*[windows/cross-compile/build.sh, line 941 at r9](https://reviewable.io/reviews/qtox/qtox/5932#-MFmu0g4A3-wBgkITGEp:-MFmu0g5BGTMsX_IiTAn:boojsuj) ([raw file](https://github.com/qtox/qtox/blob/c582323c36601b85a0abb2c284d63c0d50245d14/windows/cross-compile/build.sh#L941)):*
> ```Shell
> +$(BUILD_PFX)$(LIBVPX_SO): SONAME = libvpx.dll
>  $(BUILD_PFX)$(LIBVPX_SO): EXPORTS_FILE = $(EXPORT_FILE)
> ```

in latest update you stripped some trailing spaces from within these patches, which doesn't seem safe


<!-- Sent from Reviewable.io -->

2020-08-28 16:39 UTC, sphaerophoria reviewed
> Reviewed 1 of 12 files at r9.
> *[Reviewable](https://reviewable.io/reviews/qtox/qtox/5932)* status: 0 of 1 LGTMs obtained

___
*[src/core/coreext.cpp, line 96 at r1](https://reviewable.io/reviews/qtox/qtox/5932#-Lu-V9Pl5zM3jKVrPijJ:-MFppByyCzO2KokxObT3:b-xxey2a) ([raw file](https://github.com/qtox/qtox/blob/e94b16b2912349df473c82a0bd1c606b78ff2cc5/src/core/coreext.cpp#L96)):*
<details><summary><i>Previously, anthonybilinski (Anthony Bilinski) wrote…</i></summary><blockquote>

:thinking: good point.

I kind of feel like because Friend is a central model class, it being updated from Core and then read from anywhere else that needs it is still reasonable, even if it means CoreExt is reading from a higher level class when it's a low level class with that state already available. Having to re-do caching of old status and comparison seems unfortunate when our model already has that info in an available way.

Like is this  conceptually different from a GUI class getting a user event, updating the model, then the GUI responding in reaction to the model? That case seems fine to me, even though I'm unsure about this case.
</blockquote></details>

Tried implementing this by going through widget, and it wasn't too ugly. However the real reason for not doing it this way is that Friend indicates it's online to the rest of the system _when it finishes negotiating_. We need to bypass this abstraction for CoreExt. On testing this change I found that offline messages never sent to someone with extensions since they got flagged as online before negotiation had completed.
___
*[src/widget/widget.cpp, line 1263 at r8](https://reviewable.io/reviews/qtox/qtox/5932#-MFeZQ2Y5i-cByi4rEwT:-MFpcZf02H9LCl_zGhTw:bq9ttr4) ([raw file](https://github.com/qtox/qtox/blob/2441db95cad35fda008b73d3877118b5ccd5d716/src/widget/widget.cpp#L1263)):*
<details><summary><i>Previously, anthonybilinski (Anthony Bilinski) wrote…</i></summary><blockquote>

since this now comes from `Friend`, is it possible that it's not in FriendList? should this be an assert rather than a silent return?
</blockquote></details>

Instead opted to just remove the lookup completely. I can do the same function with friendPk and status
___
*[src/widget/widget.cpp, line 1451 at r8](https://reviewable.io/reviews/qtox/qtox/5932#-MFiqQf5CPAnbfJso8Uj:-MFpclEB-rnXqwoyv-tt:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/2441db95cad35fda008b73d3877118b5ccd5d716/src/widget/widget.cpp#L1451)):*
<details><summary><i>Previously, anthonybilinski (Anthony Bilinski) wrote…</i></summary><blockquote>

could use `friendKey` here
</blockquote></details>

Done.
___
*[src/widget/widget.cpp, line 1462 at r8](https://reviewable.io/reviews/qtox/qtox/5932#-MFiqVM07LxDfP0bdLSW:-MFpcpfECTXWuL2l3DLd:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/2441db95cad35fda008b73d3877118b5ccd5d716/src/widget/widget.cpp#L1462)):*
<details><summary><i>Previously, anthonybilinski (Anthony Bilinski) wrote…</i></summary><blockquote>

could use `friendKey` here
</blockquote></details>

Done.
___
*[test/model/messageprocessor_test.cpp, line 156 at r8](https://reviewable.io/reviews/qtox/qtox/5932#-MFiuC4f-op_V3Yywftf:-MFpeD0W8I5ZG4wNKwiq:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/2441db95cad35fda008b73d3877118b5ccd5d716/test/model/messageprocessor_test.cpp#L156)):*
<details><summary><i>Previously, anthonybilinski (Anthony Bilinski) wrote…</i></summary><blockquote>

could this test be extended to cover the new functionality of MessageProcessor?
</blockquote></details>

Done.
___
*[test/persistence/offlinemsgengine_test.cpp, line 80 at r8](https://reviewable.io/reviews/qtox/qtox/5932#-MFj1wnb5HjZVZ1QhBEg:-MFpeOkp4RmxIAzYSS2L:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/2441db95cad35fda008b73d3877118b5ccd5d716/test/persistence/offlinemsgengine_test.cpp#L80)):*
<details><summary><i>Previously, anthonybilinski (Anthony Bilinski) wrote…</i></summary><blockquote>

`receipt` instead of `ReceiptNum(0)`?
</blockquote></details>

Done.
___
*[test/persistence/offlinemsgengine_test.cpp, line 81 at r8](https://reviewable.io/reviews/qtox/qtox/5932#-MFj22J6320ETvWqyeKC:-MFpeOxj6hJHlB6VfJx5:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/2441db95cad35fda008b73d3877118b5ccd5d716/test/persistence/offlinemsgengine_test.cpp#L81)):*
<details><summary><i>Previously, anthonybilinski (Anthony Bilinski) wrote…</i></summary><blockquote>

`receipt` instead of `ReceiptNum(0)`?
</blockquote></details>

Done.
___
*[windows/cross-compile/build.sh, line 941 at r9](https://reviewable.io/reviews/qtox/qtox/5932#-MFmu0g4A3-wBgkITGEp:-MFpfUDrEgXHmMXwzPYa:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/c582323c36601b85a0abb2c284d63c0d50245d14/windows/cross-compile/build.sh#L941)):*
<details><summary><i>Previously, anthonybilinski (Anthony Bilinski) wrote…</i></summary><blockquote>

in latest update you stripped some trailing spaces from within these patches, which doesn't seem safe
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-08-28 18:33 UTC, anthonybilinski requested changes
> Reviewed 5 of 5 files at r10.
> *[Reviewable](https://reviewable.io/reviews/qtox/qtox/5932)* status: 0 of 1 LGTMs obtained

___
*[src/core/coreext.cpp, line 96 at r1](https://reviewable.io/reviews/qtox/qtox/5932#-Lu-V9Pl5zM3jKVrPijJ:-MFq7GhLCHJEQqgTfs_c:bfqv1bc) ([raw file](https://github.com/qtox/qtox/blob/e94b16b2912349df473c82a0bd1c606b78ff2cc5/src/core/coreext.cpp#L96)):*
<details><summary><i>Previously, sphaerophoria wrote…</i></summary><blockquote>

Tried implementing this by going through widget, and it wasn't too ugly. However the real reason for not doing it this way is that Friend indicates it's online to the rest of the system _when it finishes negotiating_. We need to bypass this abstraction for CoreExt. On testing this change I found that offline messages never sent to someone with extensions since they got flagged as online before negotiation had completed.
</blockquote></details>

Ah right forgot that that was changed as part of this. Ok not worth the trouble then.
___
*[src/persistence/history.cpp, line 344 at r9](https://reviewable.io/reviews/qtox/qtox/5932#-MFq8AMF8mMiknevNoZa:-MFq8AMF8mMiknevNoZb:b-szr110) ([raw file](https://github.com/qtox/qtox/blob/c582323c36601b85a0abb2c284d63c0d50245d14/src/persistence/history.cpp#L344)):*
> ```cpp
> 
>     assert(databaseSchemaVersion < static_cast<int>(upgradeFns.size()));
>     assert(SCHEMA_VERSION == upgradeFns.size());
> ```

why was this removed after being added a couple revisions ago?

started chat about it but will just comment here so it doesn't get lost,

I think you were saying that it's because we might only be upgrading from 4 to 5 and have one upgrade func in the vect.

My response is that we always have all upgrade funcs in the vect, we just start offset into it, so the length check still seems valid to me.


<!-- Sent from Reviewable.io -->

2020-08-28 23:24 UTC, sphaerophoria reviewed
> *[Reviewable](https://reviewable.io/reviews/qtox/qtox/5932)* status: 0 of 1 LGTMs obtained

___
*[src/persistence/history.cpp, line 344 at r9](https://reviewable.io/reviews/qtox/qtox/5932#-MFq8AMF8mMiknevNoZa:-MFrNWgACAxfdfrsZn6Q:b-7mm9s8) ([raw file](https://github.com/qtox/qtox/blob/c582323c36601b85a0abb2c284d63c0d50245d14/src/persistence/history.cpp#L344)):*
<details><summary><i>Previously, anthonybilinski (Anthony Bilinski) wrote…</i></summary><blockquote>

why was this removed after being added a couple revisions ago?

started chat about it but will just comment here so it doesn't get lost,

I think you were saying that it's because we might only be upgrading from 4 to 5 and have one upgrade func in the vect.

My response is that we always have all upgrade funcs in the vect, we just start offset into it, so the length check still seems valid to me.
</blockquote></details>

I'm just an idiot. I misread and thought that the vector only had the remaining upgrades in it, but in reality our schema version was just wrong :facepalm:. Should be fixed now, tested a DB upgrade from 5->6


<!-- Sent from Reviewable.io -->

2020-08-29 00:12 UTC, anthonybilinski approved these changes
All qTox sections <img class="emoji" title=":lgtm_strong:" alt=":lgtm_strong:" align="absmiddle" src="https://reviewable.io/lgtm_strong.png" height="20" width="61"/>

Just waiting on now https://github.com/toxext/toxext/pull/3 to apply initial review changes to toxext, which will then require a toxext release and a toxext messenger extension release, which will require build script updates in this PR, so I guess <img class="emoji" title=":lgtm_cancel:" alt=":lgtm_cancel:" align="absmiddle" src="https://reviewable.io/lgtm_cancel.png" height="20" width="61"/> for that.

> Reviewed 1 of 1 files at r11.
> *[Reviewable](https://reviewable.io/reviews/qtox/qtox/5932#-:-MFrYMyu6WZznegiapvU:b-nvpmyr)* status: 0 of 1 LGTMs obtained

___
*[src/persistence/history.cpp, line 344 at r9](https://reviewable.io/reviews/qtox/qtox/5932#-MFq8AMF8mMiknevNoZa:-MFrY7kW4Y5DHjbY3egQ:bjw4ox5) ([raw file](https://github.com/qtox/qtox/blob/c582323c36601b85a0abb2c284d63c0d50245d14/src/persistence/history.cpp#L344)):*
<details><summary><i>Previously, sphaerophoria wrote…</i></summary><blockquote>

I'm just an idiot. I misread and thought that the vector only had the remaining upgrades in it, but in reality our schema version was just wrong :facepalm:. Should be fixed now, tested a DB upgrade from 5->6
</blockquote></details>

During rebase I must have missed this since the schema was upgraded to 5 both on master and in your original change.

Yay assert catching a bug :partying_face: 


<!-- Sent from Reviewable.io -->

2020-08-29 08:14 UTC, anthonybilinski approved these changes
Rebased to fix minor conflict with the core/coreav split

> Reviewed 9 of 9 files at r12.
> *[Reviewable](https://reviewable.io/reviews/qtox/qtox/5932#-:-MFtH5VTCJriNhdwauTv:b-dyg31v)* status: 0 of 1 LGTMs obtained



<!-- Sent from Reviewable.io -->

2020-09-18 11:46 UTC, anthonybilinski commented
I've reviewed the two associated libs, and have suggested changes and fixes here:
https://github.com/toxext/toxext/pull/3
https://github.com/toxext/tox_extension_messages/pull/4

With these merged or addressed and then new tags made, and this qTox PR updated for the new tags this is ready to merge. So back in your hands, @sphaerophoria.

2021-01-14 07:28 UTC, sphaerophoria commented
1.2 years later I've updated this to sit on top of https://github.com/toxext/tox_extension_messages/pull/4 and . Once that is merged I'll bump the tox_extension_messages version. We'll have to re-run the CI to build against the API changes from @anthonybilinski

2021-01-24 23:12 UTC, sphaerophoria commented
Alright thanks @anthonybilinski  for helping me tie off the last pieces here.

After adding a max message size on the network layer we had to do a little support to connect it to the rest of what we've implemented in qTox.

I've stolen some code from @anthonybilinski and boiled it down to what's required to get this PR in. My goal here is to do the minimal required changes to prevent this PR from dragging on even further. With that in mind I've implemented a hack to assume that the extension max size is constant. Anyone with a max message size lower than the default we just will not support sending to over the extended api for now.

The reason for this is that it's not trivial to support per-friend max sending size. Mainly because this complicates the offline message area. Where do we store the max message size in our DB? Should it go with the peer or the offline message? What do we do when a friend comes online and the max message changes size? If max size isn't known till a friend comes online how do we send offline messages without our processor accidentally splitting them?

If this PR gets approved in this form I will file a new ticket linking the work in https://github.com/sphaerophoria/qTox/tree/multipart-messages-configurable which should provide a starting place to wrap this up.

I re-tested offline messages with/without a restart with a friend with extensions enabled. The friend still received long messages which confirms the changes around chathistory.cpp didn't really change anything. I also tested message splitting with a friend with extensions, and one without. I believe this covers most of what's changed since the last PR update.

2021-01-30 21:30 UTC, anthonybilinski requested changes
Rebased to master.

> Reviewed 28 of 28 files at r13.
> *[Reviewable](https://reviewable.io/reviews/qtox/qtox/5932#-:-MSKC2x76C3Gkcx5b9f2:b-xyy5f8)* status: 0 of 1 LGTMs obtained

___
*[windows/cross-compile/build.sh, line 860 at r10](https://reviewable.io/reviews/qtox/qtox/5932#-MSK6-DK96Y1zxnPC11M:-MSK6-DK96Y1zxnPC11N:b-l4cpyy) ([raw file](https://github.com/qtox/qtox/blob/482b1547b48b6845189cff6a6b4ff77054af764c/windows/cross-compile/build.sh#L860)):*
> ```Shell
>  $(foreach lib,$(filter %$(SO_VERSION_MAJOR).dylib,$(LIBS)),$(eval $(call dl_template,$(lib))))
>  $(foreach lib,$(filter %$(SO_VERSION_MAJOR).dll,$(LIBS)),$(eval $(call dll_template,$(lib))))
>  
> ```

IDE automatically deleted trailing whitespace from diff. Diff should remain unchanged.
___
*[windows/cross-compile/build.sh, line 866 at r10](https://reviewable.io/reviews/qtox/qtox/5932#-MSK64hM1zA6NVXWMflg:-MSK64hN1ZkONRbizmfL:b-816h6l) ([raw file](https://github.com/qtox/qtox/blob/482b1547b48b6845189cff6a6b4ff77054af764c/windows/cross-compile/build.sh#L866)):*
> ```Shell
> @@ -513,23 +513,23 @@
>  }
>  
> ```

Same.
___
*[windows/cross-compile/build.sh, line 941 at r10](https://reviewable.io/reviews/qtox/qtox/5932#-MSK65rm291enRYgUyPm:-MSK65rm291enRYgUyPn:b-816h6l) ([raw file](https://github.com/qtox/qtox/blob/482b1547b48b6845189cff6a6b4ff77054af764c/windows/cross-compile/build.sh#L941)):*
> ```Shell
> +$(BUILD_PFX)$(LIBVPX_SO): SONAME = libvpx.dll
>  $(BUILD_PFX)$(LIBVPX_SO): EXPORTS_FILE = $(EXPORT_FILE)
>  
> ```

Same.


<!-- Sent from Reviewable.io -->

2021-01-30 21:45 UTC, anthonybilinski requested changes
> *[Reviewable](https://reviewable.io/reviews/qtox/qtox/5932)* status: 0 of 1 LGTMs obtained

___
*[windows/cross-compile/build.sh, line 860 at r10](https://reviewable.io/reviews/qtox/qtox/5932#-MSK6-DK96Y1zxnPC11M:-MSKFOUcCxT2kU8SJMte:bt2vr1b) ([raw file](https://github.com/qtox/qtox/blob/482b1547b48b6845189cff6a6b4ff77054af764c/windows/cross-compile/build.sh#L860)):*
<details><summary><i>Previously, anthonybilinski (Anthony Bilinski) wrote…</i></summary><blockquote>

IDE automatically deleted trailing whitespace from diff. Diff should remain unchanged.
</blockquote></details>

Fixed.
___
*[windows/cross-compile/build.sh, line 866 at r10](https://reviewable.io/reviews/qtox/qtox/5932#-MSK64hM1zA6NVXWMflg:-MSKFPHa5ZIkGk5GQqFK:bt2vr1b) ([raw file](https://github.com/qtox/qtox/blob/482b1547b48b6845189cff6a6b4ff77054af764c/windows/cross-compile/build.sh#L866)):*
<details><summary><i>Previously, anthonybilinski (Anthony Bilinski) wrote…</i></summary><blockquote>

Same.
</blockquote></details>

Fixed.
___
*[windows/cross-compile/build.sh, line 941 at r10](https://reviewable.io/reviews/qtox/qtox/5932#-MSK65rm291enRYgUyPm:-MSKFQ4Y0404beQneriV:bt2vr1b) ([raw file](https://github.com/qtox/qtox/blob/482b1547b48b6845189cff6a6b4ff77054af764c/windows/cross-compile/build.sh#L941)):*
<details><summary><i>Previously, anthonybilinski (Anthony Bilinski) wrote…</i></summary><blockquote>

Same.
</blockquote></details>

Fixed.


<!-- Sent from Reviewable.io -->

2021-01-30 21:45 UTC, anthonybilinski reviewed
<img class="emoji" title=":lgtm_strong:" alt=":lgtm_strong:" align="absmiddle" src="https://reviewable.io/lgtm_strong.png" height="20" width="61"/> 

> Reviewed 1 of 1 files at r14.
> *[Reviewable](https://reviewable.io/reviews/qtox/qtox/5932#-:-MSKFV_u71j6dERaP_V8:b-uwkowd)* status: :shipit: complete! 1 of 1 LGTMs obtained



<!-- Sent from Reviewable.io -->

2021-01-30 22:28 UTC, sphaerophoria commented
> 
> 
> > _[Reviewable](https://reviewable.io/reviews/qtox/qtox/5932)_ status: 0 of 1 LGTMs obtained
> 
> _[windows/cross-compile/build.sh, line 860 at r10](https://reviewable.io/reviews/qtox/qtox/5932#-MSK6-DK96Y1zxnPC11M:-MSKFOUcCxT2kU8SJMte:bt2vr1b) ([raw file](https://github.com/qtox/qtox/blob/482b1547b48b6845189cff6a6b4ff77054af764c/windows/cross-compile/build.sh#L860)):_
> Previously, anthonybilinski (Anthony Bilinski) wrote…
> 
> Fixed.
> 
> _[windows/cross-compile/build.sh, line 866 at r10](https://reviewable.io/reviews/qtox/qtox/5932#-MSK64hM1zA6NVXWMflg:-MSKFPHa5ZIkGk5GQqFK:bt2vr1b) ([raw file](https://github.com/qtox/qtox/blob/482b1547b48b6845189cff6a6b4ff77054af764c/windows/cross-compile/build.sh#L866)):_
> Previously, anthonybilinski (Anthony Bilinski) wrote…
> 
> Fixed.
> 
> _[windows/cross-compile/build.sh, line 941 at r10](https://reviewable.io/reviews/qtox/qtox/5932#-MSK65rm291enRYgUyPm:-MSKFQ4Y0404beQneriV:bt2vr1b) ([raw file](https://github.com/qtox/qtox/blob/482b1547b48b6845189cff6a6b4ff77054af764c/windows/cross-compile/build.sh#L941)):_
> Previously, anthonybilinski (Anthony Bilinski) wrote…
> 
> Fixed.

Thanks!

2021-01-31 02:16 UTC, anthonybilinski approved these changes

2021-01-31 02:24 UTC, anthonybilinski approved these changes
> Reviewed 26 of 26 files at r16.
> *[Reviewable](https://reviewable.io/reviews/qtox/qtox/5932)* status: :shipit: complete! 1 of 1 LGTMs obtained



<!-- Sent from Reviewable.io -->

2021-01-31 02:28 UTC, anthonybilinski commented
Updated commit hashes for the flatpak manifest that were missed when going from 0.0.1 to 0.0.2.

2021-01-31 08:47 UTC, merged