feat(groups): Allow being in group call if only member
qTox/qTox pull request #5982
Opened 2020-02-12 04:52 UTC by sphaerophoria

In other applications chatrooms allow you to idle in a call and have
people hop in and out as desired. If a user is the only one presently
online in a group but knows someone will be joining shortly they should
be able to join the call ahead of time.

Tested in a group call with another qtox instance.
* Muting before anyone else was online worked as expected
* Deafening before anyone else was online worked as expected
* Joining and leaving calls before anyone was online worked as expected

- [ x] Commits follow our [git commit guidelines](https://github.com/qTox/qTox/blob/master/CONTRIBUTING.md#git-commit-guidelines)

2020-02-12 20:38 UTC, sudden6 commented
> Deafening before anyone else comes online prevents audio from being sent until undeafened. This might be unexpected behavior.

Do you mean that if I set the speakers to silent (deafening?) before someone joins the call, no audio (from mic) is being sent?

2020-02-12 23:06 UTC, sphaerophoria commented
yeah, it isnt great and i was planning on looking into it, just noticed
after i filed the PR :(

On Wed, Feb 12, 2020, 12:38 sudden6 <notifications@github.com> wrote:

> Deafening before anyone else comes online prevents audio from being sent
> until undeafened. This might be unexpected behavior.
>
> Do you mean that if I set the speakers to silent (deafening?) before
> someone joins the call, no audio (from mic) is being sent?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/qTox/qTox/pull/5982?email_source=notifications&email_token=AAIFF42MDM64SSZLFKCBHELRCRM33A5CNFSM4KTST7L2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOELSJQQY#issuecomment-585406531>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAIFF42ZVWFE65XJ3EGN5A3RCRM33ANCNFSM4KTST7LQ>
> .
>

2020-02-12 23:31 UTC, sudden6 commented
Ok, then I'll be waiting for a fix for that problem.

2020-02-15 18:46 UTC, sphaerophoria commented
Sorry for the bad initial PR. This update is a little less clean than I would have liked... the joinGroupCall and leaveGroupCall are now asymmetric APIs. This is because Core needs to be able to leave the call based on groupId not Group*, but the call needs Group* to determine the number of peers in the chat.

We can't use the ToxGroupCall "peers" member variable because it only flags peers that have sent audio. Using the internal peers varialbe would result in us not sending audio if all of our peers are muted.

2020-02-16 10:42 UTC, sudden6 requested changes
I think passing `Group` is better than dealing with the group numbers in the API and IMO all the API of Core and CoreAV should be moved in that direction, so for me that's perfectly fine.

> Reviewed 2 of 6 files at r1.
> *[Reviewable](https://reviewable.io/reviews/qtox/qtox/5982#-:-M0CZ69o2comFp5k-2sJ:b-klok18)* status: 0 of 1 LGTMs obtained

___
*[src/core/coreav.cpp, line 538 at r1](https://reviewable.io/reviews/qtox/qtox/5982#-M0CYTqn6AFfGjdafDz2:-M0CYTqn6AFfGjdafDz3:b-mnz3f2) ([raw file](https://github.com/qtox/qtox/blob/be563f0d180bd36db9e9919a07fe86e3616887a9/src/core/coreav.cpp#L538)):*
> ```cpp
>  * @param groupId Id of group to join
>  */
> void CoreAV::joinGroupCall(Group* group)
> ```

IMO this should be `const Group& `, because a group call with a `nullptr` group doesn't really make sense. At minimum `const` should be added, since AFAICT no non-const operations are performed on `group`


<!-- Sent from Reviewable.io -->

2020-02-23 19:49 UTC, sphaerophoria reviewed
> *[Reviewable](https://reviewable.io/reviews/qtox/qtox/5982)* status: 0 of 1 LGTMs obtained

___
*[src/core/coreav.cpp, line 538 at r1](https://reviewable.io/reviews/qtox/qtox/5982#-M0CYTqn6AFfGjdafDz2:-M0na5GYCCBfd7CxmfC_:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/be563f0d180bd36db9e9919a07fe86e3616887a9/src/core/coreav.cpp#L538)):*
<details><summary><i>Previously, sudden6 wrote…</i></summary><blockquote>

IMO this should be `const Group& `, because a group call with a `nullptr` group doesn't really make sense. At minimum `const` should be added, since AFAICT no non-const operations are performed on `group`
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-02-23 20:28 UTC, sudden6 approved these changes
<img class="emoji" title=":lgtm_strong:" alt=":lgtm_strong:" align="absmiddle" src="https://reviewable.io/lgtm_strong.png" height="20" width="61"/> will test and then merge

> Reviewed 5 of 5 files at r2.
> *[Reviewable](https://reviewable.io/reviews/qtox/qtox/5982#-:-M0nj1wA-LegYCLNR7tG:bqfau6p)* status: :shipit: complete! 1 of 1 LGTMs obtained



<!-- Sent from Reviewable.io -->

2020-02-28 17:23 UTC, merged