Fix desktop notifications
qTox/qTox pull request #6073
Opened 2020-04-06 04:31 UTC by sphaerophoria

feat(notification): Notifications now always replace the previous one
    
    This is a feature/fix to improve notification behavior when we receive
    over 3 messages.
    
    SnoreNotify prevents over 3 notifications from being displayed before a
    user clears the notification. This is presumably to avoid infinite
    notification spam.
    
    Unfortunately this results in the notifications just coming in _after_
    the user clears them. This means if there are 100s of messages built up
    the user has to clear their notifications N messages / 3 times.
    
    This feature/fix folds all notifications into a single notification
    representing the current qTox notification state. See
    notificationgenerator_test.cpp for what the new messages look like.

- [x] Commits follow our [git commit guidelines](https://github.com/qTox/qTox/blob/master/CONTRIBUTING.md#git-commit-guidelines)

2020-05-15 09:18 UTC, anthonybilinski requested changes
Sorry about the massive spam of "same", did it so it's easier to track each spotted issue through PR updates and verify them one-by-one, hopefully not too annoying.

Overall looks like a really nice improvement.

> Reviewed 16 of 16 files at r1.
> *[Reviewable](https://reviewable.io/reviews/qtox/qtox/6073#-:-M7MbxaW55nLc_VZTnAP:b-jzr7jw)* status: 0 of 1 LGTMs obtained

___
*[src/model/notificationdata.h, line 1 at r1](https://reviewable.io/reviews/qtox/qtox/6073#-M6PvkVM2szDyRU5nM-M:-M6PvkVM2szDyRU5nM-N:b-h3twsp) ([raw file](https://github.com/qtox/qtox/blob/007f2e51850179da4962f2217b4694c6fc92bff8/src/model/notificationdata.h#L1)):*
> ```objc
> #pragma once
> ```

needs license and copyright
___
*[src/model/notificationgenerator.h, line 1 at r1](https://reviewable.io/reviews/qtox/qtox/6073#-M6PvlVH8MtwsKzOVfDA:-M6PvlVI9-DGuoHidAfA:b-h3twsp) ([raw file](https://github.com/qtox/qtox/blob/007f2e51850179da4962f2217b4694c6fc92bff8/src/model/notificationgenerator.h#L1)):*
> ```objc
> #pragma once
> ```

needs license and copyright
___
*[src/model/notificationgenerator.cpp, line 27 at r1](https://reviewable.io/reviews/qtox/qtox/6073#-M6SvQKD1eom-9qnzGtK:-M6SvQKD1eom-9qnzGtL:bro8wyf) ([raw file](https://github.com/qtox/qtox/blob/007f2e51850179da4962f2217b4694c6fc92bff8/src/model/notificationgenerator.cpp#L27)):*
> ```cpp
>     QString generateMultiChatTitle(size_t numChats, size_t numMessages)
>     {
>         // FIXME: how do I tr this
> ```

this looks right. the rest is magic :fireworks:
___
*[src/model/notificationgenerator.cpp, line 36 at r1](https://reviewable.io/reviews/qtox/qtox/6073#-M6T0UUi9LPcVom-JjFE:-M6T0UUi9LPcVom-JjFF:b-90bgy6) ([raw file](https://github.com/qtox/qtox/blob/007f2e51850179da4962f2217b4694c6fc92bff8/src/model/notificationgenerator.cpp#L36)):*
> ```cpp
>     QString generateSingleChatTitle(
>         const QHash<T, size_t> numNotifications,
>         T contact)
> ```

what about using `Contact` rather than templating this? Both Friend and Group inherit from it.
___
*[src/model/notificationgenerator.cpp, line 40 at r1](https://reviewable.io/reviews/qtox/qtox/6073#-M6T3UtfCAYZmNS-LEty:-M6T3UtfCAYZmNS-LEtz:b-xtfx0f) ([raw file](https://github.com/qtox/qtox/blob/007f2e51850179da4962f2217b4694c6fc92bff8/src/model/notificationgenerator.cpp#L40)):*
> ```cpp
>         if (numNotifications[contact] > 1)
>         {
>             return QObject::tr("%1 messages from %2")
> ```

It would be good to add an example string to the translation since the meaning isn't clear from the string. e.g. `tr("%1 messages from %2", "3 messages from Bob")`. Also `message(s)` rather than `messages` will allow translators to handle language specific pluralization. I'm also not sure if translations will be the same between users and groups in different languages.. maybe it's worth splitting the group and friend translation strings in case the sentence structure is different in some languages.
___
*[src/model/notificationgenerator.cpp, line 46 at r1](https://reviewable.io/reviews/qtox/qtox/6073#-M7Lgjbk5MbDl3qbDEGG:-M7Lgjbl-akt0M__yCEK:ba2wp3) ([raw file](https://github.com/qtox/qtox/blob/007f2e51850179da4962f2217b4694c6fc92bff8/src/model/notificationgenerator.cpp#L46)):*
> ```cpp
>         else
>         {
>             return QObject::tr("%1")
> ```

I don't think this can be or needs to be translated, can just return `contact->getDisplayedName()` directly.
___
*[src/model/notificationgenerator.cpp, line 67 at r1](https://reviewable.io/reviews/qtox/qtox/6073#-M7LsT9F6spWE8mIUmTW:-M7LsT9F6spWE8mIUmTX:bhhqgve) ([raw file](https://github.com/qtox/qtox/blob/007f2e51850179da4962f2217b4694c6fc92bff8/src/model/notificationgenerator.cpp#L67)):*
> ```cpp
>     }
> 
>     QString generateTitle(
> ```

the two `generateTitle`s could be deduplicated by passing `Contact*` rather than `Group*` and `Friend*` and then having the first map always be the one that's passed to `generateSingleChatTitle`, e.g. `generateTitle(const QHash<const Friend*, size_t>& thisNotifications,  const QHash<const Group* , size_t>& otherNotifications, const Contact* f`
___
*[src/model/notificationgenerator.cpp, line 203 at r1](https://reviewable.io/reviews/qtox/qtox/6073#-M7M0Bzt7gMNR8jAIDay:-M7M0Bzu8mxKGuQDD6Tx:b-xpimj8) ([raw file](https://github.com/qtox/qtox/blob/007f2e51850179da4962f2217b4694c6fc92bff8/src/model/notificationgenerator.cpp#L203)):*
> ```cpp
>     else
>     {
>         ret.title = f->getDisplayedName() + " - " + tr("File sent");
> ```

"Bob - File sent" sounds like an outgoing transfer to me, I think "Bob - file transfer" to match the above terminology would be clearer
___
*[src/model/notificationgenerator.cpp, line 221 at r1](https://reviewable.io/reviews/qtox/qtox/6073#-M6T1T3ODYgRV6V6VBNt:-M6T1T3ODYgRV6V6VBNu:bbszzdz) ([raw file](https://github.com/qtox/qtox/blob/007f2e51850179da4962f2217b4694c6fc92bff8/src/model/notificationgenerator.cpp#L221)):*
> ```cpp
>     }
> 
>     ret.title = from->getDisplayedName() + tr(" invites you to join a group.");
> ```

since in other languages the sentence might be structured differently, use a formatted string inside the `tr` instead of combining two strings.
___
*[src/model/notificationgenerator.cpp, line 237 at r1](https://reviewable.io/reviews/qtox/qtox/6073#-M7M3hdI4TgWOFbj7UUy:-M7M3hdI4TgWOFbj7UUz:b-hwyld7) ([raw file](https://github.com/qtox/qtox/blob/007f2e51850179da4962f2217b4694c6fc92bff8/src/model/notificationgenerator.cpp#L237)):*
> ```cpp
>     }
> 
>     ret.title = sender.toString() + tr(" sent you a friend request.");
> ```

same (combine translation string)
___
*[src/model/notificationgenerator.cpp, line 237 at r1](https://reviewable.io/reviews/qtox/qtox/6073#-M7MVnpHE1Khi350jPVk:-M7MVnpHE1Khi350jPVl:by0w2yz) ([raw file](https://github.com/qtox/qtox/blob/007f2e51850179da4962f2217b4694c6fc92bff8/src/model/notificationgenerator.cpp#L237)):*
> ```cpp
>     }
> 
>     ret.title = sender.toString() + tr(" sent you a friend request.");
> ```

If the `sender` is going to overflow most notification titles, it might be better as "Friend request received from 00000000000000..." Rather than "00000000000000000000000000000000000000...". I'm not sure how long of titles are typically allowed though
___
*[src/persistence/inotificationsettings.h, line 2 at r1](https://reviewable.io/reviews/qtox/qtox/6073#-M7M5-2X7IQdTKLKOv_g:-M7M5-2X7IQdTKLKOv_h:bwgeq47) ([raw file](https://github.com/qtox/qtox/blob/007f2e51850179da4962f2217b4694c6fc92bff8/src/persistence/inotificationsettings.h#L2)):*
> ```objc
> /*
>     Copyright © 2014-2019 by The qTox Project Contributors
> ```

technically should just be 2020
___
*[src/persistence/inotificationsettings.h, line 21 at r1](https://reviewable.io/reviews/qtox/qtox/6073#-M7M4uU5AlGNCEAhLlfA:-M7M4uU5AlGNCEAhLlfB:b-ihw3wr) ([raw file](https://github.com/qtox/qtox/blob/007f2e51850179da4962f2217b4694c6fc92bff8/src/persistence/inotificationsettings.h#L21)):*
> ```objc
> 
> #ifndef INOTIFICATION_SETTINGS_H
> #define INOTIFICATION_SETTINGS_H
> ```

#pragma once is now here :partying_face: 
___
*[src/platform/desktop_notifications/desktopnotify.h, line 25 at r1](https://reviewable.io/reviews/qtox/qtox/6073#-M7M5O0mByMjy_Ow0cx7:-M7M5O0mByMjy_Ow0cx8:bse8a2h) ([raw file](https://github.com/qtox/qtox/blob/007f2e51850179da4962f2217b4694c6fc92bff8/src/platform/desktop_notifications/desktopnotify.h#L25)):*
> ```objc
> #include <libsnore/snore.h>
> #include "src/model/contact.h"
> #include "src/model/notificationdata.h"
> ```

put qTox headers above external library headers: https://github.com/qTox/qTox/blob/master/doc/coding_standards.md#includes
___
*[src/widget/widget.cpp, line 1541 at r1](https://reviewable.io/reviews/qtox/qtox/6073#-M7M7jld6j1Tf_k5zjMk:-M7M7jld6j1Tf_k5zjMl:bu3resy) ([raw file](https://github.com/qtox/qtox/blob/007f2e51850179da4962f2217b4694c6fc92bff8/src/widget/widget.cpp#L1541)):*
> ```cpp
>         ui->friendList->trackWidget(widget);
> #if DESKTOP_NOTIFICATIONS
>         auto notificationData = [...]

2020-05-15 09:40 UTC, Diadlo reviewed
> *[Reviewable](https://reviewable.io/reviews/qtox/qtox/6073)* status: 0 of 1 LGTMs obtained

___
*[src/model/notificationgenerator.cpp, line 40 at r1](https://reviewable.io/reviews/qtox/qtox/6073#-M6T3UtfCAYZmNS-LEty:-M7Mh1H8-QaMTByuz8Os:bl50zyh) ([raw file](https://github.com/qtox/qtox/blob/007f2e51850179da4962f2217b4694c6fc92bff8/src/model/notificationgenerator.cpp#L40)):*
<details><summary><i>Previously, anthonybilinski (Anthony Bilinski) wrote…</i></summary><blockquote>

It would be good to add an example string to the translation since the meaning isn't clear from the string. e.g. `tr("%1 messages from %2", "3 messages from Bob")`. Also `message(s)` rather than `messages` will allow translators to handle language specific pluralization. I'm also not sure if translations will be the same between users and groups in different languages.. maybe it's worth splitting the group and friend translation strings in case the sentence structure is different in some languages.
</blockquote></details>

Just a note. Qt can handle the plural forms
https://doc.qt.io/qt-5/i18n-source-translation.html#handling-plurals


<!-- Sent from Reviewable.io -->

2020-05-15 09:42 UTC, Diadlo reviewed
> *[Reviewable](https://reviewable.io/reviews/qtox/qtox/6073)* status: 0 of 1 LGTMs obtained

___
*[src/model/notificationgenerator.cpp, line 203 at r1](https://reviewable.io/reviews/qtox/qtox/6073#-M7M0Bzt7gMNR8jAIDay:-M7MhFjP1eMEflHuEDpl:bfvyj9t) ([raw file](https://github.com/qtox/qtox/blob/007f2e51850179da4962f2217b4694c6fc92bff8/src/model/notificationgenerator.cpp#L203)):*
<details><summary><i>Previously, anthonybilinski (Anthony Bilinski) wrote…</i></summary><blockquote>

"Bob - File sent" sounds like an outgoing transfer to me, I think "Bob - file transfer" to match the above terminology would be clearer
</blockquote></details>

Also, it is better to use formatting string too


<!-- Sent from Reviewable.io -->

2020-05-16 03:09 UTC, sphaerophoria reviewed
> *[Reviewable](https://reviewable.io/reviews/qtox/qtox/6073)* status: 0 of 1 LGTMs obtained

___
*[src/model/notificationdata.h, line 1 at r1](https://reviewable.io/reviews/qtox/qtox/6073#-M6PvkVM2szDyRU5nM-M:-M7QJWeW5GR8LQh6WYqJ:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/007f2e51850179da4962f2217b4694c6fc92bff8/src/model/notificationdata.h#L1)):*
<details><summary><i>Previously, anthonybilinski (Anthony Bilinski) wrote…</i></summary><blockquote>

needs license and copyright
</blockquote></details>

Done.
___
*[src/model/notificationgenerator.h, line 1 at r1](https://reviewable.io/reviews/qtox/qtox/6073#-M6PvlVH8MtwsKzOVfDA:-M7QJcg8CNuf2SjCDOnC:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/007f2e51850179da4962f2217b4694c6fc92bff8/src/model/notificationgenerator.h#L1)):*
<details><summary><i>Previously, anthonybilinski (Anthony Bilinski) wrote…</i></summary><blockquote>

needs license and copyright
</blockquote></details>

Done.
___
*[src/model/notificationgenerator.cpp, line 27 at r1](https://reviewable.io/reviews/qtox/qtox/6073#-M6SvQKD1eom-9qnzGtK:-M7QJg_01XdKOmG3CIU0:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/007f2e51850179da4962f2217b4694c6fc92bff8/src/model/notificationgenerator.cpp#L27)):*
<details><summary><i>Previously, anthonybilinski (Anthony Bilinski) wrote…</i></summary><blockquote>

this looks right. the rest is magic :fireworks:
</blockquote></details>

Done.
___
*[src/model/notificationgenerator.cpp, line 36 at r1](https://reviewable.io/reviews/qtox/qtox/6073#-M6T0UUi9LPcVom-JjFE:-M7QJs3I4PTt1T-dazft:btvqcsv) ([raw file](https://github.com/qtox/qtox/blob/007f2e51850179da4962f2217b4694c6fc92bff8/src/model/notificationgenerator.cpp#L36)):*
<details><summary><i>Previously, anthonybilinski (Anthony Bilinski) wrote…</i></summary><blockquote>

what about using `Contact` rather than templating this? Both Friend and Group inherit from it.
</blockquote></details>

It's because groupNotifications has to be stored as a `QHash<Group*, size_t>` in order to display who the last message was from. This forces me to store two maps that both inherit from `Contact` but `QHash<Group*, size_t>` is not castable into `QHash<Contact*, size_t>` I could duplicate the map, but I found the template solution easier.
___
*[src/model/notificationgenerator.cpp, line 40 at r1](https://reviewable.io/reviews/qtox/qtox/6073#-M6T3UtfCAYZmNS-LEty:-M7QMuCB-IPolDfvc389:b-oxt245) ([raw file](https://github.com/qtox/qtox/blob/007f2e51850179da4962f2217b4694c6fc92bff8/src/model/notificationgenerator.cpp#L40)):*
> It would be good to add an example string to the translation since the meaning isn't clear from the string. e.g. tr("%1 messages from %2", "3 messages from Bob")

I don't like the concept of putting that into the disambiguation string. According to https://doc.qt.io/qt-5/i18n-source-translation.html#disambiguation the disambiguation is more for giving a "tag" to identical strings. 

I'm going to follow the suggestion of https://doc.qt.io/qt-5/i18n-source-translation.html#translator-comments and add a comment with `//:` above the tr
___
*[src/model/notificationgenerator.cpp, line 46 at r1](https://reviewable.io/reviews/qtox/qtox/6073#-M7Lgjbk5MbDl3qbDEGG:-M7QNMSS4VrPgF-89BF5:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/007f2e51850179da4962f2217b4694c6fc92bff8/src/model/notificationgenerator.cpp#L46)):*
<details><summary><i>Previously, anthonybilinski (Anthony Bilinski) wrote…</i></summary><blockquote>

I don't think this can be or needs to be translated, can just return `contact->getDisplayedName()` directly.
</blockquote></details>

Done.
___
*[src/model/notificationgenerator.cpp, line 67 at r1](https://reviewable.io/reviews/qtox/qtox/6073#-M7LsT9F6spWE8mIUmTW:-M7QNyp-E6REVB0khJzk:b-jtbi2b) ([raw file](https://github.com/qtox/qtox/blob/007f2e51850179da4962f2217b4694c6fc92bff8/src/model/notificationgenerator.cpp#L67)):*
<details><summary><i>Previously, anthonybilinski (Anthony Bilinski) wrote…</i></summary><blockquote>

the two `generateTitle`s could be deduplicated by passing `Contact*` rather than `Group*` and `Friend*` and then having the first map always be the one that's passed to `generateSingleChatTitle`, e.g. `generateTitle(const QHash<const Friend*, size_t>& thisNotifications,  const QHash<const Group* , size_t>& otherNotifications, const Contact* f`
</blockquote></details>

Same as above, unfortunately groups/friends have to be stored separately
___
*[src/model/notificationgenerator.cpp, line 203 at r1](https://reviewable.io/reviews/qtox/qtox/6073#-M7M0Bzt7gMNR8jAIDay:-M7QOD7r-UdAtiXEXZ0E:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/007f2e51850179da4962f2217b4694c6fc92bff8/src/model/notificationgenerator.cpp#L203)):*
<details><summary><i>Previously, Diadlo (Polshakov Dmitry) wrote…</i></summary><blockquote>

Also, it is better to use formatting string too
</blockquote></details>

Done.
___
*[src/model/notificationgenerator.cpp, line 221 at r1](https://reviewable.io/reviews/qtox/qtox/6073#-M6T1T3ODYgRV6V6VBNt:-M7QOKGv6go-7cai7Zua:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/007f2e51850179da4962f2217b4694c6fc92bff8/src/model/notificationgenerator.cpp#L221)):*
<details><summary><i>Previously, anthonybilinski (Anthony Bilinski) wrote…</i></summary><blockquote>

since in other languages the sentence might be structured differently, use a formatted string inside the `tr` instead of combining two strings.
</blockquote></details>

Done.
___
*[src/model/notificationgenerator.cpp, line 237 at r1](https://reviewable.io/reviews/qtox/qtox/6073#-M7M3hdI4TgWOFbj7UUy:-M7QOP9Q9i7oiHWXZStd:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/007f2e51850179da4962f2217b4694c6fc92bff8/src/model/notificationgenerator.cpp#L237)):*
<details><summary><i>Previously, anthonybilinski (Anthony Bilinski) wrote…</i></summary><blockquote>

same (combine translation string)
</blockquote></details>

Done.
___
*[src/model/notificationgenerator.cpp, line 237 at r1](https://reviewable.io/reviews/qtox/qtox/6073#-M7MVnpHE1Khi350jPVk:-M7QOQSj9t7RmMWDDwZ-:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/007f2e51850179da4962f2217b4694c6fc92bff8/src/model/notificationgenerator.cpp#L237)):*
<details><summary><i>Previously, anthonybilinski (Anthony Bilinski) wrote…</i></summary><blockquote>

If the `sender` is going to overflow most notification titles, it might be better as "Friend request received from 00000000000000..." Rather than "00000000000000000000000000000000000000...". I'm not sure how long of titles are typically allowed though
</blockquote></details>

Done.
___
*[src/persistence/inotificationsettings.h, line 2 at r1](https://reviewable.io/reviews/qtox/qtox/6073#-M7M5-2X7IQdTKLKOv_g:-M7QOUnnBMqQSuPeXw3t:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/007f2e51850179da4962f2217b4694c6fc92bff8/src/persistence/inotificationsettings.h#L2)):*
<details><summary><i>Previously, anthonybilinski (Anthony Bilinski) wrote…</i></summary><blockquote>

technically should just be 2020
</blockquote></details>

Done.
___
*[src/persistence/inotificationsettings.h, line 21 at r1](https://reviewable.io/reviews/qtox/qtox/6073#-M7M4uU5AlGNCEAhLlfA:-M7QOYN9EsJ9dfCxben5:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/007f2e51850179da4962f2217b4694c6fc92bff8/src/persistence/inotificationsettings.h#L21)):*
<details><summary><i>Previously, anthonybilinski (Anthony Bilinski) wrote…</i></summary><blockquote>

#pragma once is now here :partying_face: 
</blockquote></details>

Done.
___
*[src/platform/desktop_notifications/desktopnotify.h, line 25 at r1](https://reviewable.io/reviews/qtox/qtox/6073#-M7M5O0mByMjy_Ow0cx7:-M7QOf1G8rQgc2-vf52x:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/007f2e51850179da4962f2217b4694c6fc92bff8/src/platform/desktop_notifications/desktopnotify.h#L25)):*
<details><summary><i>Previously, anthonybilinski (Anthony Bilinski) wrote…</i></summary><blockquote>

put qTox headers above external librar [...]

2020-05-17 01:48 UTC, anthonybilinski requested changes
> Reviewed 1 of 16 files at r1, 10 of 11 files at r3, 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/qtox/qtox/6073)* status: 0 of 1 LGTMs obtained

___
*[CMakeLists.txt, line 376 at r4](https://reviewable.io/reviews/qtox/qtox/6073#-M7VG-sOCfB7EGUOt3Ny:-M7VG-sOCfB7EGUOt3Nz:b-6bn081) ([raw file](https://github.com/qtox/qtox/blob/1fab98ffd4e1c92b3cfcbcded7507b85ac5f9799/CMakeLists.txt#L376)):*
> ```CMake
>   src/model/chathistory.h
>   src/model/chathistory.cpp
>   src/model/notificationgenerator.cpp
> ```

missing `notificationgenerator.h`
___
*[src/model/notificationgenerator.cpp, line 36 at r1](https://reviewable.io/reviews/qtox/qtox/6073#-M6T0UUi9LPcVom-JjFE:-M7VIVdzBTUlzk_fwWOy:b9lc911) ([raw file](https://github.com/qtox/qtox/blob/007f2e51850179da4962f2217b4694c6fc92bff8/src/model/notificationgenerator.cpp#L36)):*
<details><summary><i>Previously, sphaerophoria wrote…</i></summary><blockquote>

It's because groupNotifications has to be stored as a `QHash<Group*, size_t>` in order to display who the last message was from. This forces me to store two maps that both inherit from `Contact` but `QHash<Group*, size_t>` is not castable into `QHash<Contact*, size_t>` I could duplicate the map, but I found the template solution easier.
</blockquote></details>

urg.. that's annoying that it can't just cast. I guess using `Contact` maps and then `std::dynamic_cast`-ing the case where `peerList` is gotten and relying on the caller to pass in the maps in the right order is an option.. but then we're moving compile-time checks to runtime, not to mention no exception support in qTox means we'd fail _really_ hard. I guess this is the best option.
___
*[src/model/notificationgenerator.cpp, line 40 at r1](https://reviewable.io/reviews/qtox/qtox/6073#-M6T3UtfCAYZmNS-LEty:-M7QxXnf2qIv3NEbWXmk:b-mf5bbs) ([raw file](https://github.com/qtox/qtox/blob/007f2e51850179da4962f2217b4694c6fc92bff8/src/model/notificationgenerator.cpp#L40)):*
<details><summary><i>Previously, sphaerophoria wrote…</i></summary><blockquote>

> It would be good to add an example string to the translation since the meaning isn't clear from the string. e.g. tr("%1 messages from %2", "3 messages from Bob")

I don't like the concept of putting that into the disambiguation string. According to https://doc.qt.io/qt-5/i18n-source-translation.html#disambiguation the disambiguation is more for giving a "tag" to identical strings. 

I'm going to follow the suggestion of https://doc.qt.io/qt-5/i18n-source-translation.html#translator-comments and add a comment with `//:` above the tr
</blockquote></details>

looks better and more idiomatic with Qt5 :+1: 
___
*[test/model/notificationgenerator_test.cpp, line 105 at r1](https://reviewable.io/reviews/qtox/qtox/6073#-M7MJah04Yt6XMcz8WUY:-M7VAbnCCYdQM4XiJPbP:b9j2lbq) ([raw file](https://github.com/qtox/qtox/blob/007f2e51850179da4962f2217b4694c6fc92bff8/test/model/notificationgenerator_test.cpp#L105)):*
<details><summary><i>Previously, sphaerophoria wrote…</i></summary><blockquote>

I didn't want to have to set an alias, personally I find setName more clear
</blockquote></details>

`Friend` constructor allows the name to be set separately from alias, e.g. could do `Friend(0, ToxPk(), {}, "friendName")`
___
*[test/model/notificationgenerator_test.cpp, line 279 at r1](https://reviewable.io/reviews/qtox/qtox/6073#-M7MZe2t4ZxKCCFbnpmB:-M7VENCuAZpB2i0ji3ej:b-et47ia) ([raw file](https://github.com/qtox/qtox/blob/007f2e51850179da4962f2217b4694c6fc92bff8/test/model/notificationgenerator_test.cpp#L279)):*
<details><summary><i>Previously, sphaerophoria wrote…</i></summary><blockquote>

I don't think they should be considered the same. If someone sends me a group notification I want that to be separate from the message history. Ideally I think this should take up a separate notification slot (i.e. you could have a group invite notification alongside a new message notification) but I wasn't willing to put in that effort
</blockquote></details>

Agreed that they shouldn't be counted as messages. Fair that you didn't want to add it as part of this, doesn't seem essential.
___
*[test/model/notificationgenerator_test.cpp, line 238 at r4](https://reviewable.io/reviews/qtox/qtox/6073#-M7VEfweAG7fWUMfpv3W:-M7VEfweAG7fWUMfpv3X:b-c6bywj) ([raw file](https://github.com/qtox/qtox/blob/1fab98ffd4e1c92b3cfcbcded7507b85ac5f9799/test/model/notificationgenerator_test.cpp#L238)):*
> ```cpp
>     auto notificationData = notificationGenerator->fileTransferNotification(&f, "file", 5 * 1024 * 1024 /* 5MB */);
> 
>     QVERIFY(notificationData.title == "2 message(s) from friend");
> ```

when we eventually fix english -> english translations this will need to be changed to "2 messages from friend".. but for the time being this is what we output. No action required.


<!-- Sent from Reviewable.io -->

2020-05-17 02:07 UTC, anthonybilinski commented
Rebased PR commits to tip and updated your fork's branch.

2020-05-17 07:31 UTC, anthonybilinski requested changes
> Reviewed 3 of 15 files at r5, 11 of 11 files at r6, 12 of 12 files at r7.
> *[Reviewable](https://reviewable.io/reviews/qtox/qtox/6073)* status: 0 of 1 LGTMs obtained

*[a discussion](https://reviewable.io/reviews/qtox/qtox/6073#-M7WXkNO3SyZCUL6KbLP:-M7WXkNO3SyZCUL6KbLQ:b-f9ev0l) (no related file):*
When testing this, I get error logs from snore on every notification:
```
[07:30:02.940 UTC] :0 : Warning: Snore::Notification("qTest2", "1", id = 10)was already closed
[07:30:03.636 UTC] :0 : Warning: Snore::Notification("2 message(s) from qTest2", "2", id = 11)was already closed
[07:30:04.136 UTC] :0 : Warning: Snore::Notification("3 message(s) from qTest2", "3", id = 12)was already closed
[07:30:04.537 UTC] :0 : Warning: Snore::Notification("4 message(s) from qTest2", "4", id = 13)was already closed
```

---
___
*[CMakeLists.txt, line 376 at r4](https://reviewable.io/reviews/qtox/qtox/6073#-M7VG-sOCfB7EGUOt3Ny:-M7WRQp7DKmbsDUXs9P-:b-85f9a6) ([raw file](https://github.com/qtox/qtox/blob/1fab98ffd4e1c92b3cfcbcded7507b85ac5f9799/CMakeLists.txt#L376)):*
<details><summary><i>Previously, anthonybilinski (Anthony Bilinski) wrote…</i></summary><blockquote>

missing `notificationgenerator.h`
</blockquote></details>

updated myself
___
*[test/model/notificationgenerator_test.cpp, line 105 at r1](https://reviewable.io/reviews/qtox/qtox/6073#-M7MJah04Yt6XMcz8WUY:-M7WP_niBnvttI4ITzrj:b4ozphb) ([raw file](https://github.com/qtox/qtox/blob/007f2e51850179da4962f2217b4694c6fc92bff8/test/model/notificationgenerator_test.cpp#L105)):*
<details><summary><i>Previously, anthonybilinski (Anthony Bilinski) wrote…</i></summary><blockquote>

`Friend` constructor allows the name to be set separately from alias, e.g. could do `Friend(0, ToxPk(), {}, "friendName")`
</blockquote></details>

Chatted off review, basically my I wanted the `Friend` to be fully defined on construction, @sphaerophoria prefers using `setName` to having a default constructed alias and unnamed groupName constructor arguments. It doesn't seem like a big deal either way, will just leave it like this.


<!-- Sent from Reviewable.io -->

2020-05-29 08:22 UTC, anthonybilinski approved these changes
> Reviewed 11 of 11 files at r8.
> *[Reviewable](https://reviewable.io/reviews/qtox/qtox/6073)* status: 0 of 1 LGTMs obtained

*[a discussion](https://reviewable.io/reviews/qtox/qtox/6073#-M7WXkNO3SyZCUL6KbLP:-M8U3-BM2mNr0VuWYVS2:bg3vk8l) (no related file):*
<details><summary><i>Previously, anthonybilinski (Anthony Bilinski) wrote…</i></summary><blockquote>

When testing this, I get error logs from snore on every notification:
```
[07:30:02.940 UTC] :0 : Warning: Snore::Notification("qTest2", "1", id = 10)was already closed
[07:30:03.636 UTC] :0 : Warning: Snore::Notification("2 message(s) from qTest2", "2", id = 11)was already closed
[07:30:04.136 UTC] :0 : Warning: Snore::Notification("3 message(s) from qTest2", "3", id = 12)was already closed
[07:30:04.537 UTC] :0 : Warning: Snore::Notification("4 message(s) from qTest2", "4", id = 13)was already closed
```
</blockquote></details>

We only call `requestCloseNotification` from one place on a friend message, so this looks like a snore bug. I think just filtering out the log message is reasonable, since we're still getting the desired behaviour.

Adding
```
    QRegExp snoreFilte{QStringLiteral("Snore::Notification.*was already closed")};
    if (type == QtWarningMsg
        && msg.contains(snoreFilte))
    {
        return;
    }
```
to our `logMessageHandler` in main handles that.

I talked to @sphaerophoria about it and he's happy with the idea. I'll push this change to his branch.

---
*[a discussion](https://reviewable.io/reviews/qtox/qtox/6073#-M8UFoDv99nPkzUIzD3d:-M8UFoDw7_ydUQ_mSm8A:b-ftuf2t) (no related file):*
I saw an issue when receiving offline messages (or probably any messages in very rapid succession). The older messages don't close properly, e.g. when receiving 4 messages from a friend, 1,2,3,4, I see:
![image.png](https://files.reviewableusercontent.io/images/reviewable/10469203/oKOnsKguRdmvySOf52lVvDaR/image.png)

It looks like from `Snore::SnoreCore::requestCloseNotification` failing, probably because of some async race between the message being created from snore, but not yet created in the DE, so when it goes to close it nothing closes, but then it gets added after.

This isn't worse than our previous behaviour, but could maybe be worked around with a timer that only tries to close a notification after some time of it being previous opened, and until that point we just update our internal idea of what the next message will be without sending it to snore. We could have a pretty long delay (e.g. maybe even 1s) without having a major user impact, since this would only effect updating existing notifications, not the first notification that user might actually react to quickly.

I'd be ok splitting this to a new issue, since the current behaviour is already a big improvement.

---
*[a discussion](https://reviewable.io/reviews/qtox/qtox/6073#-M8URr7l6zJdYnxWJV0I:-M8URr7mDZzuex5QVi3l:bv63t5r) (no related file):*
@sphaerophoria has sent a bug report to snorenotify's mailing list regarding the inability to update notifications:

```
I believe I've found a bug in snorenotify 0.7.0 that's inhibiting me from re-using existing notifications effectively.

The symptom I'm seeing is that I cannot update a notification more than 2 times before it stops issuing the updates I requested.

I have a piece of code that does the following

    bool needsNewNotification = !lastNotification.isValid() || lastNotification.closeReason() != Snore::Notification::CloseReasons::None;

    if (needsNewNotification) {
        qDebug() << "creating new notification";
        lastNotification = Snore::Notification{snoreApp, Snore::Alert(), title, message, snoreIcon, 0};
    }
    else {
        qDebug() << "reusing last notification";
        lastNotification = Snore::Notification{lastNotification, title, message, snoreIcon, 0};
    }

    notifyCore.broadcastNotification(lastNotification);

The rest isn't super important, the point here is that we try to reuse a notification when it's valid and hasn't been closed.

I looked into the snorenotify source and it looks like snorenotify is incrementing the active count on notification updates. In snoreCore::broadcastNotification m_activeNotifications is checked to see if it contains under 3 messages. If it does it adds the new notification to the queue until the previous ones have been closed.

void SnoreCore::broadcastNotification(Notification notification)
{
    Q_D(SnoreCore);
    if (d->m_activeNotifications.size() > d->maxNumberOfActiveNotifications()) {
        qCDebug(SNORE) << "queue size:" << d->m_notificationQue.size() << "active size:" << d->m_activeNotifications.size();
        d->m_notificationQue.append(notification);
        return;
    }
    Q_ASSERT_X(!notification.data()->isBroadcasted(), Q_FUNC_INFO, "Notification was already broadcasted.");
    qCDebug(SNORE) << "Broadcasting" << notification << "timeout:" << notification.timeout();
    if (d->m_notificationBackend != nullptr) {
        if (notification.isUpdate() && !d->m_notificationBackend->canUpdateNotification()) {
            requestCloseNotification(notification.old(), Notification::Replaced);
        }
    }
    notification.data()->setBroadcasted();
    notification.addActiveIn(this);
    if (!d->m_notificationBackend) {
        d->startNotificationTimeoutTimer(notification);
    }
    emit d->notify(notification);
}


The problem is that if the backend supports updating notifications nothing ties back the notification to the old one. In Notification::addActiveIn we add a notification with a new Id unconditionally. When creating a notification based on a previous one we always get a new ID

Snore::NotificationData::NotificationData(const Notification &old, const QString &title, const QString &text, const Icon &icon, int timeout, Notification::Prioritys priority):
    m_id(m_idCount++),
    m_timeout(priority == Notification::Emergency ? 0 : timeout),
    m_application(old.application()),
    m_alert(old.alert()),
    m_title(title),
    m_text(text),
    m_icon(icon),
    m_priority(priority),
    m_hints(m_application.constHints()),
    m_toReplace(old)
{
    notificationCount++;
    qCDebug(SNORE) << "Creating Notification: ActiveNotifications" << notificationCount << "id" << m_id;
    qCDebug(SNORE) << title << text;
}

Which is added to the map unconditionally at

void Notification::addActiveIn(const QObject *o)
{
    bool contains = d->m_activeIn.contains(o);
    Q_ASSERT_X(!contains, Q_FUNC_INFO, "already active");
    if (contains) {
        qCWarning(SNORE) << o << "already active in" << id();
        return;
    }
    d->m_activeIn.insert(o);
    SnoreCorePrivate::instance()->m_activeNotifications[id()] = *this;
    qCDebug(SNORE) << SnoreCorePrivate::instance()->m_activeNotifications.size();
}


I tried to work around it by manually issuing a close request myself and only handling close requests on my end if closeReason() != Replaced, however the closeReason() method is non-const, so I cannot check the closeReason() in the notificationClosed callback.
```

hopefully if this gets addressed in the future, we won't need these workarounds.

---


<!-- Sent from Reviewable.io -->

2020-05-29 08:48 UTC, anthonybilinski commented
@sudden6 mind taking a second look, since I'm adding hacks at this point.
main things would be
1) filtering out log warnings
2) postponing fixing the deletion race to a later lower priority issue

2020-07-02 07:50 UTC, sudden6 requested changes
> Reviewed 1 of 16 files at r1, 3 of 15 files at r5, 12 of 12 files at r7, 11 of 11 files at r8, 1 of 1 files at r9.
> *[Reviewable](https://reviewable.io/reviews/qtox/qtox/6073)* status: :shipit: complete! 1 of 1 LGTMs obtained

*[a discussion](https://reviewable.io/reviews/qtox/qtox/6073#-M8URr7l6zJdYnxWJV0I:-M8_XuGp7-vQkgbw7Xl4:b-cuxrgh) (no related file):*
<details><summary><i>Previously, anthonybilinski (Anthony Bilinski) wrote…</i></summary><blockquote>

@sphaerophoria has sent a bug report to snorenotify's mailing list regarding the inability to update notifications:

```
I believe I've found a bug in snorenotify 0.7.0 that's inhibiting me from re-using existing notifications effectively.

The symptom I'm seeing is that I cannot update a notification more than 2 times before it stops issuing the updates I requested.

I have a piece of code that does the following

    bool needsNewNotification = !lastNotification.isValid() || lastNotification.closeReason() != Snore::Notification::CloseReasons::None;

    if (needsNewNotification) {
        qDebug() << "creating new notification";
        lastNotification = Snore::Notification{snoreApp, Snore::Alert(), title, message, snoreIcon, 0};
    }
    else {
        qDebug() << "reusing last notification";
        lastNotification = Snore::Notification{lastNotification, title, message, snoreIcon, 0};
    }

    notifyCore.broadcastNotification(lastNotification);

The rest isn't super important, the point here is that we try to reuse a notification when it's valid and hasn't been closed.

I looked into the snorenotify source and it looks like snorenotify is incrementing the active count on notification updates. In snoreCore::broadcastNotification m_activeNotifications is checked to see if it contains under 3 messages. If it does it adds the new notification to the queue until the previous ones have been closed.

void SnoreCore::broadcastNotification(Notification notification)
{
    Q_D(SnoreCore);
    if (d->m_activeNotifications.size() > d->maxNumberOfActiveNotifications()) {
        qCDebug(SNORE) << "queue size:" << d->m_notificationQue.size() << "active size:" << d->m_activeNotifications.size();
        d->m_notificationQue.append(notification);
        return;
    }
    Q_ASSERT_X(!notification.data()->isBroadcasted(), Q_FUNC_INFO, "Notification was already broadcasted.");
    qCDebug(SNORE) << "Broadcasting" << notification << "timeout:" << notification.timeout();
    if (d->m_notificationBackend != nullptr) {
        if (notification.isUpdate() && !d->m_notificationBackend->canUpdateNotification()) {
            requestCloseNotification(notification.old(), Notification::Replaced);
        }
    }
    notification.data()->setBroadcasted();
    notification.addActiveIn(this);
    if (!d->m_notificationBackend) {
        d->startNotificationTimeoutTimer(notification);
    }
    emit d->notify(notification);
}


The problem is that if the backend supports updating notifications nothing ties back the notification to the old one. In Notification::addActiveIn we add a notification with a new Id unconditionally. When creating a notification based on a previous one we always get a new ID

Snore::NotificationData::NotificationData(const Notification &old, const QString &title, const QString &text, const Icon &icon, int timeout, Notification::Prioritys priority):
    m_id(m_idCount++),
    m_timeout(priority == Notification::Emergency ? 0 : timeout),
    m_application(old.application()),
    m_alert(old.alert()),
    m_title(title),
    m_text(text),
    m_icon(icon),
    m_priority(priority),
    m_hints(m_application.constHints()),
    m_toReplace(old)
{
    notificationCount++;
    qCDebug(SNORE) << "Creating Notification: ActiveNotifications" << notificationCount << "id" << m_id;
    qCDebug(SNORE) << title << text;
}

Which is added to the map unconditionally at

void Notification::addActiveIn(const QObject *o)
{
    bool contains = d->m_activeIn.contains(o);
    Q_ASSERT_X(!contains, Q_FUNC_INFO, "already active");
    if (contains) {
        qCWarning(SNORE) << o << "already active in" << id();
        return;
    }
    d->m_activeIn.insert(o);
    SnoreCorePrivate::instance()->m_activeNotifications[id()] = *this;
    qCDebug(SNORE) << SnoreCorePrivate::instance()->m_activeNotifications.size();
}


I tried to work around it by manually issuing a close request myself and only handling close requests on my end if closeReason() != Replaced, however the closeReason() method is non-const, so I cannot check the closeReason() in the notificationClosed callback.
```

hopefully if this gets addressed in the future, we won't need these workarounds.
</blockquote></details>

Minor comment, rest <img class="emoji" title=":lgtm_strong:" alt=":lgtm_strong:" align="absmiddle" src="https://reviewable.io/lgtm_strong.png" height="20" width="61"/> 

As for snorenotify getting this bug fixed, I don't think that's going to happen anytime soon or ever. The

---
___
*[src/main.cpp, line 101 at r9](https://reviewable.io/reviews/qtox/qtox/6073#-M8_Xfnn5gIcXFu83Czq:-M8_Xfno2jQn921X7_WE:bwe1meu) ([raw file](https://github.com/qtox/qtox/blob/f45e7a8755fbe604258f6213bcf9ca66312f3638/src/main.cpp#L101)):*
> ```cpp
>         return;
> 
>     QRegExp snoreFilte{QStringLiteral("Snore::Notification.*was already closed")};
> ```

Is this meant to say `snoreFilter`?


<!-- Sent from Reviewable.io -->

2020-07-02 08:34 UTC, anthonybilinski reviewed
> Reviewed 1 of 1 files at r9.
> *[Reviewable](https://reviewable.io/reviews/qtox/qtox/6073)* status: :shipit: complete! 1 of 1 LGTMs obtained

*[a discussion](https://reviewable.io/reviews/qtox/qtox/6073#-M8URr7l6zJdYnxWJV0I:-MBDeAwrC2eUHJYzIYES:b-k1n9j3) (no related file):*
<details><summary><i>Previously, sudden6 wrote…</i></summary><blockquote>

Minor comment, rest :lgtm_strong: 

As for snorenotify getting this bug fixed, I don't think that's going to happen anytime soon or ever. The
</blockquote></details>

yeah agreed. Seems likely these workaround will stay in as long as we use snore, oh well.

---
___
*[src/main.cpp, line 101 at r9](https://reviewable.io/reviews/qtox/qtox/6073#-M8_Xfnn5gIcXFu83Czq:-MBDdp_e4NczUp22CtiU:b4h0aoo) ([raw file](https://github.com/qtox/qtox/blob/f45e7a8755fbe604258f6213bcf9ca66312f3638/src/main.cpp#L101)):*
<details><summary><i>Previously, sudden6 wrote…</i></summary><blockquote>

Is this meant to say `snoreFilter`?
</blockquote></details>

oops, fixed


<!-- Sent from Reviewable.io -->

2020-07-02 08:34 UTC, sudden6 approved these changes
<img class="emoji" title=":lgtm_strong:" alt=":lgtm_strong:" align="absmiddle" src="https://reviewable.io/lgtm_strong.png" height="20" width="61"/> 

> Reviewed 1 of 1 files at r10.
> *[Reviewable](https://reviewable.io/reviews/qtox/qtox/6073#-:-MBDeNvu9SSZ38FW01Le:b-uwkowd)* status: :shipit: complete! 1 of 1 LGTMs obtained



<!-- Sent from Reviewable.io -->

2020-07-02 09:51 UTC, merged