fix(preview): Fix exif orientations
qTox/qTox pull request #6143
Opened 2020-05-16 20:30 UTC by sphaerophoria

Previous exif transformations were not valid. The exif spec defines the
orientations as where the 0th row and the 0th column should end. The
previous mappings used in qTox did not respect these mappings and needed
to be updated.

Please review thoroughly. I'm pretty sure I got it right but it's easy to mess up (as seen by the previous state).

Screenshot of previous state vs Gnome's "eog" before the fix

![image](https://user-images.githubusercontent.com/1069811/82129684-57e9d280-9779-11ea-9f87-bf2a171488cc.png)

and after

![image](https://user-images.githubusercontent.com/1069811/82129695-60daa400-9779-11ea-85f5-49a84bf97bfa.png)

I couldn't think of any good way to programmatically test this, if you have suggestions I'd love to hear them.

- [x] Commits follow our [git commit guidelines](https://github.com/qTox/qTox/blob/master/CONTRIBUTING.md#git-commit-guidelines)

2020-05-16 20:36 UTC, sphaerophoria commented
As always as soon as I file the PR I have ideas. We could test this programmatically by having a special colored pixel in the top left of a pixmap and just checking where that value ends up after transformations. I'll see if I can split out some tests for this

2020-05-16 21:14 UTC, sphaerophoria commented
Updated PR with some tests... turned out I still had some wrong :facepalm:

2020-05-16 23:27 UTC, anthonybilinski requested changes
> Reviewed 7 of 7 files at r1.
> *[Reviewable](https://reviewable.io/reviews/qtox/qtox/6143)* status: 0 of 1 LGTMs obtained

___
*[src/chatlog/content/filetransferwidget.cpp, line 637 at r1](https://reviewable.io/reviews/qtox/qtox/6143#-M7Ug22z6cbrO_VVplLj:-M7Ug23-AsW_eeEPeAvO:b-m90mup) ([raw file](https://github.com/qtox/qtox/blob/8a9c89f23997e05a9674b5e1ac658e463246967e/src/chatlog/content/filetransferwidget.cpp#L637)):*
> ```cpp
>     case ExifOrientation::LeftTop:
>         exifTransform.rotate(90);
>         image = image.mirrored(0, 1);
> ```

not important, but looks like these last 4 were all exact opposite of what is right. I was probably thinking of what transformation the image was in instead of what transformation the image needs for these :facepalm: 
___
*[src/model/exiftransform.h, line 44 at r1](https://reviewable.io/reviews/qtox/qtox/6143#-M7UhbUk2axfCIyVmoej:-M7UhbUk2axfCIyVmoek:bepax0f) ([raw file](https://github.com/qtox/qtox/blob/b3f83a22520759653ee36498b3fd751ec3772e6c/src/model/exiftransform.h#L44)):*
> ```objc
> 
>     ExifOrientation getExifOrientation(QByteArray imageData);
>     QImage applyExifTransformation(QImage image, ExifOrientation orientation);
> ```

I think deduplicating the names of things inside namespaces or classes like is done with enum classes is nicer, e.g. just `Orientation` `get` and `apply` doesn't seem to lose info.
___
*[test/model/exiftransform_test.cpp, line 54 at r1](https://reviewable.io/reviews/qtox/qtox/6143#-M7UmhdnE-U8BiFqtBcw:-M7UmhdnE-U8BiFqtBcx:b-cy79nr) ([raw file](https://github.com/qtox/qtox/blob/b3f83a22520759653ee36498b3fd751ec3772e6c/test/model/exiftransform_test.cpp#L54)):*
> ```cpp
>     // First column has a blue dot in the middle
>     painter.setPen(Qt::blue);
>     painter.drawPoint(QPoint(0, 1));
> ```

It would be clearer if the 4 positions were named and the names were used with e.g. `enum class Side` with `top, right, bottom, left` and then a helper `QColor getColor(QImage&, Side)`

then each a test case could be easier to check, e.g.
```
void TestExifTransform::testTopLeft()
{
    auto image = ExifTransform::applyExifTransformation(inputImage, ExifTransform::ExifOrientation::TopLeft);
    QVERIFY(getColor(image, Side::top) == Qt::green);
    QVERIFY(getColor(image, Side::left) == Qt::blue);
}
```
___
*[test/model/exiftransform_test.cpp, line 113 at r1](https://reviewable.io/reviews/qtox/qtox/6143#-M7UlJw12TVgmvbNepas:-M7UlJw12TVgmvbNepat:b-987bbs) ([raw file](https://github.com/qtox/qtox/blob/b3f83a22520759653ee36498b3fd751ec3772e6c/test/model/exiftransform_test.cpp#L113)):*
> ```cpp
> }
> 
> QTEST_GUILESS_MAIN(TestExifTransform)
> ```

I think this should just be a `QTEST_APPLESS_MAIN` https://doc.qt.io/qt-5/qtest.html#QTEST_APPLESS_MAIN since it doesn't rely on QApplication or GUI at all.


<!-- Sent from Reviewable.io -->

2020-05-16 23:53 UTC, sphaerophoria reviewed
> *[Reviewable](https://reviewable.io/reviews/qtox/qtox/6143)* status: 0 of 1 LGTMs obtained

___
*[src/model/exiftransform.h, line 44 at r1](https://reviewable.io/reviews/qtox/qtox/6143#-M7UhbUk2axfCIyVmoej:-M7Uu3a-3CagrSvwMRrj:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/b3f83a22520759653ee36498b3fd751ec3772e6c/src/model/exiftransform.h#L44)):*
<details><summary><i>Previously, anthonybilinski (Anthony Bilinski) wrote…</i></summary><blockquote>

I think deduplicating the names of things inside namespaces or classes like is done with enum classes is nicer, e.g. just `Orientation` `get` and `apply` doesn't seem to lose info.
</blockquote></details>

Done.
___
*[test/model/exiftransform_test.cpp, line 54 at r1](https://reviewable.io/reviews/qtox/qtox/6143#-M7UmhdnE-U8BiFqtBcw:-M7Uu4Un3vaG3hrDC0aX:br8kq70) ([raw file](https://github.com/qtox/qtox/blob/b3f83a22520759653ee36498b3fd751ec3772e6c/test/model/exiftransform_test.cpp#L54)):*
<details><summary><i>Previously, anthonybilinski (Anthony Bilinski) wrote…</i></summary><blockquote>

It would be clearer if the 4 positions were named and the names were used with e.g. `enum class Side` with `top, right, bottom, left` and then a helper `QColor getColor(QImage&, Side)`

then each a test case could be easier to check, e.g.
```
void TestExifTransform::testTopLeft()
{
    auto image = ExifTransform::applyExifTransformation(inputImage, ExifTransform::ExifOrientation::TopLeft);
    QVERIFY(getColor(image, Side::top) == Qt::green);
    QVERIFY(getColor(image, Side::left) == Qt::blue);
}
```
</blockquote></details>

Done. Wow that is _way_ clearer.
___
*[test/model/exiftransform_test.cpp, line 113 at r1](https://reviewable.io/reviews/qtox/qtox/6143#-M7UlJw12TVgmvbNepas:-M7Uu70TAd3W1CJUctVa:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/b3f83a22520759653ee36498b3fd751ec3772e6c/test/model/exiftransform_test.cpp#L113)):*
<details><summary><i>Previously, anthonybilinski (Anthony Bilinski) wrote…</i></summary><blockquote>

I think this should just be a `QTEST_APPLESS_MAIN` https://doc.qt.io/qt-5/qtest.html#QTEST_APPLESS_MAIN since it doesn't rely on QApplication or GUI at all.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-05-17 00:44 UTC, anthonybilinski approved these changes
<img class="emoji" title=":lgtm_strong:" alt=":lgtm_strong:" align="absmiddle" src="https://reviewable.io/lgtm_strong.png" height="20" width="61"/> 

> Reviewed 1 of 1 files at r2, 4 of 4 files at r3.
> *[Reviewable](https://reviewable.io/reviews/qtox/qtox/6143#-:-M7V4OWq2-j9GnJV_Vh8:b-uwkowd)* status: :shipit: complete! 1 of 1 LGTMs obtained



<!-- Sent from Reviewable.io -->

2020-05-17 00:50 UTC, merged