[WIP] refactor(chatlog): remove getInstance from ChatlogItem
qTox/qTox pull request #6216
Opened 2020-08-20 20:38 UTC by sudden6

- [x] Commits follow our [git commit guidelines](https://github.com/qTox/qTox/blob/master/CONTRIBUTING.md#git-commit-guidelines)

Goal is to finally remove all users of `Core::getInstance()`.

The problem is currently where to do the lookup of `ToxPk` -> `displayedName´.

2020-08-21 20:38 UTC, sudden6 commented
This is one of the milestones defined in The Plan™ years ago. With this two commits it's now possible to use the Core class without the rest of qTox.

2020-08-21 20:40 UTC, sudden6 commented
@Diadlo :tada: :tada: :tada:

2020-08-23 16:34 UTC, bodwok commented
It fine works for me. 
But I noticed that the empty nickname is not replaced by the public key? (in SessionChatLog)

2020-08-24 18:14 UTC, anthonybilinski approved these changes
> Reviewed 7 of 7 files at r1.
> *[Reviewable](https://reviewable.io/reviews/qtox/qtox/6216)* status: 0 of 1 LGTMs obtained

___
*[src/model/sessionchatlog.cpp, line 124 at r1](https://reviewable.io/reviews/qtox/qtox/6216#-MFWf0_e28YmCB0Khcfe:-MFWf0_fAHszyNEQRBNv:bdv8h03) ([raw file](https://github.com/qtox/qtox/blob/c77fac3787f15a8f3c57785780ce104839cd9451/src/model/sessionchatlog.cpp#L124)):*
> ```cpp
>     }
> 
>     return pk.toString();
> ```

@bodwok the empty nickname is replaced by a public key here. `pk.toString()` gives the hek key, and is only called if the pk isn't found in the `FriendList` or `GroupList` which would contain the nickname if there was one. Testing off this change, unsetting one of my profiles names correctly shows the pk for both itself and its friend running this change.


<!-- Sent from Reviewable.io -->

2020-08-24 18:14 UTC, anthonybilinski approved these changes
<img class="emoji" title=":lgtm_strong:" alt=":lgtm_strong:" align="absmiddle" src="https://reviewable.io/lgtm_strong.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/qtox/qtox/6216#-:-MFWfLgDC8GXA3G8bJao:b-jbsf8z)* status: :shipit: complete! 1 of 1 LGTMs obtained



<!-- Sent from Reviewable.io -->

2020-08-24 20:46 UTC, sudden6 commented
Specifically tested the case with empty username again, couldn't find the behaviou @bodwok mentioned.

2020-08-24 20:51 UTC, anthonybilinski requested changes
<img class="emoji" title=":lgtm_cancel:" alt=":lgtm_cancel:" align="absmiddle" src="https://reviewable.io/lgtm_cancel.png" height="20" width="61"/> ah wait there is an issue. When there's no name set, it works on the receiving side, but not on the sending side.
Receiving side:
![image.png](https://files.reviewableusercontent.io/images/reviewable/10469203/1RzFS2L0S-EC6ST82id5seEu/image.png)
Sending side:
![image copy 1.png](https://files.reviewableusercontent.io/images/reviewable/10469203/pxCpdDz8qWpK6DJUsbYtTi9P/image.png)

> *[Reviewable](https://reviewable.io/reviews/qtox/qtox/6216#-:-MFXE1Ky9euDeW5V9-IC:b-5e036x)* status: 0 of 1 LGTMs obtained



<!-- Sent from Reviewable.io -->

2020-08-24 21:14 UTC, sudden6 commented
Could reproduce, but it seems this also happens when the name is not empty O_o

2020-08-24 21:25 UTC, sudden6 commented
Fixed it, I accidentally changed the logic when sending messages.

2020-08-24 21:45 UTC, anthonybilinski approved these changes
Fix looks good, and I've re-tested. Behaviour is good on both sending and receiving side. <img class="emoji" title=":lgtm_strong:" alt=":lgtm_strong:" align="absmiddle" src="https://reviewable.io/lgtm_strong.png" height="20" width="61"/> 

Thanks for pointing out the problem @bodwok :)

> Reviewed 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/qtox/qtox/6216#-:-MFXQa4t31tKvumYY6br:bpk7kcp)* status: :shipit: complete! 1 of 1 LGTMs obtained



<!-- Sent from Reviewable.io -->

2020-08-25 13:39 UTC, bodwok commented
Tested, looks good

2020-08-25 18:48 UTC, merged

2020-08-25 18:48 UTC, sudden6 commented
@bodwok Thanks for testing and reporting the problem!