Update flatpak
qTox/qTox pull request #6265
Opened 2020-11-25 12:05 UTC by anthonybilinski

- [ ] Commits follow our [git commit guidelines](https://github.com/qTox/qTox/blob/master/CONTRIBUTING.md#git-commit-guidelines)

First commit should have been prior to release, and has the version that was sent to flathub. Second commit returns it to build off release branch, and merge commit changes it to build off master branch. I believe this 3 commit change with 1 before release is how we should handle flatpak going forward, which I've included in https://github.com/qTox/qTox/pull/6264

2020-11-25 20:26 UTC, sudden6 requested changes
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/qtox/qtox/6265)* status: 0 of 1 LGTMs obtained

___
*[flatpak/io.github.qtox.qTox.json, line 129 at r1](https://reviewable.io/reviews/qtox/qtox/6265#-MN04KWQ8eGJG3lqHH-9:-MN04KWR71iTaMsHExbU:ba5i1nm) ([raw file](https://github.com/qtox/qtox/blob/542023a79acfd4aefb9dbb99bfab246ed69d0c6b/flatpak/io.github.qtox.qTox.json#L129)):*
> ```JSON
>             "sources": [
>                 {
>                     "type": "git",
> ```

why do we use git here now? Travis has the source already checked out at the appropriate commit


<!-- Sent from Reviewable.io -->

2020-11-25 20:28 UTC, sudden6 commented
I think the confusion of this might come from the upstream flathub flatpak file. How about adding a comment to the `sources` section, that Travis already has the correct source commit checked out and thus we use the `dir` source?

2020-11-26 09:55 UTC, sudden6 requested changes
> *[Reviewable](https://reviewable.io/reviews/qtox/qtox/6265)* status: 0 of 1 LGTMs obtained

___
*[flatpak/io.github.qtox.qTox.json, line 129 at r1](https://reviewable.io/reviews/qtox/qtox/6265#-MN04KWQ8eGJG3lqHH-9:-MN2yWcr6z78iVIunZs0:b-nva59e) ([raw file](https://github.com/qtox/qtox/blob/542023a79acfd4aefb9dbb99bfab246ed69d0c6b/flatpak/io.github.qtox.qTox.json#L129)):*
<details><summary><i>Previously, sudden6 wrote…</i></summary><blockquote>

why do we use git here now? Travis has the source already checked out at the appropriate commit
</blockquote></details>

still has the `branch` tag, last time I checked directories don't have branches :D


<!-- Sent from Reviewable.io -->

2020-11-26 10:43 UTC, anthonybilinski reviewed
> *[Reviewable](https://reviewable.io/reviews/qtox/qtox/6265)* status: 0 of 1 LGTMs obtained

___
*[flatpak/io.github.qtox.qTox.json, line 129 at r1](https://reviewable.io/reviews/qtox/qtox/6265#-MN04KWQ8eGJG3lqHH-9:-MN38Jh39fH9VKWadXIE:bj9pu8c) ([raw file](https://github.com/qtox/qtox/blob/542023a79acfd4aefb9dbb99bfab246ed69d0c6b/flatpak/io.github.qtox.qTox.json#L129)):*
<details><summary><i>Previously, sudden6 wrote…</i></summary><blockquote>

still has the `branch` tag, last time I checked directories don't have branches :D
</blockquote></details>

Updated again, I had the wrong line of thinking re: tag and branch builds in repo, which will just be handled automatically by the nature of the repo being checked out at that tag or branch. This removes the need for the second commit as explained here: https://github.com/qTox/qTox/pull/6264#pullrequestreview-539192246


<!-- Sent from Reviewable.io -->

2020-11-26 14:38 UTC, sudden6 approved these changes
<img class="emoji" title=":lgtm_strong:" alt=":lgtm_strong:" align="absmiddle" src="https://reviewable.io/lgtm_strong.png" height="20" width="61"/>

> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/qtox/qtox/6265#-:-MN3zTvN5Nflj0tWt92y:b-jbsf8z)* status: :shipit: complete! 1 of 1 LGTMs obtained



<!-- Sent from Reviewable.io -->

2020-11-26 19:50 UTC, merged