feat(chatlog): Ugrade db schema to support system messages
qTox/qTox pull request #6290
Opened 2021-01-26 04:17 UTC by sphaerophoria

feat(chatlog): Ugrade db schema to support system messages

* Resolves #6221
* System message schema based off of ChatMessage::createChatInfoMessage
* New table layout required many updates to the queries executed by
  history
* Bonus reduction of history signals/slots by issuing some file transfer
  insertions directly when possible

NOTE: this is on top of PR #5932 so only review the last commit. This is because of the history changes in #5932. @anthonybilinski mentioned in #6221 that this should come on top of #5932.

I'm going to attempt to summarize the changes and how I tested them, more rationale about why changes were made can be found in #6221 

* DB schema upgrade
    * Tested with db schema upgrade test
    * Tested a real world case updating from v1.17.3 (db version 4) to the new DB. I opened the new DB in sqlitebrowser and verified that all tables had the data I expected
* history changes for inserting/retrieving text/file messages
    * Tested sending/receiving files. Ensured no new error logs. Tested around broken messages and faux offline messages as well. I didn't see any dropped messages
* Search query changes to handle new text_messages table
    * Tested search on chat with > 200 messages to ensure it had to search backwards in history. Search text was found successfully

I think I've done my due diligence here. If I were a better developer I would have added some tests to ensure that we have the correct foreign key constraints... but I didn't. Manual tests of the sqlite changes are shown in #6221 

- [x] Commits follow our [git commit guidelines](https://github.com/qTox/qTox/blob/master/CONTRIBUTING.md#git-commit-guidelines)

2021-01-27 04:53 UTC, sphaerophoria commented
After thinking about this a little more and talking with @anthonybilinski I think the schema implemented for system messages isn't good enough. Initially I was thinking that just dropping the string in there would be sufficient, but there are some cases where that doesn't work very well.

1. What if we want to update the system messages later, we'd have to scour the DB for the old version and update it to the new one to ensure consistency. This means we'd have to keep the old versions of the system messages around forever
2. If a user changes their language we cannot re-translate the strings with the current schema.

This gets a little hairy too with arguments in the system message. We can't even re-translate once the arguments have been applied. This means our table needs to have the arguments stored separately from the main message string itself

This actually forces us to have better practices anyways, why store system messages as strings when we don't have to?

After thinking about it a little I think we can get away with a schema of 

`CREATE TABLE system_messages (id INTEGER PRIMARY KEY,  message_type CHAR(1) NOT NULL CHECK (message_type = 'S'), system_message_type INTEGER NOT NULL, arg1 BLOB, arg2 BLOB, arg3 BLOB, arg4 BLOB)`

In this schema system_message_type will be an integer referring to some lookup table of int -> translation string. Then we just apply the arguments and hope we never have a system message with more than 4 arguments. If we do end up having more than 4 in the future we can always add more nullable fields to the table.

2021-01-27 05:48 UTC, Chiitoo commented
Probably meant 'Upgrade' here?  :]

```
feat(chatlog): Ugrade db schema to support system messages
```

2021-01-27 06:06 UTC, sphaerophoria commented
Proof of concept hook up with chatform shown in https://github.com/qTox/qTox/issues/6222#issuecomment-768054724 proving that the schema is good enough.

2021-01-31 08:53 UTC, anthonybilinski commented
Could you rebase now that #5932  is in? Also it looks like `dbschema_test` is failing.

2021-01-31 21:41 UTC, sphaerophoria commented
> Could you rebase now that #5932 is in? Also it looks like `dbschema_test` is failing.

I've rebased, but I don't see the dbschema failure locally.

```
└> ./test_dbschema
********* Start testing of TestDbSchema *********
Config: Using QtTest library 5.15.2, Qt 5.15.2 (x86_64-little_endian-lp64 shared (dynamic) release build; by GCC 10.2.0), arch unknown
PASS   : TestDbSchema::initTestCase()
PASS   : TestDbSchema::testCreation()
PASS   : TestDbSchema::testIsNewDb()
PASS   : TestDbSchema::test0to1()
PASS   : TestDbSchema::test1to2()
PASS   : TestDbSchema::test2to3()
PASS   : TestDbSchema::test3to4()
PASS   : TestDbSchema::test4to5()
PASS   : TestDbSchema::test5to6()
PASS   : TestDbSchema::test6to7()
PASS   : TestDbSchema::cleanupTestCase()
Totals: 11 passed, 0 failed, 0 skipped, 0 blacklisted, 447ms
********* Finished testing of TestDbSchema *********
```

Will check travis after it runs with the rebase.

2021-02-01 01:07 UTC, sphaerophoria commented
Failed again. I'm willing to bet it has something to do with sqlite version... I'll try to repro with an older one

2021-02-01 02:06 UTC, sphaerophoria commented
Ah nice found the issue. It looks like the foreign key references are not being updated when we use ALTER TABLE to move a table on older sqlite versions. See section 2 of https://www.sqlite.org/lang_altertable.html for further information. It looks like the solution in section 5 of https://www.sqlite.org/lang_altertable.html may help us... I'm hoping that FOREIGN KEYs are based off one of the items they listed....

2021-02-12 04:54 UTC, sphaerophoria commented
Patched up the upgrade path for the old alter table behavior. It isn't pretty, but it's the best I could come up with. If you find a better suggestion feel free to let me know.

2021-02-16 06:54 UTC, sphaerophoria commented
> Ah nice found the issue. It looks like the foreign key references are not being updated when we use ALTER TABLE to move a table on older sqlite versions. See section 2 of https://www.sqlite.org/lang_altertable.html for further information. It looks like the solution in section 5 of https://www.sqlite.org/lang_altertable.html may help us... I'm hoping that FOREIGN KEYs are based off one of the items they listed....

On second read I realize I misread last time... the reason the test was failing is because pragma foreign_key wasn't enabled in our test case but it was in our real upgrade path. All I had to do was enable it before running the upgrade code I had the first time round. I tested on ubuntu 16.04 with an old sqlite and it seems to do the job now

2021-02-28 19:56 UTC, sphaerophoria commented
Just rebased to master, no changes.

2021-04-19 18:46 UTC, sudden6 reviewed
Sorry for the very long delay, I found time to review, everything <img class="emoji" title=":lgtm_strong:" alt=":lgtm_strong:" align="absmiddle" src="https://reviewable.io/lgtm_strong.png" height="20" width="61"/> 

> *[Reviewable](https://reviewable.io/reviews/qtox/qtox/6290#-:-MYfSAQ-4a-lgujWHPHn:b6yqm7t)* status: :shipit: complete! 1 of 1 LGTMs obtained



<!-- Sent from Reviewable.io -->

2021-04-19 18:51 UTC, sudden6 commented
@sphaerophoria could you rebase on latest master?

2021-05-02 10:23 UTC, anthonybilinski requested changes
Also sorry for the long delay, looks like a really well done change. Better than I imagined in #6221.

For reference the upgrade which does a lot of data shuffling took under 2s (on slow SSD) on my main profile, which has years of history and takes about 40s to load normally (damn #5812), so it doesn't seem concerning even for near worst case real world data sets.

<img class="emoji" title=":lgtm_strong:" alt=":lgtm_strong:" align="absmiddle" src="https://reviewable.io/lgtm_strong.png" height="20" width="61"/> 

> Reviewed 3 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/qtox/qtox/6290#-:-MZgZRH_9bGp4CRTAbL5:b-2150t4)* status: :shipit: complete! 2 of 1 LGTMs obtained

___
*[src/persistence/history.cpp, line 373 at r1](https://reviewable.io/reviews/qtox/qtox/6290#-MZgWWyY48VdVLKD6A2-:-MZgWWyZ9Gwpqce0R456:b-qap27) ([raw file](https://github.com/qtox/qtox/blob/6d80e9c04e560256481b422dc768df3f0f9c6434/src/persistence/history.cpp#L373)):*
> ```cpp
>         RawDatabase::Query("ALTER TABLE faux_offline_pending_new RENAME TO faux_offline_pending");
> 
>     // broken_messages needs to be re-created to reference the new history tablek
> ```

"tablek" typo, will fix myself


<!-- Sent from Reviewable.io -->

2021-05-02 10:28 UTC, anthonybilinski approved these changes
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/qtox/qtox/6290)* status: :shipit: complete! 2 of 1 LGTMs obtained



<!-- Sent from Reviewable.io -->

2021-05-03 06:51 UTC, merged