fix(smileys): fix flag emojis
qTox/qTox pull request #6302
Opened 2021-02-15 02:16 UTC by warisb

Fix two small problems that break flag emojis

(1) Multi-byte emojis are accidentally grouped together with emoticons
(such as : smile :). This is fixed by using a more robust isAscii(...) function
(2) Smiley regexp construction is undeterministic, causing multi-bytes to
sometimes be processed first, sometimes last. This is fixed by explicitly
inserting multi-byte patterns first.

Issue: #5147

- [ ] Commits follow our [git commit guidelines](https://github.com/qTox/qTox/blob/master/CONTRIBUTING.md#git-commit-guidelines)

2021-02-15 02:24 UTC, warisb commented
Some tests I ran to ensure it's fixed and didn't break functionalities in this area.
![image](https://user-images.githubusercontent.com/29346402/107898911-cbc82f80-6ef1-11eb-91a1-9afa517abebf.png)

2021-02-16 12:35 UTC, anthonybilinski requested changes
Just a pedantic comment on byte vs character, change <img class="emoji" title=":lgtm_strong:" alt=":lgtm_strong:" align="absmiddle" src="https://reviewable.io/lgtm_strong.png" height="20" width="61"/>

> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/qtox/qtox/6302#-:-MTepP9B08ABqKIIR3B3:b51k4hg)* status: :shipit: complete! 1 of 1 LGTMs obtained

___
*[src/persistence/smileypack.cpp, line 108 at r1](https://reviewable.io/reviews/qtox/qtox/6302#-MTelrTjBdevuboJFMMn:-MTelrTk6zSFUK8MF3RC:b-xmy9n5) ([raw file](https://github.com/qtox/qtox/blob/4670ce1054549cf54145fb34a2e45b6c1af92385/src/persistence/smileypack.cpp#L108)):*
> ```cpp
> }
> 
> bool isAscii(const QString& string)
> ```

Just a thought, it's convenient that all of our text shortcuts for emoji are ascii and not some other utf8 text characters, that could not hold in the future.
___
*[src/persistence/smileypack.cpp, line 268 at r1](https://reviewable.io/reviews/qtox/qtox/6302#-MTemuIvCC70SPDGrwth:-MTemuIvCC70SPDGrwti:b74xuat) ([raw file](https://github.com/qtox/qtox/blob/4670ce1054549cf54145fb34a2e45b6c1af92385/src/persistence/smileypack.cpp#L268)):*
> ```cpp
>     QString allPattern = QStringLiteral("(");
>     QString regularPatterns;
>     QString multibyteEmojiPatterns;
> ```

The naming here is a bit off, "multibyte" emoji here is really referring to multi-character emoji, i.e. multiple UTF8 character code points together. Even single character emoji are multi-byte.

Could it be changed to `multiCharacterEmojiPatterns`? Note this byte/character thing is mentioned a couple times in commit message too.


<!-- Sent from Reviewable.io -->

2021-02-16 17:30 UTC, warisb commented
@anthonybilinski you're totally right, good point. Fixed the variables, comments, and also commit messages to say multichar instead of multibyte.

2021-02-16 21:40 UTC, warisb commented
___
*[src/persistence/smileypack.cpp, line 268 at r1](https://reviewable.io/reviews/qtox/qtox/6302#-MTemuIvCC70SPDGrwth:-MTgmEfU1O1eR2GelkWB:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/4670ce1054549cf54145fb34a2e45b6c1af92385/src/persistence/smileypack.cpp#L268)):*
<details><summary><i>Previously, anthonybilinski (Anthony Bilinski) wrote…</i></summary><blockquote>

The naming here is a bit off, "multibyte" emoji here is really referring to multi-character emoji, i.e. multiple UTF8 character code points together. Even single character emoji are multi-byte.

Could it be changed to `multiCharacterEmojiPatterns`? Note this byte/character thing is mentioned a couple times in commit message too.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-02-17 04:38 UTC, anthonybilinski approved these changes
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/qtox/qtox/6302)* status: :shipit: complete! 1 of 1 LGTMs obtained



<!-- Sent from Reviewable.io -->

2021-02-17 04:38 UTC, merged