feat(chatlog): Add SystemMessages to SessionChatLog
qTox/qTox pull request #6310
Opened 2021-02-28 20:05 UTC by sphaerophoria

* Rendering of system messages consolidated into single place
* API added to ichatlog to insert a system message at current location
* System messages are now used as type + args which will fit nicely with
  the work in #6221

This is the work shown in https://github.com/qTox/qTox/issues/6222#issuecomment-768054724 but without the changes to history. I've split the work so that this can be reviewed without waiting for #6290 to complete. Integration with #6290 will come in a separate PR

- [x] Commits follow our [git commit guidelines](https://github.com/qTox/qTox/blob/master/CONTRIBUTING.md#git-commit-guidelines)

2021-10-01 23:51 UTC, anthonybilinski requested changes
> Reviewed 13 of 13 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/qtox/qtox/6310)* status: 0 of 1 LGTMs obtained

___
*[src/model/chatlogitem.cpp, line 124 at r1](https://reviewable.io/reviews/qtox/qtox/6310#-MkyCK126DF-pgi-0s9J:-MkyCK126DF-pgi-0s9K:b-13v1) ([raw file](https://github.com/qtox/qtox/blob/22063172af81ab757bcee881dc23e26e546d9266/src/model/chatlogitem.cpp#L124)):*
> ```cpp
>     }
>     case ChatLogItem::ContentType::systemMessage: {
>         return QDateTime::currentDateTime();
> ```

Why use currentDateTime here? I think either session messages should store a datetime of just whenever they were initially added, or make make getTimestamp return an optional? It seems like it would be confusing if you export some 1 year old chat and all the system messages have today's date
___
*[src/widget/form/genericchatform.cpp, line 620 at r1](https://reviewable.io/reviews/qtox/qtox/6310#-MkyEvQvE7ZVl8gTf-u1:-MkyEvQvE7ZVl8gTf-u2:bgsajq0) ([raw file](https://github.com/qtox/qtox/blob/22063172af81ab757bcee881dc23e26e546d9266/src/widget/form/genericchatform.cpp#L620)):*
> ```cpp
> }
> 
> void GenericChatForm::addSystemInfoMessage(const QDateTime& datetime, SystemMessageType messageType,
> ```

datetime argument is unused (though maybe should be used rather than removed as mentioned above?)


<!-- Sent from Reviewable.io -->

2021-10-02 00:53 UTC, anthonybilinski requested changes
> *[Reviewable](https://reviewable.io/reviews/qtox/qtox/6310)* status: 0 of 1 LGTMs obtained

___
*[src/model/chatlogitem.cpp, line 124 at r1](https://reviewable.io/reviews/qtox/qtox/6310#-MkyCK126DF-pgi-0s9J:-MkyU7v56AKEVjGMVyoe:b70ouza) ([raw file](https://github.com/qtox/qtox/blob/22063172af81ab757bcee881dc23e26e546d9266/src/model/chatlogitem.cpp#L124)):*
<details><summary><i>Previously, anthonybilinski (Anthony Bilinski) wrote…</i></summary><blockquote>

Why use currentDateTime here? I think either session messages should store a datetime of just whenever they were initially added, or make make getTimestamp return an optional? It seems like it would be confusing if you export some 1 year old chat and all the system messages have today's date
</blockquote></details>

Reviewing #6311, it looks like the timestamp is correctly saved and restored from history, but then not carried into the chatlogitem from `ChatHistory::loadHistoryIntoSessionChatLog`. Seems like might as well include it there for a more accurate chatlog?


<!-- Sent from Reviewable.io -->

2021-10-02 04:52 UTC, sphaerophoria reviewed
> *[Reviewable](https://reviewable.io/reviews/qtox/qtox/6310)* status: 0 of 1 LGTMs obtained

___
*[src/model/chatlogitem.cpp, line 124 at r1](https://reviewable.io/reviews/qtox/qtox/6310#-MkyCK126DF-pgi-0s9J:-MkzKXlZ1AvFgr6-aJGs:buad0l5) ([raw file](https://github.com/qtox/qtox/blob/22063172af81ab757bcee881dc23e26e546d9266/src/model/chatlogitem.cpp#L124)):*
<details><summary><i>Previously, anthonybilinski (Anthony Bilinski) wrote…</i></summary><blockquote>

Reviewing #6311, it looks like the timestamp is correctly saved and restored from history, but then not carried into the chatlogitem from `ChatHistory::loadHistoryIntoSessionChatLog`. Seems like might as well include it there for a more accurate chatlog?
</blockquote></details>

I think it's only because there was no reason to. System messages don't show with a timestamp so I didn't see any reason to go out of our way to carry them around. We can add them if you want, I just didn't see any reason to


<!-- Sent from Reviewable.io -->

2021-10-05 19:31 UTC, anthonybilinski requested changes
> *[Reviewable](https://reviewable.io/reviews/qtox/qtox/6310)* status: 0 of 1 LGTMs obtained

___
*[src/widget/form/genericchatform.h, line 82 at r1](https://reviewable.io/reviews/qtox/qtox/6310#-MlGvjShAxaYXwKk-UAX:-MlGvjSi87fOprlNaYYc:bep0a6m) ([raw file](https://github.com/qtox/qtox/blob/22063172af81ab757bcee881dc23e26e546d9266/src/widget/form/genericchatform.h#L82)):*
> ```objc
>                               SystemMessage::Args messageArgs);
>     static QString resolveToxPk(const ToxPk& pk);
>     QDateTime getLatestTime() const;
> ```

This causes I think an undesirable interaction with getLatestTime now counting all system messages. Activity based sorting relies on the latest chat message in the chatlog, which used to exclude system messages. So now the friend just coming online is enough to bump them into the "today" group, which doesn't seem desirable.

Including some of the system messages probably makes sense, like calls, but not things like status changes or online/offline. Maybe a new property should be added to them?


<!-- Sent from Reviewable.io -->

2021-10-05 19:56 UTC, anthonybilinski reviewed
> *[Reviewable](https://reviewable.io/reviews/qtox/qtox/6310)* status: 0 of 1 LGTMs obtained

___
*[src/model/chatlogitem.cpp, line 124 at r1](https://reviewable.io/reviews/qtox/qtox/6310#-MkyCK126DF-pgi-0s9J:-MlH0W348f3xVhMQIllC:blsbrg3) ([raw file](https://github.com/qtox/qtox/blob/22063172af81ab757bcee881dc23e26e546d9266/src/model/chatlogitem.cpp#L124)):*
<details><summary><i>Previously, sphaerophoria wrote…</i></summary><blockquote>

I think it's only because there was no reason to. System messages don't show with a timestamp so I didn't see any reason to go out of our way to carry them around. We can add them if you want, I just didn't see any reason to
</blockquote></details>

Ah fair, thought this was still used in export but all system messages are skipped there. If that were to change, then including time could make sense even though it's not displayed, but for now I think keeping it as default constructed is fine.


<!-- Sent from Reviewable.io -->

2021-10-16 21:04 UTC, sphaerophoria reviewed
> *[Reviewable](https://reviewable.io/reviews/qtox/qtox/6310)* status: 0 of 1 LGTMs obtained

___
*[src/model/chatlogitem.cpp, line 124 at r1](https://reviewable.io/reviews/qtox/qtox/6310#-MkyCK126DF-pgi-0s9J:-Mm9utQv5uMj8ulT2J0a:bxs1s3r) ([raw file](https://github.com/qtox/qtox/blob/22063172af81ab757bcee881dc23e26e546d9266/src/model/chatlogitem.cpp#L124)):*
<details><summary><i>Previously, anthonybilinski (Anthony Bilinski) wrote…</i></summary><blockquote>

Ah fair, thought this was still used in export but all system messages are skipped there. If that were to change, then including time could make sense even though it's not displayed, but for now I think keeping it as default constructed is fine.
</blockquote></details>

See other comment, opted to add timestamp to system messages
___
*[src/widget/form/genericchatform.h, line 82 at r1](https://reviewable.io/reviews/qtox/qtox/6310#-MlGvjShAxaYXwKk-UAX:-Mm9uSLlDp_ZabxibDty:bee2hfb) ([raw file](https://github.com/qtox/qtox/blob/22063172af81ab757bcee881dc23e26e546d9266/src/widget/form/genericchatform.h#L82)):*
<details><summary><i>Previously, anthonybilinski (Anthony Bilinski) wrote…</i></summary><blockquote>

This causes I think an undesirable interaction with getLatestTime now counting all system messages. Activity based sorting relies on the latest chat message in the chatlog, which used to exclude system messages. So now the friend just coming online is enough to bump them into the "today" group, which doesn't seem desirable.

Including some of the system messages probably makes sense, like calls, but not things like status changes or online/offline. Maybe a new property should be added to them?
</blockquote></details>

Looks like this is only a problem when loading from history, so this only hurts us in combination with the system messages being loaded from history.

_that_ means that we have to store the correct timestamp in history, which means we should use the correct timestamp.

I've altered the behavior in GenericChatForm to ignore messages for certain system message types. No need to add a property I think, we can just filter based off what we think is relevant.
___
*[src/widget/form/genericchatform.cpp, line 620 at r1](https://reviewable.io/reviews/qtox/qtox/6310#-MkyEvQvE7ZVl8gTf-u1:-Mm9uR5GBgL-rL4Hz69C:bq6g5w6) ([raw file](https://github.com/qtox/qtox/blob/22063172af81ab757bcee881dc23e26e546d9266/src/widget/form/genericchatform.cpp#L620)):*
<details><summary><i>Previously, anthonybilinski (Anthony Bilinski) wrote…</i></summary><blockquote>

datetime argument is unused (though maybe should be used rather than removed as mentioned above?)
</blockquote></details>

Opted to use it


<!-- Sent from Reviewable.io -->

2021-10-24 12:13 UTC, anthonybilinski approved these changes
> Reviewed 2 of 3 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/qtox/qtox/6310)* status: 0 of 1 LGTMs obtained



<!-- Sent from Reviewable.io -->

2021-10-24 12:34 UTC, anthonybilinski approved these changes
<img class="emoji" title=":lgtm_strong:" alt=":lgtm_strong:" align="absmiddle" src="https://reviewable.io/lgtm_strong.png" height="20" width="61"/> 

> *[Reviewable](https://reviewable.io/reviews/qtox/qtox/6310#-:-MmmHwc910mxLNtjcQwW:b-uwkowd)* status: :shipit: complete! 1 of 1 LGTMs obtained



<!-- Sent from Reviewable.io -->

2021-10-24 12:35 UTC, merged