refactor(ui): separation of responsibility for sorting the contact list
qTox/qTox pull request #6347
Opened 2021-06-13 17:43 UTC by bodwok

Reducing FriendListWidget responsibility and fixing some bugs:

- Added FriendListManager class that owns contacts(friends, groups), sorts them by request and provides a sorted list.
- Added abstract class IFriendListItem providing necessary data for FriendListManager. 
- The sort logic is encapsulated in cmpByName and cmpByActivity members. Can be trivial changed or added other logic rules if necessary.

Fix: [6291](https://github.com/qTox/qTox/issues/6291) and place groupchats at top of friend list when switching mode
Looks like this PR might help with: [5595](https://github.com/qTox/qTox/issues/5595), [4891](https://github.com/qTox/qTox/issues/4891)

- [ ] Commits follow our [git commit guidelines](https://github.com/qTox/qTox/blob/master/CONTRIBUTING.md#git-commit-guidelines)

2021-06-16 22:15 UTC, sudden6 requested changes
> Reviewed 14 of 14 files at r1.
> *[Reviewable](https://reviewable.io/reviews/qtox/qtox/6347)* status: 0 of 1 LGTMs obtained

___
*[src/model/friendlist/friendlistmanager.h, line 69 at r1](https://reviewable.io/reviews/qtox/qtox/6347#-McLoarYDybB3-6k1MFP:-McLoarYDybB3-6k1MFQ:b2nspos) ([raw file](https://github.com/qtox/qtox/blob/89fa7db90a74100c1e3ff584b42557c0896101fd/src/model/friendlist/friendlistmanager.h#L69)):*
> ```objc
>     bool byName = true;
>     bool hideCircles = false;
>     static bool groupsOnTop;
> ```

What's the reasoning behind making this static? I'd prefer not to introduce static variables if possible.
___
*[src/model/friendlist/friendlistmanager.cpp, line 23 at r1](https://reviewable.io/reviews/qtox/qtox/6347#-McLp4od6UiuH5Jds2ap:-McLp4od6UiuH5Jds2aq:b61wvzr) ([raw file](https://github.com/qtox/qtox/blob/89fa7db90a74100c1e3ff584b42557c0896101fd/src/model/friendlist/friendlistmanager.cpp#L23)):*
> ```cpp
> #include "src/widget/genericchatroomwidget.h"
> 
> #include <QApplication>
> ```

I don't see any items used from `QApplication`, please choose a narrower include
___
*[src/model/friendlist/friendlistmanager.cpp, line 50 at r1](https://reviewable.io/reviews/qtox/qtox/6347#-McLsmke0ueMAiaQj4je:-McLsmkf1e6OH2TV4uEM:b-x1y0qh) ([raw file](https://github.com/qtox/qtox/blob/89fa7db90a74100c1e3ff584b42557c0896101fd/src/model/friendlist/friendlistmanager.cpp#L50)):*
> ```cpp
>                             groupItem->getWidget()->deleteLater();}));
>     }
>     else {
> ```

here and throughout this PR the formatting is strange, it should be `} else {`
___
*[src/widget/friendlistwidget.cpp, line 162 at r1](https://reviewable.io/reviews/qtox/qtox/6347#-McLq91DC1gnGnDUAxeH:-McLq91DC1gnGnDUAxeI:bj0aq3g) ([raw file](https://github.com/qtox/qtox/blob/89fa7db90a74100c1e3ff584b42557c0896101fd/src/widget/friendlistwidget.cpp#L162)):*
> ```cpp
>         // Linking a friend with a circle and setting scroll position
>         for (int i = 0; i < itemsTmp.size(); ++i) {
>             if (itemsTmp[i]->isFriend()) {
> ```

combine these two conditions with `&&` to avoid this deep nesting for better readability


<!-- Sent from Reviewable.io -->

2021-06-16 22:16 UTC, sudden6 reviewed
great PR overall, the logic seems sound to me.

> *[Reviewable](https://reviewable.io/reviews/qtox/qtox/6347#-:-McLtAFXE8H8URTWaT85:b9zvmj9)* status: 0 of 1 LGTMs obtained



<!-- Sent from Reviewable.io -->

2021-06-17 16:41 UTC, bodwok reviewed
Thanks for looking.

> *[Reviewable](https://reviewable.io/reviews/qtox/qtox/6347#-:-McPpltREFhxLjzG-17T:b-4xtnak)* status: 0 of 1 LGTMs obtained

___
*[src/model/friendlist/friendlistmanager.h, line 69 at r1](https://reviewable.io/reviews/qtox/qtox/6347#-McLoarYDybB3-6k1MFP:-McPovrXD34bRXmvz_SM:b-8mcya8) ([raw file](https://github.com/qtox/qtox/blob/89fa7db90a74100c1e3ff584b42557c0896101fd/src/model/friendlist/friendlistmanager.h#L69)):*
<details><summary><i>Previously, sudden6 wrote…</i></summary><blockquote>

What's the reasoning behind making this static? I'd prefer not to introduce static variables if possible.
</blockquote></details>

The member function <code>cmpByName</code> is used in <code>std::sort</code> and must be static. In this case, <code>groupsOnTop</code> is used in the static function <code>cmpByName</code> and must also be static to detach from the object. Another way is to take the position of the groups from the settings when comparing, but it seems that it will be more expensive and we will get the dependence on the settings.
___
*[src/model/friendlist/friendlistmanager.cpp, line 23 at r1](https://reviewable.io/reviews/qtox/qtox/6347#-McLp4od6UiuH5Jds2ap:-McPpMOV9fL-wiZF-LoN:bb6un1j) ([raw file](https://github.com/qtox/qtox/blob/89fa7db90a74100c1e3ff584b42557c0896101fd/src/model/friendlist/friendlistmanager.cpp#L23)):*
<details><summary><i>Previously, sudden6 wrote…</i></summary><blockquote>

I don't see any items used from `QApplication`, please choose a narrower include
</blockquote></details>

Done
___
*[src/model/friendlist/friendlistmanager.cpp, line 50 at r1](https://reviewable.io/reviews/qtox/qtox/6347#-McLsmke0ueMAiaQj4je:-McPpP6TCtXV2biK-6Bg:bb6un1j) ([raw file](https://github.com/qtox/qtox/blob/89fa7db90a74100c1e3ff584b42557c0896101fd/src/model/friendlist/friendlistmanager.cpp#L50)):*
<details><summary><i>Previously, sudden6 wrote…</i></summary><blockquote>

here and throughout this PR the formatting is strange, it should be `} else {`
</blockquote></details>

Done
___
*[src/widget/friendlistwidget.cpp, line 162 at r1](https://reviewable.io/reviews/qtox/qtox/6347#-McLq91DC1gnGnDUAxeH:-McPpXG6DqXg6Eqg7VVp:bb6un1j) ([raw file](https://github.com/qtox/qtox/blob/89fa7db90a74100c1e3ff584b42557c0896101fd/src/widget/friendlistwidget.cpp#L162)):*
<details><summary><i>Previously, sudden6 wrote…</i></summary><blockquote>

combine these two conditions with `&&` to avoid this deep nesting for better readability
</blockquote></details>

Done


<!-- Sent from Reviewable.io -->

2021-06-17 20:46 UTC, sudden6 requested changes
> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/qtox/qtox/6347)* status: 0 of 1 LGTMs obtained

___
*[src/model/friendlist/friendlistmanager.h, line 69 at r1](https://reviewable.io/reviews/qtox/qtox/6347#-McLoarYDybB3-6k1MFP:-McQh9yiEL_lNv28Q4E5:b-o4bx73) ([raw file](https://github.com/qtox/qtox/blob/89fa7db90a74100c1e3ff584b42557c0896101fd/src/model/friendlist/friendlistmanager.h#L69)):*
<details><summary><i>Previously, bodwok wrote…</i></summary><blockquote>

The member function <code>cmpByName</code> is used in <code>std::sort</code> and must be static. In this case, <code>groupsOnTop</code> is used in the static function <code>cmpByName</code> and must also be static to detach from the object. Another way is to take the position of the groups from the settings when comparing, but it seems that it will be more expensive and we will get the dependence on the settings.
</blockquote></details>

You could pass a lambda to `std::sort` which captures `groupsOnTop` by value, and calls the respective sort function with `groupsOnTop` as parameter. Alternatively you could capture `this` and make the `cmp` functions member functions. This gets rid of the statics.


<!-- Sent from Reviewable.io -->

2021-06-18 06:09 UTC, sphaerophoria reviewed
Absolute phenomenal PR. Would love to see you stick around. 

> *[Reviewable](https://reviewable.io/reviews/qtox/qtox/6347#-:-McSj3T_850p7e8FGv1m:bqpu1lo)* status: 0 of 1 LGTMs obtained

___
*[src/model/friendlist/friendlistmanager.h, line 69 at r1](https://reviewable.io/reviews/qtox/qtox/6347#-McLoarYDybB3-6k1MFP:-McSi20T7rgNwJp41WLF:b-p68dh4) ([raw file](https://github.com/qtox/qtox/blob/89fa7db90a74100c1e3ff584b42557c0896101fd/src/model/friendlist/friendlistmanager.h#L69)):*
<details><summary><i>Previously, sudden6 wrote…</i></summary><blockquote>

You could pass a lambda to `std::sort` which captures `groupsOnTop` by value, and calls the respective sort function with `groupsOnTop` as parameter. Alternatively you could capture `this` and make the `cmp` functions member functions. This gets rid of the statics.
</blockquote></details>

+1 to lambda + capture
___
*[src/model/friendlist/friendlistmanager.cpp, line 1 at r2](https://reviewable.io/reviews/qtox/qtox/6347#-McS_5QMD6bRfTB93R4H:-McS_5QMD6bRfTB93R4I:bdn1w1o) ([raw file](https://github.com/qtox/qtox/blob/1d5dd8063eab9ed547e7ee78effd0e6c64ec6901/src/model/friendlist/friendlistmanager.cpp#L1)):*
> ```cpp
> /*
> ```

This whole file makes it clear how necessary this PR is. There's a surprising amount of logic in here and it's abstracted quite nicely (given the amount of constraints)
___
*[src/model/friendlist/friendlistmanager.cpp, line 42 at r2](https://reviewable.io/reviews/qtox/qtox/6347#-McSZmSYDMRW3-oYzXRN:-McSZmSYDMRW3-oYzXRO:b-x4eikp) ([raw file](https://github.com/qtox/qtox/blob/1d5dd8063eab9ed547e7ee78effd0e6c64ec6901/src/model/friendlist/friendlistmanager.cpp#L42)):*
> ```cpp
> void FriendListManager::addFriendItem(IFriendListItem *item)
> {
>     removeAll(item);
> ```

Out of curiosity did you actually hit this? As far as I can tell duplicates shouldn't happen since Widget should call remove*** on group/friend removal
___
*[src/model/friendlist/ifriendlistitem.h, line 55 at r2](https://reviewable.io/reviews/qtox/qtox/6347#-McSiDY8-FDsW9vTTbBi:-McSiDY8-FDsW9vTTbBj:beg9o1s) ([raw file](https://github.com/qtox/qtox/blob/1d5dd8063eab9ed547e7ee78effd0e6c64ec6901/src/model/friendlist/ifriendlistitem.h#L55)):*
> ```objc
> 
> private:
>     int posForName = -1;
> ```

Weird to see state in an Ixxx class, but that might just be me not having worked on qtox for a while.
___
*[src/widget/friendlistwidget.cpp, line 118 at r2](https://reviewable.io/reviews/qtox/qtox/6347#-McSadTvBl53MxK5CEPQ:-McSadTvBl53MxK5CEPR:b-u26vw9) ([raw file](https://github.com/qtox/qtox/blob/55fb28b08b7eeb60fc2698ad9cb8e36e9db93e19/src/widget/friendlistwidget.cpp#L118)):*
> ```cpp
>     mode = Settings::getInstance().getFriendSortingMode();
>     sortByMode(mode);
>     if (mode != SortingMode::Name) {
> ```

Note to reviewers. This is likely replaced with sortByMode() when friend list items are added.
___
*[src/widget/friendlistwidget.cpp, line 127 at r2](https://reviewable.io/reviews/qtox/qtox/6347#-McSb223AezJjy623rCI:-McSb223AezJjy623rCJ:b-fcjiuc) ([raw file](https://github.com/qtox/qtox/blob/1d5dd8063eab9ed547e7ee78effd0e6c64ec6901/src/widget/friendlistwidget.cpp#L127)):*
> ```cpp
> {
>     for (int i = 0; i < Settings::getInstance().getCircleCount(); ++i) {
>         CircleWidget* circle = CircleWidget::getFromID(i);
> ```

It would be nice if we didn't have to do this, but given the existing CircleWidget infra I see why it's done this way
___
*[src/widget/friendlistwidget.cpp, line 160 at r2](https://reviewable.io/reviews/qtox/qtox/6347#-McSbg_r1p9hl18hf0Ha:-McSbg_r1p9hl18hf0Hb:b-v3qovb) ([raw file](https://github.com/qtox/qtox/blob/1d5dd8063eab9ed547e7ee78effd0e6c64ec6901/src/widget/friendlistwidget.cpp#L160)):*
> ```cpp
>         QVector<IFriendListItem*> friendItems;
>         int posByName = 0; // Needed for scroll contacts
>         // Linking a friend with a circle and setting scroll position
> ```

Oh my goodness. We're tying the items to their circles correctly... I bet this fixes a bunch of layout bugs

Side note. I tried testing activity/circle sorting after this change and it worked great.

Beforehand just switching to activity mode froze qtox and I had to force kill it.
___
*[src/widget/friendlistwidget.cpp, line 168 at r2](https://reviewable.io/reviews/qtox/qtox/6347#-McSecRDAvzvT2-3CnH0:-McSecRDAvzvT2-3CnH1:b-uhu1xy) ([raw file](https://github.com/qtox/qtox/blob/1d5dd8063eab9ed547e7ee78effd0e6c64ec6901/src/widget/friendlistwidget.cpp#L168)):*
> ```cpp
>                             qobject_cast<FriendWidget*>((itemsTmp[i].get())->getWidget());
>                     circleWgt->addFriendWidget(frndTmp, frndTmp->getFriend()->getStatus());
>                     continue;
> ```

nit: it took me a disappointingly long time to figure out that this is why friends are not added to the list twice. A comment making it clear that this is what this is for might help future readers.
___
*[src/widget/friendlistwidget.cpp, line 291 at r2](https://reviewable.io/reviews/qtox/qtox/6347#-McSfjbnCflUrGfPHE3R:-McSfjbnCflUrGfPHE3S:b-8oozye) ([raw file](https://github.com/qtox/qtox/blob/1d5dd8063eab9ed547e7ee78effd0e6c64ec6901/src/widget/friendlistwidget.cpp#L291)):*
> ```cpp
> QWidget* FriendListWidget::getNextWidgetForName(IFriendListItem *currentPos, bool forward) const
> {
>     int pos = currentPos->getPosForName();
> ```

A few comments here
* I don't know if I like this "posForName" naming scheme. If I understand correctly this represents the position in the friends list when the sorting mode is "by name". Maybe something along the lines of nameSortedPos to make it clear that the position is related to the sorting, and not to the name itself?
* This currently will iterate over items that are hidden. Is this the behavior we want? Type something into the search bar and hit ctrl-tab to cycle contacts. I'd argue it should only go over visible contacts, at the moment it will iterate over contacts alphabetically even if they are hidden.
___
*[src/widget/friendlistwidget.cpp, line 342 at r2](https://reviewable.io/reviews/qtox/qtox/6347#-McSgzeR0HBU2dFElEtN:-McSgzeR0HBU2dFElEtO:b-i7fgz6) ([raw file](https://github.com/qtox/qtox/blob/1d5dd8063eab9ed547e7ee78effd0e6c64ec6901/src/widget/friendlistwidget.cpp#L342)):*
> ```cpp
>     });
> 
>     manager->addFriendItem(widget);
> ```

Nit: How do you feel about calling these "FriendListItem"s instead of "FriendItem"s. It's a little jarring to see a group added as a friend item.
___
*[src/widget/friendlistwidget.cpp, line 398 at r2](https://reviewable.io/reviews/qtox/qtox/6347#-McShGOdEO1oI3aWaitJ:-McShGOdEO1oI3aWaitK:b-j3jw6y) ([raw file](https://github.com/qtox/qtox/blob/1d5dd8063eab9ed547e7ee78effd0e6c64ec6901/src/widget/friendlistwidget.cpp#L398)):*
> ```cpp
>                                        bool hideOffline, bool hideGroups)
> {
>     manager->setFilter(searchString, hideOnline, hideOffline, hideGroups);
> ```

The link between this and the filter being applied is a little odd, but I don't see an obvious way around it
___
*[src/widget/friendwidget.cpp, line 364 at r2](https://reviewable.io/reviews/qtox/qtox/6347#-McSiYq29Gmnbv-xJIuP:-McSiYq29Gmnbv-xJIuQ:b-wbzduz) ([raw file](https://github.com/qtox/qtox/blob/1d5dd8063eab9ed547e7ee78effd0e6c64ec6901/src/widget/friendwidget.cpp#L364)):*
> ```cpp
> bool FriendWidget::isGroup() const
> {
>     return false;
> ```

I'm not the biggest fan of these isXXX APIs, but I don't have a good alternative in mind. This is wayyyy better than the way it is so not blocking, just mentioning it in case you were already on the fence about it and had an alternative in mind


<!-- Sent from Reviewable.io -->

2021-06-18 06:45 UTC, anthonybilinski requested changes
> Reviewed 12 of 14 files at r1, 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/qtox/qtox/6347)* status: 0 of 1 LGTMs obtained

___
*[src/model/friendlist/friendlistmanager.cpp, line 46 at r2](https://reviewable.io/reviews/qtox/qtox/6347#-McSncWfClNRnyGi9Dfk:-McSncWfClNRnyGi9Dfl:bst1g00) ([raw file](https://github.com/qtox/qtox/blob/1d5dd8063eab9ed547e7ee78effd0e6c64ec6901/src/model/friendlist/friendlistmanager.cpp#L46)):*
> ```cpp
>     if (item->isGroup()) {
>         items.push_back(IFriendItemPtr(item, [](IFriendListItem* groupItem){
>                             groupItem->getWidget()->deleteLater();}));
> ```

why does GroupWidget need to be `deleteLater`'d, but FriendWidget doesn't? Shouldn't the shared_ptr deleting it directly? Comment?
___
*[src/widget/friendlistwidget.cpp, line 128 at r2](https://reviewable.io/reviews/qtox/qtox/6347#-McSaKbO8ZYxE2xKA6Ct:-McSaKbO8ZYxE2xKA6Cu:b-mjop46) ([raw file](https://github.com/qtox/qtox/blob/1d5dd8063eab9ed547e7ee78effd0e6c64ec6901/src/widget/friendlistwidget.cpp#L128)):*
> ```cpp
>     for (int i = 0; i < Settings::getInstance().getCircleCount(); ++i) {
>         CircleWidget* circle = CircleWidget::getFromID(i);
>         if (circle != nullptr) {
> ```

nullptr check is unneeded, free/delete do nothing on null.
___
*[src/widget/friendlistwidget.cpp, line 284 at r2](https://reviewable.io/reviews/qtox/qtox/6347#-McSeWM9C2EJZxb8vDq1:-McSeWM9C2EJZxb8vDq2:bf0trz3) ([raw file](https://github.com/qtox/qtox/blob/1d5dd8063eab9ed547e7ee78effd0e6c64ec6901/src/widget/friendlistwidget.cpp#L284)):*
> ```cpp
>                 delete itemTmp;
>             }
>         }
> ```

I don't think you need to remove the parent from a widget before deleting it, null checks also aren't needed before calling delete, meaning you don't have to differentiate between widgets and layouts.
See https://doc.qt.io/qt-5/qlayout.html#takeAt. It looks like this could be done safely as just
```
    while ((itemForDel = listLayout->takeAt(0)) != nullptr) {
        delete itemForDel->widget();
        delete itemForDel
    }
```


<!-- Sent from Reviewable.io -->

2021-06-22 19:08 UTC, bodwok reviewed
Thanks for comments.

> *[Reviewable](https://reviewable.io/reviews/qtox/qtox/6347#-:-Mcp1u4B8JVRdWeb5DQ7:bgegwc1)* status: 0 of 1 LGTMs obtained

___
*[src/model/friendlist/friendlistmanager.h, line 69 at r1](https://reviewable.io/reviews/qtox/qtox/6347#-McLoarYDybB3-6k1MFP:-Mcp-VvpCEGJWd3ffrR9:b-b2c1hk) ([raw file](https://github.com/qtox/qtox/blob/89fa7db90a74100c1e3ff584b42557c0896101fd/src/model/friendlist/friendlistmanager.h#L69)):*
<details><summary><i>Previously, sphaerophoria wrote…</i></summary><blockquote>

+1 to lambda + capture
</blockquote></details>

Changed to the sort with lambda expression.
___
*[src/model/friendlist/friendlistmanager.cpp, line 1 at r2](https://reviewable.io/reviews/qtox/qtox/6347#-McS_5QMD6bRfTB93R4H:-Mcp2K3B2UWk62wOfal0:bau0j3c) ([raw file](https://github.com/qtox/qtox/blob/1d5dd8063eab9ed547e7ee78effd0e6c64ec6901/src/model/friendlist/friendlistmanager.cpp#L1)):*
<details><summary><i>Previously, sphaerophoria wrote…</i></summary><blockquote>

This whole file makes it clear how necessary this PR is. There's a surprising amount of logic in here and it's abstracted quite nicely (given the amount of constraints)
</blockquote></details>

I thought about a possible test for this in the future, I think it helped.
___
*[src/model/friendlist/friendlistmanager.cpp, line 42 at r2](https://reviewable.io/reviews/qtox/qtox/6347#-McSZmSYDMRW3-oYzXRN:-Mcp2TcNBfUGNlvKy78Y:buyhndj) ([raw file](https://github.com/qtox/qtox/blob/1d5dd8063eab9ed547e7ee78effd0e6c64ec6901/src/model/friendlist/friendlistmanager.cpp#L42)):*
<details><summary><i>Previously, sphaerophoria wrote…</i></summary><blockquote>

Out of curiosity did you actually hit this? As far as I can tell duplicates shouldn't happen since Widget should call remove*** on group/friend removal
</blockquote></details>

It looks like it might cause a segfault. I removed it since qTox already detects a double addition, but if a check is needed - we can simple exit the function without delete.
___
*[src/model/friendlist/friendlistmanager.cpp, line 46 at r2](https://reviewable.io/reviews/qtox/qtox/6347#-McSncWfClNRnyGi9Dfk:-Mcp-rCc9PH9H05fjV8c:b-m22jk5) ([raw file](https://github.com/qtox/qtox/blob/1d5dd8063eab9ed547e7ee78effd0e6c64ec6901/src/model/friendlist/friendlistmanager.cpp#L46)):*
<details><summary><i>Previously, anthonybilinski (Anthony Bilinski) wrote…</i></summary><blockquote>

why does GroupWidget need to be `deleteLater`'d, but FriendWidget doesn't? Shouldn't the shared_ptr deleting it directly? Comment?
</blockquote></details>

If directly delete <code>GroupWidget</code> it causes a segfault, it is not completely clear why (I think something with event loops). It is not new behavior in this PR. For <code>FriendWidget</code> calling <code>deleteLater</code> can be useful also.
___
*[src/model/friendlist/ifriendlistitem.h, line 55 at r2](https://reviewable.io/reviews/qtox/qtox/6347#-McSiDY8-FDsW9vTTbBi:-Mcp08pU7AaEZLml5W32:b-b7qscv) ([raw file](https://github.com/qtox/qtox/blob/1d5dd8063eab9ed547e7ee78effd0e6c64ec6901/src/model/friendlist/ifriendlistitem.h#L55)):*
<details><summary><i>Previously, sphaerophoria wrote…</i></summary><blockquote>

Weird to see state in an Ixxx class, but that might just be me not having worked on qtox for a while.
</blockquote></details>

I agree, <code>posForName</code> added to here for the keeping exists behavior navigation by items of list. I think navigation needs to be encapsulated in the future. 
___
*[src/widget/friendlistwidget.cpp, line 118 at r2](https://reviewable.io/reviews/qtox/qtox/6347#-McSadTvBl53MxK5CEPQ:-Mcp2r1D1G2Hvo3Ewp6d:b-5kp0ir) ([raw file](https://github.com/qtox/qtox/blob/55fb28b08b7eeb60fc2698ad9cb8e36e9db93e19/src/widget/friendlistwidget.cpp#L118)):*
<details><summary><i>Previously, sphaerophoria wrote…</i></summary><blockquote>

Note to reviewers. This is likely replaced with sortByMode() when friend list items are added.
</blockquote></details>

If return the call to <code>QApplication::processEvents(QEventLoop::ExcludeSocketNotifiers)</code> to <code>CategoryWidget::setExpanded</code>, then <code>sortByMode(mode)</code> necessary return to <code>FriendListWidget::FriendListWidget</code>. Otherwise circles are added incorrectly. 
___
*[src/widget/friendlistwidget.cpp, line 127 at r2](https://reviewable.io/reviews/qtox/qtox/6347#-McSb223AezJjy623rCI:-Mcp3DOPCuskB2HDjmPN:bbfmzwx) ([raw file](https://github.com/qtox/qtox/blob/1d5dd8063eab9ed547e7ee78effd0e6c64ec6901/src/widget/friendlistwidget.cpp#L127)):*
<details><summary><i>Previously, sphaerophoria wrote…</i></summary><blockquote>

It would be nice if we didn't have to do this, but given the existing CircleWidget infra I see why it's done this way
</blockquote></details>

For the case when circles created and the app closes with mode by activity.
___
*[src/widget/friendlistwidget.cpp, line 128 at r2](https://reviewable.io/reviews/qtox/qtox/6347#-McSaKbO8ZYxE2xKA6Ct:-Mcp10RgAd6z_U6wk6tp:bb6un1j) ([raw file](https://github.com/qtox/qtox/blob/1d5dd8063eab9ed547e7ee78effd0e6c64ec6901/src/widget/friendlistwidget.cpp#L128)):*
<details><summary><i>Previously, anthonybilinski (Anthony Bilinski) wrote…</i></summary><blockquote>

nullptr check is unneeded, free/delete do nothing on null.
</blockquote></details>

Done
___
*[src/widget/friendlistwidget.cpp, line 160 at r2](https://reviewable.io/reviews/qtox/qtox/6347#-McSbg_r1p9hl18hf0Ha:-Mcp3MrnBgGKPrbpMLUS:b1y4zlg) ([raw file](https://github.com/qtox/qtox/blob/1d5dd8063eab9ed547e7ee78effd0e6c64ec6901/src/widget/friendlistwidget.cpp#L160)):*
<details><summary><i>Previously, sphaerophoria wrote…</i></summary><blockquote>

Oh my goodness. We're tying the items to their circles correctly... I bet this fixes a bunch of layout bugs

Side note. I tried testing activity/circle sorting after this change and it worked great.

Beforehand just switching to activity mode froze qtox and I had to force kill it.
</blockquote></details>

Yep it is was issue 6291
___
*[src/widget/friendlistwidget.cpp, line 168 at r2](https://reviewable.io/reviews/qtox/qtox/6347#-McSecRDAvzvT2-3CnH0:-Mcp0NRAEDt9un898uU1:b8sr1tk) ([raw file](https://github.com/qtox/qtox/blob/1d5dd8063eab9ed547e7ee78effd0e6c64ec6901/src/widget/friendlistwidget.cpp#L168)):*
<details><summary><i>Previously, sphaerophoria wrote…</i></summary><blockquote>

nit: it took me a disappointingly long time to figure out that this is why friends are not added to the list twice. A comment making it clear that this is what this is for might help future readers.
</blockquote></details>

If a friend has the circle ID, he will be added to the circle layout only. Otherwise we set the position and add to the vector friendItems. Then the position for friends from circles is set. Here it was done to preserve the existing behavior when navigation through the items. I added some comments. Tell me if more info is needed.
___
*[src/widget/friendlistwidget.cpp, line 284 at r2](https://reviewable.io/reviews/qtox/qtox/6347#-McSeWM9C2EJZxb8vDq1:-Mcp1KSU0HxY4Ey-0rJc:b13holg) ([raw file](https://github.com/qtox/qtox/blob/1d5dd8063eab9ed547e7ee78effd0e6c64ec6901/src/widget/friendlistwidget.cpp#L284)):*
<details><summary><i>Previously, anthonybilinski (Anthony Bilinski) wrote…</i></summary><blockquote>

I don't think you need to remove the parent from a widget before deleting it, null checks also aren't needed before calling delete, meaning you don't have to differentiate between widgets and layouts.
See https://doc.qt.io/qt-5/qlayout.html#takeAt. It looks like this could be done safely as just
```
    while ((itemForDel = listLayout->takeAt(0)) != nullptr) {
        delete itemForDel->widget();
        delete itemForDel
    }
```
</blockquote></details>

<code>manager->resetParents()</code> and <code>cleanMainLayout()</code> should return listLayout and used widgets to the state before sortByMode is called. <code>manager->resetParents()</code> performs actions on Friends and Groups. <code>cleanMainLayout() [...]

2021-06-22 20:56 UTC, sudden6 reviewed
<img class="emoji" title=":lgtm_strong:" alt=":lgtm_strong:" align="absmiddle" src="https://reviewable.io/lgtm_strong.png" height="20" width="61"/> from my side, waiting for lgtm from @sphaerophoria and @anthonybilinski 

> Reviewed 1 of 4 files at r3.
> *[Reviewable](https://reviewable.io/reviews/qtox/qtox/6347#-:-McpV5ZBE-g98gjA0XqT:b-vvgad6)* status: :shipit: complete! 1 of 1 LGTMs obtained



<!-- Sent from Reviewable.io -->

2021-06-23 04:40 UTC, sphaerophoria reviewed
<img class="emoji" title=":lgtm_strong:" alt=":lgtm_strong:" align="absmiddle" src="https://reviewable.io/lgtm_strong.png" height="20" width="61"/>

> Reviewed 3 of 4 files at r3.
> *[Reviewable](https://reviewable.io/reviews/qtox/qtox/6347#-:-Mcr9rqL87asGIzKcJNP:b-jbsf8z)* status: :shipit: complete! 2 of 1 LGTMs obtained

___
*[src/widget/friendwidget.cpp, line 364 at r2](https://reviewable.io/reviews/qtox/qtox/6347#-McSiYq29Gmnbv-xJIuP:-Mcr9mkoEQJlcZZ5bvW7:b-3t7fm6) ([raw file](https://github.com/qtox/qtox/blob/1d5dd8063eab9ed547e7ee78effd0e6c64ec6901/src/widget/friendwidget.cpp#L364)):*
<details><summary><i>Previously, bodwok wrote…</i></summary><blockquote>

Now the <code>FriendListManager</code> manages only friends and groups and if will need we can use only <code>isFriend</code> and <code>!isFriend</code>. But with <code>isFriend</code> and <code>isGroup</code> might be clearer? Tell me if need to change.
</blockquote></details>

Nah it's fine, I think it's good as is


<!-- Sent from Reviewable.io -->

2021-06-27 08:18 UTC, anthonybilinski requested changes
> Reviewed 1 of 4 files at r3.
> *[Reviewable](https://reviewable.io/reviews/qtox/qtox/6347)* status: :shipit: complete! 2 of 1 LGTMs obtained

___
*[src/model/friendlist/friendlistmanager.cpp, line 46 at r2](https://reviewable.io/reviews/qtox/qtox/6347#-McSncWfClNRnyGi9Dfk:-MdBVq1vE-YnUcWbkljQ:b-g6nbdq) ([raw file](https://github.com/qtox/qtox/blob/1d5dd8063eab9ed547e7ee78effd0e6c64ec6901/src/model/friendlist/friendlistmanager.cpp#L46)):*
<details><summary><i>Previously, bodwok wrote…</i></summary><blockquote>

If directly delete <code>GroupWidget</code> it causes a segfault, it is not completely clear why (I think something with event loops). It is not new behavior in this PR. For <code>FriendWidget</code> calling <code>deleteLater</code> can be useful also.
</blockquote></details>

A bit concerning, but ok, don't want to hold up this PR and we can look into it if it causes issues later.
___
*[src/widget/friendlistwidget.cpp, line 284 at r2](https://reviewable.io/reviews/qtox/qtox/6347#-McSeWM9C2EJZxb8vDq1:-MdBWr5sAEN6JX6IMDFB:b-dcrzkz) ([raw file](https://github.com/qtox/qtox/blob/1d5dd8063eab9ed547e7ee78effd0e6c64ec6901/src/widget/friendlistwidget.cpp#L284)):*
<details><summary><i>Previously, bodwok wrote…</i></summary><blockquote>

<code>manager->resetParents()</code> and <code>cleanMainLayout()</code> should return listLayout and used widgets to the state before sortByMode is called. <code>manager->resetParents()</code> performs actions on Friends and Groups. <code>cleanMainLayout()</code> above the rest of the listLayout items. I put <code>resetParents()</code> in <code>cleanMainLayout()</code> because they have a call order dependency.
</blockquote></details>

I see, but I don't think that addresses what I was saying, unless I'm misunderstanding. I was saying that I think all of

```
    QLayoutItem* itemForDel;
    while ((itemForDel = listLayout->takeAt(0)) != nullptr) {
        listLayout->removeWidget(itemForDel->widget());
        QWidget* wgt = itemForDel->widget();
        if (wgt != nullptr) {
            wgt->setParent(nullptr);
        } else if (itemForDel->layout() != nullptr) {
            QLayout* layout = itemForDel->layout();
            QLayoutItem* itemTmp;
            while ((itemTmp = layout->takeAt(0)) != nullptr) {
                wgt = itemTmp->widget();
                delete wgt;
                delete itemTmp;
            }
        }
```

could be replaced with just

```
    while ((itemForDel = listLayout->takeAt(0)) != nullptr) {
        delete itemForDel->widget();
        delete itemForDel;
    }
```

based on Qt docs. Testing with the change also doesn't give any obvious UI problems or crashes.


<!-- Sent from Reviewable.io -->

2021-06-28 11:22 UTC, bodwok reviewed
> *[Reviewable](https://reviewable.io/reviews/qtox/qtox/6347)* status: :shipit: complete! 2 of 1 LGTMs obtained

___
*[src/widget/friendlistwidget.cpp, line 284 at r2](https://reviewable.io/reviews/qtox/qtox/6347#-McSeWM9C2EJZxb8vDq1:-MdHFbuK3nL9Rp46Hl6g:b-dmzx6w) ([raw file](https://github.com/qtox/qtox/blob/1d5dd8063eab9ed547e7ee78effd0e6c64ec6901/src/widget/friendlistwidget.cpp#L284)):*
<details><summary><i>Previously, anthonybilinski (Anthony Bilinski) wrote…</i></summary><blockquote>

I see, but I don't think that addresses what I was saying, unless I'm misunderstanding. I was saying that I think all of

```
    QLayoutItem* itemForDel;
    while ((itemForDel = listLayout->takeAt(0)) != nullptr) {
        listLayout->removeWidget(itemForDel->widget());
        QWidget* wgt = itemForDel->widget();
        if (wgt != nullptr) {
            wgt->setParent(nullptr);
        } else if (itemForDel->layout() != nullptr) {
            QLayout* layout = itemForDel->layout();
            QLayoutItem* itemTmp;
            while ((itemTmp = layout->takeAt(0)) != nullptr) {
                wgt = itemTmp->widget();
                delete wgt;
                delete itemTmp;
            }
        }
```

could be replaced with just

```
    while ((itemForDel = listLayout->takeAt(0)) != nullptr) {
        delete itemForDel->widget();
        delete itemForDel;
    }
```

based on Qt docs. Testing with the change also doesn't give any obvious UI problems or crashes.
</blockquote></details>

In case of use:

    while ((itemForDel = listLayout->takeAt(0)) != nullptr) {
        delete itemForDel->widget();
        delete itemForDel;
    }


if you remove a friend from the circle, the application will terminate unexpectedly.

<code>FriendWidget::removeFromCircle()</code> will call <code>FriendListWidget::moveWidget()</code> in which circles will be deleted, and then <code>FriendWidget::removeFromCircle()</code> will refer to the already deleted circle. 

Now circles are created on the first call. Circle is owned by FriendListWidget. 

Also, in the "by activity" mode, an additional layout containing CategoryWidget is added, but CategoryWidget is not deleted when switching to the mode by name.

This has been fixed in my version. Perhaps changing removeFromCircle will remove everything unnecessary from here...


<!-- Sent from Reviewable.io -->

2021-06-30 06:49 UTC, anthonybilinski approved these changes
<img class="emoji" title=":lgtm_strong:" alt=":lgtm_strong:" align="absmiddle" src="https://reviewable.io/lgtm_strong.png" height="20" width="61"/> 

> *[Reviewable](https://reviewable.io/reviews/qtox/qtox/6347#-:-MdQfMuy66pbo2qPLBEK:b-uwkowd)* status: :shipit: complete! 3 of 1 LGTMs obtained

___
*[src/widget/friendlistwidget.cpp, line 284 at r2](https://reviewable.io/reviews/qtox/qtox/6347#-McSeWM9C2EJZxb8vDq1:-MdQfHjJ7JoA00yEjqkz:b99bk2i) ([raw file](https://github.com/qtox/qtox/blob/1d5dd8063eab9ed547e7ee78effd0e6c64ec6901/src/widget/friendlistwidget.cpp#L284)):*
<details><summary><i>Previously, bodwok wrote…</i></summary><blockquote>

In case of use:

    while ((itemForDel = listLayout->takeAt(0)) != nullptr) {
        delete itemForDel->widget();
        delete itemForDel;
    }


if you remove a friend from the circle, the application will terminate unexpectedly.

<code>FriendWidget::removeFromCircle()</code> will call <code>FriendListWidget::moveWidget()</code> in which circles will be deleted, and then <code>FriendWidget::removeFromCircle()</code> will refer to the already deleted circle. 

Now circles are created on the first call. Circle is owned by FriendListWidget. 

Also, in the "by activity" mode, an additional layout containing CategoryWidget is added, but CategoryWidget is not deleted when switching to the mode by name.

This has been fixed in my version. Perhaps changing removeFromCircle will remove everything unnecessary from here...


</blockquote></details>

Ok makes sense :+1: 


<!-- Sent from Reviewable.io -->

2021-06-30 16:35 UTC, merged