Chatlog Cleanup
qTox/qTox pull request #6374
Opened 2021-09-12 21:43 UTC by sphaerophoria

**NOTE: Based on top of #6311** 

Refactor/fixes for chatlog to resolve #6223 #5878 #5940

This PR has commits that fall under two categories
* Re-apply backouts from 1.17
* Implement a more architecturally sound sliding window chat log

Quick sample of what the new sliding window looks like in practice. Given the scope of this change I suggest reviewers try it themselves to see how it feels.

![new_chatlog](https://user-images.githubusercontent.com/1069811/133003690-dba435e8-a763-48cc-8eb2-bcb2e00fce23.gif)

The only remaining janky behavior is that selections for messages removed from the chatlog are cleared. This means you have to use the export chat log feature to get long logs. A future improvement would be to not purge messages that are selected.

Implementation commit messages for review context...

refactor(chatlog): Rename ChatLog -> ChatWidget

* Makes the distinction between IChatLog (the model class) and
  ChatWidget (the view class) more clear

refactor(chatlog): Remove unused getRow functions from ChatLine

* The getRow functions would not track correctly since the rows indexes
  cannot be fixed to the view anymore

feat(chatlog): Re-implement sliding window ChatLog view

* Replace lines/messages with helper class to synchronize state between
  IChatLog and ChatLog more easily
* selection indexes have been replaced with ChatLine::Ptrs, this is to
  ensure consistency while the view slides around
	* This has another benefit of removing all the code that has to
	  manually slide the selection boxes around
* Replaced all insertion/removal functions with single "insertAtIdx".
  This helps ensure that mappings between ChatLogIdx and position within
  the view are captured correctly as items in the view slide around
* workerTimeout replaced with more generic name "renderFinished" that is
  used in synchronous and asynchronous paths
* Removed unused function ChatForm::insertChatMessage
* Re-implemented "Go to current date" with new ChatLog APIs
* Removed unused GenericChatForm::addSystemDateMessage. This is handled
  by ChatLog now
* Resolves #6223
* Resolves #5878
* Resolves #5940

refactor(chatlog): Store ChatLine::Ptr in messages instead of ChatMessage

* This simplifies future refactoring since the rest of ChatLog expects
  to be working with the base class

refactor(chatlog): Move rendering of messages from GenericChatForm -> ChatLog

* Simplifies reasoning about who owns what functionality between
  GenericChatForm and ChatLog. GenericChatForm is now just a layout
  class and ChatLog handles all interactions with retrieving and
  displaying messages from the model
* Reasoning for work is described in more detail in #6223

- [x] Commits follow our [git commit guidelines](https://github.com/qTox/qTox/blob/master/CONTRIBUTING.md#git-commit-guidelines)

2021-10-07 03:08 UTC, anthonybilinski requested changes
> *[Reviewable](https://reviewable.io/reviews/qtox/qtox/6374)* status: 0 of 1 LGTMs obtained

*[a discussion](https://reviewable.io/reviews/qtox/qtox/6374#-MlNgkkeE80FhTORXhPz:-MlNgkkeE80FhTORXhQ-:b-yyyyjx) (no related file):*
While running this, I saw an issue where when lots of chat is loaded, i.e. the scroll bar is small, sometimes the chatlog stays white for a long time, over 10s. Right click -> go to current date, which evicts most messages seems to make this go away. Could be reproduced fairly infrequently by just scrolling up lots then scrolling back down and sending messages.

---
*[a discussion](https://reviewable.io/reviews/qtox/qtox/6374#-MlNh26yBEmgX08VNgwx:-MlNh26yBEmgX08VNgwy:b7ng0cq) (no related file):*
Another issue I saw, after starting up a profile and just quickly sending maybe 100 messages to another profile that was offline, I think while scrolled up, after scrolling back down to the bottom, it didn't have the latest sent messages, and sending more new messages didn't add them either. Right click -> go to current date also didn't show the new messages. Scrolling up and down also didn't. Right click -> load history was the only thing I tried that did.

I haven't been able to repro this trying the same steps :S

---


<!-- Sent from Reviewable.io -->

2021-10-11 19:42 UTC, sphaerophoria reviewed
> *[Reviewable](https://reviewable.io/reviews/qtox/qtox/6374)* status: 0 of 1 LGTMs obtained

*[a discussion](https://reviewable.io/reviews/qtox/qtox/6374#-MlNgkkeE80FhTORXhPz:-MlkrTrd1hltg1tfqLEq:b-jib8gf) (no related file):*
<details><summary><i>Previously, anthonybilinski (Anthony Bilinski) wrote…</i></summary><blockquote>

While running this, I saw an issue where when lots of chat is loaded, i.e. the scroll bar is small, sometimes the chatlog stays white for a long time, over 10s. Right click -> go to current date, which evicts most messages seems to make this go away. Could be reproduced fairly infrequently by just scrolling up lots then scrolling back down and sending messages.
</blockquote></details>

I haven't been able to reproduce this, but I'll try some more. The only time I saw this behavior was if I manually commented out the resize worker, but I don't see a way that you would have ended up in that state the way the code is now.

---
*[a discussion](https://reviewable.io/reviews/qtox/qtox/6374#-MlNh26yBEmgX08VNgwx:-MlkrnKyACoarfLzg03S:b-8ehfnw) (no related file):*
<details><summary><i>Previously, anthonybilinski (Anthony Bilinski) wrote…</i></summary><blockquote>

Another issue I saw, after starting up a profile and just quickly sending maybe 100 messages to another profile that was offline, I think while scrolled up, after scrolling back down to the bottom, it didn't have the latest sent messages, and sending more new messages didn't add them either. Right click -> go to current date also didn't show the new messages. Scrolling up and down also didn't. Right click -> load history was the only thing I tried that did.

I haven't been able to repro this trying the same steps :S
</blockquote></details>

I managed to reproduce something along these lines. Don't have a root cause yet but it's fairly easily for me to reproduce messages not showing after scrolling back down by just not scrolling _all_ the way. I do not see the behavior where re-scrolling does not fix it, but maybe it has the same root cause

---


<!-- Sent from Reviewable.io -->

2021-10-12 05:14 UTC, anthonybilinski requested changes
> *[Reviewable](https://reviewable.io/reviews/qtox/qtox/6374)* status: 0 of 1 LGTMs obtained

*[a discussion](https://reviewable.io/reviews/qtox/qtox/6374#-MlNgkkeE80FhTORXhPz:-Mlmu2DABq_JgZnQQ-8m:brcqhca) (no related file):*
<details><summary><i>Previously, sphaerophoria wrote…</i></summary><blockquote>

I haven't been able to reproduce this, but I'll try some more. The only time I saw this behavior was if I manually commented out the resize worker, but I don't see a way that you would have ended up in that state the way the code is now.
</blockquote></details>

Hmm have seen this a couple more times just during normal conversation. It would happen only when the chat is large, right on an incoming message, last (seemingly indefinitely) with no resize worker overlay, then stop as soon as I receive another new message, and come back as soon as  I receive another. No date line was in the view. I could scroll across the whole chatlog area, scroll against the very top or the very bottom with no change.

Again right click -> "Go to current date" stopped it and made it stop happening on new message, while also evicting most of the chat from view.

---
*[a discussion](https://reviewable.io/reviews/qtox/qtox/6374#-MlNh26yBEmgX08VNgwx:-MlmueBJ3aDk6YTNW4Tf:b4g4t15) (no related file):*
<details><summary><i>Previously, sphaerophoria wrote…</i></summary><blockquote>

I managed to reproduce something along these lines. Don't have a root cause yet but it's fairly easily for me to reproduce messages not showing after scrolling back down by just not scrolling _all_ the way. I do not see the behavior where re-scrolling does not fix it, but maybe it has the same root cause
</blockquote></details>

I might have seen this again, or maybe something similar, where I was scrolled I think due to search, received a new message, scrolled down and saw it, searched again, and then could never get it to show back up. Scrolling down all the way didn't show it, and "Go to current date" also wouldn't show it, nor would "Load history". Closing qTox and re-opening it did show the message, but this seems like not just not scrolling to the bottom, I don't think.

---


<!-- Sent from Reviewable.io -->

2021-10-16 18:43 UTC, sphaerophoria reviewed
> *[Reviewable](https://reviewable.io/reviews/qtox/qtox/6374)* status: 0 of 1 LGTMs obtained

*[a discussion](https://reviewable.io/reviews/qtox/qtox/6374#-MlNgkkeE80FhTORXhPz:-Mm9Na3ABJQG4SwfQPsV:bq7w7op) (no related file):*
<details><summary><i>Previously, anthonybilinski (Anthony Bilinski) wrote…</i></summary><blockquote>

Hmm have seen this a couple more times just during normal conversation. It would happen only when the chat is large, right on an incoming message, last (seemingly indefinitely) with no resize worker overlay, then stop as soon as I receive another new message, and come back as soon as  I receive another. No date line was in the view. I could scroll across the whole chatlog area, scroll against the very top or the very bottom with no change.

Again right click -> "Go to current date" stopped it and made it stop happening on new message, while also evicting most of the chat from view.
</blockquote></details>

I haven't managed to reproduce this. I think I can mitigate it though.

The current behavior is already kind of annoying. Every 100 messages the chat log flickers because we have to re-calculate the chatlog to render all our messages. Most chat apps don't clear messages while the window is open I've noticed, so I've just followed that pattern and moved the message purging to when a chat is hidden.

Note: I think this behavior could be improved if we do chat layout from bottom to top instead of top to bottom, but I don't want to take on that complexity here.

---
*[a discussion](https://reviewable.io/reviews/qtox/qtox/6374#-MlNh26yBEmgX08VNgwx:-Mm9OZQREQBglyzhARIi:b9m165u) (no related file):*
<details><summary><i>Previously, anthonybilinski (Anthony Bilinski) wrote…</i></summary><blockquote>

I might have seen this again, or maybe something similar, where I was scrolled I think due to search, received a new message, scrolled down and saw it, searched again, and then could never get it to show back up. Scrolling down all the way didn't show it, and "Go to current date" also wouldn't show it, nor would "Load history". Closing qTox and re-opening it did show the message, but this seems like not just not scrolling to the bottom, I don't think.
</blockquote></details>

Hm, interesting. I can't seem to reproduce this. Maybe we get lucky and the removal of chatlog shuffling while it's open will help. One guess is there's a race between re-rendering on messages received and re-rendering on scroll, so it's not an unreasonable hope for an improvement there.

---


<!-- Sent from Reviewable.io -->

2021-11-22 00:11 UTC, anthonybilinski requested changes
> Reviewed 33 of 41 files at r1, 9 of 9 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/qtox/qtox/6374)* status: :shipit: complete! 1 of 1 LGTMs obtained

*[a discussion](https://reviewable.io/reviews/qtox/qtox/6374#-MlNgkkeE80FhTORXhPz:-Mn4Mf-i4JvPO3d7MiKF:b-889sf0) (no related file):*
<details><summary><i>Previously, sphaerophoria wrote…</i></summary><blockquote>

I haven't managed to reproduce this. I think I can mitigate it though.

The current behavior is already kind of annoying. Every 100 messages the chat log flickers because we have to re-calculate the chatlog to render all our messages. Most chat apps don't clear messages while the window is open I've noticed, so I've just followed that pattern and moved the message purging to when a chat is hidden.

Note: I think this behavior could be improved if we do chat layout from bottom to top instead of top to bottom, but I don't want to take on that complexity here.
</blockquote></details>

Running the new version with both manual testing with two local profiles for quite a while, sending many messages back and forth with varying timing and with typing notification on both etc, I wasn't able to reproduce this issue. I also had a normal long conversation, which is where I saw the issue many times before, and didn't see it once. So I think this workaround is working as intended :+1: 

---
*[a discussion](https://reviewable.io/reviews/qtox/qtox/6374#-MlNh26yBEmgX08VNgwx:-Mn4ZVhp00IXsrEr27-M:b-1afz6f) (no related file):*
<details><summary><i>Previously, sphaerophoria wrote…</i></summary><blockquote>

Hm, interesting. I can't seem to reproduce this. Maybe we get lucky and the removal of chatlog shuffling while it's open will help. One guess is there's a race between re-rendering on messages received and re-rendering on scroll, so it's not an unreasonable hope for an improvement there.
</blockquote></details>

I haven't seen this one again and haven't been able to reproduce it in testing either, so hopefully it's dealt with. I don't think it's worth holding up the merge.

---
*[a discussion](https://reviewable.io/reviews/qtox/qtox/6374#-Mp3xsF34J6gxjP1REtu:-Mp3xsF34J6gxjP1REtv:b-uwkowd) (no related file):*
<img class="emoji" title=":lgtm_strong:" alt=":lgtm_strong:" align="absmiddle" src="https://reviewable.io/lgtm_strong.png" height="20" width="61"/> 

---


<!-- Sent from Reviewable.io -->

2021-11-22 00:32 UTC, anthonybilinski reviewed
> Reviewed 19 of 19 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/qtox/qtox/6374)* status: :shipit: complete! 1 of 1 LGTMs obtained



<!-- Sent from Reviewable.io -->

2021-11-22 00:40 UTC, anthonybilinski approved these changes
> *[Reviewable](https://reviewable.io/reviews/qtox/qtox/6374)* status: :shipit: complete! 1 of 1 LGTMs obtained



<!-- Sent from Reviewable.io -->

2021-11-22 01:34 UTC, merged