refactor: Provide a Virtual Method Anchor for Classes in Headers
qTox/qTox pull request #6394
Opened 2021-10-15 05:34 UTC by brandonmosher

Define at least one virtual method in cpp files for classes with
vtables to improve link time. This is done by defining a defaulted
destructor in the cpp file, or moving an overridden method from the
header to the cpp file. Where neccessary, create new cpp files and
add them to CMakeLists.

See http://llvm.org/docs/CodingStandards.html#provide-a-virtual-method-anchor-for-classes-in-headers.

Fixes #6036.

- [ ] Commits follow our [git commit guidelines](https://github.com/qTox/qTox/blob/master/CONTRIBUTING.md#git-commit-guidelines)

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/qtox/qtox/6394)

2021-10-20 20:14 UTC, jwestell commented
By explicitly adding a destructor declaration (even if defaulted in the .cpp file), the implicitly defined move constructor will no longer be generated, thus removing any possibility of move semantics. 

http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2017/n4713.pdf
> 8 If the definition of a class X does not explicitly declare a move constructor, a non-explicit one will be implicitly
declared as defaulted if and only if
(8.1) — X does not have a user-declared copy constructor,
(8.2) — X does not have a user-declared copy assignment operator,
(8.3) — X does not have a user-declared move assignment operator, and
(8.4) — X does not have a user-declared destructor.

Is removing automatic move semantics worth the strong vtables? Perhaps consider defining default move constructors and move-assignment operators for applicable concrete classes in this PR to retain this behaviour.

2021-10-21 04:00 UTC, anthonybilinski commented
Good point @jwestell. To be honest I don't think we are very concerned about link time savings that this warning is suggesting, but also not very concerned about move constructor or inline savings...

So I think the options are
1) Current method, slower linking due to repeated vtable in each object
2) Current proposed version, loses copy constructor and inlining of the destructor.
3) @jwestell method of explicitly defining the copy constructors as default, still losing inlining of the destructor
4) Adding a dummy defined function to each class defined in the source file.

What a mess of a language :D I think of these, 3 is probably best, adding a `= default` definition for the move constructor and move assignment operator. It addresses the clang warning and conforms to lvm coding guidelines for what that's worth, but it's still low impact on us either way.

2021-10-21 07:26 UTC, anthonybilinski requested changes
> Reviewed 5 of 44 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/qtox/qtox/6394)* status: 0 of 1 LGTMs obtained

___
*[src/core/icoregroupquery.cpp, line 3 at r1](https://reviewable.io/reviews/qtox/qtox/6394#-MmWiPKS0uDjViqnXy6u:-MmWiPKS0uDjViqnXy6v:bokzboz) ([raw file](https://github.com/qtox/qtox/blob/cdf4f7440c2386db45da1b8f9ff4b18594bb0e26/src/core/icoregroupquery.cpp#L3)):*
> ```cpp
> /*
>     Copyright © 2013 by Maxim Biro <nurupo.contributions@gmail.com>
>     Copyright © 2014-2019 by The qTox Project Contributors
> ```

For new files in general, the date should just be the current year. Also looks like here you copy pasted in nurupo's copyright from another file


<!-- Sent from Reviewable.io -->

2021-10-21 15:54 UTC, brandonmosher commented
Defaulting the constructor in this way does in fact make it user-provided rather than implicitly declared: "A function is user-provided if it is user-declared and not explicitly defaulted or deleted on its first declaration."

In addition to explicitly defaulting the move constructor, it may be wise to explicitly default the copy constructor and copy assignment operator as their implicit declaration is now deprecated for classes with a user-declared destructor.

As far as I can tell, a user provided destructor does not prevent implicit declaration of the move assignment operator. That said, it can't hurt to explicitly default it as well.

I propose adding the following to the affected class headers. This has the added benefit of not having to think about which special member functions the compiler is implicitly generating.

T(const T&) = default;
T& operator=(const T&) = default;
T(T&&) = default;
T& operator=(T&&) = default;

If this is more trouble than it's worth, we can also abandon this PR :)

2021-10-21 16:08 UTC, jwestell commented
> As far as I can tell, a user provided destructor does not prevent implicit declaration of the move assignment operator. That said, it can't hurt to explicitly default it as well.

A little further down in that standard document I linked above (S15.8.2.4) it also mentions the same thing for move assignment operators.

> In addition to explicitly defaulting the move constructor, it may be wise to explicitly default the copy constructor and copy assignment operator as their implicit declaration is now deprecated for classes with a user-declared destructor.

Agreed. This is in line with the [rule of five](https://en.cppreference.com/w/cpp/language/rule_of_three) guidance.

2021-10-21 19:44 UTC, brandonmosher commented
Any thoughts on whether it is also worth following [C.67: A polymorphic class should suppress public copy/move](https://github.com/isocpp/CppCoreGuidelines/blob/master/CppCoreGuidelines.md#c67-a-polymorphic-class-should-suppress-public-copymove)?

This would require changes in addition to simply adding the defaulted special member functions. The public copy and move assignment operators in the ContactId class, for example, seem to violate this rule. In this case, if ContactId is always passed by reference, as it appears to be, the change should be trivial.

2021-10-22 07:48 UTC, anthonybilinski commented
I don't think pure virtual classes like `ContactId` are vulnerable to slicing since it can't be instantiated without a derived type since `getSize` would be undefined, and I think that's the case for most (but not all) polymorphic classes we have.

In general though, it seems worth following for classes that are vulnerable to slicing.

Re:
> If this is more trouble than it's worth, we can also abandon this PR :)

I'd be happy to accept the change, so as long as you're willing to complete it no need to abandon it. If it's getting to be too much of a pain on your side though, feel free :P

2021-10-25 06:48 UTC, brandonmosher commented
Not a pain at all, just want to make sure the extra lines of code are warranted. I went ahead and pushed the changes.

2021-10-25 07:38 UTC, anthonybilinski requested changes
> Reviewed 3 of 44 files at r1, 37 of 37 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/qtox/qtox/6394)* status: 0 of 1 LGTMs obtained

*[a discussion](https://reviewable.io/reviews/qtox/qtox/6394#-MmqKbV7BE8W8t-xH2jj:-MmqKbV7BE8W8t-xH2jk:b-47t8ei) (no related file):*
Building with clang and `-Wweak-vtables`, I'm still seeing warnings for `IAudioSink`, `ImagePreviewButton` (newly added since start of PR), and `IAudioSink`, and a couple minor formatting issues.

Otherwise looking good.

---
___
*[src/chatlog/chatmessage.h, line 55 at r2](https://reviewable.io/reviews/qtox/qtox/6394#-MmqLgJW-tZjLyRDcEQ1:-MmqLgJX3yY7JeuF_ZrQ:b8zg5oq) ([raw file](https://github.com/qtox/qtox/blob/7050eaeeb04237864317d3bca51d29856c1fd620/src/chatlog/chatmessage.h#L55)):*
> ```objc
>     ChatMessage& operator=(const ChatMessage&) = default;
>     ChatMessage(ChatMessage&&) = default;
>     
> ```

avoid trailing spaces at end of line
___
*[src/core/icoreextpacket.cpp, line 25 at r3](https://reviewable.io/reviews/qtox/qtox/6394#-MmqMGR2CV2DGqPjOuwT:-MmqMGR3754mki9N-Mpc:b-eomijg) ([raw file](https://github.com/qtox/qtox/blob/63c8a7b92ef8ba7392fd0c36c70049aecf5fa505/src/core/icoreextpacket.cpp#L25)):*
> ```cpp
> ICoreExtPacket::~ICoreExtPacket() = default;
> 
> ICoreExtPacketAllocator::~ICoreExtPacketAllocator() = default;
> ```

all lines should end in newlines, including the last lines of a file
___
*[src/core/icoregroupmessagesender.cpp, line 22 at r3](https://reviewable.io/reviews/qtox/qtox/6394#-MmqMvC62E-WTtQPjn8B:-MmqMvC62E-WTtQPjn8C:b-k922xl) ([raw file](https://github.com/qtox/qtox/blob/63c8a7b92ef8ba7392fd0c36c70049aecf5fa505/src/core/icoregroupmessagesender.cpp#L22)):*
> ```cpp
> #include "icoregroupmessagesender.h"
> 
> ICoreGroupMessageSender::~ICoreGroupMessageSender() = default;
> ```

same re: missing newline at end of file
___
*[src/core/icoregroupquery.h, line 40 at r3](https://reviewable.io/reviews/qtox/qtox/6394#-MmqMwOO0g3xYiSVpOKG:-MmqMwOO0g3xYiSVpOKH:b-slzui3) ([raw file](https://github.com/qtox/qtox/blob/63c8a7b92ef8ba7392fd0c36c70049aecf5fa505/src/core/icoregroupquery.h#L40)):*
> ```objc
>     ICoreGroupQuery(ICoreGroupQuery&&) = default;
>     ICoreGroupQuery& operator=(ICoreGroupQuery&&) = default;
>     
> ```

same: re trailing spaces
___
*[src/core/icoregroupquery.cpp, line 3 at r1](https://reviewable.io/reviews/qtox/qtox/6394#-MmWiPKS0uDjViqnXy6u:-MmqExl47x4B8m5Uokde:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/cdf4f7440c2386db45da1b8f9ff4b18594bb0e26/src/core/icoregroupquery.cpp#L3)):*
<details><summary><i>Previously, anthonybilinski (Anthony Bilinski) wrote…</i></summary><blockquote>

For new files in general, the date should just be the current year. Also looks like here you copy pasted in nurupo's copyright from another file
</blockquote></details>

Done.
___
*[src/core/icoregroupquery.cpp, line 22 at r3](https://reviewable.io/reviews/qtox/qtox/6394#-MmqMgCH8tObcV1ukWNZ:-MmqMgCH8tObcV1ukWN_:b-k922xl) ([raw file](https://github.com/qtox/qtox/blob/63c8a7b92ef8ba7392fd0c36c70049aecf5fa505/src/core/icoregroupquery.cpp#L22)):*
> ```cpp
> #include "icoregroupquery.h"
> 
> ICoreGroupQuery::~ICoreGroupQuery() = default;
> ```

same re: missing newline at end of file
___
*[src/core/icoreidhandler.cpp, line 22 at r3](https://reviewable.io/reviews/qtox/qtox/6394#-MmqNIbo3hw8J42uH72f:-MmqNIbo3hw8J42uH72g:b-k922xl) ([raw file](https://github.com/qtox/qtox/blob/63c8a7b92ef8ba7392fd0c36c70049aecf5fa505/src/core/icoreidhandler.cpp#L22)):*
> ```cpp
> #include "icoreidhandler.h"
> 
> ICoreIdHandler::~ICoreIdHandler() = default;
> ```

same re: missing newline at end of file
___
*[src/model/about/iaboutfriend.cpp, line 22 at r3](https://reviewable.io/reviews/qtox/qtox/6394#-MmqNNTjDCHinRLvLnK0:-MmqNNTjDCHinRLvLnK1:b-k922xl) ([raw file](https://github.com/qtox/qtox/blob/63c8a7b92ef8ba7392fd0c36c70049aecf5fa505/src/model/about/iaboutfriend.cpp#L22)):*
> ```cpp
> #include "iaboutfriend.h"
> 
> IAboutFriend::~IAboutFriend() = default;
> ```

same re: missing newline at end of file
___
*[src/model/dialogs/idialogs.cpp, line 22 at r3](https://reviewable.io/reviews/qtox/qtox/6394#-MmqNQ1FBYPItyDq7x0E:-MmqNQ1FBYPItyDq7x0F:b-k922xl) ([raw file](https://github.com/qtox/qtox/blob/63c8a7b92ef8ba7392fd0c36c70049aecf5fa505/src/model/dialogs/idialogs.cpp#L22)):*
> ```cpp
> #include "idialogs.h"
> 
> IDialogs::~IDialogs() = default;
> ```

same re: missing newline at end of file
___
*[src/model/dialogs/idialogsmanager.h, line 36 at r3](https://reviewable.io/reviews/qtox/qtox/6394#-MmqNQrT8GiSsb0Akj0p:-MmqNQrU1ISMBamLxjTW:btpm72b) ([raw file](https://github.com/qtox/qtox/blob/63c8a7b92ef8ba7392fd0c36c70049aecf5fa505/src/model/dialogs/idialogsmanager.h#L36)):*
> ```objc
>     IDialogsManager(IDialogsManager&&) = default;
>     IDialogsManager& operator=(IDialogsManager&&) = default;
>     
> ```

same re: trailing spaces
___
*[src/model/dialogs/idialogsmanager.cpp, line 22 at r3](https://reviewable.io/reviews/qtox/qtox/6394#-MmqNSdU4AH12T1bunm8:-MmqNSdU4AH12T1bunm9:b-k922xl) ([raw file](https://github.com/qtox/qtox/blob/63c8a7b92ef8ba7392fd0c36c70049aecf5fa505/src/model/dialogs/idialogsmanager.cpp#L22)):*
> ```cpp
> #include "idialogsmanager.h"
> 
> IDialogsManager::~IDialogsManager() = default;
> ```

same re: missing newline at end of file
___
*[src/model/friendlist/ifriendlistitem.cpp, line 22 at r3](https://reviewable.io/reviews/qtox/qtox/6394#-MmqNU9-2yuvBROq0wZL:-MmqNU9-2yuvBROq0wZM:b-k922xl) ([raw file](https://github.com/qtox/qtox/blob/63c8a7b92ef8ba7392fd0c36c70049aecf5fa505/src/model/friendlist/ifriendlistitem.cpp#L22)):*
> ```cpp
> #include "ifriendlistitem.h"
> 
> IFriendListItem::~IFriendListItem() = default;
> ```

same re: missing newline at end of file
___
*[src/persistence/ifriendsettings.cpp, line 22 at r3](https://reviewable.io/reviews/qtox/qtox/6394#-MmqNWui8fNsl7lI9t9Y:-MmqNWui8fNsl7lI9t9Z:b-k922xl) ([raw file](https://github.com/qtox/qtox/blob/63c8a7b92ef8ba7392fd0c36c70049aecf5fa505/src/persistence/ifriendsettings.cpp#L22)):*
> ```cpp
> #include "ifriendsettings.h"
> 
> IFriendSettings::~IFriendSettings() = default;
> ```

same re: missing newline at end of file


<!-- Sent from Reviewable.io -->

2021-10-25 16:06 UTC, brandonmosher commented
Changes made. I left the `-Wweak-vtables` flag set in `CMakeLists.txt` to warn when future classes fail to comply with this pattern. `MockGroupQuery` and `MockCoreIdHandler` are still generating warnings as a result. I could apply the same changes to these classes, but I'm not sure how to configure CMake to include additional CPP files when building tests, or if that's even desired.

2021-10-25 20:16 UTC, anthonybilinski requested changes
re: testing, in `cmake/Testing.cmake`, we define each test and what deps it requires with the function `auto_test`. Its last argument allows for arbitrary additional source files to be given for any individual test. I think using that would allow for fixing this in tests as well, and passing in mock source files needed for the test.

> Reviewed 20 of 20 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/qtox/qtox/6394#-:-Mmt4e334UV_8U2gKQ2P:bynpr4l)* status: 0 of 1 LGTMs obtained

___
*[CMakeLists.txt, line 96 at r4](https://reviewable.io/reviews/qtox/qtox/6394#-MmszXA-7lMwurhdihoF:-MmszXA-7lMwurhdihoG:b-1xluf) ([raw file](https://github.com/qtox/qtox/blob/7dc57774f3b16a72051349dcdc33990d140022a0/CMakeLists.txt#L96)):*
> ```CMake
> set(POSITION_INDEPENDENT_CODE True)
> 
> set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -Wweak-vtables")
> ```

`-Wweak-vtables` is only available on clang, so this addition causes compilation to fail with gcc. We'd need to conditionally add the warning only for clang or compilers that support it.

It looks like cmake's `CHECK_CXX_COMPILER_FLAG` would allow for this.


<!-- Sent from Reviewable.io -->

2021-10-26 16:59 UTC, brandonmosher commented
OK, I think I've got everything working. Now compiling in gcc and clang with no warnings.

2021-10-26 22:59 UTC, anthonybilinski approved these changes
<img class="emoji" title=":lgtm_strong:" alt=":lgtm_strong:" align="absmiddle" src="https://reviewable.io/lgtm_strong.png" height="20" width="61"/> 

GH actions CI seems to not be re-running :thinking: I'll try pushing a dummy commit to your branch and then force-push stripping that dummy commit off, sometimes that makes it re-evaluate.

> Reviewed 6 of 6 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/qtox/qtox/6394#-:-MmyomJg8WHfqCYNNkuB:bz78an8)* status: :shipit: complete! 1 of 1 LGTMs obtained



<!-- Sent from Reviewable.io -->

2021-10-26 23:22 UTC, merged

2021-10-26 23:25 UTC, anthonybilinski commented
Thanks for the change and follow up, @brandonmosher!